### PR TITLE
added search fields for unramified degree and tame degree

### PR DESCRIPTION
**Pull request by jakobderaaij**
Addressing a part of issue #4509 that was asking for the possibility to search for p-adic fields by their unramified degree and tame degree. I added these two search boxes to the p-adic field start page and to the p-adic field search page. They work exactly like the other search boxes on these pages.  

Before: http://www.lmfdb.org/padicField/ and http://www.lmfdb.org/padicField/?search_type=List&all=1
After: http://localhost:37777/padicField/ and http://localhost:37777/padicField/?u=4&t=2&search_type=List

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
@jwj61 Can you review this when you get a chance (it will only take a moment) just to be sure you are happy with it?  I think Jakob is planning to do some more work related to #4509 next week, but I suggested doing these first.

**Comment by jwj61** [comment]
Will do.

**Comment by jwj61** [comment]
On the search results page, I don't we can add a column instead of another line.

The knowls need to be adjusted.  On the page of a field, they are in a section about the Galois closure which I think is enough to indicate that they are the tame and unramified degrees of the Galois closure.  But, the notions make sense for any p-adic field, so a user might think that the search boxes are referring the the fields in the search results as opposed to their Galois closures.  In short, they need to be labelled differently in this context.

**Comment by AndrewVSutherland** [comment]
@jwj61 -- thanks for the feedback, I agree with both the points you made and will hold off merging until they have been addressed. The layout changes are easy and I can help Jakob with the know edits (but feel free to make them yourself if you prefer).

**Comment by jwj61** [comment]
Maybe the labels for them should be "Galois unramified degree" and "Galois tame degree".

I suppose the knowls could each have an added paragraph that just said, e.g., The Galois unramified degree of a field $K$ is the unramified degree of its Galois closure.

Thinking about it now, it might also make sense to make the connection in the knowl between the unramified degree and the residue field degree.

**Comment by jakobderaaij** [comment]
I changed the layout of the search result page such that the search boxes are now all in two rows and have clearer labels.
I edited the knows of the unramified and tame degree to contain the information about Galois unramified/tame degree.

**Comment by edgarcosta** [comment]
Great work @jakobderaaij feel free to add yourself to the contributors list https://github.com/LMFDB/lmfdb/blob/master/CONTRIBUTORS.yaml

**Pull request merged**
