### PR TITLE
fixed code snippet formatting for Dirichlet and Hecke characters

### PR DESCRIPTION
**Pull request by JohnCremona**
This addresses #1997 by adding an import statement with a comment.  At the same time I fixed the bad formatting of multi-line code snippets for both Dirichlet and Hecke characters.  For examples see

http://localhost:37777/Character/Hecke/2.2.8.1/28.12a0+4a1/1

and

http://localhost:37777/Character/Dirichlet/65/14

-- in both cases, click on both the SageMath and PariGP buttons to see the differences.

### CODE REVIEW

**Comment by pjbruin** [comment]
The Sage code in the first example now looks as follows:
```
sage: k.<a> = NumberField(x^2 - 2)
sage: m = k.ideal(⟨28,4a+12⟩)
sage: G = RayClassGroup(k,m)
sage: H = G.dual_group()
sage: chi = H([1])
```
There are two remaining problems:
- The angle brackets and the "4a" without asterisk in the second line cause a SyntaxError, it should be `m = k.ideal([28,4*a+12])`
- The name `RayClassGroup` is not defined

**Comment by JohnCremona** [comment]
OK -- I'll fix the easy one but until Sage trac ticket implementing RayClassGroups gets merged there is perhaps little point in having this code visible anyway.

**Comment by sanni85** [comment]
One of the command is 

sage: chi.values_on_gens()

which does not work.

**Comment by JohnCremona** [comment]
I have dealt with the issues found.  On RayClassGroup I added a comment saying this was not yet available in Sage.  I think that is OK since by the time this is out of beta, the reviewing process for that might be finished.

**Comment by pjbruin** [comment]
The formatting bug on the Dirichlet and Hecke character pages appears to be fixed, but it still exists on pages for Hecke character _groups_, e.g. http://localhost:37777/Character/Hecke/2.2.8.1/28.12a0+4a1: clicking on "Show commands for SageMath" gives
```
sage: ['k.<a> = NumberField(x^2 - 2)', 'm = k.ideal(\\(\\langle 28, 4 a + 12\\rangle\\))', 'G = RayClassGroup(k,m)', 'H = G.dual_group()']
```
and for Pari/GP it gives
```
pari: ['k=bnfinit(x^2 - 2)', 'g=bnrinit(k,m,1)']
```

**Comment by pascalmolin** [comment]
I am fixing it.
(btw: originally the linebreaks were inserted in the template, it must have
disappeared when code snippets were uniformized.)

Pascal

2017-03-27 11:31 GMT+02:00 Peter Bruin <notifications@github.com>:

**Comment by pjbruin** [comment]
For PARI, the modulus `m` is not defined; I think the correct command is something like
```
pari: m = idealhnf(k, 28, 4*x + 12)
```
or more generally (specifying the infinite places as well)
```
pari: m = [idealhnf(k, 28, 4*x + 12), [0, 0]]
```
This should be fixed on both the Hecke group pages (e.g. http://localhost:37777/Character/Hecke/2.2.8.1/28.12a0+4a1) and the Hecke character pages (e.g. http://localhost:37777/Character/Hecke/2.2.8.1/28.12a0+4a1/1).

**Comment by pjbruin** [comment]
There is a typo in the PARI code for getting the conductor of a Hecke character: the capital `G` in
```
pari: bnrconductorofchar(G,chi)
```
should be a small `g` (again after clicking "Show commands for Pari/GP" on e.g. http://localhost:37777/Character/Hecke/2.2.8.1/28.12a0+4a1/1)

**Comment by JohnCremona** [comment]
Thanks Pascal, can I assume that you are taking my branch and adding more fixes to it?  If so I will leave this to you now.

**Comment by JohnCremona** [comment]
One thing I did to help testing of these code snippets for elliptic curves (so far I only did this for curves over Q though) was to all users to download a file containing all of the code snippets, including comments.  Then the test is to download this for each relevant language and actually run the code.  That would be a good thing to do everywhere we have such code snippets -- easier testing and easier for users too.  For this to make sense it is essential that *exactly* the same strings which are displayed on the page one by one go into the download file.

**Comment by pascalmolin** [comment]
OK, and I also add a download link if I manage to do so

Pascal

2017-03-27 13:08 GMT+02:00 John Cremona <notifications@github.com>:

**Comment by JohnCremona** [comment]
ping?

**Comment by pascalmolin** [comment]
:-( sorry (in fact I did the patch but stopped in the process of
reinstalling sage to run the tests... 3 weeks already... I'm doing it)

2017-04-18 17:00 GMT+02:00 John Cremona <notifications@github.com>:

**Comment by davidfarmer** [comment]
Closing, because this was handles by pr #2083

**Pull request closed without merging**
