### PR TITLE
Cleaned up color.css just a bit more.

### PR DESCRIPTION
**Pull request by adeines**

### CODE REVIEW

**Comment by JohnCremona** [comment]
I think has changed some sidebar colours in a way not discussed.  Was that intentional?
@alinabucur noticed this.

**Comment by adeines** [comment]
Nope.  That wasn't on purpose.  Which sidebar colors?  I could get to this
tonight/this weekend (and in the meantime you could revert back.)

I was mostly trying to separate some colors so Holly could make a color
scheme with better contrast and was hopefully not actually changing
anything . . .

**Comment by davidfarmer** [comment]
The changes I noticed in the sidebar colors were all corrections.  The word "elliptic",
for example, is now black, meaning that it is not a link.  The /Q below it is green,
meaning that is the link to follow.

Unless I have missed something, all is well with the sidebar colors.

**Comment by adeines** [comment]
Awesome!  (Yes, Holly had me set all non-links to black.)

**Pull request merged**
