### PR TITLE
refactoring code for L-func friends

### PR DESCRIPTION
**Pull request by edgarcosta**
The goal of this PR is to move most of the code used to find friends/origins/related objects through the database of L-functions to one single file `lmfdb/lfunctions/LfunctionDatabase.py`.
At the moment due to various data structures in the database, we use various hacks, and now this concentrates all the hacks in one spot.

Further, this also enables us to use this code in the future for ECNFs and Artin Representations.

For last, I'm not aware of any page changing, and if so it will be by including more friends that we were missing before.

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
@edgarcosta Thanks for this, I will review it this afternoon.

**Comment by AndrewVSutherland** [comment]
Looks good, but it might be nice if we sorted the lfunction friends before adding them, e.g. on http://127.0.0.1:37777/Genus2Curve/Q/20736/i/373248/1, this would put the two EC isogeny classes next to each other.

I was expecting to see this used on the ECNF pages, but I see this is just refactoring.  Do you plan to add a call to the new function to ECNF in a seaprate PR?  It might make sense to do it in this PR as it would be a further exercise the new code.

**Comment by AndrewVSutherland** [comment]
Actually there is one thing I noticed.  There are "closing cursor" messages showing up on the debug console that were not there before, can we get rid of these?

**Comment by edgarcosta** [comment]
> Actually there is one thing I noticed. There are "closing cursor" messages showing up on the debug console that were not there before, can we get rid of these? 
I did that in #3016

**Comment by edgarcosta** [comment]
@AnewewVSutherland I will address the other comments later on

**Comment by AndrewVSutherland** [comment]
@edgarcosta Do you want me to merge this now, or are you planning to make further changes?

**Comment by edgarcosta** [comment]
I still have some changes to push for ECNF.
However, it is not clear how to do the sorting properly in general.

**Comment by AndrewVSutherland** [comment]
@edgarcosta and I discussed this and have a general plan for how to do the sorting in a reasonable way (it won't be perfect, but it will be reasonable and better than it is now).   Please hold off merging this PR (I'll review it once Edgar has implemented the changes and pushed them).

**Comment by AndrewVSutherland** [comment]
Travis failed due to an error downloading a classical modular form.  I just reloaded mf_hecke_nf and am in the process of reloading mf_newforms, which I suspect is what caused the error

**Comment by edgarcosta** [comment]
I'm done with my commits. I believe this is ready for being reviewed.
If tests fail, I will look into it in the morning.

**Comment by edgarcosta** [comment]
Here are some links for ECNF and G2C that have changed:
http://localhost:37777/EllipticCurve/2.0.8.1/324.3/a/1
http://localhost:37777/EllipticCurve/2.2.8.1/9.1/a/
http://localhost:37777/EllipticCurve/2.2.24.1/36.1/a/1
http://localhost:37777/EllipticCurve/2.0.11.1/256.1/b/1
http://localhost:37777/Genus2Curve/Q/20736/i/

**Comment by edgarcosta** [comment]
@AndrewVSutherland, now the only test that fails is :
```
page = self.tc.get('/ModularForm/GL2/Q/holomorphic/download_newform/27.2.e.a', follow_redirects=True)
>       assert '[-1, 0, 0, 0, 1, 0, 0, 0, 0, -1, 0, 0]' in page.data # a_2
```

**Comment by AndrewVSutherland** [comment]
@edgarcosta Yeah the test needs to be changed because of a change in the basis for the Hecke ring, I will fix this in a separate PR.  I'm reviewing this PR now.

**Comment by AndrewVSutherland** [comment]
Looks great!  I will fix the failing test in a separate PR.

**Pull request merged**
