### PR TITLE
py3: some fixes for filter and for the import of StringIO, etc

### PR DESCRIPTION
**Pull request by fchapoton**
- replace many filter by list comprehension
- import StringIO from six
- other fixes

Tool used: `~/lmfdb/lmfdb$ pylint --py3k -d W1618,W1619 */*.py`

### CODE REVIEW

**Comment by roed314** [comment]
The test failures look related to `StringIO`

**Comment by fchapoton** [comment]
I am afraid this is just the tip of unicode/str/bytes hell. Given that you manipulate so many files, this will be very tricky.

**Comment by fchapoton** [comment]
would it be ok to use sage helping method "bytes_to_str" ?

**Comment by roed314** [comment]
I know @AndrewVSutherland has wanted to minimize dependencies when possible, but in this case I would say that using this utility function will make our lives much easier and we should go ahead with it.  @fchapoton, do you know where the source for `bytes_to_str` is viewable online?  I can find it in my local sage installation (in `$SAGE_ROOT/local/lib/python3.7/site-packages/sage/cpython/string.pxd` and `$SAGE_ROOT/local/lib/python3.7/site-packages/sage/cpython/string_impl.h`).

I'd say that this is a function that's been developed to ease the transition from Python 2 to 3 and we should take advantage of it.

**Comment by fchapoton** [comment]
The code can be found here:

https://github.com/sagemath/sage/blob/develop/src/sage/cpython/string.pxd

**Comment by edgarcosta** [comment]
The errors are almost all from using strIO 
```
strIO.write(bytes_to_str(s))
...
TypeError: expected bytes, unicode found
```

**Comment by fchapoton** [comment]
Damn. Here is another tentative, using six

**Comment by fchapoton** [comment]
now everything looks fine.

**Pull request merged**
