### PR TITLE
Monogenic fields etc.

### PR DESCRIPTION
**Pull request by jwj61**
Addressing issue #5044, this adds the display and search for number fields for whether or not a field is monogenic, its index, and the list of inessential primes.

Searching is visible on the main number field page

http://127.0.0.1:37777/NumberField/

and the display can be seen on any particular field page, e.g., 

where we have data
http://127.0.0.1:37777/NumberField/2.0.567764.1

and where we (currently) do not have data

http://127.0.0.1:37777/NumberField/3.1.244.1

### CODE REVIEW

**Comment by jwj61** [comment]
I notice that parse_posints accepts 0 as a positive integer.  I can fix this, but would that break the expected behavior elsewhere?

**Comment by AndrewVSutherland** [comment]
@jwj61 Well, it shouldn't, but of course it might.  My vote would be to try changing it, and if tests pass go ahead and fix it, what do you think @roed314 and @edgarcosta ?

**Comment by JohnCremona** [comment]
I would be more worried if we had more French developers :)

**Comment by AndrewVSutherland** [comment]
FYI, we are experimenting with a change to the search results interface that will allow us to show a warning to the user when the search results are known to exclude rows with unknown values that might match the search criteria if the values were known.  I want to hold off merging this PR until that one is ready.

**Comment by jwj61** [comment]
That's fine.  I am mainly working on data for this anyway.

**Comment by roed314** [comment]
The test failures are probably due to adding some null statistics in support of #5052, and should be fixed by the changes there.

**Comment by roed314** [comment]
I thought I had merged in fixes for the underlying data change in #5054; I'm not sure why tests are still failing.  I can take a look soon, but maybe not until Monday.

**Pull request merged**
