### PR TITLE
Breadcrumbs

### PR DESCRIPTION
**Pull request by JohnCremona**
Added & made more consistent breadcrumbs everywhere.

Also replaced Top with a house symbol (including for Home page).  This can be changed but all the rest should be merged as soon as possible to avoid future conflicts.

Fixes Issue #599

### CODE REVIEW

**Comment by davidfarmer** [comment]
I don't think the home house is big enough to tell that is what it is supposed to be.

Try putting this in lmfdb/templates/style.css at line 228:

#header .bread a:first-child {
    font-size: 150%;
}

and also comment out line 225, which says
    padding-top: 2px;

Even with those changes, it is hard to tell it is a house.

**Comment by JohnCremona** [comment]
I know that the house symbol is not good enough.  When I have time (tomorrow) I can try other things.  But all the other breadcrumb changes are surely OK and need to be merged soon, so perhaps it is better for now to reinstate "Top" and not worry about the symbol.

**Comment by davidfarmer** [comment]
I will merge and then make those CSS changes

**Comment by JohnCremona** [comment]
Thanks!

**Pull request merged**
