### PR TITLE
Magma

### PR DESCRIPTION
**Pull request by danyasaki**
added magma code to genus 2 curve pages.  Followed Cremona's code.  Left most sage and pari empty.  See 
http://localhost:37777/Genus2Curve/Q/12500/a/12500/1
for example.

### CODE REVIEW

**Comment by JohnCremona** [comment]
Great!  I will check it out...

**Comment by davidfarmer** [comment]
Please look at how I edited the previous comment.  The < p> and < /p> tags were taken
as HTML and thus not displayed.  The same would have happened here if I had not
pus spaces after each "less than" sign.

There are other ways to indicate that a string should appear literally, but I forget how
to do it and I just put in the space.

**Comment by JohnCremona** [comment]
Thanks -- clearly I did not look at  the post after posting.

**Comment by danyasaki** [comment]
addressed John's comments and pushed again.

**Comment by JohnCremona** [comment]
Looks good to me.  Now I hope that someone will merge #318!

**Pull request merged**
