### PR TITLE
Knowl bread

### LINKED ISSUE #2831: Knowl breadcrumbs
The breadcrumbs for a knowl page such as http://beta.lmfdb.org/knowledge/show/g2c.discriminant  looks like 
Knowledge -> Discriminant...
It would be nice to have an intermediate breadcrumb, in this case 'g2c',  which linked to the same page as "up".

### PR DESCRIPTION
**Pull request by roed314**
Resolves #2831.  See any knowl homepage to test.

### CODE REVIEW

**Comment by JohnCremona** [comment]
One of the changed files implements this, the other two changed files do different things.  This makes it harder to review, since I am not sure what the side-effects of the other two changes will be.
Meanwhile, would it be possible also to have a view such as http://localhost:37777/knowledge/?category=ec  to have the ec in the breadcrumbs?  That seems logical, and currently the category name is highlighted somehow to I expect that this will not be hard.

**Comment by roed314** [comment]
I've added the bread to the index page when relevant.

I'm confused about the other two files.  That change was already merged in #2891, so I don't know why it's still showing up here when comparing against master....

**Comment by JohnCremona** [comment]
Thanks, I'll look at the new version.  Don't worry about the other two files -- as you say, github should probably not be showing them.  Perhaps you did a forced push so that the most recent common ancestor is not what it logically is.  I'll ignore that.

**Comment by JohnCremona** [comment]
Looks good: to be merged once tests have passed.

**Comment by roed314** [comment]
I do remember doing a forced push since I pushed the wrong branch somewhere.  That seems like a likely explanation.

**Pull request merged**
