### PR TITLE
Fix a bug in upload_from_file when extra columns present

### LINKED ISSUE #5649: Rewrite broken for number field database
I tried rewrite with the identity function as the modification function:

```
from lmfdb import db
def nmod(ent):
    return ent
db.nf_fields.rewrite(nmod)
```

and get the error

Traceback (most recent call last):
  File "/home/jj/lmfdb/lmfdb/backend/base.py", line 313, in _execute
    cur.execute(query, values)
psycopg2.errors.UndefinedColumn: column "zk" of relation "nf_fields_tmp" does not exist
LINE 1: ...ling" = "tmp_update_from_file"."minimal_sibling", "zk" = "tm...
                                                             ^

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nfmod.py", line 39, in <module>
    db.nf_fields.rewrite(nmod) #,datafile='/home/jj/nf-lmfdb/DELETE.ME')
  File "/home/jj/lmfdb/lmfdb/backend/table.py", line 1005, in rewrite
    self.update_from_file(
  File "/home/jj/lmfdb/lmfdb/backend/table.py", line 1124, in update_from_file
    self._execute(updater.format(
  File "/home/jj/lmfdb/lmfdb/backend/base.py", line 319, in _execute
    reraise(type(e), type(e)(str(e) + context), sys.exc_info()[2])
  File "/home/jj/lmfdb/lmfdb/backend/utils.py", line 230, in reraise
    raise exc_value.with_traceback(exc_traceback)
  File "/home/jj/lmfdb/lmfdb/backend/base.py", line 313, in _execute
    cur.execute(query, values)
psycopg2.errors.UndefinedColumn: column "zk" of relation "nf_fields_tmp" does not exist
LINE 1: ...ling" = "tmp_update_from_file"."minimal_sibling", "zk" = "tm...
 
 happens while executing b'UPDATE "nf_fields_tmp" SET "label" = "tmp_update_from_file"."label", "degree" = "tmp_update_from_file"."degree", "r2" = "tmp_update_from_file"."r2", "cm" = "tmp_update_from_file"."cm", "iso_number" = "tmp_update_from_file"."iso_number", "disc_abs" = "tmp_update_from_file"."disc_abs", "disc_sign" = "tmp_update_from_file"."disc_sign", "disc_rad" = "tmp_update_from_file"."disc_rad", "galt" = "tmp_update_from_file"."galt", "class_number" = "tmp_update_from_file"."class_number", "class_group" = "tmp_update_from_file"."class_group", "used_grh" = "tmp_update_from_file"."used_grh", "rd" = "tmp_update_from_file"."rd", "regulator" = "tmp_update_from_file"."regulator", "ramps" = "tmp_update_from_file"."ramps", "coeffs" = "tmp_update_from_file"."coeffs", "num_ram" = "tmp_update_from_file"."num_ram", "conductor" = "tmp_update_from_file"."conductor", "subfields" = "tmp_update_from_file"."subfields", "subfield_mults" = "tmp_update_from_file"."subfield_mults", "torsion_order" = "tmp_update_from_file"."torsion_order", "galois_label" = "tmp_update_from_file"."galois_label", "is_galois" = "tmp_update_from_file"."is_galois", "gal_is_abelian" = "tmp_update_from_file"."gal_is_abelian", "gal_is_cyclic" = "tmp_update_from_file"."gal_is_cyclic", "gal_is_solvable" = "tmp_update_from_file"."gal_is_solvable", "local_algs" = "tmp_update_from_file"."local_algs", "inessentialp" = "tmp_update_from_file"."inessentialp", "index" = "tmp_update_from_file"."index", "monogenic" = "tmp_update_from_file"."monogenic", "embeddings_gen_real" = "tmp_update_from_file"."embeddings_gen_real", "embeddings_gen_imag" = "tmp_update_from_file"."embeddings_gen_imag", "is_minimal_sibling" = "tmp_update_from_file"."is_minimal_sibling", "minimal_sibling" = "tmp_update_from_file"."minimal_sibling", "zk" = "tmp_update_from_file"."zk", "units" = "tmp_update_from_file"."units", "unitsGmodule" = "tmp_update_from_file"."unitsGmodule", "unitsType" = "tmp_update_from_file"."unitsType", "res" = "tmp_update_from_file"."res", "frobs" = "tmp_update_from_file"."frobs", "torsion_gen" = "tmp_update_from_file"."torsion_gen", "dirichlet_group" = "tmp_update_from_file"."dirichlet_group", "subfield_inclusions" = "tmp_update_from_file"."subfield_inclusions", "source" = "tmp_update_from_file"."source" FROM "tmp_update_from_file" WHERE "nf_fields_tmp"."id" = "tmp_update_from_file"."id"'

### PR DESCRIPTION
**Pull request by roed314**
@jwj61 I think this will fix #5649.  Can you check?

### CODE REVIEW

**Comment by jwj61** [comment]
OK, just started a run

**Comment by jwj61** [comment]
Got a different error:

Traceback (most recent call last):
  File "nfmod.py", line 39, in <module>
    db.nf_fields.rewrite(mymod) #,datafile='/home/jj/nf-lmfdb/DELETE.ME')
  File "/home/jj/lmfdb/lmfdb/backend/table.py", line 1005, in rewrite
    self.update_from_file(
  File "/home/jj/lmfdb/lmfdb/backend/table.py", line 1143, in update_from_file
    ecols = SQL(", ").join([
  File "/home/jj/lmfdb/lmfdb/backend/table.py", line 1144, in <listcomp>
    SQL("{0} = {1}.{0}").format(col, Identifier(tmp_table))
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.8/lib/python3.8/site-packages/psycopg2/sql.py", line 256, in format
    return Composed(rv)
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.8/lib/python3.8/site-packages/psycopg2/sql.py", line 108, in __init__
    raise TypeError(
TypeError: Composed elements must be Composable, got 'zk' instead

**Comment by roed314** [comment]
@jwj61, fixed another bug.  I'm surprised that we haven't hit these before, since I thought you had used `rewrite` on `nf_fields` before.

**Comment by jwj61** [comment]
Traceback (most recent call last):
  File "/home/jj/lmfdb/lmfdb/backend/base.py", line 313, in _execute
    cur.execute(query, values)
psycopg2.errors.DiskFull: could not extend file "base/16403/684415237.54": No space left on device
HINT:  Check free disk space.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nfmod.py", line 39, in <module>
    db.nf_fields.rewrite(mymod) #,datafile='/home/jj/nf-lmfdb/DELETE.ME')
  File "/home/jj/lmfdb/lmfdb/backend/table.py", line 1005, in rewrite
    self.update_from_file(
  File "/home/jj/lmfdb/lmfdb/backend/table.py", line 1147, in update_from_file
    self._execute(updater.format(
  File "/home/jj/lmfdb/lmfdb/backend/base.py", line 319, in _execute
    reraise(type(e), type(e)(str(e) + context), sys.exc_info()[2])
  File "/home/jj/lmfdb/lmfdb/backend/utils.py", line 230, in reraise
    raise exc_value.with_traceback(exc_traceback)
  File "/home/jj/lmfdb/lmfdb/backend/base.py", line 313, in _execute
    cur.execute(query, values)
psycopg2.errors.DiskFull: could not extend file "base/16403/684415237.54": No space left on device
HINT:  Check free disk space.
 happens while executing b'UPDATE "nf_fields_extras_tmp" SET "zk" = "tmp_update_from_file"."zk", "units" = "tmp_update_from_file"."units", "unitsGmodule" = "tmp_update_from_file"."unitsGmodule", "unitsType" = "tmp_update_from_file"."unitsType", "res" = "tmp_update_from_file"."res", "frobs" = "tmp_update_from_file"."frobs", "torsion_gen" = "tmp_update_from_file"."torsion_gen", "dirichlet_group" = "tmp_update_from_file"."dirichlet_group", "subfield_inclusions" = "tmp_update_from_file"."subfield_inclusions", "source" = "tmp_update_from_file"."source" FROM "tmp_update_from_file" WHERE "nf_fields_extras_tmp"."id" = "tmp_update_from_file"."id"'

**Comment by jwj61** [comment]
Tried again and:

Traceback (most recent call last):
  File "/home/jj/lmfdb/lmfdb/backend/base.py", line 313, in _execute
    cur.execute(query, values)
psycopg2.OperationalError: could not receive data from server: Connection timed out
SSL SYSCALL error: Connection timed out


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nfmod.py", line 45, in <module>
    db.nf_fields.rewrite(mymod ,datafile='/home/jj/nf-lmfdb/DELETE.ME')
  File "/home/jj/lmfdb/lmfdb/backend/table.py", line 1006, in rewrite
    self.update_from_file(
  File "/home/jj/lmfdb/lmfdb/backend/table.py", line 1148, in update_from_file
    self._execute(updater.format(
  File "/home/jj/lmfdb/lmfdb/backend/base.py", line 319, in _execute
    reraise(type(e), type(e)(str(e) + context), sys.exc_info()[2])
  File "/home/jj/lmfdb/lmfdb/backend/utils.py", line 230, in reraise
    raise exc_value.with_traceback(exc_traceback)
  File "/home/jj/lmfdb/lmfdb/backend/base.py", line 313, in _execute
    cur.execute(query, values)
psycopg2.OperationalError: could not receive data from server: Connection timed out
SSL SYSCALL error: Connection timed out
 happens while executing b'UPDATE "nf_fields_extras_tmp" SET "zk" = "tmp_update_from_file"."zk", "units" = "tmp_update_from_file"."units", "unitsGmodule" = "tmp_update_from_file"."unitsGmodule", "unitsType" = "tmp_update_from_file"."unitsType", "res" = "tmp_update_from_file"."res", "frobs" = "tmp_update_from_file"."frobs", "torsion_gen" = "tmp_update_from_file"."torsion_gen", "dirichlet_group" = "tmp_update_from_file"."dirichlet_group", "subfield_inclusions" = "tmp_update_from_file"."subfield_inclusions", "source" = "tmp_update_from_file"."source" FROM "tmp_update_from_file" WHERE "nf_fields_extras_tmp"."id" = "tmp_update_from_file"."id"'

**Comment by roed314** [comment]
@jwj61 The disk space problems are in a much better place.  Can you try again?

**Comment by jwj61** [comment]
Started it

**Pull request merged**
