### PR TITLE
Rename cmf.hecke-orbit to cmf.hecke_orbit

### PR DESCRIPTION
**Pull request by roed314**
Mainly for testing #2892.

### CODE REVIEW

**Comment by roed314** [comment]
Merged in #2895 so that tests pass; that PR should be reviewed first.

**Comment by roed314** [comment]
I merged in master, so this should be less scary to review now.

**Comment by AndrewVSutherland** [comment]
Looks good, but I'm slightly confused by the fact that the knowl being renamed still has knowl references to it (even though it has no code references to it).  Is the assumption that knowls won't be updated until after the code has changed?  I guess this makes sense in that it delays all changes until something irrevocable happens (updated code gets merged), but I just want to confirm that this is intentional.

In any case, the answer to my question is irrelavent to this PR, so I will merge it.

**Comment by roed314** [comment]
Yeah, the current workflow is that the Finish Renaming step updates the other knowls in the database.

**Pull request merged**
