### PR TITLE
only say Galois closure if not Galois

### PR DESCRIPTION
**Pull request by BarinderBanwait**
addresses latest discussion on #4919

### CODE REVIEW

**Comment by BarinderBanwait** [comment]
the test failure here is unrelated and is apparently already in LMFDB:master

**Comment by AndrewVSutherland** [comment]
Test failure is caused by BMF test failing because dimension 2 forms are no longer present, which is unrelated to this PR and fixed in #4957

**Comment by AndrewVSutherland** [comment]
"Artin stem field" should be changed to "Artin field" on http://127.0.0.1:37777/ArtinRepresentation/2.39.4t3.a.a (the knowl link also needs to change), and I would change "Artin number field" to "Artin field" on http://127.0.0.1:37777/ArtinRepresentation/2.39.4t3.a (knowl link is fine here).

**Comment by JohnCremona** [comment]
> Test failure is caused by BMF test failing because dimension 2 forms are no longer present, which is unrelated to this PR and fixed in #4957

Apologies for that: not caused by my BMF PR itself, which I tested, but by the subsequent data change.

**Comment by BarinderBanwait** [comment]
> "Artin stem field" should be changed to "Artin field" on http://127.0.0.1:37777/ArtinRepresentation/2.39.4t3.a.a (the knowl link also needs to change), and I would change "Artin number field" to "Artin field" on http://127.0.0.1:37777/ArtinRepresentation/2.39.4t3.a (knowl link is fine here).

I thought that @jwj61 was saying that we use "Artin stem field" if the field is *not* Galois, which is the case for the first link you sent, so that "Artin stem field" should *not* be changed to "Artin field" in that first case?

On the other hand, in the second link to the Galois orbit, it *should* be changed from "Artin number field" to "Artin stem field"?

In all cases, all instances of "Artin number field" should be changed to "Artin field"?

**Comment by jwj61** [comment]
I will see if I can clarify this.

With issue #4435, the page for Artin reps was changed so that it would say "stem field" or "field" depending on whether or not the field is Galois.  This. was for both the Artin field and the projective field.  The orbit pages were not updated to match at that time.

The current issue points out 2 problems.  One is that rep pages are not in sync with orbit pages.  The other is the preference for "Galois closure of" over use of the term "stem field".  So, no more use of the term stem field, and only say "Galois closure of" when the field is not Galois.

So, there are two types of pages (orbit and rep) and changes to be made in two places on each (Artin field and projective field), and they all need to be able to switch back and forth depending on whether or not the field is Galois.

**Comment by BarinderBanwait** [comment]
Thanks everyone for the clarifications, hopefully the latest version is correct now

**Comment by AndrewVSutherland** [comment]
Looks good to me!  But I'll give @jwj61 a chance to comment before merging.

**Comment by jwj61** [comment]
Looks good to me.  If the test failure is inconsequential, I would merge.

**Comment by AndrewVSutherland** [comment]
The test failure is unrelated (caused by data change to BMFs that invalidated a test that is fixed in another PR).  I'll merge.

**Pull request closed without merging**
