### PR TITLE
master --> beta after #1392

### PR DESCRIPTION
**Pull request by JohnCremona**
Making the PR but not about to merge.

### CODE REVIEW

**Comment by JohnCremona** [comment]
I reckon that after accepting this as a normal (not squashed) merge, beta and master will have the same file content but beta will be one commit ahead of master owing to the merge commit.  Similarly with PR #1395 for prod.

**Comment by AndrewVSutherland** [comment]
You can see from this e-mail the cause of my concern -- the pull request 
to master whose changes you are now trying to apply to beta did not 
modify either lmfdb/elliptic_curves/elliptic_curve.py or 
lmfdb/search_parsing.py.

So its not just a question of what you see when you look at the file 
changes in the pull request on github, the e-mails going out to all the 
RMs will have misleading information in them (unless we revert to 
pushing from the command line, in which case the RMs won't get an e-mail 
at all).

**Comment by AndrewVSutherland** [comment]
Merging (without squashing) to see if J.C.'s prediction holds :)

It appears that contrary to J.C.'s prediction, it is 4 commits ahead (which is what I expected but was not so bold as to publicly predict :).  There are no file differences (as we both expected, since this was not a squash-merge).  I predict the "commits ahead" count will keep growing, but as long as we do not squash merges, there will be no file differences when you compare the branches after merging master -> beta (and ditto for prod).

**Comment by JohnCremona** [comment]
I cannot see how github thinks that beta is 4 commits ahead of master.  beta is now at a commit with two parents, one of which is master and the other is the previous beta,  That sounds like one ahead to me.

**Comment by AndrewVSutherland** [comment]
On the page https://github.com/LMFDB/lmfdb/tree/beta if you look at the 
grey text you will see "This branch is 4 commits ahead of master".

If you then go to https://github.com/LMFDB/lmfdb/compare/beta you will 
see a list of the 4 commits:

https://github.com/LMFDB/lmfdb/commit/d39935413e81ec9be14f6d177aa13442e4981792
https://github.com/LMFDB/lmfdb/commit/080da20d400a3ae60d7fc97bbb26b4250c659730
https://github.com/LMFDB/lmfdb/commit/e79f6d066364008f8611d4bf470064c3842114b6
https://github.com/LMFDB/lmfdb/commit/0e8c2b2cc0ae3baa8df3c071ee82404f08aabef1

Or are you seeing something different in github than I am?

**Comment by JohnCremona** [comment]
The page  https://github.com/LMFDB/lmfdb/compare/beta is a compare with master as base so it is showing you what would happen if you tried to merge the other way.  By comparison if you start to do a new pull reuest from master to beta (without confirming that you want to actually do this) it shows you
https://github.com/LMFDB/lmfdb/compare/beta...master
which says that there is nothing to be done: "beta is up to date with all commits from master".

So the incomprehensible thing (to me) is why, when looking at the code page for branch beta (https://github.com/LMFDB/lmfdb/tree/beta) it tells you that beta is 4 commits ahead.  That looks like a bug to me....and it is what is confusing us all.

**Comment by JohnCremona** [comment]
I am going to make a tiny new branch deleting one line from hilbert_modular_forms.py to satisfy #1332, then merge to master and then to beta and prod.  (I will test long the way!)  Then we'll see how these view change.  All merges will be non-squashed.

**Comment by AndrewVSutherland** [comment]
On 2016-05-18 08:02, John Cremona wrote:
> The page  https://github.com/LMFDB/lmfdb/compare/beta is a compare
> with master as base so it is showing you what would happen if you
> tried to merge the other way.

Right, it is showing the 4 commits (listed in my previous e-mail) that 
are in beta but not master (and which would be applied if you merged 
from beta to master).

These are the 4 commits by which beta is ahead.

>  By comparison if you start to do a new
> pull reuest from master to beta (without confirming that you want to
> actually do this) it shows you
> https://github.com/LMFDB/lmfdb/compare/beta...master
> which says that there is nothing to be done: "beta is up to date with
> all commits from master".

Right, beta is not behind master at all (it has every commit master 
does, as a result of merging the pull request from master), to that is 
why it says beta is up to date with all commits from master.

But notice that it does not say that the branches are identical (which 
it would if neither was ahead of the other). I guess the only thing we 
disagree on is the number of commits by which github thinks beta is 
ahead, I believe github thinks 4 (the 4 I listed in my previous e-mail), 
while you say 1.

> 
> So the incomprehensible thing (to me) is why, when looking at the code
> page for branch beta (https://github.com/LMFDB/lmfdb/tree/beta) it
> tells you that beta is 4 commits ahead.  That looks like a bug to
> me....and it is what is confusing us all.

I don't think this is a "bug", it is consistent with everything else you 
see in github (beta is 4 commits ahead and 0 commits behind master and 
their files are identical).  If you compare in one direction (imagining 
a pull request from beta to update master) you will see 4 commits (and 
no file changes), if you compare in the other direction (imagining a 
pull request from master to beta), you will see 0 commits because beta 
is not behind master at all.

Perhaps it would be better to characterize this as a "feature" that we 
do not particularly like (caused by the fact that every merge creates a 
commit that is then present in the target but not the source -- without 
squashing this commit will involve no file changes).  Subsequent merges 
in the same direction will not change this.

**Comment by JohnCremona** [comment]
OK, I misled you: I did not mean that guthub said that beta was 1 ahead of master, only that if you actually look at the commit beta is pointing to (0e8c2b2) then it has master (51ebe3e) as one of its immediate parents, so to go along the graph from master to beta is only one step.  Since the beta commit at 0e8c2b2 is a merge commit (from master and its previous state) it certainly follows that beta contains all changes in master, we are agreed on that.   There is still a mystery as to why there would be anything to do to merge beta onto master: their files are the same, and 3 of the 4 commits you list are merge commits while the other is not.  I think that the one which is not a merge might be the result of a (misguided) squash operation.

I will still do what I said above (merge a very small patch and see how things change).  If I am right that it was the sqush-merge which made the only non-merge commit in those 4, then we could improve the situation by (just this once) updating beta and prod on github  from master using the command line (as we always used to do) to have a fresh start where all three are literally at the same point (same commit), and then even though we would see these "n commits ahead of master" messages they would all be merges (and visibly so) so we would know that it was OK to ignore them.

**Comment by AndrewVSutherland** [comment]
On 2016-05-18 08:25, John Cremona wrote:
> OK, I misled you: I did not mean that guthub said that beta was 1
> ahead of master, only that if you actually look at the commit beta is
> pointing to (0e8c2b2) then it has master (51ebe3e) as one of its
> immediate parents, so to go along the graph from master to beta is
> only one step.  Since the beta commit at 0e8c2b2 is a merge commit
> (from master and its previous state) it certainly follows that beta
> contains all changes in master, we are agreed on that.   There is
> still a mystery as to why there would be anything to do to merge beta
> onto master: their files are the same, and 3 of the 4 commits you list
> are merge commits while the other is not.  I think that the one which
> is not a merge might be the result of a (misguided) squash operation.

Right, if we avoid squashes this will not happen and none of the commits 
by which beta (or prod) is ahead of master will include any file 
changes, they will just be "empty" merge commits.

> 
> I will still do what I said above (merge a very small patch and see
> how things change).  If I am right that it was the sqush-merge which
> made the only non-merge commit in those 4, then we could improve the
> situation by (just this once) updating beta and prod on github  from
> master using the command line (as we always used to do) to have a
> fresh start where all three are literally at the same point (same
> commit), and then even though we would see these "n commits ahead of
> master" messages they would all be merges (and visibly so) so we would
> know that it was OK to ignore them.

I agree 100% with everything you say in this paragraph!

**Comment by JohnCremona** [comment]
OK I did what I said and did all the merges and (as @AndrewVSutherland predicted) both beta and prod are 5 commits ahead of master, exactly one more than before and that's the new merge commit.

Shall I rest this counter (as it were) with a clean push?  So that these bogus extra commits in future are all merges with no code changes?

**Comment by AndrewVSutherland** [comment]
Yes, please do!  We should then all expect to see the "commits ahead" 
counter to get incremented by 1 with each merge from master to beta or 
prod (which we are agreeing to never squash, right?), and none of these 
commits will have any file changes in them.

**Comment by JohnCremona** [comment]
Done.  Yes, we are agreed to never use squash when merging from master to weither beta or prod.  It matters less when merging a PR into master but given the confusion it might cause I suggest that we do not do that either.

For the record: as of 14:00 BST on Wednesday 18 May all three branches master, beta, prod are idential and at the commit  9755a2efa91edd36ce29d46086f16f4a040beb79

**Pull request merged**
