### PR TITLE
Create pages at /L/lhash/<Lhash>/

### PR DESCRIPTION
**Pull request by davidlowryduda**
This is a progress update on having pages directly for each L-function.
We began thinking about doing this in #2269 and #2268.

There are some design choices that need to be made, which is why this
is a good place to stop and consider. This pull request is not ready to be
pulled right now.

With this pull request, it is possible to go to, for example, the L-functions

    http://localhost:37777/L/lhash/1938322253992393114/
    http://localhost:37777/L/lhash/dirichlet_L_6253.458/

These pages are arrived at from the lhash and values stored in the
database. For initial comparisons, other places where this exact
L-function appear in the "Instances" box in the gaga box. [In the
future, we may want to have a canonical page for each L-function, and
so this Instances box would need to be removed. I have indicated the
lines to remove in the code with `#TODO DLD` marks.] It is good to
compare the Lhash version against another instance, to see some
differences.

In the example above, there are a few obvious differences. Most of these
are because this "canonical" Lhash page doesn't know what sort of
L-function it is, and so it omits things displayed using this
information.

Let's see some of these for the first example page above.

1. The "Related objects" box on the side doesn't appear.

  This is because the related objects (created in `lfunctions.main.py`)
  populated the topics on the gaga box differently based on the type of
  the L-function. But Lhash doesn't have a type.

2. The Euler Product is displayed incorrectly.

  The Euler product is essentially gathered in `lfuncEPtex` in
  `lfunctions.Lfunctionutilities.py`. This has different cases depending
  on the type of the L-function. So an elliptic curve Euler product is
  constructed differently than a Dirichlet L-function's Euler product,
  for instance.

  I note that the good and bad factors are stored in the database. So it is
  possible to rewrite the Euler product constructor to produce the
  correct output using only the contents of the database. There is a
  question of presentation, though. Do we want a Dirichlet L-function's
  Euler product to have the correct `chi` displayed, for instance?

3. The plot of the Z-function doesn't appear.

  The plot is presented by modifying the url of the L-function to arrive
  at the url for the plot. It is possible to still do this, and just
  handle urls for the plots under Lhash's, but as this is an initial set
  of changes I thought that handling the plot is less important.

### CODE REVIEW

**Comment by edgarcosta** [comment]
As you can see my definition of "week" is quite wide.

1. Having some missing origins is okay by me, you can always force those to show up by adding an entry to the instances DB (even though the object doesn't exist).

On the same note, the related objects in one case are the symmetric square/cube, I'm not sure why we can't have those for every page, but if I recall correctly those are computed on the fly.

2. This is the trickiest one. I would still want to show the Euler factors, even if they are straightforward as in the case of the Dirichlet L-function. However, in that case I also want to write that each factor as a really simple description, given by chi. 
I'm not sure how to solve this one.
Perhaps, this could be an optional field on the DB? Where else you think one would like to have such description for the Euler factors?

3. Yes, I would not worry about the plot at the moment.

4. The name should be: "L-function of degree D, weight W, conductor N, and X character" with D, W, N, and X replaced accordingly.

**Comment by AndrewVSutherland** [comment]
@davidlowryduda What is the status of this PR.  Are you planning to make changes in response to @edgarcosta's comments?  Is their a timeline for when you think this will be ready to be merged?  It makes me nervous having PRs open for such a long period of time.

@davidfarmer do you have any feedback on this PR?

**Comment by davidlowryduda** [comment]
@AndrewVSutherland I think I got bogged down in thinking about how things should ideally be a bit too much. Thank you for the prompt. But I have in mind a path that should work.

I will make some changes per @edgarcosta's comments. I'll do this within the next week, and I think this can be made ready for merging shortly after. Now that you mention it, this PR has been open for a long time.

**Comment by davidlowryduda** [comment]
I believe this is ready to merge. Let me describe how I handled Edgar's comments.

1. I agree that having some missing origins is okay. It's more important to have access to the other instances of this L-function, and then one can determine their origins from their own pages.

2. I've removed the Euler product from the page entirely. To show the Euler product would require some additional information to be held in the database. Instead of displaying the Euler product, I have a bit of text encouraging viewers to check out other instances of that L-function.

3. Good. Instead of being blank, it now displays "Plot not available."

4. The name is now what you suggest.

@edgarcosta Would you mind taking another look?

**Comment by davidlowryduda** [comment]
Thanks to Edgar for pointing something out to me, plots are now available. So my point (3) has changed, and now plots are handled appropriately.

**Comment by edgarcosta** [comment]
I took a look and all looks good.

The failure is because: http://icms.org.uk/workshops/onlinedatabases from http://www.lmfdb.org/acknowledgment/activities got moved or deleted. We perhaps should stop testing that. @JohnCremona, what do you think?

**Comment by JohnCremona** [comment]
Note that master now has a fix for the onlinedatabases link, so as long as the tests do now pass I am happy with this.

**Comment by davidlowryduda** [comment]
Ok. I'll just pull the new changes to master and travis will rerun.

**Comment by JohnCremona** [comment]
@davidlowryduda Could you resolve the merge conflicts?

**Comment by davidlowryduda** [comment]
@JohnCremona Which merge conflicts? Is this not fully merged already?

I would be happy to resolve any conflicts, but I'm not quite sure how to see these conflicts. My local branch is fully merged without conflict, though.

**Comment by JohnCremona** [comment]
Apologies, last time I looked here there was a red X saying it coudn't be merged, but I had already merged it so I have no idea what that was about.  Ignore!

**Pull request merged**
