### PR TITLE
L-function search and browse

### PR DESCRIPTION
**Pull request by roed314**
We're aiming to allow users to browse and search among the 24 million L-functions in the database.  See https://teal.lmfdb.xyz/L/ and https://teal.lmfdb.xyz/L/rational for a version of the LMFDB running this branch.

We're providing a browse page analogous to the other sections of the LMFDB, rather than the hand-curated lists of L-functions currently shown on the [degree2](https://beta.lmfdb.org/L/degree2/), [degree3](https://beta.lmfdb.org/L/degree3/) and [degree4](https://beta.lmfdb.org/L/degree4/) pages.  As a consequence some of these L-functions will be harder to find: none of the GL2 Maass form L-functions are in the database, so they won't show up in search results (though they are still accessible as friends links from Maass form pages).  Some GL3, GL4 and GSp4 Maass forms are included in the database so they show up in the results (though some are broken: see #2845).

The other L-function browse pages that didn't easily fit into the new model are the [Maass form browse page](https://beta.lmfdb.org/L/degree2/MaassForm/) and signature pages [r0e3](https://beta.lmfdb.org/L/degree3/r0r0r0/) and [r0e4](https://beta.lmfdb.org/L/degree4/r0r0r0r0/).  We have a long term plan for incorporating these into a new type of search results (where the results would show up as a plot of dot-links rather than a list), but they're currently removed from the browse page.

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
Please don't merge this until I have merged a small PR I want to get into production before this one is merged to master (that should happen tonight or tomorrow morning).

**Comment by AndrewVSutherland** [comment]
FYI, there were test failures in ECNF and two pylint errors in lfunctions that should be fixed.

**Comment by JohnCremona** [comment]
> FYI, there were test failures in ECNF and two pylint errors in lfunctions that should be fixed.

Can I help with the ECNF things?  I looked at Travis output but could not see the failures easily.

**Comment by AndrewVSutherland** [comment]
Below are two test failures in ECNFs.  I also noticed failures in HMFs, BMFs, and G2C (almost all have to do with related objects, I'm guessing this is something @roed314 or @edgarcosta):
```
______________ EcnfIsogClassTest.test_ecnf_isclass_related_object ______________
self = <lmfdb.ecnf.test_isog_class.EcnfIsogClassTest testMethod=test_ecnf_isclass_related_object>
    def test_ecnf_isclass_related_object(self):
        r"""
        Check related object (near Properties box) of an ECNF isogeny class.
        """
        L = self.tc.get('/EllipticCurve/2.2.5.1/31.1/a/').get_data(as_text=True)
        assert 'Hilbert modular form 2.2.5.1-31.1-a' in L
    
        L = self.tc.get('/EllipticCurve/2.2.8.1/9.1/a/').get_data(as_text=True)
        assert 'Hilbert modular form 2.2.8.1-9.1-a' in L
>       assert 'Isogeny class 576.a' in L
E       AssertionError: assert 'Isogeny class 576.a' in '<!DOCTYPE html>\n<html lang="en">\n  <head>\n    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">\...middot;\n      SageMath version 9.1\n      &middot;\n      LMFDB Release 1.2\n    </div>\n</div>      </body>\n</html>'
lmfdb/ecnf/test_isog_class.py:47: AssertionError
```
```
self = <lmfdb.ecnf.test_ecnf.EllCurveTest testMethod=test_related_objects>
    def test_related_objects(self):
        for url, text in [('/EllipticCurve/2.0.8.1/324.3/a/1',
                ['Isogeny class 324.3-a',
                 'Twists',
                 'Base change of 36.a4',
                 'Base change of 576.f3',
                 'Bianchi modular form 2.0.8.1-324.3-a',
                 'Hilbert modular form 2.2.24.1-36.1-a',
                 'Isogeny class 2.2.24.1-36.1-a',
                 'Isogeny class 20736.i',
                 'L-function']),
                ('/EllipticCurve/2.0.11.1/256.1/b/1',
                    ['Isogeny class 256.1-b',
                     'Twists',
                     'Bianchi modular form 2.0.11.1-256.1-a',
                     'Bianchi modular form 2.0.11.1-256.1-b',
                     'Hilbert modular form 2.2.44.1-16.1-a',
                     'Hilbert modular form 2.2.44.1-16.1-c',
                     'Isogeny class 2.0.11.1-256.1-a',
                     'Isogeny class 2.2.44.1-16.1-a',
                     'Isogeny class 2.2.44.1-16.1-c',
                     'L-function'])]:
            L = self.tc.get(url).get_data(as_text=True)
            for t in text:
>               assert t in L
E               AssertionError: assert 'Isogeny class 2.2.24.1-36.1-a' in '<!DOCTYPE html>\n<html lang="en">\n  <head>\n    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">\...middot;\n      SageMath version 9.1\n      &middot;\n      LMFDB Release 1.2\n    </div>\n</div>      </body>\n</html>'
lmfdb/ecnf/test_ecnf.py:139: AssertionError
```

Here are two test failures in HMFs:

```
self = <lmfdb.hilbert_modular_forms.test_hmf.HMFTest testMethod=test_EC>
    def test_EC(self): #778
        L = self.tc.get('ModularForm/GL2/TotallyReal/5.5.126032.1/holomorphic/5.5.126032.1-82.1-b')
        assert 'EllipticCurve/5.5.126032.1/82.1/b/' in L.get_data(as_text=True)
    
        L = self.tc.get('/ModularForm/GL2/TotallyReal/2.2.89.1/holomorphic/2.2.89.1-2.1-a')
>       assert 'Isogeny class' in L.get_data(as_text=True)
E       AssertionError: assert 'Isogeny class' in '<!DOCTYPE html>\n<html lang="en">\n  <head>\n    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">\...middot;\n      SageMath version 9.1\n      &middot;\n      LMFDB Release 1.2\n    </div>\n</div>      </body>\n</html>'
E        +  where '<!DOCTYPE html>\n<html lang="en">\n  <head>\n    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">\...middot;\n      SageMath version 9.1\n      &middot;\n      LMFDB Release 1.2\n    </div>\n</div>      </body>\n</html>' = <bound method BaseResponse.get_data of <Response 16586 bytes [200 OK]>>(as_text=True)
E        +    where <bound method BaseResponse.get_data of <Response 16586 bytes [200 OK]>> = <Response 16586 bytes [200 OK]>.get_data
lmfdb/hilbert_modular_forms/test_hmf.py:24: AssertionError
```
```
self = <lmfdb.hilbert_modular_forms.test_hmf.HMFTest testMethod=test_friends>
    def test_friends(self):
        for url, texts, notitself in [
                ('/ModularForm/GL2/TotallyReal/2.2.5.1/holomorphic/2.2.5.1-31.1-a',
                    ('Hilbert modular form 2.2.5.1-31.2-a',
                        'Isogeny class 2.2.5.1-31.1-a',
                        'Isogeny class 2.2.5.1-31.2-a'),
                    'Hilbert modular form 2.2.5.1-31.1-a'),
                ('/ModularForm/GL2/TotallyReal/2.2.5.1/holomorphic/2.2.5.1-31.2-a',
                    ('Hilbert modular form 2.2.5.1-31.1-a',
                        'Isogeny class 2.2.5.1-31.1-a',
                        'Isogeny class 2.2.5.1-31.2-a'),
                    'Hilbert modular form 2.2.5.1-31.2-a'),
                ('/ModularForm/GL2/TotallyReal/2.2.497.1/holomorphic/2.2.497.1-1.1-a',
                    ('Isogeny class 2.0.7.1-5041.1-CMa',
                        'Isogeny class 2.0.7.1-5041.3-CMa',
                        'Isogeny class 2.2.497.1-1.1-a',
                        'Modular form 497.2.b.a'),
                    'Hilbert modular form 2.2.497.1-1.1-a'),
                ('/ModularForm/GL2/TotallyReal/2.2.8.1/holomorphic/2.2.8.1-32.1-a',
                    ('Bianchi modular form 2.0.8.1-32.1-a',
                        'Isogeny class 2.0.8.1-32.1-a',
                        'Isogeny class 2.2.8.1-32.1-a'),
                    'Hilbert modular form 2.2.8.1-32.1-a')
                ]:
            L = self.tc.get(url)
            for t in texts:
>               assert t in L.get_data(as_text=True)
E               AssertionError: assert 'Isogeny class 2.2.5.1-31.1-a' in '<!DOCTYPE html>\n<html lang="en">\n  <head>\n    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">\...middot;\n      SageMath version 9.1\n      &middot;\n      LMFDB Release 1.2\n    </div>\n</div>      </body>\n</html>'
E                +  where '<!DOCTYPE html>\n<html lang="en">\n  <head>\n    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">\...middot;\n      SageMath version 9.1\n      &middot;\n      LMFDB Release 1.2\n    </div>\n</div>      </body>\n</html>' = <bound method BaseResponse.get_data of <Response 16685 bytes [200 OK]>>(as_text=True)
E                +    where <bound method BaseResponse.get_data of <Response 16685 bytes [200 OK]>> = <Response 16685 bytes [200 OK]>.get_data
lmfdb/hilbert_modular_forms/test_hmf.py:129: AssertionError
```


Here is a test failure in BMFs:

```
self = <lmfdb.bianchi_modular_forms.test_bmf.BMFTest testMethod=test_friends>
    def test_friends(self):
        for url, texts, notitself in [
                ('/ModularForm/GL2/ImaginaryQuadratic/2.0.7.1/44.3/a/',
                    ('Bianchi modular form 2.0.7.1-44.4-a',
                        'Isogeny class 2.0.7.1-44.3-a',
                        'Isogeny class 2.0.7.1-44.4-a'),
                    'Bianchi modular form 2.0.7.1-44.3-a'),
                ('/ModularForm/GL2/ImaginaryQuadratic/2.0.7.1/44.4/a/',
                    ('Bianchi modular form 2.0.7.1-44.3-a',
                        'Isogeny class 2.0.7.1-44.3-a',
                        'Isogeny class 2.0.7.1-44.4-a'),
                    'Bianchi modular form 2.0.7.1-44.4-a'),
                ('/ModularForm/GL2/ImaginaryQuadratic/2.0.8.1/32.1/a/',
                    ('Hilbert modular form 2.2.8.1-32.1-a',
                        'Isogeny class 2.0.8.1-32.1-a',
                        'Isogeny class 2.2.8.1-32.1-a'),
                    'Bianchi modular form 2.0.8.1-32.1-a')
                    ]:
            L = self.tc.get(url)
            for t in texts:
>               assert t in L.get_data(as_text=True)
E               AssertionError: assert 'Isogeny class 2.0.7.1-44.3-a' in '<!DOCTYPE html>\n<html lang="en">\n  <head>\n    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">\...middot;\n      SageMath version 9.1\n      &middot;\n      LMFDB Release 1.2\n    </div>\n</div>      </body>\n</html>'
E                +  where '<!DOCTYPE html>\n<html lang="en">\n  <head>\n    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">\...middot;\n      SageMath version 9.1\n      &middot;\n      LMFDB Release 1.2\n    </div>\n</div>      </body>\n</html>' = <bound method BaseResponse.get_data of <Response 18213 bytes [200 OK]>>(as_text=True)
E                +    where <bound method BaseResponse.get_data of <Response 18213 bytes [200 OK]>> = <Response 18213 bytes [200 OK]>.get_data
lmfdb/bianchi_modular_forms/test_bmf.py:111: AssertionError
```

Here is a test failure in genus 2 curves:

```
self = <lmfdb.genus2_curves.test_genus2_curves.Genus2Test testMethod=test_related_objects>
    def test_related_objects(self):
        for url, friends in [
                ('/Genus2Curve/Q/20736/i/373248/1',
                    ('L-function',
                        'Isogeny class 20736.i',
                        'Elliptic curve 576.f3',
                        'Elliptic curve 36.a4',
                        'Isogeny class 2.0.8.1-324.3-a',
                        'Bianchi modular form 2.0.8.1-324.3-a',
                        'Hilbert modular form 2.2.24.1-36.1-a',
                        'Isogeny class 2.2.24.1-36.1-a',
                        'Twists',)
                    ),
                ('/Genus2Curve/Q/20736/i/',
                    ('L-function',
                        'Isogeny class 576.f',
                        'Isogeny class 36.a',
                        'Isogeny class 2.0.8.1-324.3-a',
                        'Bianchi modular form 2.0.8.1-324.3-a',
                        'Hilbert modular form 2.2.24.1-36.1-a',
                        'Isogeny class 2.2.24.1-36.1-a',)
                    ),
                ('/Genus2Curve/Q/576/a/',
                    ('L-function',
                        'Isogeny class 2.2.8.1-9.1-a',
                        'Modular form 24.2.d.a',
                        'Hilbert modular form 2.2.8.1-9.1-a',)
                    )
                ]:
            data = self.tc.get(url).get_data(as_text=True)
            for friend in friends:
>               assert friend in data
E               AssertionError: assert 'Isogeny class 2.0.8.1-324.3-a' in '<!DOCTYPE html>\n<html lang="en">\n  <head>\n    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">\...middot;\n      SageMath version 9.1\n      &middot;\n      LMFDB Release 1.2\n    </div>\n</div>      </body>\n</html>'
lmfdb/genus2_curves/test_genus2_curves.py:288: AssertionError
```

Home page:
```
self = <lmfdb.tests.test_homepage.HomePageTest testMethod=test_box1>
    def test_box1(self):
        r"""
        Check that the links in Box 1 work.
        """
        homepage = self.tc.get("/").get_data(as_text=True)
>       self.check(homepage, "/L/degree2/", '9.53369')
lmfdb/tests/test_homepage.py:14: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <lmfdb.tests.test_homepage.HomePageTest testMethod=test_box1>
homepage = '<!DOCTYPE html>\n<html lang="en">\n  <head>\n    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">\...middot;\n      SageMath version 9.1\n      &middot;\n      LMFDB Release 1.2\n    </div>\n</div>      </body>\n</html>'
path = '/L/degree2/', text = '9.53369'
    def check(self, homepage, path, text):
        assert path in homepage, "%s not in the homepage" % path
        assert text in self.tc.get(path, follow_redirects=True).get_data(
            as_text=True
>       ), "%s not in the %s" % (text, path)
E       AssertionError: 9.53369 not in the /L/degree2/
lmfdb/tests/__init__.py:28: AssertionError
```
Here is a test failure in Belyi:
```
self = <lmfdb.belyi.test_belyi.BelyiTest testMethod=test_friends>
    def test_friends(self):
        for url, friends in [
            ('/Belyi/4T5/4/4/3.1/a',
                ('Passport',
                    'Curve 48.a6',)
                ),
            ('/Belyi/5T3/5/4.1/4.1/a',
                ('Passport',
                    'Curve 2.0.4.1-1250.3-a3',)
                ),
            ('/Belyi/6T6/6/6/3.3/a',
                ('Passport',
                    'Curve 1728.b.442368.1',)
                )
            ]:
            data = self.tc.get(url).get_data(as_text=True)
            for friend in friends:
>               assert friend in data
E               AssertionError: assert 'Curve 48.a6' in '<!DOCTYPE html>\n<html lang="en">\n  <head>\n    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">\...middot;\n      SageMath version 9.1\n      &middot;\n      LMFDB Release 1.2\n    </div>\n</div>      </body>\n</html>'
lmfdb/belyi/test_belyi.py:147: AssertionError
```

**Comment by edgarcosta** [comment]
We should point out that we changed lmfdb/utils/names_and_urls.py

thus, we no longer say "Isogeny class" and now we say "Elliptic curve" or "Genus 2 curve".

Compare for example:
- https://teal.lmfdb.xyz/EllipticCurve/2.0.11.1/256.1/b/1
vs
- https://beta.lmfdb.org/EllipticCurve/2.0.11.1/256.1/b/1
- 
- https://teal.lmfdb.xyz/EllipticCurve/2.0.8.1/324.3/a/1
vs
- https://beta.lmfdb.org/EllipticCurve/2.0.8.1/324.3/a/1
I will keep fixing the tests

**Comment by edgarcosta** [comment]
The tests now pass.

**Comment by AndrewVSutherland** [comment]
@davidfarmer noticed an apparent bug: the search results for a search on root number -1 list 1 as the root number (but the results do appear to be L-functions with root number -1).See

https://teal.lmfdb.xyz/L/rational?hst=List&degree=2&root_number=-1&search_type=List

This should be fixed before we merge.

**Comment by edgarcosta** [comment]
On it

**Comment by edgarcosta** [comment]
Fixed

**Pull request merged**
