### PR TITLE
a bunch of python3 fixes suggested by pyflakes

### PR DESCRIPTION
**Pull request by fchapoton**
another set of rather simple fixes

* get rid of reduce, which is not available in python3
* some syntax errors in raise
* etc

### CODE REVIEW

**Comment by roed314** [comment]
These all look fine to me.  The only one that I'm a bit hesitant about is the change to `Factorization([(P,e) for P,edd in zip(badprimes,mindisc_ords)])`.  It looks like there's currently a bug that @fchapoton is fixing, but I wasn't able to find a current example where this problem appeared.

**Comment by edgarcosta** [comment]
I agree with you, it looks like we are fixing a bug. 
@JohnCremona will be the best person to approve that change.

**Comment by JohnCremona** [comment]
I'll take a look. The snippet quoted certainly looks bad but the exponents are to be ignored whatever identifier is used.

**Comment by JohnCremona** [comment]
> These all look fine to me. The only one that I'm a bit hesitant about is the change to `Factorization([(P,e) for P,edd in zip(badprimes,mindisc_ords)])`. It looks like there's currently a bug that @fchapoton is fixing, but I wasn't able to find a current example where this problem appeared.

Yes this was definitely a bug.  It would result in the exponents being wrong in the factorization of the minimal discriminant ideal whenever the exponents were not all equal to whatever the last value of "e" was.  The new code is much simpler (and this and the similar changes have nothing much to do with the Python 3 conversion other than because P3 is stricter about the values of dummy variables not being available after a list comprehension so that under P3 "the last value of e" would not exist).

If that was all, feel free to merge.

**Pull request merged**
