### PR TITLE
modifying display of q-expansion to always have 100 coefficients

### PR DESCRIPTION
**Pull request by assaferan**
Resolving issue #5040

### CODE REVIEW

**Comment by roed314** [comment]
I think there are more places that need to be changed:
* The "Trace form" sections of `cmf_full_gamma1_space.html` and `cmf_space.html`,
* The `show_exp` javascript functions should be deleted in all three files.

**Comment by assaferan** [comment]
Oops, thanks for catching this! Should be fixed now.

**Comment by roed314** [comment]
I like this change, but I want to hear other opinions about whether the default $$q$$-expansion shown for something like [3.14.a.b](http://localhost:37780/ModularForm/GL2/Q/holomorphic/3/14/a/b/) is too much.  If we think there's too much shown by default there, then we might need to tweak the parameters to [raw_typeset_qexp](https://github.com/LMFDB/lmfdb/blob/main/lmfdb/utils/web_display.py#L589) which has `compress_threshold=100` as a default, and then that variable does not seem to be used....

**Comment by roed314** [comment]
@AndrewVSutherland, what do you think?

**Comment by AndrewVSutherland** [comment]
I'm slightly puzzled as to why it is not compressing the 3.14.a.b q-expansion at all, e.g. as on http://127.0.0.1:37777/ModularForm/GL2/Q/holomorphic/882/4/g/z/

My assumption was that large q-expansions were going to be compressed (indeed, the original objection was that we say "show 100 coefficients" but often don't show 100 coefficients due to compression.

**Comment by assaferan** [comment]
It seems that until now the q-expansion would only be compressed if there was some compression in the coefficients. I modified it to instead use the compression threshold that was never used, as David suggested, and it seems better now, I think.

**Comment by roed314** [comment]
Looks good to me.  There are still a few modular forms that aren't compressed (e.g. [3600.1.e.a (localhost)](http://127.0.0.1:37777/ModularForm/GL2/Q/holomorphic/3600/1/e/a/)) but most of them are now compressed, which was the intention of #5040.

I'm happy to merge this, but will give @AndrewVSutherland a chance to weigh in.

**Comment by AndrewVSutherland** [comment]
Certainly 3600.1.e.a doesn't need any compression!

This looks pretty good, but I think we are being slightly too agresseive on the compression of the number of terms, for example compare

https://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/680/6/a/f/ (click to see 100 coefficients)
http://127.0.0.1:37777/ModularForm/GL2/Q/holomorphic/680/6/a/f/

I think we should be aiming to have compressed q-expansion extend roughly as far as the line above, and it's not the end of the world if it wraps to two lines.

**Comment by assaferan** [comment]
Just to be clear, if one looks at https://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/680/6/a/f/, the compression does not work well (at least not as intended) - there is no compression for the trace, and the form itself is being compressed starting with the first compressed term (which happens to be $$q^{19}$$). 

If we are being too aggressive, and would like the threshold to have more characters (e.g. as above), it's easy to do, but line / two lines is display dependent. Do we want the string to depend on the display parameters?

**Comment by AndrewVSutherland** [comment]
I thinks this looks good! (and no I don't think we should do anything display dependent)

**Pull request merged**
