### PR TITLE
remove dependency on gps_gl2zhat in web_ec.py

### PR DESCRIPTION
**Pull request by AndrewVSutherland**
This PR updates `gl2_subgroup_data` in `web_ec.py` which is used to render subgroup knowls for mod-ell/ell-adic image data on ECQ pages to use the new modular curves table `gps_gl2zhat_fine` for all queries.  Once this is merged and pushed to dev/prod we can delete the table `gps_gl2zhat`.

### CODE REVIEW

**Comment by roed314** [comment]
I'm trying to figure out where `gl2_subgroup_data` is called from so that I can test this.  `git grep gl2_subgroup_data` just returns
```
lmfdb/elliptic_curves/elliptic_curve.py:from lmfdb.elliptic_curves.web_ec import WebEC, match_lmfdb_label, match_cremona_label, split_lmfdb_label, split_cremona_label, weierstrass_eqn_regex, short_weierstrass_eqn_regex, class_lmfdb_label, curve_lmfdb_label, EC_ainvs, latex_sha, gl2_subgroup_data, CREMONA_BOUND, match_weierstrass_polys, match_coeff_vec
lmfdb/elliptic_curves/elliptic_curve.py:    return {'gl2_subgroup_data': gl2_subgroup_data}
lmfdb/elliptic_curves/web_ec.py:def gl2_subgroup_data(label):
```
none of which calls this function.  Is it called from a knowl somewhere?

**Comment by roed314** [comment]
The test failure looks spurious.

**Comment by AndrewVSutherland** [comment]
It's used as a context processor for the knowl gl2.subgroup_data which is used on elliptic curve pages, e.g.

http://127.0.0.1:37777/knowledge/show/gl2.subgroup_data?label=13.78.3.a.1
http://127.0.0.1:37777/knowledge/show/gl2.subgroup_data?label=13.78.3.1
http://127.0.0.1:37777/knowledge/show/gl2.subgroup_data?label=13Nn

will all exercise the new code, and can be compared to

https://beta.lmfdb.org/knowledge/show/gl2.subgroup_data?label=13.78.3.1
https://beta.lmfdb.org/knowledge/show/gl2.subgroup_data?label=13Nn

**Comment by roed314** [comment]
Ok, looks good.

**Pull request merged**
