### PR TITLE
Add Galois group search for abvar.fq_isog

### PR DESCRIPTION
**Pull request by roed314**

### CODE REVIEW

**Comment by roed314** [comment]
Great!  Do you know when this will go live on the website?  I think once it's up I'll send another e-mail to the list proposing adding abelian varieties to the sidebar.

**Comment by AndrewVSutherland** [comment]
My guess is we'll do a push to beta tomorrow, but I want to coordinate with @JohnCremona before doing so (there was a user management change made today that at least merits monitoring when it gets pushed just to be sure it doesn't break anything).

**Comment by roed314** [comment]
Sounds good.

**Comment by roed314** [comment]
Any updates on when this will get pushed to beta?

**Comment by JohnCremona** [comment]
Pushed to beta just now, should be live in 8 mins.

**Comment by AndrewVSutherland** [comment]
Okay @roed314, I think we are good to go, feel free to submit a PR whenever you are ready.

**Pull request merged**
