### PR TITLE
Create Stats Page for HigherGenus/C/Aut and fix URL issues

### PR DESCRIPTION
**Pull request by jenpaulhus**
This pull request does the following:
1.	Introduces a stats page for the /HigherGenus/Aut/C pages: http://127.0.0.1:37777/HigherGenus/C/Aut/stats  

2.	 Creates new pages from that stats page which give a complete list of all groups that appear for any fixed genus in the database.  See hgcwa-stats-group-per-genus.html. 

3.	Shortens the URL query strings (see #2277 ) for http://127.0.0.1:37777/HigherGenus/Aut/C pages. The code for this is in file: template/hgcwa-clean-submit.html  (we had to add some code to get rid of the ?include for dropdown menus too). 

4.	Fixes an error in typing certain bad labels. It turns out that if you enter a label which is almost correct but not quite correct, the production pages would return an error, instead of just a message saying that the label didn’t exist.  Observe the behavioral difference on the production version versus this pull request if you try to search for label 2.12-4.0.2-2-2-3.1.11, which doesn’t exist.   http://www.lmfdb.org/HigherGenus/C/Aut/?jump_to=2.12-4.0.2-2-2-3.1.11
vs.
http://127.0.0.1:37777/HigherGenus/C/Aut/?jump_to=2.12-4.0.2-2-2-3.1.11

5.	In order to make the group per genus pages work we added a field to the data in the database called group_order.  I seem to  remember I need to do something to make searching over this field easier (indexing?)  but I couldn’t exactly remember what I needed to do.

6. Since more pages have been added to the /HigherGenus/C/Aut pages,  I’ve added a few new tests as well. 

Question:
1. Capitalization of breadcrumbs.  I’ve noticed that on other pages most breadcrumbs are capitalized (like Completeness/Label/Source) but “statistics” was not.  So I didn’t capitalize it on these pages.  Should I? (I did capitalized “error” and “result” in the “Search Result” and “Search Error” breadcrumbs to conform with other pages.)  

2. Right now if you search with empty fields you get this URL:
   http://127.0.0.1:37777/HigherGenus/C/Aut/?all=1
and when you hit the “Search Again” button you get this URL:
   http://127.0.0.1:37777/HigherGenus/C/Aut/?start=0&paging=0
Is that appropriate behavior?

### CODE REVIEW

**Comment by jenpaulhus** [comment]
Not sure this travis fail is on my end.  All my tests past locally.

**Comment by edgarcosta** [comment]
@jenpaulhus, you are correct. I'm sorry that once again you need to deal with our automatic testing giving false negatives.

Copy pasting from #2299 
> The failure is because: http://icms.org.uk/workshops/onlinedatabases from http://www.lmfdb.org/acknowledgment/activities got moved or deleted. We perhaps should stop testing that.

**Comment by jenpaulhus** [comment]
No worries!  Just let me know when this is resolved and I'll make some trivial change and re-submit.

Jen

**Comment by JohnCremona** [comment]
Thanks for all this work!  It might take a while before I can look at and test it thoroughly but meanwhile I am running the automatic tests locally -- master has changed since this PR was made so the Travis report is out of date.

Meanwhile, there is a small pyflakes issue:
./scripts/higher_genus_w_automorphisms/import_cap_data.py:7: 'MongoClient' imported but unused
and if you can fix that (just delete that line) and update your branch then the test will run here again.

**Comment by jenpaulhus** [comment]
I think pyflakes should be happy now!  I had forgotten about that file in the scripts folder.  It generates the stats data, and should be run whenever new data is added.

**Comment by JohnCremona** [comment]
This looks really good!

Some missing knowls (or the wrong link) I spotted:
http://localhost:37777/HigherGenus/C/Aut/ (Group orders)
http://localhost:37777/HigherGenus/C/Aut/stats (refined passports and generating vectors)

To your specific questions:  1. capitalisation of breadcrumbs should of course be consistent but I am not very surprised that it is not.  Don't worry -- one day someone might feel like consistently dealing with this.

2. I would not worry -- as long as the results are the same, which they are.

3. Indexing.  Yes, there should be an index on group_order.  I just added one -- but that is on the beta database (as is any recent data you added) so the collections need to be copied to the cloud too.  So will the passports.stats collection before we push this new code to run on the main website.  Would you like me to refresh the collections passports, passports.rand and copy passports.stats to the cloud now?

**Comment by jenpaulhus** [comment]
Finally had a moment to get back to this. I forgot to mention in the original pull that the bulk of the code from this pull was written by one of my students @DeoxNA. 

I've fixed the knowl
http://localhost:37777/HigherGenus/C/Aut/ (Group orders)

Also fixed the knowls at the top of the page here
http://localhost:37777/HigherGenus/C/Aut/stats (refined passports and generating vectors)
I also removed them from inside the table as it seemed unnecessary since they are already at the top of the page.

Yes, please refresh the collections passport and passports.rand  and copy the passports.stats to the cloud.

**Comment by AndrewVSutherland** [comment]
The updated files have been copied to the cloud.  Is the PR now ready to merge?

**Comment by JohnCremona** [comment]
Fine by me (though I have not looked at the new version yet).  @jenpaulhus we should add @DeoxNA to the list of contributors (next time you do something just edit the file CONTRIBUTORS.yaml).

**Comment by jenpaulhus** [comment]
@DeoxNA is already added as a contributor. I preemptively added him just about the time I made this pull request initially.   Thanks for thinking of that, though!

**Comment by JohnCremona** [comment]
All looks very good!

**Comment by JohnCremona** [comment]
@jenpaulhus This is now running on beta.lmfdb.org

**Comment by jenpaulhus** [comment]
Thanks so much!

**Pull request merged**
