### PR TITLE
Fix bug in search by point count on modular curves

### PR DESCRIPTION
**Pull request by roed314**
Currently the point count search for modular curves is broken and always searches for non-cuspal points, regardless of the value of the dropdown.  This PR fixes the issue.

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
I don't understand the results of this search:

http://127.0.0.1:37777/ModularCurve/Q/?hst=List&level=6&index=12&points_type=all&contains_negative_one=yes&points=1&search_type=List&showcol=num_known_degree1_points

The unique search result 6.12.1.b.1 claims to have 2 rational cusps and no known rational points.

Also (and probably a separate issue), the Weierstrass model for this curve is 144a1, but this is not compatible with the decomposition of the Jacobian as 36.2.a.a

**Comment by AndrewVSutherland** [comment]
Should "non-CM" mean "non-CM and non-cuspidal" (probably it should, and maybe it does, but this isn't clear in the drop down).  I'm also confused by 6.12.0.b1, which based on the point count searches appears to satisfy all=17, non-CM=15, non-cusp=16, which is consistent with

http://127.0.0.1:37777/ModularCurve/Q/low_degree_points?curve=6.12.0.b.1&degree=1

if one supposes there is just one rational cusp, but there are two rational cusps.

Is there perhaps a problem with how cuspidal points are being counted?  I think this would explain both the inconsistencies that are bothering me.

**Comment by AndrewVSutherland** [comment]
I like j-points better (the cusps all correspond to a single j-point at  infinity).

I think there is still an issue with the non-CM points, if you look at

http://127.0.0.1:37777/ModularCurve/Q/?hst=List&level=6&index=18&points_type=noncm&contains_negative_one=yes&points=1&search_type=List&showcol=num_known_degree1_points

The counts don't make sense.

**Comment by roed314** [comment]
I'll take a look tomorrow; going to sleep early tonight.

**Comment by roed314** [comment]
The non-CM counts were including cusps.  I've updated the data, so it should be okay now.

**Pull request merged**
