### PR TITLE
Adding exclude option to search for bad primes in CMF

### PR DESCRIPTION
**Pull request by rbommel**
In accordance with issue #3771, this PR implements the exclude option for CMF.

### CODE REVIEW

**Comment by roed314** [comment]
Travis seems not to be starting automatically here either....

**Comment by roed314** [comment]
Maybe Raymond and Sam aren't part of the LMFDB organization on github, so travis doesn't automatically test their PRs?

**Comment by roed314** [comment]
Though it looks like it worked last week on #3764.

**Comment by AndrewVSutherland** [comment]
Travis received the pull request.  It is not starting the build because it is complaining that "sage" is an unknown language.

**Comment by AndrewVSutherland** [comment]
Actually it says the same thing about PR #3737 and it did run there, so I'm not sure that is the problem.  (fyi the language is set in travis.yml)

**Comment by AndrewVSutherland** [comment]
Travis says the builds are queued and are waiting for the virtual machine to start.  It is possible we are just seeing a resource issue with Travis.  I actually don't think it is a configuration problem on our end.

**Comment by AndrewVSutherland** [comment]
Pyflakes is not happy:

The command "pyflakes . > pyflakeslog" exited with 1.
0.01s$ if [[ $(wc -l < pyflakeslog) != 0 ]]; then echo "ERROR pyflakes failed!"; cat pyflakeslog; else echo "PASS pyflakes is happy!"; fi
ERROR pyflakes failed!
./lmfdb/classical_modular_forms/main.py:11: 'lmfdb.utils.SubsetBox' imported but unused

**Comment by roed314** [comment]
This is included in #3779 and should be closed if that PR is merged.

**Comment by AndrewVSutherland** [comment]
I plan to merge #3779 so I will close this (the Travis error is due to pyflakes)

**Pull request closed without merging**
