### PR TITLE
Use BytesIO instead of StringIO for Python3 downloads

### PR DESCRIPTION
**Pull request by roed314**
Many downloads currently fail in Python3.

### CODE REVIEW

**Comment by roed314** [comment]
Actually, looking at classical modular forms I think we might just be able to use the Python 3 solution in Python 2 as well.

**Comment by edgarcosta** [comment]
We should just import `BytesIO` from `six`:
```
This is a fake file object for binary data. 
In Python 2, it’s an alias for StringIO.StringIO, 
but in Python 3, it’s an alias for io.BytesIO
```
https://six.readthedocs.io/#six.BytesIO

and we can always encode it:
https://github.com/LMFDB/lmfdb/blob/master/lmfdb/utils/downloader.py#L143

**Comment by roed314** [comment]
Okay, switched to using `BytesIO` all the time.

**Comment by AndrewVSutherland** [comment]
@roed314 This PR seems to have broken all Maass form downloads due to the change you made at line 227 of lmfdb/modular_forms/maass_forms/maass_waveforms/views/mwf_main.py, where you are trying to execute the encode method of a ditctionary (which does not have such a methid).  Can you please submit a PR to fix this as soon as you can (getting the download working again would be a big help in trying to sort out some of the recent Maass form problems).

**Comment by edgarcosta** [comment]
Checkout #3786

**Comment by roed314** [comment]
I'll take a look in an hour or so.
David

**Pull request merged**
