### PR TITLE
Do not display broken L-fun links for EC over quadratic fields

### PR DESCRIPTION
**Pull request by edgarcosta**

### CODE REVIEW

**Comment by edgarcosta** [comment]
#2706 takes care of avoiding broken links

**Comment by JohnCremona** [comment]
An example to show the effect of this:
http://localhost:37780/EllipticCurve/2.0.218017403.1/1.0.1/a/1
has an L-function link but clicking on it raises an error -- a properly displayed error saying "No L-function instance data for "EllipticCurve/2.0.218017403.1/1.0.1/a" was found in the database."

I will check out the revised code...

**Comment by edgarcosta** [comment]
I will look into it,
as db.lfunc_instances.exists({'url':'EllipticCurve/2.0.218017403.1/1.0.1/a'})
returns False

**Comment by JohnCremona** [comment]
I meant that the example displayed the error message before applying your patch, not after.  I have not tested the patch yet.

**Comment by AndrewVSutherland** [comment]
@edgarcosta Are you going to resolve the merge conflict?

**Comment by edgarcosta** [comment]
I will look into this later, not a priority at the moment.

**Comment by davidlowryduda** [comment]
While visiting Edgar (thanks again Edgar, David, and Drew for your hospitality), I resolved the merge conflict. With this, the page `/EllipticCurve/2.0.218017403.1/1.0.1/a/1` displays `L-function not available` instead of offering a link to a broken page.

**Comment by AndrewVSutherland** [comment]
Thanks for fixings this David!

**Pull request merged**
