### PR TITLE
get rid of several string escape deprecation warnings

### PR DESCRIPTION
**Pull request by JohnCremona**
This fixes most of the deprecaton warnings mentioned at #4327, and a few unnecessary print statements.  In one file I changed the way some Sage things were being imported as one of those also raised a warning.

### CODE REVIEW

**Comment by edgarcosta** [comment]
all the changes look good to me, and the tests pass.

I modified one import statement, to be backward compatible with sage 9.1.
I can't upgrade Travis right now to sage 9.2

**Comment by JohnCremona** [comment]
Ah, I had not realised that Travis was on 9.1.  Thanks for the extra fix.

**Comment by JohnCremona** [comment]
I restarted the Travis build anyway.

**Comment by JohnCremona** [comment]
It's a pyflakes failure but I don't see the output -- where's pyflakes log file on Travis?

**Comment by JohnCremona** [comment]
The problem is that it does not know what ModuleNotFoundError is.  @edgarcosta !

**Comment by JohnCremona** [comment]
This makes no sense to me -- I ran these import lines on sage 9.1 on another machine and it works fine.  I see that ModuleNotFoundError is new to Python 3.6 though.  Which python version was used in the Travis build of Sage 9.1?  Can you run that and see what happens when you enter "from sage.banana import banana"?

**Comment by JohnCremona** [comment]
I think I should revert the change of import of verbose in that file and we can ignore the deprecation warning until Travis gets Sage 9.2.   @edgarcosta you did not make sorting this out any easier by making a code change directly on github!  I think I will have to close this PR and make a new one.

**Comment by edgarcosta** [comment]
@JohnCremona Thanks.

You can always edit other people PRs, and I was planning to fix this 👍

**Pull request merged**
