### PR TITLE
BMF & ECNF: minor updates for new data for 2.0.19.1

### PR DESCRIPTION
**Pull request by JohnCremona**
I have added BMF and ECNF data for a new field, Q(sqrt(-19)).  Some minor code changes were needed.  This PR also clears out old redundant upload scripts.

When these changes are pushed to prod, the ec_nfcurves tabel should also be copied.  By that time I will have also updated the relevant RCS knowls.

This PR relates to #4573, and the code update fixes something noticed in #4576.

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
ec_nfcurves has been copied to production

**Comment by JohnCremona** [comment]
> ec_nfcurves has been copied to production

Thanks!  2.0.43.0 should not be much longer, I have almost got to level norm 10000 with the BMFs.  Meanwhile if you could also copy bmf_forms and bmf_dims then these new curves should have matching forms on prod (except for one conjugate pair which does not, but this should be indicated properly).

**Comment by AndrewVSutherland** [comment]
Does bmf_forms also need to be copied over?

**Comment by JohnCremona** [comment]
Yes please (see above)

**Comment by AndrewVSutherland** [comment]
Done!  See https://www.lmfdb.org/ModularForm/GL2/ImaginaryQuadratic/2.0.19.1/19.1/a/.

**Pull request merged**
