### PR TITLE
Isogeny classes for elliptic curves over Q

### PR DESCRIPTION
**Pull request by JohnCremona**
See issue #1985 

The missing data has been added by rewriting the collection 'curves' to 'newcurves'; at the same time, for each curve, a new data field called 'isogeny_degree' was added for every curve.

The code changes here 
1. change the collection name from curves to newcurves (temporary);
2. avoid all elliptic curve construction in creating an instance of class ECisog_class, which happens every time an isogeny class is displayed;
3. adjusted one test of an isogeny class page
4. Show on each e.c. home page a list of the isogeny degrees (if any)
4. fix an unrelated test in hmfs 
5. add an irrelevant file by mistake -- I will update this PR in a minute.

I have not yet implemented searching for curves by specifying a desired isogeny degrees; that will be done in a future PR.

### CODE REVIEW

**Comment by JohnCremona** [comment]
NB It is safe to merge to master and beta but *not* to prod until the new collection has been copied to the cloud.

**Comment by JohnCremona** [comment]
Please hold off testing on this: I am recreating the curves.new collection and will be updating the branch.

**Comment by JohnCremona** [comment]
OK to review again.  Ignore commit 0fe0fe9, I started something new then commented it out.
The rewritten data is still in a collection called new since the old code should work fine on it.

There was a bug (the permutation used to convert between Cremona and LMFDB numbers was inverted in  the code which displays isogeny classes).  I also found some more data gliitches and fixed them, also providing a new script function which checked that every one of the 2.5 million curve recordsin the database has the correct fields and that these have the correct types.

**Comment by JohnCremona** [comment]
Currently doing final testing after recreating the collection so that the isogeny matrices are stored in lmfdb order (as they used to be for N<230000) with no need to reorder on the fly, and so that the old code for isogeny classes displays properly with the new collection, for ease of transition.

Yet another new version of the isogs branch up soon.

**Comment by JohnCremona** [comment]
OK, good for testing again.

**Comment by AndrewVSutherland** [comment]
Looks good.

**Pull request merged**
