### PR TITLE
Remove many instances of web_latex_split_on_pm as katex handles this well

### PR DESCRIPTION
**Pull request by alexjbest**
See #3444 for discussion, maybe @edgarcosta can make a branch for people to see this, or people can test the old way of course!
I saw no issues with any page I tested with this (and I tried hard to ensure I looked at every possible impacted page). Having done this it looks like a win-win to me.

Maybe more testing to make sure I didnt break web_latex_poly would be good

### CODE REVIEW

**Comment by edgarcosta** [comment]
Running on red.lmfdb.xyz

**Comment by JohnCremona** [comment]
Please post some links to pages which are different now to allow people to compare.

**Comment by alexjbest** [comment]
@JohnCremona apologies, here are some of the main examples:
In all cases before clicking a long math string (like a q-expansion) would select one term only to copy, now the whole expression will be selected. The important difference is that if you click and drag to select a whole expression previously and copy paste it there will be a lot of $ signs between each term and mathstruts which was not good for pasting into a tex document of CAS.
Importantly the new code should still not overflow or look weird if the string is too long for the screen, it should still break on a plus or minus and continue on the next line as before.

https://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/1410/2/a/k/
https://red.lmfdb.xyz/ModularForm/GL2/Q/holomorphic/1410/2/a/k/
changes affected the q-expansion trace expansion and hecke polynomials

https://www.lmfdb.org/NumberField/30.30.20159382829191092591451779536401274948781988965475418112.1
https://red.lmfdb.xyz/NumberField/30.30.20159382829191092591451779536401274948781988965475418112.1
should affect the defining polynomial.

I can give more if you like as I made changes to many sections (hilbert mfs, hecke chars, mod l) also but those changes were the same and so these should be representative.

**Comment by JohnCremona** [comment]
Thanks.  I see that (as explained in #3444) the idea is not to have the display look any different, and as far as I can see it does not so I have no objection.

Since we already provide code snippets (in some places) and download options for data, I don't think we should expend a lot of effort trying to make formulas on web pages cut-and-pastable.  But I have no objection to this being merged.

**Comment by alexjbest** [comment]
@JohnCremona yes exactly, though the number field example looks ever so slightly different to my eye on chrome (with the new one looking better of course as the spacing around +- being more balanced and compact now).

I don't propose we do expend any effort doing anything more in this direction right now. But as you say the code snippets are not present for CMFs for instance, and even if they are it can take some time for a CAS to produce the data again. (You are right that someone can download data to get a q-expansion as a list for instance, I'm just lazy and like to copy paste directly from the website ;).)

**Pull request merged**
