### PR TITLE
Fix #1803

### LINKED ISSUE #1803: Server errors on many Maass form pages
Many Maass form pages are throwing internal server errors that show up in the flasklogs of the www.lmfdb.org server.  This is apparently due to some sort of data inconsistency -- the specified ids are object ids of records in MaassWaveForms/Coefficients (e.g. see http://www.lmfdb.org/api/MaassWaveForms/Coefficients/4f55571188aece241f00000d for the first example listed below), but the ObjectId listed in the coeff_id attribute of that record is not found.

There are at least 49 affected pages:

http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f55571188aece241f00000d
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f5692ca88aece2afe000002
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f5693de88aece2afe00000e
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f56952f88aece2afe00001e
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f5697fc88aece2afe00003e
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f56984e88aece2afe000044
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f56990188aece2afe00004d
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f56990388aece2afe00004e
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f56990888aece2afe00004f
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f56990b88aece2afe000050
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f56991588aece2afe000051
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f56991f88aece2afe000053
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f56992188aece2afe000054
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f56998f88aece2afe00005e
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f56999c88aece2afe000060
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f5699a288aece2afe000061
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f5699a588aece2afe000062
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f5699ad88aece2afe000063
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f569a1588aece2afe00006d
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f569a1c88aece2afe00006e
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f569a2288aece2afe00006f
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f569a2688aece2afe000070
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f569a2a88aece2afe000071
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f569a2e88aece2afe000072
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f569a3088aece2afe000073
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f569a3588aece2afe000074
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f569a3b88aece2afe000076
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f569a8488aece2afe000081
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f569a8788aece2afe000082
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f569a8c88aece2afe000083
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f569a8e88aece2afe000084
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f569a9088aece2afe000085
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f569a9288aece2afe000086
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f569a9c88aece2afe000088
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f569aa188aece2afe000089
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f569aa388aece2afe00008a
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f569aa488aece2afe00008b
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f569aaa88aece2afe00008c
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f5929f388aece2afe0000d3
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f5d541f88aece4440000025
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f5d544288aece4440000026
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f5d546188aece4440000027
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f5d549888aece4440000028
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f5d54bc88aece4440000029
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f5d5a7488aece444000002a
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f5d5ab188aece444000002b
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f5d5aea88aece444000002c
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f5d5b5688aece444000002d
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f5d5ba088aece444000002e

### PR DESCRIPTION
**Pull request by AndrewVSutherland**
This is a simple fix for #1803; it returns a 404 page not found error when a lookup for a maass form fails because the record is not present in the FS collection.

So the pages listed in #1803 will now all give a page not found error, compare:

http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f55571188aece241f00000d
http://127.0.0.1:37777/ModularForm/GL2/Q/Maass/4f55571188aece241f00000d

It does the same things for plot requests, compare:

http://www.lmfdb.org/ModularForm/GL2/Q/Maass/plot/4f55571188aece241f00000d
http://127.0.0.1:37777/ModularForm/GL2/Q/Maass/plot/4f55571188aece241f00000d

And it will handle L-function errors (rather than displaying a page that looks quasi-reasonable at first glance but actually has no information in it other than a claim the level is 1, which has no basis, it will say the same thing for any string of 24 hex chars you type in for the object id)

http://www.lmfdb.org/L/ModularForm/GL2/Q/Maass/4f55571188aece241f00000d
http://127.0.0.1:37777/L/ModularForm/GL2/Q/Maass/4f55571188aece241f00000d

To see that maass forms that are in the database still display correctly (whether they have a plot or not), compare:

http://www.lmfdb.org/ModularForm/GL2/Q/Maass/4cb8503a58bca91458000032 (scroll down for plot)
http://127.0.0.1:37777/ModularForm/GL2/Q/Maass/4cb8503a58bca91458000032

http://www.lmfdb.org/ModularForm/GL2/Q/Maass/53222e00acf7560f8ad4cd64 (no plot)
http://127.0.0.1:37777/ModularForm/GL2/Q/Maass/53222e00acf7560f8ad4cd64

You can also see that the scatter plots still work:

http://www.lmfdb.org/ModularForm/GL2/Q/Maass/BrowseGraph/1/10/0/10/
http://127.0.0.1:37777/ModularForm/GL2/Q/Maass/BrowseGraph/1/10/0/10/
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/BrowseGraph/100/250/0/2/
http://127.0.0.1:37777/ModularForm/GL2/Q/Maass/BrowseGraph/100/250/0/2/
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/BrowseGraph/100/1000/0/1/
http://127.0.0.1:37777/ModularForm/GL2/Q/Maass/BrowseGraph/100/1000/0/1/

And you can try creating a table (e.g. type in level 1) at

http://www.lmfdb.org/ModularForm/GL2/Q/Maass/
http://127.0.0.1:37777/ModularForm/GL2/Q/Maass/

### CODE REVIEW

**Comment by JohnCremona** [comment]
STarted to review this but I must be missing something or have done something wrong:

In the first example, the error page on www.lmfdb.org is already quite detailed, and not a server error.  The new one gives less informatin.

The second is good -- page not found instead of server error.

The third:  on www.lmfdb.org I get a page saying that the eros and plot are not available, while with this branch I get a server error (KeyError: 'massid 4f55571188aece241f00000d not found in database')

This is running commit 504a969

**Comment by AndrewVSutherland** [comment]
@JohnCremona Regarding the first example, the "detailed" error message is very misleading, it will say exactly the same thing no matter what object id is specified regardless of whether there is any or no data in the LMFDB related to it.  This PR gives a more "accurate" error message, i.e. we know nothing about the specified object id.  Consider

http://www.lmfdb.org/ModularForm/GL2/Q/Maass/aaaaaaaaaaaaaaaaaaaaaaaa
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/zzzzzzzzzzzzzzzzzzzzzzzzzzz

The only difference between those two URLs is that the first corresponds to a legal object id (i.e. 24 hex characters) and the second does not, but neither of them has anything to do with any Maass form stored in the LMFDB and both should be treated as object not found.  The earlier interim "fix" I put in in PR #1807 was really a red herring.  None of the URLs listed in #1803 corresponds to a record in MaassWaveForms/FS (which is where the code looks), the only thing they have in common is that they do correspond to a record in MaassWaveForms/Coefficients (which is presumably why a robot was requesting them), but in fact the code never looks at MaassWaveForms/Coefficients (as you can verify using --dbmon=MaassWaveForms), only MaassWaveForms/Coefficients.chunks and MaassWaveForms/Coefficients.Files are used, and these collections are accessed only **after** a successful lookup in MaassWaveForms/FS.

I'm still not sure how a robot every found these object ids in the first place, but it is clear to me that we should treat any object id that is not in MaassWaveForms/FS as a 404 (to verify this, note that the count of 16599 Maass forms displayed on http://www.lmfdb.org/ModularForm/GL2/Q/Maass/ is exactly the number of objects in MaassWaveForms/FS.

All of this confusion is due to the fact that the constructor method for the MaassWaveForm class will construct a partially filled in object no matter what object id you give it. It's as if the EllipticCurve class would create a an object corresponding to the label 11.b1 with conductor set to 11 and isogeny class set to 11.b that looks like it is a partially filled in elliptic curve object even though now elliptic curve with this label exists.  Displaying a message saying that the curve equation, j-invariant, etc... are missing from the database for elliptic curve 11.b1 would not be helpful.

**Comment by AndrewVSutherland** [comment]
Regarding the third example, consider

http://www.lmfdb.org/L/EllipticCurve/Q/11.b/

So when you try to display the L-function of an elliptic curve that does not exist, it gives you an error message saying that this elliptic curve does not exist.  This is much better than having it display the page of an L-function with conductor set to 1 and everything else either blank, marked as missing, or set to a value that is the same for every elliptic curve L-function, which is effectively what 

http://www.lmfdb.org/L/ModularForm/GL2/Q/Maass/4f55571188aece241f00000d

is doing, whereas

http://127.0.0.1:37777/ModularForm/GL2/Q/Maass/53222e00acf7560f8ad4cd64

is behaving exactly as it would if you tried to display the L-function of an elliptic curve with a label that does not exist in the database.

**Comment by JohnCremona** [comment]
Thanks for the explanations -- all fine but I still got a KeyError (which would cause a server error) from the 3rd example.

**Comment by AndrewVSutherland** [comment]
@JohnCremona Don't run in debug mode (you are hitting the code in render_lfunction_exception in Lfunctions.py that intentionally raises errors when you are running in debug mode -- I can change this behavior if you like, since it seems to be causing a lot of confusion (I'm not the one that put it there)).

**Comment by JohnCremona** [comment]
Sorry, I always run in debug mode when running locally.  I'll test again.

**Comment by JohnCremona** [comment]
OK, I am happy now, though I think it a rather odd design decisino to have errors raised in debug mode which are not errors when not in debug mode!

**Pull request merged**
