### PR TITLE
Fix HGCWA Stats

### PR DESCRIPTION
**Pull request by jenpaulhus**
This pull request is to update stats on the HGCWA pages and it takes care of part of #2755.  At the bottom of this explanation I mention two small issues we're having related to the stats data and which I hope someone who understands the stats tables in postgres better than me will immediately be able to tell me how to fix! 

Updated page:
http://localhost:37777/HigherGenus/C/Aut/stats
vs
https://beta.lmfdb.org/HigherGenus/C/Aut/stats

We took this opportunity to add stats for quotient genus >0 also and modified the list of groups per genus page to also reflect topological and braid equivalence up through genus 7 (where that data has been added so far).  
http://localhost:37777/HigherGenus/C/Aut/stats/groups_per_genus/4
vs
https://beta.lmfdb.org/HigherGenus/C/Aut/stats/groups_per_genus/4
(also quotient genus >0 data is added through genus 4 at the bottom of these pages)

The HGCWA data is a unique little snowflake and so we didn't just follow the given stats framework.  In particular, a lot of the stats data is relatively static on these pages, i.e. once a new genus is added to the database, many of its stats are fixed.  

So we created two new tables in the db: hgcwa_unique_groups and hgcwa_complete which store much of the data which is presented the new stats page. The schema for both of them is located here:
https://github.com/jenpaulhus/group-actions-RS/blob/master/Schema.md

The one exception is the dimension data which will continue to grow across all values as the genus increases.  So we used the stats_display code to make that table (found at the bottom of our stats page).

There are 2 data issues for dimension, however, that I am not exactly sure how to fix because I don't really understand the stats tables postgres stores.  One issue is that right now there are two entries for each of dimension 0 through 10. The other is that some of the values where there are no entries of that dimension do show up (e.g. dim=22) but there are others where it does not show up (e.g. dim=16, 18, etc). I'm not sure how I managed to do these two things.

Credits:
One of my students, @kwang23 did a large amount of the work for this PR. I've added his name to contributors (I think we are still listing people there, instead of on individual section pages).

@ngonhi  and @370417  coded some of the original MongoDB versions in Summer 2018, and some of their code is used here to.

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
@roed314 Have you had a chance to look at this?

**Comment by roed314** [comment]
I was busy preparing for my talk on Monday in STAGE, then working on some other stats PRs yesterday.  I'm looking at this now.

**Comment by roed314** [comment]
@jenpaulhus Currently the summary has less information than the short summary (these are the snippets at the top of the homepage and the top of the stats page).  Should we just set `short_summary = summary + "Here are some further statistics"`?  Or do you want these to be different in this way?

**Comment by roed314** [comment]
Overall it looks good!  Here are some comments, and I'll be submitting a PR to your PR with some fixes and improvements.

* I wouldn't include the text data files in the code repository.  I've deleted them in my PR, which I think is enough (I don't think they're big enough that we need to worry about excising them from the history).
* It would be good to include knowls for the terms in the headers (genus, dimension, etc).
* It would be nice if as many of the counts as possible could be links to search results (I think this is possible for the "distinct generating vectors" row of the first table for example).  It's nice for people to be able to get examples of the kind of objects that you're enumerating.  I know that for some of these counts, this would require additional search functionality which probably needs to wait for another PR.

**Pull request merged**
