### PR TITLE
Add order of root of unity on number field page

### PR DESCRIPTION
**Pull request by jwj61**
Addresses issue #2527 by displaying the order of the root of unity on individual pages of number fields.

### CODE REVIEW

**Comment by JohnCremona** [comment]
Thanks!  Checking it out.

**Comment by JohnCremona** [comment]
Something is causing all totally real fields (I think) to fail -- not just this branch but on beta (and even legendre.mit.edu).  www.lmfdb.org/NumberField/1.1.1.1  

Surely nothing to do with this PR but something is broken somewhere.  In Artin reps I think.

**Comment by AndrewVSutherland** [comment]
It seems OK on www.lmfdb.org (in particular, the link to Q you posted works for me) but not on beta, and the link http://beta.lmfdb.org/NumberField/2.2.5.1 also throws a server error.

Needless to say, we should *NOT* merge to prod until this is fixed.

**Comment by AndrewVSutherland** [comment]
Just to be clear, this has nothing to do with this PR.

**Comment by JohnCremona** [comment]
So it must be a data issue with some collection not copied to the cloud.  Since lots of number field tests fail this must be recent -- in fact since Travis pass this PR!  Perhaps @jwj61 can help.

**Comment by jwj61** [comment]
I suspect that the current problems are with Artin representations as you guessed.  I was adding a feature which meant storing a new field in the database, but forgot that artin rep'ns are more complicated.  Reverting the change is in progress.

**Comment by jwj61** [comment]
It should be back now.

**Pull request merged**
