### PR TITLE
Fix for #1753

### PR DESCRIPTION
**Pull request by AndrewVSutherland**

### CODE REVIEW

**Comment by JohnCremona** [comment]
Looks good, will test.

**Comment by JohnCremona** [comment]
The final breadcriumb is now fine but not the penultimate, which gives the amazing error
TypeError: Error executing code in GP: CODE: sage[89]=bnrinit(sage[82],sage[87],sage[88]); PARI/GP ERROR: *** at top-level: sage[89]=bnrinit(sage[82],sag *** ^-------------------- *** bnrinit: domain error in Idealstar: ideal = 0

the previous code resulted in a URL here ending in 8.4a1 but your fix changes that to some latex!

**Comment by AndrewVSutherland2** [comment]
Good catch, will fix

**Comment by AndrewVSutherland** [comment]
Should be fixed now.

**Comment by JohnCremona** [comment]
OK, checking again...

**Pull request merged**
