### PR TITLE
fixed labels for holomorphics in degree 2 L-function browse page

### PR DESCRIPTION
**Pull request by JohnCremona**
This corrects all the wrong labels for holomorphic degree 2 L-functions, fixing Issue #1117

### CODE REVIEW

**Comment by JohnCremona** [comment]
To test, go to L/degree2/ and click on all the links in any row with "holomorphic".  I fixed 8 of them.

**Comment by davidfarmer** [comment]
My merge comment seems to have been lost:

I will add tests after I also fix the degree 3 and 4 browsing page (those have to be fixed because of PR #1114, currently under review by me )

**Comment by JohnCremona** [comment]
thanks, I have pushed to beta & prod.

**Comment by JohnCremona** [comment]
For adding tests smoothly take a look at lmfdb/test_homepage.html and the function check(self, homepage, path, text)

**Pull request merged**
