### PR TITLE
Dirichlet modulus/order/conductor tables and browse item spacing

### PR DESCRIPTION
**Pull request by AndrewVSutherland**
More minor UI cleanup for Release 1.2 with the following changes:
- Dirichlet modulus table now truncates at order 8 to keep tables from scrolling horizontally off the screen, compare [new](https://blue.lmfdb.xyz/Character/Dirichlet/?modbrowse=41-60) vs [old](https://www.lmfdb.com/Character/Dirichlet/?modbrowse=41-60)
- Dirichlet conductor and order browse not return search results, ranges have been changed, compare [new](https://blue.lmfdb.xyz/Character/Dirichlet/) vs [old](https://www.lmfdb.org/Character/Dirichlet/) (click order/conductor ranges).
- Interlink spacing in browse by search links have been uniformized to match number field browse (two nbsp; between entries, no commas).  Compare [new](https://blue.lmfdb.xyz/EllipticCurve/Q/) vs [old](https://www.lmfdb.org/EllipticCurve/Q/) for example (there are similar changes that impact almost all of the browse pages)

You can see this on https://blue.lmfdb.xyz.

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
I'm going to close this for a bit while I make a few more tweaks

**Comment by AndrewVSutherland** [comment]
OK, this is ready for review.  In order to get consistent formatting in all the browse sections I created a new "browse" table class that is now used in all the browse pages.  I also added a few browse options in places where it seemed useful.  The browse pages for ECNF, HMF, and BMF have the most visible changes, but there is at least some change on every browse page outside of the L-functions section (these were not changed).

CMF: [before](https://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/) [after](https://blue.lmfdb.xyz/ModularForm/GL2/Q/holomorphic/)
Maass: [before](https://beta.lmfdb.org/ModularForm/GL2/Q/Maass/) [after](https://blue.lmfdb.xyz/ModularForm/GL2/Q/Maass/)
HMF: [before](https://beta.lmfdb.org/ModularForm/GL2/TotallyReal/) [after](https://blue.lmfdb.xyz/ModularForm/GL2/TotallyReal/)
BMF: [before](https://beta.lmfdb.org/ModularForm/GL2/ImaginaryQuadratic/) [after](https://blue.lmfdb.xyz/ModularForm/GL2/ImaginaryQuadratic/)
SMF: [before](https://beta.lmfdb.org/ModularForm/GSp/Q/) [after](https://blue.lmfdb.xyz/ModularForm/GSp/Q/)
ECQ: [before](https://beta.lmfdb.org/EllipticCurve/Q/) [after](https://blue.lmfdb.xyz/EllipticCurve/Q/)
ECNF: [before](https://beta.lmfdb.org/EllipticCurve/) [after](https://blue.lmfdb.xyz/EllipticCurve/)
G2C: [before](https://beta.lmfdb.org/Genus2Curve/Q/) [after](https://blue.lmfdb.xyz/Genus2Curve/Q/)
HGC: [before](https://beta.lmfdb.org/HigherGenus/C/Aut/) [after](https://blue.lmfdb.xyz/HigherGenus/C/Aut/)
AV: [before](https://beta.lmfdb.org/Variety/Abelian/Fq/) [after](https://blue.lmfdb.xyz/Variety/Abelian/Fq/)
Belyi: [before](https://beta.lmfdb.org/Belyi/) [after](https://blue.lmfdb.xyz/Belyi/)
NF: [before](https://beta.lmfdb.org/NumberField/) [after](https://blue.lmfdb.xyz/NumberField/)
LF: [before](https://beta.lmfdb.org/LocalNumberField/) [after](https://blue.lmfdb.xyz/LocalNumberField/)
DC: [before](https://beta.lmfdb.org/Character/Dirichlet/) [after](https://blue.lmfdb.xyz/Character/Dirichlet/)
Artin: [before](https://beta.lmfdb.org/ArtinRepresentation/) [after](https://blue.lmfdb.xyz/ArtinRepresentation/)
HGM: [before](https://beta.lmfdb.org/Motive/Hypergeometric/Q/) [after](https://blue.lmfdb.xyz/Motive/Hypergeometric/Q/)
GG: [before](https://beta.lmfdb.org/GaloisGroup/) [after](https://blue.lmfdb.zyz/GaloisGroup/)
ST: [before](https://beta.lmfdb.org/SatoTateGroup/) [after](https://blue.lmfdb.xyz/SatoTateGroup/)
Lattices: [before](https://beta.lmfdb.org/Lattice/) [after](https://blue.lmfdb.xyz/Lattice/)

I also made sure that the jump boxes all handle the "banana test" correctly (typing an invalid label such as "banana" into the jump box should flash an error on the main page, it should not take you to a search results error page (you can ignore the triple error message in Dirichlet characters, this has been fixed in a PR that was merged after this branch was created).

**Comment by AndrewVSutherland** [comment]
One other thing to note, in the "Browse by .blah: first-choice ... last-choice" lines in the browse section, if the choices listed do not exhaust the possibilities a $\cdots$ should appear at the and of the list as a cue the user that there are more possibilities for blah than are listed, but I did not make $\cdots$ into a search link (this isn't easy/feasible to do in all cases), but I think this is fine.

**Comment by JohnCremona** [comment]
Great job!!  I looked at BMF, HMF, ECQ, ECNF, NF and DC.  (It is *so* useful and conveient to have these before/after links!  A lot easier than having to pull branches etc.  Thanks for making this so easy).
I'm not 100% sure about not having anything other than whitespace between the columns (there use to be commas as they were lists), but that's a negligible thing.

I hope others will look at the ones I did not yet.  +1 from me.

**Comment by jenpaulhus** [comment]
I'm happy with HGC.  Thanks!

**Comment by jwj61** [comment]
Sections I looked at look good

**Comment by AndrewVSutherland** [comment]
I think this is ready to merge.  If there is anyone who has not had a chance to look at it and would like to do so before I merge this, please chime in soon (we can of course still make changes after it is merged).  I'm happy to wait if there is a good reason to, but otherwise I'd like to try and wrap up Release 1.2 (formerly known as 1.1.2) today.

**Comment by edgarcosta** [comment]
Looks good to me

**Comment by AndrewVSutherland** [comment]
I just resolved a merge conflict (caused by merging #4178 ).  I will merge this PR once tests pass.

**Comment by AndrewVSutherland** [comment]
Travis still hasn't started 2 of the 5 jobs, but the tests pass on grace so I am going to merge this.

**Pull request merged**
