### PR TITLE
Show isogeny classes instead of curves in 'Jacobian is isogenous to...'

### PR DESCRIPTION
**Pull request by rbommel**
This should resolve issue #4478. You can see the changes for example on:
http://localhost:37777/Genus2Curve/Q/196/a/21952/1 and http://localhost:37777/Genus2Curve/Q/196/a/

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
There is a test failure caused by this change in "test_by_curve_label".  Presumably it is looking for a complete elliptic curve label where there is no only an isogeny class label.

**Comment by AndrewVSutherland** [comment]
lmfdb/genus2_curves/test_genus2_curves.py:23: AssertionError

**Comment by rbommel** [comment]
Okay, I changed this now. Hopefully it works, but I have no way to test it myself as the test script doesn't run anymore in my Legendre account. It says "no module named 'lmfdb.utils'".

**Comment by AndrewVSutherland** [comment]
Looks good.

**Pull request merged**
