### PR TITLE
Bianchi download skeleton

### PR DESCRIPTION
**Pull request by bebr117**
A tiny amount of skeleton code for downloading properties of Bianchi modular forms (Issue #4053 ). Based on the analogous code used for Hilbert modular forms.

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
I think @barinder has copied this skeleton into the code he is working on;  given that this PR is generating pyflakes complaints and to avoid merge conflicts latter, I'm going to close this, but thanks for submitting it!

**Comment by barinder** [comment]
> I think @barinder has copied this skeleton into the code he is working on; given that this PR is generating pyflakes complaints and to avoid merge conflicts latter, I'm going to close this, but thanks for submitting it!

Hey Andrew,

I haven't copied this skeleton ;), I guess you've wrongly tagged me. Mostly I work on Drupal, let me know if you need any help in Drupal. And also if I can be any help to you in this project too. :)

**Comment by JohnCremona** [comment]
@bebr117 was meant I think: Barinder Banwait.

**Comment by AndrewVSutherland** [comment]
@JohnCremona Indded, apologies for the confusion!

**Pull request closed without merging**
