### PR TITLE
Some modular forms improvements

### LINKED ISSUE #1505: Attempt to render classical modular form page gets stuck in an infinite loop (sage bug?)
Go to the elliptic curve isogeny class http://www.lmfdb.org/EllipticCurve/Q/234446/a/ and click on the modular form link http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/234446/2/1/a/.

This should result in a message saying the form is not in the database, but instead the page hangs and eventually times out with a 502 server error.  Similar behavior occurs for several other (but by no means all) elliptic curve isogeny classes.

If you run the lmfdb server locally, it appears to go into an infinite loop (or at least a multi-hour computation) inside sage while attempting to process this request (it is unclear to me why it should be accessing Sage at all, it only needs to determine that the form is not in the database).

Pressing ctrl-C yields an apparently infinite traceback, a portion of which appears below:

```
Traceback (most recent call last):
  File "/usr/local/sage/sage-1/local/lib/python/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/sage/sage-1/local/lib/python/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/sage/sage-1/local/lib/python/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/sage/sage-1/local/lib/python/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/local/sage/sage-1/local/lib/python2.7/site-packages/Werkzeug-0.11.4-py2.7.egg/werkzeug/serving.py", line 216, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/local/sage/sage-1/local/lib/python/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/sage/sage-1/local/lib/python2.7/site-packages/Werkzeug-0.11.4-py2.7.egg/werkzeug/serving.py", line 251, in handle_one_request
    return self.run_wsgi()
  File "/usr/local/sage/sage-1/local/lib/python2.7/site-packages/Werkzeug-0.11.4-py2.7.egg/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/usr/local/sage/sage-1/local/lib/python2.7/site-packages/Werkzeug-0.11.4-py2.7.egg/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/sage/sage-1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/sage/sage-1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/sage/sage-1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/sage/sage-1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/drew/github/lmfdb/lmfdb/modular_forms/elliptic_modular_forms/views/emf_main.py", line 130, in render_elliptic_modular_forms
    return render_web_newform(**info)
  File "/home/drew/github/lmfdb/lmfdb/modular_forms/elliptic_modular_forms/views/emf_render_web_newform.py", line 42, in render_web_newform
    info = set_info_for_web_newform(level, weight, character, label, **kwds)
  File "/home/drew/github/lmfdb/lmfdb/modular_forms/elliptic_modular_forms/views/emf_render_web_newform.py", line 71, in set_info_for_web_newform
    WNF = WebNewForm_cached(level=level, weight=weight, character=character, label=label)
  File "/home/drew/github/lmfdb/lmfdb/modular_forms/elliptic_modular_forms/backend/web_newforms.py", line 965, in WebNewForm_cached
    F = WebNewForm(level,weight,character,label,**kwds)
  File "sage/misc/classcall_metaclass.pyx", line 329, in sage.misc.classcall_metaclass.ClasscallMetaclass.__call__ (build/cythonized/sage/misc/classcall_metaclass.c:1188)
    return cls.classcall(cls, *args, **kwds)
  File "sage/misc/cachefunc.pyx", line 973, in sage.misc.cachefunc.CachedFunction.__call__ (build/cythonized/sage/misc/cachefunc.c:5376)
    w = self.f(*args, **kwds)
  File "/usr/local/sage/sage-1/local/lib/python2.7/site-packages/sage/structure/unique_representation.py", line 1021, in __classcall__
    instance = typecall(cls, *args, **options)
  File "sage/misc/classcall_metaclass.pyx", line 496, in sage.misc.classcall_metaclass.typecall (build/cythonized/sage/misc/classcall_metaclass.c:1614)
    return (<PyTypeObject*>type).tp_call(cls, args, kwds)
  File "/home/drew/github/lmfdb/lmfdb/modular_forms/elliptic_modular_forms/backend/web_newforms.py", line 516, in __init__
    else False),
  File "/home/drew/github/lmfdb/lmfdb/modular_forms/elliptic_modular_forms/backend/web_character.py", line 233, in __init__
    self._default_value = WebChar_cached(modulus, number, update_from_db=True, compute=True)
  File "/home/drew/github/lmfdb/lmfdb/modular_forms/elliptic_modular_forms/backend/web_character.py", line 273, in WebChar_cached
    X = WebChar(modulus,number,**kwds)
  File "sage/misc/classcall_metaclass.pyx", line 329, in sage.misc.classcall_metaclass.ClasscallMetaclass.__call__ (build/cythonized/sage/misc/classcall_metaclass.c:1188)
    return cls.classcall(cls, *args, **kwds)
  File "sage/misc/cachefunc.pyx", line 973, in sage.misc.cachefunc.CachedFunction.__call__ (build/cythonized/sage/misc/cachefunc.c:5376)
    w = self.f(*args, **kwds)
  File "/usr/local/sage/sage-1/local/lib/python2.7/site-packages/sage/structure/unique_representation.py", line 1021, in __classcall__
    instance = typecall(cls, *args, **options)
  File "sage/misc/classcall_metaclass.pyx", line 496, in sage.misc.classcall_metaclass.typecall (build/cythonized/sage/misc/classcall_metaclass.c:1614)
    return (<PyTypeObject*>type).tp_call(cls, args, kwds)
  File "/home/drew/github/lmfdb/lmfdb/modular_forms/elliptic_modular_forms/backend/web_character.py", line 92, in __init__
    update_from_db=update_from_db
  File "/home/drew/github/lmfdb/lmfdb/modular_forms/elliptic_modular_forms/backend/web_object.py", line 344, in __init__
    self.init_dynamic_properties()
  File "/home/drew/github/lmfdb/lmfdb/modular_forms/elliptic_modular_forms/backend/web_character.py", line 134, in init_dynamic_properties
    self.sage_character = self.character.sage_character()
  File "dirichlet_conrey.pyx", line 1475, in dirichlet_conrey.DirichletCharacter_conrey.sage_character (dirichlet_conrey.c:19264)
  File "dirichlet_conrey.pyx", line 395, in dirichlet_conrey.DirichletGroup_conrey.standard_dirichlet_group (dirichlet_conrey.c:6601)
  File "sage/structure/factory.pyx", line 361, in sage.structure.factory.UniqueFactory.__call__ (build/cythonized/sage/structure/factory.c:1469)
    key, kwds = self.create_key_and_extra_args(*args, **kwds)
  File "sage/structure/factory.pyx", line 459, in sage.structure.factory.UniqueFactory.create_key_and_extra_args (build/cythonized/sage/structure/factory.c:2602)
    return self.create_key(*args, **kwds), {}
  File "/usr/local/sage/sage-1/local/lib/python2.7/site-packages/sage/modular/dirichlet.py", line 1903, in create_key
    base_ring = rings.CyclotomicField(e)
  File "sage/structure/factory.pyx", line 363, in sage.structure.factory.UniqueFactory.__call__ (build/cythonized/sage/structure/factory.c:1551)
    return self.get_object(version, key, kwds)
  File "sage/structure/factory.pyx", line 406, in sage.structure.factory.UniqueFactory.get_object (build/cythonized/sage/structure/factory.c:1906)
    obj = self.create_object(version, key, **extra_args)
  File "/usr/local/sage/sage-1/local/lib/python2.7/site-packages/sage/rings/number_field/number_field.py", line 1098, in create_object
    return NumberField_cyclotomic(n, names, embedding=embedding)
  File "/usr/local/sage/sage-1/local/lib/python2.7/site-packages/sage/rings/number_field/number_field.py", line 8895, in __init__
    maximize_at_primes=maximize_at_primes)
  File "/usr/local/sage/sage-1/local/lib/python2.7/site-packages/sage/rings/number_field/number_field.py", line 6444, in __init__
    assume_disc_small=assume_disc_small, maximize_at_primes=maximize_at_primes, structure=structure)
  File "/usr/local/sage/sage-1/local/lib/python2.7/site-packages/sage/rings/number_field/number_field.py", line 1223, in __init__
    embedding = number_field_morphisms.create_embedding_from_approx(self, embedding)
  File "sage/rings/number_field/number_field_morphisms.pyx", line 494, in sage.rings.number_field.number_field_morphisms.create_embedding_from_approx (build/cythonized/sage/rings/number_field/number_field_morphisms.c:7033)
    if not P.is_exact() or f(gen_image) != 0:
  File "sage/structure/element.pyx", line 1007, in sage.structure.element.Element.__richcmp__ (build/cythonized/sage/structure/element.c:9714)
    return coercion_model.richcmp(self, other, op)
  File "sage/structure/coerce.pyx", line 1801, in sage.structure.coerce.CoercionModel_cache_maps.richcmp (build/cythonized/sage/structure/coerce.c:18652)
    return PyObject_RichCompare(x, y, op)
  File "sage/structure/element.pyx", line 1005, in sage.structure.element.Element.__richcmp__ (build/cythonized/sage/structure/element.c:9690)
    return (<Element>self)._richcmp_(<Element>other, op)
  File "sage/structure/element.pyx", line 1040, in sage.structure.element.Element._richcmp_ (build/cythonized/sage/structure/element.c:9871)
    c = left._cmp_(right)
  File "sage/rings/real_lazy.pyx", line 699, in sage.rings.real_lazy.LazyFieldElement._cmp_ (build/cythonized/sage/rings/real_lazy.c:8630)
    left, right = self.approx(), other.approx()
  File "sage/rings/real_lazy.pyx", line 771, in sage.rings.real_lazy.LazyFieldElement.approx (build/cythonized/sage/rings/real_lazy.c:9311)
    return self.eval(self._parent.interval_field())
  File "sage/rings/real_lazy.pyx", line 1133, in sage.rings.real_lazy.LazyBinop.eval (build/cythonized/sage/rings/real_lazy.c:12492)
    left = self._left.eval(R)
  File "sage/rings/real_lazy.pyx", line 1133, in sage.rings.real_lazy.LazyBinop.eval (build/cythonized/sage/rings/real_lazy.c:12492)
    left = self._left.eval(R)
  File "sage/rings/real_lazy.pyx", line 1133, in sage.rings.real_lazy.LazyBinop.eval (build/cythonized/sage/rings/real_lazy.c:12492)
...
```

### PR DESCRIPTION
**Pull request by sehlen**
This PR includes:
- Do not compute values and other properties of WebChar in init, in particular this fixes #1505
- some smaller fixes in the modular forms code, not really affecting the website currently.

All tests passed.

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
Testing now...

**Comment by AndrewVSutherland** [comment]
@sehlen emf_test_pages.py is now complaining about spaces with weight 0, did you intend to create records for these?  Should I change emf_test_pages.py to ignore them?

**Comment by sehlen** [comment]
Ha, great that you use the test script. It's not critical at all but I just deletde them. I'm not entirely sure how it happened but probably in some update script where I accidentally started the iteration at 0.

**Comment by sehlen** [comment]
Same for weight 1 - deleting now.

**Comment by sehlen** [comment]
It's ok to leave it in the test, because the records should not really be there I guess.

**Comment by AndrewVSutherland** [comment]
OK I think this looks good.  For the record, there are still database problems with the following spaces (which I understand has nothing to do with this change request but is relevant to #1248).

[u'13.4.2', u'20.9.11', u'21.2.5', u'21.2.4', u'22.2.3', u'23.10.2', u'25.9.2', u'26.10.25', u'27.8.4', u'27.9.2', u'27.10.4', u'28.7.13', u'28.7.15', u'28.9.13', u'28.9.15', u'29.6.28', u'29.7.2', u'29.8.16', u'29.8.28', u'29.9.2', u'29.10.4', u'29.10.28', u'30.7.11', u'30.7.29', u'30.9.11', u'30.9.29', u'31.1.30.a', u'31.7.3', u'31.8.9', u'31.9.3', u'31.10.9', u'32.4.21', u'32.6.21', u'36.5.5', u'37.5.2', u'37.7.2', u'37.8.16', u'37.9.8', u'37.9.2', u'37.10.4', u'37.10.16', u'38.10.23', u'39.10.2', u'43.10.9', u'43.10.41', u'46.10.3', u'47.1.46', u'47.8.2', u'47.10.2', u'49.5.6', u'49.7.6', u'49.8.8', u'49.8.2', u'49.9.6', u'49.10.8', u'49.10.2', u'50.2.49', u'50.4.49', u'50.7.3', u'50.8.9', u'50.9.3', u'50.10.9']

**Pull request merged**
