### PR TITLE
Minor tweaks to higher genus pages

### PR DESCRIPTION
**Pull request by AndrewVSutherland**
Small changes to some of the html templates for families of higher genus curves to add know links and  tweak wording.

### CODE REVIEW

**Comment by JohnCremona** [comment]
Quick question: the knowl 'curve.highergenus.aut.full' does not exist.  Is the idea to make one or will one of g2c.aut_grp or g2c.geom_aut_grp serve?  The latter in particular makes no reference to any specific genus; the former does but only after giving the general definition.
Otherwise this is good to go.

**Comment by AndrewVSutherland** [comment]
Yes, I will create the knowl as soon as this is merged to beta.  Neither 
g2c.aut_grp or g2c.geom_aut_grp is appropriate.

**Comment by AndrewVSutherland** [comment]
@JohnCremona Apologies for not making that clear in the PR description.

**Comment by JohnCremona** [comment]
No problem.

**Pull request merged**
