### PR TITLE
fix for issue #562 (heading for ecnf isogeny class page)

### PR DESCRIPTION
**Pull request by JohnCremona**
This fixes the issue, and also makes a similar fix for the Properties box and includes nf knowls for the base field.  All in 3 lines -- a bargain!

### CODE REVIEW

**Comment by jwj61** [comment]
I think we had a general preference to not use knowls in the property box.  The item will appear in the main part of the page as a knowl, but the properties box gets just text.

**Comment by JohnCremona** [comment]
OK, I will make that change.  Thanks for looking.

**Comment by JohnCremona** [comment]
OK now?

**Comment by jwj61** [comment]
Not working for me.  I think you need 

self.ECNF.field.field_pretty()

instead of field_pretty(self..)

**Comment by JohnCremona** [comment]
That's funny, I'm sure it worked for me.  For example 
http://localhost:37777/EllipticCurve/2.2.5.1/31.1/a/1
gives no problems?

Meanwhile I added another small fix for issue #589 to this p.r.

**Pull request merged**
