### PR TITLE
Add doctesting, unittesting to tests

### PR DESCRIPTION
**Pull request by davidlowryduda**
**Note: This is not ready to be pulled yet.**

In #2177, John Cremona asked about adding in doctesting into our testing suite. This is possible, and the change to the testing suite is minimal (it now includes `--with-doctest`).

We also don't have any unittests in the code, but this is possible from our framework as well. So I've added an example unittest for utils.py, as well as a template unittest in case others felt inclined to see what this looks like. This is only good, I think.

However, there is a downside to incorporating doctests. Before, the only python files called during testing were files of the form test_<something>.py. An advantage and disadvantage of doctests is that now generic python files are called during testing, and docstrings are parsed to give doctests. The disadvantage here is that this also means that the various scripts and files that some have made for importing data to the database or testing for database coverage are called.

This has two negative side effects. 

1. Firstly, this causes files which are actually scripts (in the sense that their functionality isn't hiding behind functions) to be called. This is clearly a bad thing. As an example, this causes lmfdb/modular_forms/elliptic_modular_forms/emf_db_stats.py (which computes some statistics related to the database, and which takes some time) to run.

2. This also causes several scripts (such as lmfdb/local_fields/import_fields.py) to run. These should fail, and cause spurious errors. But it is dangerous to run random import scripts throughout the code.

Both of these are resolved by separating out scripts into the scripts/ directory, instead of lying somewhere within lmfdb/. I believe this is the intention of the scripts/ directory, but I wasn't certain enough to move those scripts first. It is also possible to avoid testing files which satisfy a REGEX, such as being named `import_<restOfFilename>.py`. But this wouldn't catch emf_db_stats.py, for example.

It is also possible to have a separate doctest call, which only calls certain files. We would probably want to doctest utility functions, but much of the frontend display code is not appropriate for doctesting.

Alternately, we may simply choose to not have doctests. It is still possible (and I think desirable) to include unittests, with or without doctests. But doctests have some nice properties.

So I ask others, what do you think is the best path to follow? I am happy to pursue any of these (or another) courses of action regarding tests (though I think that incorporating some unittests is a good idea).

### CODE REVIEW

**Comment by haraldschilly** [comment]
Yes, running doctests on the code as it is now is not a good idea. Back then when I disabled it, I started https://github.com/LMFDB/lmfdb-data as a separate repository related to all these ETL tasks. It's not so easy, though, because these scripts here depend on the lmfdb code as a library. Hence I think lmfdb itself needs to be a submodule inside that lmfdb-data repository and then everyone can start to move over their  scripts. Next step would be to also add tests for these import/load tasks, and later test scripts to validate/verify the data inside the database.

**Comment by AndrewVSutherland** [comment]
Import scripts should reside in sub-directories of lmfdb/scripts, see open issue #1837.  So lmfdb/local_fields/import_fields.py should probably be moved to lmfdb/scripts/local_fields/import_fields.py (but @Jwj61 would be the one to confirm this).

I think doctesting across the board is likely to be more trouble than it is worth, but for utility functions it makes sense.  unittests are definitely desirable across the board (including utility functions), and should already be present in most modules (although there are certainly a lot of places where more could be added).   Many unittests are designed to check particularly annoying special cases that are data dependent and probably would not get hit by doctesting  (a good rule of thumb is that every time you fix a non-trivial bug you should add a unittest that verifies the fix, this also makes it easier for us to review pull requests).

The only constraint on unittests is that they should not be too time consuming-- it should be feasible to run https://github.com/LMFDB/lmfdb/blob/master/test.sh with no arguments (meaning it will run all unittests across the entire code base) on atkin in a reasonably short period of time (e.g. 10 minutes).  This is something we do anytime we are reviewing a non-trivial PR that is not completely localized (note that even apparently local changes to modules like numberfields or lfunctions, for example, can easily break code unittests outside of these modules).

**Comment by jwj61** [comment]
I just moved two import scripts.  Let me know if there are others I overlooked.

**Comment by davidlowryduda** [comment]
I like the the view of @AndrewVSutherland and @haraldschilly and, in particular, I now think that doctesting across the board is  probably more trouble than it is worth. I also think that unittests are desirable, including local unit tests for things like utility functions, as well as the end-to-end tests we have for many modules.

I'm going to close this pull request. I will later put a list of the scripts within the website code that I came across on #1837. And I will also begin to write some unit tests for utility functions.

**Comment by JohnCremona** [comment]
Sorry for being late to comment but I wanted to make certain that we are all talking about the same location for "the scripts directory".  Relative to the lmfdb base (containing start-lmfdb.py for example) there is a scripts directory, with subdirectories for different sections (e.g. genus2_curves), and that is the one meant here.
There is also (by mistake possibly) a directory (relative to the same base) ./lmfdb/scripts, whoc contents I think should be moved to ./scripts, perhaps into ./scripts/Lfunctions.

**Comment by AndrewVSutherland** [comment]
@JohnCremona Right, the "correct" directory is https://github.com/LMFDB/lmfdb/tree/master/scripts, the files in https://github.com/LMFDB/lmfdb/tree/master/lmfdb/scripts should be moved.  I will do this once a verify there are no code dependencies on the current location.

The key point is that only code that runs as part of the website should live under https://github.com/LMFDB/lmfdb; everything else should live somewhere else.  This will simplify unit testing, tracking down code dependencies and pyflakes issues, etc...

**Comment by JohnCremona** [comment]
Agreed.  Note that we do allow code in the import scripts to import functions from the website directory, so that utility functions (e.g. constructing a number field element from a string representation, that sort of thing) is only implemented once.

**Comment by AndrewVSutherland2** [comment]
Sure, we just don't want dependencies going the other way.

**Pull request closed without merging**
