### PR TITLE
Dirichlet search

### PR DESCRIPTION
**Pull request by pascalmolin**
implement search page for Dirichlet characters similar to other search pages.
and solves #1506

No 'next' or 'previous' buttons right now (there is some code already but I gave up for the moment, anyway these buttons launch a new search which can be entered manually)

Tests pass.

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
@pascalmolin Thanks for this!  I'll review it shortly.

**Comment by AndrewVSutherland** [comment]
@pascalmolin This isn't quite right, now none of the pages will load (the problem is changing the name of render_characterNavigation to main broke all the breadcrumbs that reference render_characterNavigation).

Given that you are not able to test things right now, what I might suggest is that you update your PR to undo the changes in your most recent "change routes" commit, I will go ahead and merge and then fix the routing issues (and any other problems I find).  Is that OK with you?

**Comment by pascalmolin** [comment]
OK, I reverted the last commit (sorry for the errors, I did not expect this
careless commit to update the PR).

Pascal

2016-07-01 15:13 GMT+02:00 Andrew Sutherland <notifications@github.com>:

**Comment by AndrewVSutherland** [comment]
@pascalmolin Thanks (and no worries, not everyone realizes that while you have an outstanding PR any further commits you make on the same branch will automatically be included in it).  I will go ahead and merge and take it from here.

**Pull request merged**
