### PR TITLE
Galois orbits for Dirichlet Characters

### PR DESCRIPTION
**Pull request by BarinderBanwait**
This addresses #4172 - creating pages for Galois orbits of Dirichlet characters. A demo of the new functionality is available on the [pink branch](https://pink.lmfdb.xyz); e.g. the Galois orbit [35.f](https://pink.lmfdb.xyz/Character/Dirichlet/35/f).

The comments of @davidfarmer made on the original ticket have been implemented, although I was not able to determine how the orbits have been labelled; it seems it is lexicographic based on the order, but I can't see how to distinguish between orbits of the same order. The "Source of the Data" page tells me that the data was computed using Jonathan Bober's package, so I have reached out to him for clarification on this point. However, this information will be put into the shiny new [knowledge page](https://beta.lmfdb.org/knowledge/show/character.dirichlet.conrey.orbit_label), and not be under source control in this repo, so I feel that opening this PR with this outstanding issue is still warranted.

@AndrewVSutherland's review comments have also been implemented. Since these were given virtually in a Friday session, here they are recorded: all pertain to searching for Dirichlet characters

1. Have the orbit label show leftmost on the results table, before Conrey labels;
2. Make these orbit labels into URLs;
3. Remove the vdots display and replace with cdots to save vertical space.

Some modest unit testing has also been added. This passes locally on legendre.

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
The orbit labels are determined by lexicographically ordering the Galois orbits of a given modulus N using the the Galois invariant vector

   [Order(chi), Trace(chi(2)), Trace(chi(3)), ..., Trace(N-1)]

The labels that are used in the LMFDB were not computed by Bober's code, they were computed using the Magma code developed for the CMF project.  See 

https://github.com/JohnCremona/CMFs/blob/56e7397dabcdcc522894cd951ceb88ba4dabc895/magma/chars.m#L196

for the function that compares Dirichlet characters in this lexicogrpahic ordering, as well as functions that will compute representatives for each Galois orbit in the correct order (see CharacterOrbitReps or ConreyCharacterOrbitReps, the first returns a list of Magma Dirichlet characters, the second returns a list of Conrey labels of minimal representatives).

**Comment by davidfarmer** [comment]
I don't have any other comments, based on what I see at pink.

**Comment by AndrewVSutherland** [comment]
@BarinderBanwait It looks like pyflakes is complaining about an unused import in web_character.py

**Comment by BarinderBanwait** [comment]
Thanks for the explanation about orbit labels @AndrewVSutherland - I'll summarise this on the new knowledge page.

I thought that Bober's code was used here because that's what the [Source of the data](https://www.lmfdb.org/Character/Dirichlet/Source) page writes - perhaps this should also be clarified/updated?

I'll get onto those pyflakes issues

**Comment by BarinderBanwait** [comment]
That last commit fixed all tests apart from one (`test_ell_curves.py::EllCurveTest::test_completeness`) which is also currently failing on trunk; so when it's fixed there I can do a final merge from master.

I've edited the knowledge page for [Labels for Galois orbits of Dirichlet Characters](https://beta.lmfdb.org/knowledge/show/character.dirichlet.conrey.orbit_label) to explain the labelling of orbits, as well as the page for [Source of Dirichlet character computations](https://beta.lmfdb.org/knowledge/show/rcs.source.character.dirichlet) to reflect @AndrewVSutherland 's comments above.

**Comment by JohnCremona** [comment]
Sorry @BarinderBanwait that's my fault.  I changed the text on a page and did not change the test, and also pushed my patch to be merged before the tests ran.  Sorry.  I'll fix that in a separate PR now and then restart the test on yours.

**Comment by JohnCremona** [comment]
I restarted just the Travis job which included the failing test after fixing it in a separate PR.

**Comment by BarinderBanwait** [comment]
No worries @JohnCremona - thanks for restarting the test here! My "hopefully final fix" is now indeed the final fix!

**Comment by BarinderBanwait** [comment]
pink branch has been updated with latest commits

**Comment by AndrewVSutherland** [comment]
Looks good, thanks @BarinderBanwait !

**Pull request merged**
