### PR TITLE
master -> beta

### PR DESCRIPTION
**Pull request by AndrewVSutherland**

### CODE REVIEW

**Comment by jwj61** [comment]
Could you copy numberfields.fields (and numberfields.fields.rand) to the cloud.  It provides more examples or siblings, and my new favorites, the 16t98 fields.

**Comment by AndrewVSutherland** [comment]
@jwj61 Done.  Can you take a look and let me know if everything appears to be OK (there was a slight hiccup when reloading the collection).

**Comment by jwj61** [comment]
The number field database may be ok.  I am seeing some glitches, but I think that is probably that  transitivegroups.groups also needs to be updated.

**Comment by AndrewVSutherland** [comment]
So should I copy over transitivegroups.groups now?

**Comment by jwj61** [comment]
Yes, please.  (I am guessing that this is causing the difference between beta and the main site.)

**Comment by AndrewVSutherland2** [comment]
@jwj61 Done.  Let me know if there are still any differences.

**Comment by jwj61** [comment]
Looks good.

**Pull request merged**
