### PR TITLE
Modular Curves Verification: checking ratpts map to ratpts

### PR DESCRIPTION
**Pull request by BarinderBanwait**
This addresses #5918 

Specifically: this PR consists of a verification test on `modcurve_modelmaps` and `modcurve_points`. Here's what it does:

1. for each map in `modcurve_modelmaps`:
2. get the rational points on the domain of the map with a search on `modcurve_points`;
3. send these rational points to the codomain;
4. ASSERT the image point is rational ("Test 1");
5. ASSERT the image point actually lies on the codomain ("Test 2");
6. ASSERT the image point is already accounted for in `modcurve_points` (on the codomain curve) ("Test 3")

This combined test passes on legendre in about 80 seconds.

@roed314 we have discussed this PR in person, if you could review before it gets merged, that'd be great

### CODE REVIEW

**Comment by BarinderBanwait** [comment]
more changes to be made here 🛠️

**Comment by BarinderBanwait** [comment]
With @roed314  help, I've got a script running that's verifying modcurve_modelmaps and modcurve_pts. It's raising an issue in the data that I'd like to understand:

Taking [this model map](https://beta.lmfdb.org/api/modcurve_modelmaps/527) and applying it to [this point](https://beta.lmfdb.org/api/modcurve_points/1096) seems to return [0:0:0], when I think it should be returning [1:0:1]; this complains because of course [0:0:0] is not a point in projective space.

This is the first such error; there may well be others; the verification script stops at the first error. (@roed314 do you know how i can tell it to run on all the data, not just stop at first error??)

**Comment by roed314** [comment]
You should be able to do `@slow(ratio=1, max_failures=10)`

**Comment by roed314** [comment]
I suspect that this point is valid, it's just that this rational function is not defined by the same set of polynomials everywhere.  It would be nice to write down an open cover of the curve together with a set of polynomials on each open in the cover that agree on the overlap, but we haven't done so.

**Comment by BarinderBanwait** [comment]
ok; then i'm wondering what to do in these cases (9224 of them across the whole data) where a point maps to all zero coordinates; are we ok with allowing these to pass?

there are also about 200 or so 'missing points', where the mapped point is not listed in modcurve_points. The first time this happens is with [this map](https://beta.lmfdb.org/api/modcurve_modelmaps/524) applied to [the point ''-1/2:1/2:1/2:1'' ](https://beta.lmfdb.org/api/modcurve_points/1097), which returns [0 : 1 : 4], a point not listed in the '5' entry of 'coordinates' of the latter link. Eyeballing the output, it seems this only ever happens with maps from the curve to itself, so maybe this too is ok?

**Comment by BarinderBanwait** [comment]
coming back to a long-overdue PR here after various other deadlines in the meanwhile ...

I'm keen to get this closed out, so I've scaled back the tests in this verification script; I'm now no longer going to check that the image points are accounted for in `modcurve_points`, which I wrote as Test 3 above. As written above, there are some missing points, and dealing with all points mapping to zero coordinates needs some thought; I do have magma code to do this, but getting this implemented is something I think can wait for after the initial release of modular curves (which IIRC is July). When this PR is merged I will create a follow-up issue and tag it for a future release milestone. 

The tests now mostly pass, but there are three failures out of 85,903 tests. These are the maps: [failure 1](https://beta.lmfdb.org/api/modcurve_modelmaps/?codomain_label=12.288.13.j.1), [failure 2](https://beta.lmfdb.org/api/modcurve_modelmaps/?codomain_label=40.288.13.cz.3) and [failure 3](https://beta.lmfdb.org/api/modcurve_modelmaps/?codomain_label=60.180.13.ie.1).

Looking into the first of these failures, I wrote the following magma script to verify the sage code:

```
numVars := 13;
PBig<x,y,z,w,t,u,v,r,s,a,b,c,d> := ProjectiveSpace(Rationals(), numVars-1);

CanonicalModelFromWeb := ["r^2+r*d-c*d", "t*c-s*a-a*b-a*c", "x*y+x*w+y*w+w^2+t^2-r^2", "t^2-r^2-r*b+a*b+b*c", "t^2-r^2-r*s-s*a+s*c", "x*y-y*w-y*t-y*u+t^2+t*u-s*b-c*d", "x*y-y*w+y*u-y*v-t^2-s*b+s*d+b*d-d^2", "2*x*y-x*w-y*w-w^2-t^2+r*c+c*d", "x^2-x*y+x*w+x*u-x*v-y*w-w^2+r^2+r*s+a*b+b*c", "x*w-y*w+y*t+y*u+w^2-t*u-r^2+s^2+s*c+b^2+b*c-c*d-d^2", "x^2-x*w+x*u-x*v-t^2+r^2-r*d+s*a-s*b+a^2-a*b-c*d", "x*y-y*w+y*t+y*v-t*u-r^2-r*s-r*b-r*c-s*b", "r*a-r*b-r*c-s*b+a*d-b^2-b*c+b*d", "y*r-t*r+t*c+v*c", "y*d+t*r+v*r+v*d", "y*r+t*r-t*c-u*c", "t*r+t*d+r*b+r*c+s^2+s*b+s*c-s*d", "t^2+t*r+t*b-r*s-r*c-s*b-c*d", "t*a-r*c-r*d-s*b-c*d", "t^2-t*r-t*s-r*b-r*c-s*b-c*d", "y*d-t*r-u*r-u*d", "x^2+x*y-y*t-y*v+t*u+u*v+r^2", "x*y-y*w+y*t+y*v+t^2+t*v-s*b-c*d", "x*z-y*r+y*d-z*w-z*u+t*d+v*d-a*d", "t*b+u*b-u*d+v*b-v*d-r*s-r*a+r*d", "t^2-t*r-t*a+u*s-u*d+v*s-v*d-r*a", "x*y-y*w-y*u-y*s-y*a+y*b+t*u-v*s+v*b+r*c+r*d", "x*s+x*b+x*c-x*d+y*r-u*r+v*r", "x^2-x*w+x*u-x*v+t*a+u*a+v*a+r^2+r*c", "t^2-u^2+u*v-v^2-s*d-b*d-c*d+d^2", "x*y+x*w-x*v-y*v-y*a-w*a-u^2+r*s+r*b+r*c", "x*d-w*r+t^2+u*s-v*b-r*c-r*d-s*b-c*d", "x*t+x*u+w*v-t*v-v^2+v*a+r*c+r*d", "y*w+y*u-y*v+w^2+w*u-w*v+s*b", "x*z-y*r+2*z*w-z*u-v*r-r*s-r*c-s^2-s*b-s*c+s*d", "2*x*z+z*w+z*u-t*c-u*r-v*c+r*a", "2*x*y+x*w-x*v+x*a-x*b-x*c-y*w+y*b-t*u-u^2-u*b+v*b-r^2-s*b", "x*u-x*a+y*t-y*a+w*v-t*u+u*a-v^2+r*c+r*d", "x*w-x*t+y*w+y*u-y*v-w*t-w*v-u*a+r*b-s*a+s*b+s*c", "y*t-z*c-w*a-u*a+v*a", "2*x*y+x*w-x*v+x*s+x*a+x*c-y*w-y*s-t*u-u^2+u*s-v*s-r^2-s*b", "x*r+x*d+w*d+t^2-t*r-u*r-u*b+v*s-v*d-r*c-r*d-s*b-c*d", "x*r+x*d+y*s+y*b-w*c", "x*u+x*r+x*d+y*r+y*b+w*v+w*b+t^2-t*u+u*s-u*b-v^2+v*a-s*b-c*d", "x*r+x*s+x*c+y*t+y*r-y*a-w*t+w*r+w*s", "z*d+w*t-t^2+t*u-t*v-u*s+u*b+r*c+r*d+s*b+c*d", "x*t-x*s-x*c-y*r-z*b-t^2-u*s+v*b+r*c+r*d+s*b+c*d", "x*c+z*a+w*r", "x*t+x*b+x*c+y*r-z*s+t^2+u*s-v*b-r*c-r*d-s*b-c*d", "x*t+z*r", "z*u+z*v-u*r+u*c+v*r-v*c", "y*r-z*t", "x*y+z^2", "3*y*z+t*r+r*s+r*c+s^2+s*b-s*d-a*c+b*c", "x*y-3*y^2-y*w+y*u-y*v-r*c-r*d+s*a-s*b-a*b+c^2"];
CanonicalModelFromWeb := [eval(f) : f in CanonicalModelFromWeb];
D := Curve(PBig, CanonicalModelFromWeb);

PXYZ<X,Y,Z> := ProjectiveSpace(Rationals(), 2);

PlaneModelFromWeb := ["X^8*Y^16+6*X^7*Y^17+9*X^6*Y^18-8*X^8*Y^15*Z-54*X^7*Y^16*Z-126*X^6*Y^17*Z-108*X^5*Y^18*Z+24*X^8*Y^14*Z^2+180*X^7*Y^15*Z^2+579*X^6*Y^16*Z^2+882*X^5*Y^17*Z^2+432*X^4*Y^18*Z^2-24*X^8*Y^13*Z^3-204*X^7*Y^14*Z^3-984*X^6*Y^15*Z^3-2142*X^5*Y^16*Z^3-1809*X^4*Y^17*Z^3-648*X^3*Y^18*Z^3-36*X^8*Y^12*Z^4-276*X^7*Y^13*Z^4-468*X^6*Y^14*Z^4-738*X^5*Y^15*Z^4-1746*X^4*Y^16*Z^4-2052*X^3*Y^17*Z^4+324*X^2*Y^18*Z^4+120*X^8*Y^11*Z^5+1020*X^7*Y^12*Z^5+3984*X^6*Y^13*Z^5+11358*X^5*Y^14*Z^5+20286*X^4*Y^15*Z^5+26460*X^3*Y^16*Z^5+10368*X^2*Y^17*Z^5-88*X^8*Y^10*Z^6-732*X^7*Y^11*Z^6-4092*X^6*Y^12*Z^6-14562*X^5*Y^13*Z^6-30861*X^4*Y^14*Z^6-61776*X^3*Y^15*Z^6-29160*X^2*Y^16*Z^6-3888*X*Y^17*Z^6-88*X^8*Y^9*Z^7-924*X^7*Y^10*Z^7-3096*X^6*Y^11*Z^7-9594*X^5*Y^12*Z^7-17136*X^4*Y^13*Z^7+17604*X^3*Y^14*Z^7-57618*X^2*Y^15*Z^7-36288*X*Y^16*Z^7+972*Y^17*Z^7+198*X^8*Y^8*Z^8+1848*X^7*Y^9*Z^8+8886*X^6*Y^10*Z^8+36414*X^5*Y^11*Z^8+83871*X^4*Y^12*Z^8+115290*X^3*Y^13*Z^8+311769*X^2*Y^14*Z^8+113076*X*Y^15*Z^8+17496*Y^16*Z^8-88*X^8*Y^7*Z^9-528*X^7*Y^8*Z^9-3324*X^6*Y^9*Z^9-18234*X^5*Y^10*Z^9-43686*X^4*Y^11*Z^9-127818*X^3*Y^12*Z^9-383184*X^2*Y^13*Z^9+128952*X*Y^14*Z^9-31104*Y^15*Z^9-88*X^8*Y^6*Z^10-1188*X^7*Y^7*Z^10-6030*X^6*Y^8*Z^10-26334*X^5*Y^9*Z^10-75861*X^4*Y^10*Z^10-51840*X^3*Y^11*Z^10-64773*X^2*Y^12*Z^10-919998*X*Y^13*Z^10+203472*Y^14*Z^10+120*X^8*Y^5*Z^11+1116*X^7*Y^6*Z^11+6072*X^6*Y^7*Z^11+33066*X^5*Y^8*Z^11+89082*X^4*Y^9*Z^11+131868*X^3*Y^10*Z^11+573318*X^2*Y^11*Z^11+1452654*X*Y^12*Z^11-1005777*Y^13*Z^11-36*X^8*Y^4*Z^12-12*X^7*Y^5*Z^12+300*X^6*Y^6*Z^12-1494*X^5*Y^7*Z^12+17739*X^4*Y^8*Z^12+11394*X^3*Y^9*Z^12-503847*X^2*Y^10*Z^12-748278*X*Y^11*Z^12+2567052*Y^12*Z^12-24*X^8*Y^3*Z^13-444*X^7*Y^4*Z^13-2880*X^6*Y^5*Z^13-16182*X^5*Y^6*Z^13-68814*X^4*Y^7*Z^13-94554*X^3*Y^8*Z^13+88776*X^2*Y^9*Z^13-610254*X*Y^10*Z^13-3843936*Y^11*Z^13+24*X^8*Y^2*Z^14+204*X^7*Y^3*Z^14+1092*X^6*Y^4*Z^14+7578*X^5*Y^5*Z^14+19665*X^4*Y^6*Z^14+864*X^3*Y^7*Z^14+124659*X^2*Y^8*Z^14+1239300*X*Y^9*Z^14+3706479*Y^10*Z^14-8*X^8*Y*Z^15+12*X^7*Y^2*Z^15+312*X^6*Y^3*Z^15+1746*X^5*Y^4*Z^15+21600*X^4*Y^5*Z^15+62316*X^3*Y^6*Z^15-137862*X^2*Y^7*Z^15-914652*X*Y^8*Z^15-2378727*Y^9*Z^15+X^8*Z^16-30*X^7*Y*Z^16-279*X^6*Y^2*Z^16-1926*X^5*Y^3*Z^16-14571*X^4*Y^4*Z^16-20466*X^3*Y^5*Z^16+133299*X^2*Y^6*Z^16+375840*X*Y^7*Z^16+1029348*Y^8*Z^16+6*X^7*Z^17+42*X^6*Y*Z^17+126*X^5*Y^2*Z^17+630*X^4*Y^3*Z^17-14958*X^3*Y^4*Z^17-94608*X^2*Y^5*Z^17-57996*X*Y^6*Z^17-285768*Y^7*Z^17+3*X^6*Z^18+180*X^5*Y*Z^18+1377*X^4*Y^2*Z^18+9072*X^3*Y^3*Z^18+29673*X^2*Y^4*Z^18-46494*X*Y^5*Z^18+40338*Y^6*Z^18-36*X^5*Z^19-153*X^4*Y*Z^19-324*X^3*Y^2*Z^19+594*X^2*Y^3*Z^19+37422*X*Y^4*Z^19-1863*Y^5*Z^19-45*X^4*Z^20-486*X^3*Y*Z^20-2025*X^2*Y^2*Z^20-10206*X*Y^3*Z^20+3888*Y^4*Z^20+54*X^3*Z^21+216*X^2*Y*Z^21+162*X*Y^2*Z^21-1944*Y^3*Z^21+81*X^2*Z^22+648*X*Y*Z^22+567*Y^2*Z^22+243*Y*Z^23"];

PlaneModelFromWeb := [eval(f) : f in PlaneModelFromWeb];

C := Curve(PXYZ, PlaneModelFromWeb);

MapFromWeb := [b, 1/3*c, 1/3*d];
phiAmb:=map<PBig->PXYZ|MapFromWeb>;
//phi:=Restriction(phiAmb,D,C); // fails
```

The last restriction fails. Moreover, as suggested by @koffie , computing the genus of the image curve:

```
phi:=Restriction(phiAmb,D,PXYZ);
realImage := Image(phi);
```

returns 5, whereas the genus is supposed to be 13. 

This suggests that it is the maps themselves that are possibly incorrect.

**Comment by AndrewVSutherland** [comment]
Thanks for getting back to this.  I'll leave it to @roed314 to comment further, but it sounds to me like the verification is now doing what it should do (finding errors in the data), so I'm happy to merge this if David is.

**Pull request merged**
