### PR TITLE
Various backend things

### LINKED ISSUE #3054: Add index by default to counts tables
By default, we should do
```
CREATE INDEX tablename_counts_cols_vals_split ON tablename_counts USING
btree (cols, values, split);
```
when creating a table and then rename them accordingly when reloading table.

See #2971

### PR DESCRIPTION
**Pull request by edgarcosta**
- We no longer use to_regclass, to test if a relation exists, as it behaves in a weird fashion with upper case names.
- The bug above was creating name clashing of the indexes on reload, when these had upper case characters
- We now avoid name clashing when restoring or renaming indexes, by renaming them
eg
```
WARNING:LMFDB@2019-05-16 19:04:22,895: Index with name bmf_forms_field_label_level_label_CM_bc_tmp already exists. It has been renamed to bmf_forms_field_label_level_label_CM_bc_dep0_tmp and it can be deleted with the following SQL command:
DROP INDEX "bmf_forms_field_label_level_label_CM_bc_dep0_tmp" 
```
- Added indexes on the counts tables on reload, and thus resolves #3054
- Added a warning message when more than 10k rows are inserted into the counts tables, eg
```
WARNING:LMFDB@2019-05-17 10:26:18,285: 45083 rows, with with cols = '["degree", "class_number"]', were added into nf_fields_counts.This might decrease the counts table performance significantly! Consider clearing all the stats db.nf_fields_clear_stats_counts() and rebuilding them more carefully.
```
as we saw in #3093

- Better error message when a SQL command fails

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
These are all great changes that should solve a lot of annoying problems, but it is tricky to really test it properly.  @roed314 have you looked at these changes?

**Comment by edgarcosta** [comment]
David is traveling. Might only have time to look into this on Monday.

**Comment by AndrewVSutherland** [comment]
@edgarcosta any of the 13 issues labelled "postgres" other than #3054 adressed by this PR?

**Comment by edgarcosta** [comment]
This now also addresses #2848

**Comment by edgarcosta** [comment]
I also believe that this addresses #2622 in two ways:
- Now when there is a db error, we reraise the error the SQL command, thus it's clearer what is going on
- By default adjust the schema of a table on reload, i.e., we use the headers from the files to adjust the schema (or even create the table with `reload_all`) automatically

**Comment by roed314** [comment]
* `begin_renamer = SQL("ALTER TABLE {0} RENAME CONSTRAINT").format(tablename)` and the needs to change `tablename` to `SQL(tablename)` (and the same for two lines below).

Otherwise I don't see any problems.

**Pull request merged**
