### PR TITLE
add --dbmon flag to support mongo db call monitoring

### PR DESCRIPTION
**Pull request by AndrewVSutherland**
This PR adds a --dbmon=NAME command line option that you can specify when you start the LMFDB webserver to log (with timings) all calls to mongo db on the specified database.  To monitor everything, use --dbmon=* (or even just --dbmon=), and to monitor everything except the specified datbase, put a twiddle in front of it (e.g. --dbmon=~knowledge will not log knowl lookups).

This will be useful both for analyzing performance, and for debugging issues like #1533 and #1803, both of which are caused by problems with invalid or inconsistent data across multiple collections (and it is not always easy to tell from the code which collections are being accessed when).

To see it in action just add --dbmon=* to your usual lmfdb startup and visit some of your favorite pages

sage -python start-lmfdb.py --dbmon=*

To prevent being overwhelmed by messages about knowl lookups use

sage -python start-lmfdb.py --dbmon=~knowledge

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
EDIT: I changed the --dbmon command line option to take an argument that specifies the name of the database to monitor (e.g. --dbmon=MaassWaveForms) and updated the description above accordingly.  

You can specify an empty name to monitor everything (e.g. --dbmon=), but knowls make it a bit overwhelming.

**Comment by AndrewVSutherland** [comment]
One more tweak, you can now use --dbmon=* to monitor everything, and --dbmon=~foo to monitor all databases **except** foo (so --dbmon=~knowledge will avoid logging every knowl lookup).  OK, I will stop fiddling with it now.

**Comment by edgarcosta** [comment]
This is great and really helpful!

This is exactly what I used back in May to analyze why our first version of lmfdb.org in the cloud was so slow
https://github.com/LMFDB/lmfdb/compare/master...edgarcosta:mongostuff

I should have PRed a clean version of it back then, but at the time I only was trying to make everything work.

**Comment by JohnCremona** [comment]
I'll let Edgar finish reviewing this one so I don't have to go into mongo configuration myself.

**Comment by edgarcosta** [comment]
It looks good to me. 

Regarding the coding style, I prefer: `(a, b)` vs `(a,b)`, and parenthesis around logical operators. 
:)

**Pull request merged**
