### PR TITLE
Siegel modular forms cleanup

### PR DESCRIPTION
**Pull request by AndrewVSutherland**
This is large PR with a long description, the tldr is that it fixes at least 6 outstanding issues including 4 production issues and general makes the Siegel modular forms (SMF) section of the LMFDB more usable.  There are plenty of SMF issues not addressed by this PR, the goal was simply to hit all the high priority issues and make things "less bad".

Those who care or are willing to review this PR should read on.  I have tried to make it as easy to review this PR as possible.  I added a large test script (which runs without errors), and below I give a bunch of before-and-after page links that you can use to decide whether this PR fixes the issues it claims to fix and whether it is indeed "less bad" than the current incarnation -- these should be the sole criteria for accepting this PR -- it is not intended to fix everything that is wrong with the current Seigel modular forms implementation, just to be a step in the right direction.

Once this PR is merged we should be able to close six issues: #488, #989, #1531, #1569, #1571, #1573 (four of these are marked as production problems, one critical), and it partially addresses or provides a workaround for five other issues: #492, #627, #951, #1164, #1247 #1539 (one or two of these may actually be closeable once this PR is merged, but most identify multiple issues and/or are not specific to Siegel modular forms).

As part of this work I cleaned up the siegel_modular_forms database and documented it (see https://github.com/LMFDB/lmfdb-inventory/blob/master/db-siegel_modular_forms.md), allowing https://github.com/LMFDB/lmfdb-inventory/issues/19 to also be closed).  The main data changes are:

* Consolidated samples and experimental_samples into a single samples collection (the code was accessing both, now it only accesses samples)
* Removed orphaned eigenvalue and fourier coefficient data whose owner_id was no longer present.
* Changed the data type of several small integer fields (e.g. weight, degree, etc...) that were previously strings to facilitate faster indexing and range lookup.
* Changed the attribute "311" which is meant to identify a partition of 6 to "3111"
* Uniformized boolean attributes that were sometimes encoded as True and sometimes as "True"
* Added indexes to improve performance

All data changes are backward compatible (new field names only referenced by the new code).  Once this PR is merged and pushed to prod I will remove the obsolete fields.

As for the code changes, I had the following objectives:

* Remove dangerous or nonstandard usage (e.g. eval, sage_eval, javascript input validation with alert boxes, etc...  this address #1539 for SMF and also a lot of usability/nonstandard UI issues)
* Fix serious performance issues that were causing at least two of the production issues above (including the critical one, this also address #1247 for SMF and would allow the SMF tag to be removed from this issue).
* Fix pages that were trying to display more data than could be reasonably displayed on a web page (even when this doesn't cause a performance issue, it can make the pages unusable, if, for example, you have to scroll down ten pages to get to an input field you want to access)
* Bring the UI closer to LMFDB standards (in regards to searching and error handling in particular).
* Try to make the most of what we have -- there is a lot of useful Siegel modular form data in the mongo database, but much of it was either not being displayed at all (hidden because of U/I issues identified prior to Release 1.0), or displayed in an unusable way (there were plenty of pages that should have been hidden prior to Release 1.0 but were not).

The new test script explicitly loads all 129 of the sample Siegel modular forms for which we have data in the LMFDB (previously about 30 of these were hidden and about 10 should have been hidden because they either don't load at all or attempt to display several megabytes of data).  They now all load quickly and none is larger than 50kb or so (much of which is fixed LMFDB overhead).

Below is a before/after tour of pages that have changed, starting from the SMF home page:

Home page:
Before: http://www.lmfdb.org/ModularForm/GSp/Q/
After: http://127.0.0.1:37777/ModularForm/GSp/Q/ (faster + browsing options)

Dimension table page (now uses standard input ranges, better error handling, table formatting, etc.. see #488.)
Before: http://www.lmfdb.org/ModularForm/GSp/Q/dimensions/
After: http://127.0.0.1:37777/ModularForm/GSp/Q/?table=1 (also on main page)

A featured family of samples (now all links are available, dimension table is prettier and has standard input and error handling)
Before: http://www.lmfdb.org/ModularForm/GSp/Q/Sp4Z/
After: http://127.0.0.1:37777/ModularForm/GSp/Q/Sp4Z/

Sample pages that didn't work at all now work (critical issue #1531)
Before: http://www.lmfdb.org/ModularForm/GSp/Q/Sp4Z_2.28_C
After: http://127.0.0.1:37777/ModularForm/GSp/Q/Sp4Z_2.28_C/
(the download link does work, but it's about **200MB**, so only test on a fast link)

Pages that tried to display too much data now do something more reasonable
Before: http://www.lmfdb.org/ModularForm/GSp/Q/Sp4Z_2.22_C/
After: http://127.0.0.1:37777/ModularForm/GSp/Q/Sp4Z_2.22_C/
After: http://127.0.0.1:37777/ModularForm/GSp/Q/Sp4Z_2.22_C/?modulus=11,a%2B2
(second after reduces modulo the ideal (11,a+2))

Parsing lists in dimension tables now works (issue #1569)
Before: http://www.lmfdb.org/ModularForm/GSp/Q/Sp4Z_j/  (and enter **4,9,16** for k)
After: http://127.0.0.1:37777/ModularForm/GSp/Q/Sp4Z.24_Klingen/  (and enter **4,9,16** for k)

Changing the modulus now works (issue #1571)
Before: http://www.lmfdb.org/ModularForm/GSp/Q/Sp4Z.24_Klingen/  (and enter modulus **2**)
After: http://127.0.0.1:37777/ModularForm/GSp/Q/Sp4Z.24_Klingen/  (and enter modulus **2**)

Reduction is now defined when it should be (issue #1573)
Before: http://www.lmfdb.org/ModularForm/GSp/Q/Sp4Z_2.16_C/  (and enter modulus **3*a+14**)
After: http://127.0.0.1:37777/ModularForm/GSp/Q/Sp4Z_2.16_C/  (and enter modulus **3*a+14**)

(more generally, I believe that the combination of suppressing the display of Fourier coefficients that are too large to fit on the screen and making modulus reduction work correctly addresses #989).

You can also now access a random Siegel modular form from the main page:

http://127.0.0.1:37777/ModularForm/GSp/Q/random

Please feel free to explore, I don't claim that everything is perfect, only that nothing should break (no internal server errors) and that pages should look no worse than the do now (and most look a lot better).  And be sure to try out the new test script.

### CODE REVIEW

**Comment by JohnCremona** [comment]
OK I took a deep breath and am looking at this now.

**Comment by JohnCremona** [comment]
Many great improvements here.  I did some exploring as well as testing all the suggested pages, and have no hesitation in accepting this.
I did run the new test, of course.  For a test like the one which tests lots of things and prints a line for each I tried out reformatting so there's no newline except at the end.  See https://github.com/JohnCremona/lmfdb/tree/siegel
I'll make a PR from there to your siegel-cleanup branch in case you like it, but feel free to ignore that -- I'll merge this either way.

**Comment by JohnCremona** [comment]
@AndrewVSutherland I'll leave you to close the relevant issues where appropriate.  Thanks for the good work.

**Comment by AndrewVSutherland** [comment]
@JohnCremona Will do, thanks for reviewing and merging.

**Pull request merged**
