### PR TITLE
Elliptic curve code tidy up

### PR DESCRIPTION
**Pull request by JohnCremona**
Nothing here has any visible effect on the website, it is only tidying up some older obsolete code and making sure that there are no more references to obsolete keys in a curve record so that the records can subsequently be tidied up.
Note: as well as running the standard tests I also ran ~100,000 random curves with this code.

### CODE REVIEW

**Comment by JohnCremona** [comment]
The Travis failure was a timeout on a workshop link.

**Comment by jwj61** [comment]
That machine is currently down while being upgraded/replaced.

**Comment by JohnCremona** [comment]
@jwj61 Shall we disable that test then?

**Comment by jwj61** [comment]
It is up to you.  I hope it will be up and running today.  Then again, I was hoping they would get it set up properly yesterday.

**Comment by edgarcosta** [comment]
I would just wait for the link to be back online and move along with the
merge if that is desired.

**Comment by JohnCremona** [comment]
OK, so I will merge this having checked manually that the only test failure was that one.

**Comment by jwj61** [comment]
For the record, hobbes is back up

**Pull request merged**
