### PR TITLE
EC/Q revision

### PR DESCRIPTION
**Pull request by JohnCremona**
See #4255.   This makes a big code change, mostly in elliptic_curves but with some consequent changes elsewhere,, to use new ec_* tables as described in that Issue, no loger using ec_curves (either the main or the extras table).

At the same time the code now allows for curves outside the range of the Cremona database (conductors < 500000) and to demonstrate that  I have included curves from Benjamin Matschke et al of 3 conductors which complete the set of all curves with good reduction outside {2,3,5,7}.   This meant changing the stats summary lines in the code -- but I have *not* yet changed the source knowl which will require some additional text.

This branch may be seen in action at purple.lmfdb.xyz.  If merged it will work fine on beta but will require 8 tables copying to prod before pushing there.

### CODE REVIEW

**Comment by JohnCremona** [comment]
If people prefer I can delete/hide the 32082 curves of conductor >500000 until after this has been merged.

**Comment by jwj61** [comment]
I clicked around a little and every page looked good.  I would keep the new curves there so people can see that they work as well.

**Comment by JohnCremona** [comment]
Thanks. On the browse page shall I make the conductor ranges end with ... 1000000-500000, >5000000. ?

**Comment by jwj61** [comment]
I like that change.

**Comment by edgarcosta** [comment]
I have preemptively copied the 8 tables: ec_localdata, ec_galrep, ec_torsion_growth, ec_2adic, ec_classdata, ec_iwasawa, ec_mwbsd, and ec_curvedata to proddb.

**Comment by AndrewVSutherland** [comment]
LGTM, merging.

**Comment by JohnCremona** [comment]
Thanks!

**Comment by AndrewVSutherland** [comment]
@JohnCremona FYI merging my subsequent PR caused a problem that the merge conflict missed (an old reference to ec_curves) which I am fixing and testing now, I'll submit a new PR shortly.

While checking for references to ec_curves I noticed that there are still two in scripts/ecnf/bmf_check and scripts/ecnf/hmf_check, should those be changed?  I realize they may no longer be relevant, but it is probably better not to have any references to ec_curves lingering in the code.

**Comment by JohnCremona** [comment]
I'll take a look at those scripts.

**Pull request merged**
