### PR TITLE
Interesting objects via knowls

### PR DESCRIPTION
**Pull request by roed314**
Generates lists of interesting objects using top and bottom knowls.

Each section of the LMFDB needs to update its annotations so that the list is populated with interesting objects.  This mainly means ensuring that the list is non-empty, that each knowl has a good title, and that the knowls all have content.

- [x] Classical [newforms](https://red.lmfdb.xyz/ModularForm/GL2/Q/holomorphic/interesting_newforms) (13) and [newspaces](https://red.lmfdb.xyz/ModularForm/GL2/Q/holomorphic/interesting_spaces) (2)
- [x] [Maass forms](https://red.lmfdb.xyz/ModularForm/GL2/Q/Maass/interesting) (7)
- [x] [Hilbert modular forms](https://red.lmfdb.xyz/ModularForm/GL2/TotallyReal/interesting) (4)
- [x] [Bianchi modular forms](https://red.lmfdb.xyz/ModularForm/GL2/ImaginaryQuadratic/interesting) (3)
- Siegel modular forms (skipped)
- [x] [Elliptic curves over Q](https://red.lmfdb.xyz/EllipticCurve/Q/interesting) (74)
- [x] [Elliptic curves over number fields](https://red.lmfdb.xyz/EllipticCurve/interesting) (5)
- [x] [Genus 2 curves](https://red.lmfdb.xyz/Genus2Curve/Q/interesting) (31)
- [ ] [Belyi maps](https://red.lmfdb.xyz/Belyi/interesting) (2)
- [x] [Higher genus families](https://red.lmfdb.xyz/HigherGenus/C/Aut/interesting) (4)
- [x] [Abelian varieties over Fq](https://red.lmfdb.xyz/Variety/Abelian/Fq/interesting) (15)
- [x] [Number fields](https://red.lmfdb.xyz/NumberField/interesting) (21)
- [x] [p-adic fields](https://red.lmfdb.xyz/LocalNumberField/interesting) (5)
- [x] [Dirichlet characters](https://red.lmfdb.xyz/Character/Dirichlet/interesting) (2)
- [x] [Artin representations](https://red.lmfdb.xyz/ArtinRepresentation/interesting) (3)
- [x] [Hypergeometric families](https://red.lmfdb.xyz/Motive/Hypergeometric/Q/interesting_families) (5)
- [x] [Galois groups](https://red.lmfdb.xyz/GaloisGroup/interesting) (7)
- [x] [Sato-Tate groups](https://red.lmfdb.xyz/SatoTateGroup/interesting) (5)
- [x] [Lattices](https://red.lmfdb.xyz/Lattice/interesting) (13)

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
There are some non-trivial travis errors that should be fixed before this is merged (at least BMFs and abvar are failing).

**Comment by roed314** [comment]
I'll take a look later tonight.

**Comment by roed314** [comment]
There were some tests that checked that various lists of favorites were present.  I've removed those; once lists of favorites stabilize we should add some tests for them.

**Comment by jwj61** [comment]
There are Galois groups with bottom knowls, but they do not show up on the interesting objects page.

**Comment by roed314** [comment]
It was a capitalization issue (we had been using lower case t in the knowls but the labels used upper case).  I've changed the code to use upper case Ts and copied the four existing knowls over to the new format, and now they show up.

**Comment by roed314** [comment]
I think this PR is ready for review.  Every section has at least 2 interesting objects.

**Comment by AndrewVSutherland** [comment]
Looks good!  It would be nice to get more interesting objects (e.g. Belyi maps, Hilbert and Bianchi modular forms, etc..) but I see no reason not to merge this now.

**Pull request merged**
