### PR TITLE
Higher Genus curves w/autos: a series of small fixes

### PR DESCRIPTION
**Pull request by jenpaulhus**
Suggestions from #1657:
1. Changed the link from /HigherGenus/C/aut to HigherGenus/C/Aut.  But, could we put a short term redirect from the lower case version to the upper case version? I have given a few people the link with "aut" and would like it to redirect instead of returning an error.

2. Separated breadcrumbs and added links for each one, see for example:
http://127.0.0.1:37777/HigherGenus/C/Aut/
http://127.0.0.1:37777/HigherGenus/C/Aut/5.48-49.0.2-6-6
http://127.0.0.1:37777/HigherGenus/C/Aut/5.48-49.0.2-6-6.5

3. Added random refined passport option at http://127.0.0.1:37777/HigherGenus/C/Aut/

4. Uniformized error handling

5. Added Next/Previous at the top of searches, see:
http://127.0.0.1:37777/HigherGenus/C/Aut/?genus=5

6. Added more tests to test_hgcwa.py

From #1663 deleted "num_entries" variable which was assigned and never used.

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
@jenpaulhus These look like good changes, just a few small issues:

* You need to enclose the latex breadcrumb for the group in $'s or \( \);
* The random link should redirect so that the user sees the correct URL for the passport page in their URL bar (e.g. if they want to bookmark the page, they don't want to bookmark /random);
* Now that the error handling is uniform, I think you can remove the "Error" heading and info.err display from hwcga-search.html (just display "Either modify your search above or go back").
* I think you can remove hwcga-error.html, which does not appear to be used any longer.

Regarding redirecting .../aut to .../Aut, it would be a slight pain to put in redirect, but what you could do instead (in the short term) is to have both lines

app.register_blueprint(higher_genus_w_automorphisms_page, url_prefix="/HigherGenus/C/aut")
app.register_blueprint(higher_genus_w_automorphisms_page, url_prefix="/HigherGenus/C/Aut")

in your __init__.py (all the internal links will still use /Aut, and anyone poking around will see this).  

When we go to beta you should remove the "/aut" line (the link will then be accessible on the sidebar anyway, so it shouldn't be a problem for people to find it).

**Comment by jenpaulhus** [comment]
@AndrewVSutherland Made the small changes you suggested above.  

1. Breadcrumb groups are now showing as latex.
2. Random curves are given their proper passport label.
3. I deleted the Error piece of the hgcwa-search.html file. (In a minute I will make one last commit because I just remembered that I need to  delete commented out code).
4. I removed /template/hgcwa-error.html file.
5. I added the line app.register_blueprint(higher_genus_w_automorphisms_page, url_prefix="/HigherGenus/C/aut")  back into the init.py file (although I put it second because if it was first, the urls on the rest of the pages all defaulted to the "aut" instead of "Aut".)

**Comment by AndrewVSutherland** [comment]
@jenpaulhus It looks like there is a typo in hgcwa-search.html causing a server error on http://127.0.0.1:37777/HigherGenus/C/Aut/?genus=&group=&signature=&dim=&inc_hyper=include&count=20&Submit=Search, maybe an extra {% endif %}.

**Comment by jenpaulhus** [comment]
@AndrewVSutherland Oops!  Should be fixed now.

**Comment by AndrewVSutherland** [comment]
Looks good!

**Pull request merged**
