### PR TITLE
python3 in data_mgt (step1)

### PR DESCRIPTION
**Pull request by fchapoton**
some python fixes for print and Error syntax

### CODE REVIEW

**Comment by JohnCremona** [comment]
The changes to print statements are all fine.  As on the other tickets I ask whether the future imports are necessary.

By the way, the file checknowl.py can be deleted as it is been superseded (1000%) by new functionality implemented elsewhere.

**Comment by fchapoton** [comment]
This one is also very small and should be easy and quick to review, and I explained elsewhere two good reasons for having the future imports.

**Comment by JohnCremona** [comment]
Please merge. I'm not able to right now.

**Comment by JohnCremona** [comment]
I was wrong: managed to merge via phone

**Pull request merged**
