### PR TITLE
If a space is trivial because of parity, show it in grey

### PR DESCRIPTION
**Pull request by davidfarmer**
I think all possibilities occur on these two pages:

ModularForm/GL2/Q/holomorphic/5/4/
ModularForm/GL2/Q/holomorphic/42/2/

Also fixed a color problem with included knowls.

### CODE REVIEW

**Comment by davidfarmer** [comment]
Fixes the last part of issue #702

**Comment by JohnCremona** [comment]
How about explaining this grey convention on the page, wehere we already have an explanation in small print of what "n/a" means?

Also wasn't there an intention to sort the spaces by parity?   So that (e.g.) ModularForm/GL2/Q/holomorphic/42/2/
would have the nontrivial even ones first, followed by the trivial grey odd spaces?

**Comment by davidfarmer** [comment]
I added the sentence (after the n/a explanation):
Spaces in grey are trivial because the character and the weight have opposite parity.

I think the spaces should be in a natural order, perhaps by the label of the character,
and it would lose information if you grouped them by parity.  I assume there is some
logic to the current order (but I am not sure because I didn't implement it), so I would
rather leave the order as-is, and discuss that in a separate issue.

**Comment by fredstro** [comment]
The order comes from (or at least it used to come from) the ordering of the
galois orbits as returned by the dirichletgroupconrey

Fredrik

**Pull request merged**
