### PR TITLE
First large bunch of absolute imports

### PR DESCRIPTION
**Pull request by fchapoton**
made purely automatically using

`futurize -W --fix=libfuturize.fixes.fix_absolute_import lmfdb`

and then reverting the changes in the subfolders users/ and inventory_app/

### CODE REVIEW

**Comment by fchapoton** [comment]
Apparently, all doctests are ok

**Comment by JohnCremona** [comment]
@fchapoton What is happening with the file in deprecated/?

Also, please add yourself to CONTRIBUTORS.yaml at some point and make a PR for that.  Thanks!

**Comment by fchapoton** [comment]
will do.

About the deprecated file, I have no idea. Maybe this file was deleted elsewhere and reintroduced here ?

I can prepare a cleaner branch with no change in this file.

**Comment by JohnCremona** [comment]
Yes I think this file was moved. It is from an unfinished project from a few years ago (I think).

It's not necessary to remove this change from the PR.   I did a small amount of manual testing of this branch but would be happier if someone else did more (I have no time today).

**Comment by fchapoton** [comment]
ok, here is a branch without 2 problematic files. Now one needs to wait for Travis CI

**Comment by fchapoton** [comment]
the failure does not seem to be related to the changes made here

**Comment by fchapoton** [comment]
so this should be good to go now

**Comment by fchapoton** [comment]
please merge before it bitrots

**Pull request merged**
