### PR TITLE
Minor formatting changes to Sato Tate groups

### PR DESCRIPTION
**Pull request by AndrewVSutherland**
The only changes are in the formatting / sort order of the search results and some minor tweaks to the properties box layou.

### CODE REVIEW

**Comment by JohnCremona** [comment]
Can you make a test file for Sato-Tate?  It would increase confidence if we could run the tests after these changes and know that everything still worked.
Ideally there should be a lot of tests on the ST home page which includes a test of all links from there and a variety of searches, as well as some tests for the individual pages.

**Comment by jwj61** [comment]
Checking ...

**Comment by AndrewVSutherland** [comment]
@JohnCremona added test_st.py

**Comment by JohnCremona** [comment]
Thanks for the tests.  I'll let JJ merge this one as I'm off to dinner.

**Pull request merged**
