### PR TITLE
Add sage code for dirchars without conrey package

### PR DESCRIPTION
**Pull request by davidlowryduda**
This commit adds code for computing Dirichlet characters without using
the extra package conrey_dirichlet_characters from Bober's github. In
addition, this now also links to that package from the Dirichlet
character pages.

To see this code, go to a page such as

https://www.lmfdb.org/Character/Dirichlet/60/7

and click on the `Show commands for SageMath` option.

Right now, I present both the conrey-code and an independent sage code.
We could choose to only show one if desired.

There is a choice to be made for the code down the rest of the page.
Almost all of the code snippets work for both conrey_characters and for
sage_characters, except for the final couple (where we allow explicit
evaluation of Gauss sums, Jacobi sums, and Kloosterman sums for whatever
reason).

This is related to (but also slightly orthogonal to) #1912

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
Given how simple the independent sage code is, I think it would be better to just show that pure sage code.

Including the conrey-code is going to make the code snippets more confusing, with no real benefit (if we wanted to add a mention of Bober's package in the Dirchlet character labels learnmoreabout box I think that would be fine).

**Comment by davidlowryduda** [comment]
I agree. I removed the conrey-code. We still mention Bober's package in the description of the source of the data, and I'm content with that.

**Comment by roed314** [comment]
Looks good, except you're missing an import:
```
sage: H = DirichletGroup(1473)
sage: M = H._module
sage: chi = DirichletCharacter(H, M([0,247]))
...
NameError: name 'DirichletCharacter' is not defined
```

**Comment by davidlowryduda** [comment]
Aha. I was overzealous in removing the previous conrey-code. I've fixed this. Thanks for taking a look.

**Comment by roed314** [comment]
No problem!

**Pull request merged**
