### PR TITLE
Searching on number of integral points

### PR DESCRIPTION
**Pull request by SamSchiavone**
Addressing https://github.com/LMFDB/lmfdb/issues/3238. I've added functionality allowing one to search for elliptic curves by number of integral points.

I also recomputed the number of integral points using the script update_num_int_pts in import_ec_data.py and rewrote the data in ec_curves. Now the field num_int_pts should give the number of integral points rather than the number of integral points up to sign. I backed up a copy of the data before the rewrite under ec_backup in case there are any problems.

### CODE REVIEW

**Comment by roed314** [comment]
It looks like pyflakes failed with
```
./scripts/elliptic_curves/import_ec_data.py:154: 'lmfdb.elliptic_curves.web_ec.make_y_coord' imported but unused
```

**Comment by SamSchiavone** [comment]
Thanks, David! I've deleted that unnecessary import of make_y_coord.

**Comment by AndrewVSutherland** [comment]
There is a print statement that has been added to line 249 of elliptic_curve.py that I expect was put in during development to help with debugging -- this should be removed.

**Comment by JohnCremona** [comment]
I have a small concern about what has happened here.  The data (on beta) has *already* been changed, by overwriting the existing column with the new count.  I think it would have been better to create a new column for the new count.  That would have safer, though in this case the num_int_pts column is not referred to in the website code, so it is OK.  But thiat would also have allowed an option in the integral point search, of which of the two counts to search on.  Never mind that, it would be easy to recreate the old column since the old number is just the length of the x-coordinate list.

The code changes now being asked to be merged are mostly simple.  There are coercions to RR and back to ZZ in the revised code which are unnecessary (my old code did work correctly as it converted each x to ZZ first).

**Comment by AndrewVSutherland** [comment]
@JohnCremona This was my call -- my thinking was that since we don't currently display or allow searching on number of integral points there was no harm in changing the value on beta, especially since the new value is arguably the correct one.   There is a backup copy of the table that we can revert to if needed -- let me know if you would like me to do that.

**Comment by JohnCremona** [comment]
@AndrewVSutherland No it's fine, I had not realised that the number we stored before was never used at all.

Independently of this PR though, we really ought to have a way to propose/approve/implement changes in table schemas (including cases such as this one where the schema has only changes in a subtle way to do with the definition of the stored integer).   We have got away with it up to now mostly because each table has only been ever touched by one person (an exception was of course CMFs but then the people working on it were all talking to each other).

**Pull request merged**
