### PR TITLE
Special subgroup knowls

### PR DESCRIPTION
**Pull request by jwj61**
For special subgroups, the subgroups themselves are now subgroup knowls when possible.

Also, commutator length is 0 when the group is abelian.

https://beta.lmfdb.org/Groups/Abstract/132.2
http://127.0.0.1:37777/Groups/Abstract/132.2

Also fixed highlighting for Sylow subgroups.

### CODE REVIEW

**Comment by jwj61** [comment]
There are a couple of highlight things going on.  When hovering, all examples of that subgroup get a background highlight.  In the list, characteristic subgroups have a different font color.  The latter one confused me for a while and others.  The question is whether to explain it, or undo it.

**Comment by AndrewVSutherland** [comment]
Okay, I understand that the characteristic font color issue is separate from this PR.

But it seems the hover highlight is part of this PR (e.g. if I hover on C_11 only one gets highlighted on beta, but two copies of C_11 get highlighted in this PR) and I also have a question about that.  Should the hover highlight also apply to quotients (e.g. C_2 appears twice as G/Soc and G/Fit, Soc and Fit both are both C_66 and get highlighted together when you hover, but the corresponding quotients don't)?

**Comment by roed314** [comment]
I'm fine with highlighting quotients to show their equivalence.  It could also highlight them in the normal subgroup profiles....

**Comment by AndrewVSutherland** [comment]
I'm happy to merge this as is, just wanted to make sure it was intentional.

**Pull request merged**
