### PR TITLE
Move label search

### PR DESCRIPTION
**Pull request by sanni85**
the box for searching by label has been moved before the block with search queries all over the website (hopefully all occurrences.....)

### CODE REVIEW

**Comment by JohnCremona** [comment]
David volunteered to go through this one, and I suggest that we don't merge others until that is done.

**Comment by davidfarmer** [comment]
At /EllipticCurve/,  the following appears at the bottom of the page
 Raw field data: [['the rational field', (('1.1.1.1', ['/EllipticCurve/Q/', 'Q']),)], ['real quadratic fields', <generator object <genexpr> at 0x11197f3c0>], ['imaginary quadratic fields', <generator object <genexpr> at 0x11197f410>], ['cubic fields', <generator object <genexpr> at 0x11197f460>]]

**Comment by davidfarmer** [comment]
At /Genus2Curve/Q/, the "Find a specific curve by label" appears twice.

**Comment by davidfarmer** [comment]
Except for the two comments above, everything looks okay for this merge.

If this is holding up other things, it might be reasonable to fix those issues later?

Note that this pull request does not take care of the left/right justification of the search
tables: it only puts the "find" above the "search".

**Comment by sanni85** [comment]
for EllipticCurve/, that part of code appears because in the html is under the check
{% if DEBUG %}, so if you run sage -python start-lmfdb.py --debug -t you will see it while if you run sage -python start-lmfdb.py -t  you will not see it. Probably it needs an edit but that was not the aim of this pull request.

Fixing the genus 2 now.

**Pull request merged**
