### PR TITLE
Display default values for characters on character pages.

### PR DESCRIPTION
**Pull request by davidlowryduda**
This was first mentioned in #71, although there is more discussion
there. See also #2465.

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
So this works and the sliders are gone, which is great, but before we can merge this we are going to need to impose a bound on the modulus for which we try to compute Gauss/Jacobi/Kloosterman sums.  If you go to a random Dirichlet character, the modulus is likely to be large enough that these sums cannot be computed in a reasonable amount of time (i.e. a second or two).   Try going to http://127.0.0.1:37777/Character/Dirichlet/87497/76911 for example.  The compute buttons are then completely non-responsive.

I would suggest that we not try to compute these sums when the modulus exceeds 999 (it still works OK at 9999 but is sluggish, whereas at 999 everything is snappy).  I think we should simply hide the sums entirely when the modulus is 1000 or greater.  Is this a change you can make @davidlowryduda ?

**Comment by pascalmolin** [comment]
There should be already this kind of mechanism. If the modulus is large the
WebCharacter class has some features disabled (character values, character
sums...).
Right now the limit is fixed at 100000, we could set it to 1000.

(see the lines "if modulus < 100000:" in characters/main.py)

Do you think there should be a different limit for character sums and
display of character values and generators ?

Pascal



2018-05-30 0:05 GMT+02:00 Andrew Sutherland <notifications@github.com>:

**Comment by AndrewVSutherland** [comment]
@pascalmolin Yes, I am aware of this.  I think ideally there should different (lower) value for character sums.  But if this is a pain to implement, compromising on 10000 for both would be manageable.

**Comment by pascalmolin** [comment]
Done in PR#2471 (sorry I should have merged with David's PR).

Also I read David's PR#2470, I think we could handle these default values
differently:
- using javascript calls makes the server recompute the dirichlet group for
each
- those values could be computed from the beginning and added to the
character object instead.

I can do this if you want (for q<1000 this is not a big deal).

Pascal

2018-05-30 11:14 GMT+02:00 Andrew Sutherland <notifications@github.com>:

**Comment by davidlowryduda** [comment]
Yes, when I wrote my initial PR I hadn't thought about limiting the modulus, so it didn't occur to me to precompute values. But it's not clear to me that it's a good idea to precompute them still, unless I misunderstood your comment and you meant to add them to the database? Otherwise I think that precomputing a million Kloosterman sums on each page is a bit excessive.

I notice that Pascal's #2471 is almost exactly what I would have done, but also that we both modify some of the same parts of the same file in slightly different ways. In a little bit I will go ahead and absorb #2471 into #2470 and not worry about the merge later.

**Comment by davidlowryduda** [comment]
Ah, i see now that @pascalmolin put in his own pull request to do the same thing. These two pull requests are now essentially duplicate. I shall close mine and merge his.

**Pull request closed without merging**
