### PR TITLE
Uniform Capitalization of Titles

### PR DESCRIPTION
**Pull request by jenpaulhus**
This pull request is the second part of my summer students' warmup exercise.  They went through the webpages and updated all the titles to be capitalized uniformly.  

Our recommendation, and what we chose to do, is to capitalize all words except for articles, coordinating conjunctions, and prepositions, since the page titles were almost all non-sentences (verses short sentences used as titles where the convention is only to capitalize the first word of the title, and proper names and such).

We didn't change phrasing of titles with one exception.   The Dirichlet Character search result page had "LMFDB" as a title (see: http://beta.lmfdb.org/Character/Dirichlet/?modulus=&conductor=&order=&search=1&limit=25).   We changed that to "Dirichlet Character Search Result" 

Here are a list of all the changes.   We did not list the webpages these changes appear on, but if that is something you need to see, we can add them.
 
**From lmfdb/website.py** 
-  LMFDB page not found → LMFDB Page Not Found
-  LMFDB error → LMFDB Error

**Universe**
 universe → Universe

**News**
 LMFDB in the news → LMFDB in the News 

**First zeros**
-  Search for first zeros of L-functions→ Search for First Zeros of L-functions 
- Tensor Products (Operations in sidebar) Tensor products → Tensor Products Tensor products navigation → Tensor Products Navigation 

**Holomorphic Cusp Forms (from Degree 2 L-functions)**
 L-functions of Cusp Forms on \Gamma_0(N) with trivial character → L-functions of Cusp Forms on \Gamma_0(N) with Trivial Character

**L-functions of Elliptic Curves** 
- Symmetric square L-functions of Elliptic Curves → Symmetric Square L-functions of Elliptic Curves Symmetric cube L-functions of Elliptic curve → Symmetric Cube  L-functions of Elliptic Curve  
- A brief history of L-functions → A Brief History of L-functions  
- L-functions of Cusp Forms on \(\Gamma_0(N)\) with trivial character → L-functions of Cusp Forms on \(\Gamma_0(N)\) with Trivial Character  
- L-functions of GL(2) Maass Forms of weight 0 → L-functions of GL(2) Maass Forms of Weight 0  

**Riemann Zeta Function** 
-  Riemann zeta function → Riemann Zeta Function 
- Extent of data for Riemann zeta zeros → Extent of Data for Riemann Zeta Zeroes	
- How the Riemann zeta zeros were computed → How the Riemann Zeta Zeros were Computed

**Maass Forms**  
- Browsing graph of Maass forms → Browsing Graph of Maass Forms   
- Maass form of weight {0} and level {0} → Maass Form of Weight {0} and Level {0}   
- Maass form(s) on \(\mathrm{PSL}(2,\mathbb{Z}[i])\) → Maass Form(s) on \(\mathrm{PSL}(2,\mathbb{Z}[i])\) 

**Hilbert Modular Forms** 
- Search results → Search Results       
- Hilbert modular forms over totally real cubic number fields → Hilbert Modular Forms over Totally Real Cubic Number Fields
- Completeness of the Hilbert Modular Forms data → Completeness of the Hilbert Modular Forms Data 
- Source of the Hilbert Modular Forms data → Source of the Hilbert Modular Forms Data  - 

**Bianchi Modular Forms** 
- Bianchi modular forms → Bianchi Modular Forms  
- Labels for Bianchi newforms → Labels for Bianchi Newforms  
- Search results → Search Results 

**Half Integral Weight Cusp Forms** 
Search results → Search Results 

**Siegel Modular Forms**
-  search results → Search Results 
- Siegel modular forms for... → Siegel Modular Forms for...   
- Siegel modular forms dimension tables → Siegel Modular Forms Dimension Tables   
- Siegel modular forms sample... → Siegel Modular Forms Sample... 

**Elliptic Curves over Q**
- Elliptic curves over Q → Elliptic Curves over Q
- Elliptic curves over Q: statistics → Elliptic Curves over Q: Statistics
- Elliptic Curves over Q of conductor … → Elliptic Curves over Q of Conductor …
- Elliptic Curves search results → Elliptic Curves Search Results
- Completeness of the elliptic curve data over Q → Completeness of the elliptic Curve Data over Q
- Source of the elliptic curve data over Q → Source of the Elliptic Curve Data over Q
- Labels for elliptic curves over Q → Labels for Elliptic Curves over Q

**Elliptic Curves over Number Fields**
- Completeness of the elliptic curve data over number fields → Completeness of the Elliptic Curve Data over Number Fields
- Source of the elliptic curve data over number fields → Source of the Elliptic Curve Data over Number Fields
- Labels for elliptic curves over number fields → Labels for Elliptic Curves over Number Fields
- Elliptic Curves over … of conductor → Elliptic Curves over … of Conductor
- Elliptic Curve isogeny class … over Number Field … → Elliptic Curve Isogeny Class … over Number Field …
- Elliptic Curve search results → Elliptic Curve Search Results
- Elliptic curves over quadratic number fields → Elliptic Curves over Quadratic Number Fields
- Elliptic curves over quartic number fields → Elliptic Curves over Quartic Number Fields
- Elliptic curves over quintic number fields → Elliptic Curves over Quintic Number Fields
- Elliptic curves over sextic number fields → Elliptic Curves over Sextic Number Fields
- Elliptic curves over number fields of degree … → Elliptic Curves over Number Fields of Degree ...
- Elliptic curves over real quadratic number fields → Elliptic Curves over Real Quadratic Number Fields
- Elliptic curves over imaginary quadratic number fields → Elliptic Curves over Imaginary Quadratic Number Fields
- Elliptic curves over totally real cubic number fields → Elliptic Curves over Totally Real Cubic Number Fields
- Elliptic curves over mixed cubic number fields → Elliptic Curves over Mixed Cubic Number Fields
- Elliptic curves over totally real quartic number fields → Elliptic Curves over Totally Real Quartic Number Fields
- Elliptic curves over totally real quintic number fields → Elliptic Curves over Totally Real Quintic Number Fields
- Elliptic curves over totally real sextic number fields → Elliptic Curves over Totally Real Sextic Number Fields
- Elliptic curves over number fields of degree …, signature … → Elliptic Curves over Number Fields of Degree …, Signature ...

**Genus Curves 2 over Q** 
- Genus 2 curves over Q → Genus 2 Curves over Q
- Genus 2 curves over Q: statistics → Genus 2 Curves over Q: Statistics
- Genus 2 curves in isogeny class … of discriminant … → Genus 2 Curves in Isogeny Class … of Discriminant …
- Genus 2 curves of conductor … → Genus 2 Curves of Conductor …
- Genus 2 Curve search results → Genus 2 Curve Search Results
- Completeness of genus 2 curve data over Q → Completeness of Genus 2 Curve Data over Q
- Source of genus 2 curve data over Q → Source of Genus 2 Curve Data over Q
- Labels for genus 2 curves over Q → Labels for Genus 2 Curves over Q

**Families of Higher Genus Curves with Automorphisms**
- Families of Higher Genus Curves with Automorphisms: statistics → Families of Higher Genus Curves with Automorphisms: Statistics
- Families of Higher Genus Curves with Automorphisms: genus … group statistics … → Families of Higher Genus Curves with Automorphisms: Genus … Group Statistics …
- Families of Higher Genus Curves with Automorphisms Search Result → Families of Higher Genus Curves with Automorphisms Search Results
- Family of genus … curves with automorphism group … → Family of Genus … Curves with Automorphism Group …
- One refined passport of genus … with automorphism group … → One Refined Passport of Genus … with Automorphism Group …
- Completeness of the automorphisms of curves data → Completeness of the Automorphisms of Curve Data
- Label scheme for the data → Label Scheme for the Data
- Source of the automorphisms of curve data → Source of the Automorphisms of Curve Data

**Abelian Variety**
- Abelian Variety isogeny class → Abelian Variety Isogeny Class
- Abelian Variety search results → Abelian Variety Search Results
- Abelian Variety search input error → Abelian Variety Search Input Error
- Completeness of the Weil polynomial data → Completeness of the Weil Polynomial Data
- Source of the Weil polynomial data → Source of the Weil Polynomial Data
- Labels for isogeny classes of abelian varieties → Labels for Isogeny Classes of Abelian Varieties

**Global Number Fields**
- How Number Field Data was Computed → How Global Number Field Data was Computed
- Galois group labels → Galois Group Labels
- Number field labels → Number Field Labels
- Global number field statistics → Global Number Field Statistics
- Global Number Field search results → Global Number Field Search Results
- Number field algebra → Number Field Algebra

**Local Number Fields**
- Completeness of the local field data → Completeness of the Local Number Field Data
- Labels for local number fields → Labels for Local Number Fields
- Source of the local field data → Source of the Local Number Field Data

 **Dirichlet**
- Dirichlet Characters of modulus … → Dirichlet Characters of Modulus …
- Dirichlet Characters of conductor … → Dirichlet Characters of Conductor …
- Dirichlet character labels → Dirichlet Character Labels
- Source of Dirichlet characters → Source of Dirichlet Characters
- Extent of Dirichlet characters data → Source of Dirichlet Character Data
- Group of Dirichlet Characters of modulus … → Group of Dirichlet Characters of Modulus …

 **Hecke Algebras**
- …-adic and mod … data for the Hecke Algebra orbit … → …-adic and mod … Data for the Hecke Algebra Orbit
- Completeness of the Hecke Algebra data → Completeness of the Hecke Algebra Data
- Source of the Hecke Algebra data → Source of the Hecke Algebra Data
- A brief history of Hecke Algebra → A Brief History of Hecke Algebra

**Artin**
- Artin representation search results → Artin Representation Search Results
- Artin representation “label” → Artin Representation “label”
- Completeness of Artin representation data → Completeness of the Artin Representation Data
- Labels for Artin representations → Labels for Artin Representations
- Source of Artin representation data → Source of the Artin Representation Data

**Hypergeometric Motives over Q**
- Completeness of hypergeometric motive data over Q → Completeness of Hypergeometric Motive Data over Q
- Source of hypergeometric motive data over Q → Source of Hypergeometric Motive Data over Q
- Labels for hypergeometric motives over Q → Labels for Hypergeometric Motives over Q

**Galois Groups** 
- Completeness of Galois group data → Completeness of Galois Group Data
- Labels for Galois groups → Labels for Galois Groups
- Source of the Galois group data → Source of the Galois Group Data

**Sato-Tate Groups**
- Sato-Tate groups → Sato-Tate Groups
- Sato-Tate groups search input error → Sato-Tate Group Search Input Error
- Sato-Tate group search results → Sato-Tate Group Search Results
- Sato-Tate group … of weight … and degree … → Sato-Tate Group … of Weight … and Degree …
- Completeness of Sato-Tate group data → Completeness of Sato-Tate Group Data
- Source of Sato-Tate group data → Source of Sato-Tate Group Data
- Labels for Sato-Tate groups → Labels for Sato-Tate Groups

**Lattices**
- Completeness of the integral lattice data → Completeness of the Integral Lattice Data
- Source of the integral lattice data → Source of the Integral Lattice Data
- Label of an integral lattice → Label of an Integral Lattice
- A brief history of lattices → A Brief History of Lattices

### CODE REVIEW

**Comment by jenpaulhus** [comment]
I don't think the check failure is on our end. If I am wrong, just let me know.

**Comment by JohnCremona** [comment]
I restarted the Travis build since the only failure was the one we get regularly when one of the external sites is slow to respond.

**Comment by JohnCremona** [comment]
There's another failure now (here and in #PR2522), namely the signature search for number fields which is timing out.

**Comment by JohnCremona** [comment]
There are fixes for the two test failures in a PR to jenpaulhus/lmfdb/capstitles which when merged will trigger a re-test here which should work.  See https://github.com/jenpaulhus/lmfdb/pull/32

**Comment by jenpaulhus** [comment]
Thanks, John.  All clear now.  Apologies for not running tests before.  In my rush to get this up, I forgot about that step.

**Comment by davidlowryduda** [comment]
Good! And I think it's nice that you had your students get involved. I'm merging this in.

**Pull request merged**
