### PR TITLE
Tweak universe

### PR DESCRIPTION
**Pull request by davidfarmer**
Does this fix the visibility problems with the universe picture?

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
It helps!  But it's still a bit too big, let me play with it on my machine and I may post another pull request shortly.

**Comment by davidfarmer** [comment]
For those people who have a narrow browser, it is already on the small side.  (For example, if
I put two browsers side-by-side.)

Let's not ruin it for everyone else just to accommodate those people who maximize their browser.

**Comment by AndrewVSutherland** [comment]
If I change the svg.width to 72% it just fits.  At 88% clicking on the L-function button puts all the text below the bottom of the screen except the word "Example".   I think running browser maximized is a more common use case (and at least it would still works at 72% when not maximized, where as it is not usable at 88% when maximized).

**Comment by davidfarmer** [comment]
It seems like you are testing on a screen that is unusually wide compared
to its height.

**Comment by AndrewVSutherland** [comment]
It's a standard 16:9 aspect ratio, which is also the standard ratio for projectors.

**Comment by sanni85** [comment]
One of the problem is that the information displayed on hovering are at the bottom of the picture, so it would be great not to have to scroll, and have it all on one screen.

**Pull request merged**
