### PR TITLE
Serve static files from inventory sub-dir

### PR DESCRIPTION
**Pull request by hratcliffe**
Backup routing for static files, so that they are correctly handled if webserver does not intercept them.

### CODE REVIEW

**Comment by JohnCremona** [comment]
How could we test this, given that in a local instance of the webserver the code would not run?  I see that Edgar has just merged it so perhaps the plan is to push to beta and see.

**Comment by edgarcosta** [comment]
@JohnCremona, I just checked that you can load the static files in `lmfdb/inventory_app/static/`, e.g.:
http://localhost:37777/inventory/static//inventory_general.js
or 
http://localhost:37777/inventory/static/index_viewer.js

and now that these files load, you should be able to test inventory in a local instance

**Comment by JohnCremona** [comment]
@edgarcosta I am puzzled.  I could already test the inventory locally and did so before merging the big PR.  I just ran into problems on beta.  As for the two URLs above, the first shows the text file which I think is expected, but the second returns a Bad Request page saying "No collection static.index_viewer.js exists".

**Comment by edgarcosta** [comment]
This PR should fix that.

**Comment by JohnCremona** [comment]
> This PR should fix that.

Yes it does, thanks.  Any objection to merging to beta now?

**Comment by edgarcosta** [comment]
Nope!

**Pull request merged**
