### PR TITLE
Jumpbox

### PR DESCRIPTION
**Pull request by AndrewVSutherland**
If you visit https://blue.lmfdb.xyz/ and go to any of the main browse pages (e.g. elliptic curves or number fields), you will see that the headings have been streamlined to "Browse", "Search", "Find", and that "Find" has been moved below "Search".

The motivation for this change is that Search is more common than Find and requires less LMFDB specific knowledge.

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
The build errors are a pyflakes unused import (caused by a recent PR, not this one) and a timeout in the usual place.  I'm going to merge this and then fix the pyflakes issue.

**Comment by roed314** [comment]
I'm getting test failures that look related to this.  I'll make a separate PR to fix them.

**Comment by AndrewVSutherland** [comment]
There were three merge conflicts I had to fix, it's possible I messed up one of them.  Let me know if you want me to look at anything.

**Comment by roed314** [comment]
Let's let Travis run on #4090.

**Pull request merged**
