### PR TITLE
ECs over Q: Show both endomorphism rings and introduce "potential Complex Multiplication"

### PR DESCRIPTION
**Pull request by samuel-rice**
This works towards finishing off issue #3683 

This builds on and includes the first commit of #4075. This is somewhat redundant information for ECs over Q, but if we like this presentation then I can also do this for ECs over number fields, where the data will be more interesting.

### CODE REVIEW

**Comment by samuel-rice** [comment]
I apologise if the multiple PRs are confusing. Probably best to just run with this one.

**Comment by samuel-rice** [comment]
Just pushed some build fixes

**Comment by JohnCremona** [comment]
@samuel-rice It's good practice to give a couple or URLs so that reviewers can see what has changed.  Here there are two types of curves worth looking at:

    - http://localhost:37777/EllipticCurve/Q/11a1/ (no CM, not even potential)
    - http://localhost:37777/EllipticCurve/Q/27a1/ (potential CM)

I suggest that in the second case "(potential CM)" would look better on the second line (the Geometric one) than on the first of the two lines.

Secondly, on the search page and also the search results page, for consistency we should change the label of one search box from "CM" to "potential CM".  (The "CM discriminant" box can stay as it is.)

We also now need a knowl for "potential CM", or perhaps add to the existing knowl for CM the definition of potential CM.  Then, make the entire phrase "potential CM" into the knowl link on both the search box and on the curve's own page.

Lastly -- unless people think that this should be a separate issue, it seems to go naturally in with this change -- the should improce the way CM is indicated on an isogeny class page such as http://localhost:37777/EllipticCurve/Q/27a/.  The point here is that isogenous curves either all have CM or all do not, and the CM field is the same for all but the CM order (and discriminant) is not.  Currently the only menyion of CM on an isogeny lcass page is in the Properties box which shows one discriminant, probably that of curve #1 in the class.  Here is one suggestion for what we can do here:
   1. Add a section to the page with title "Complex Multiplication" which either says "The curve/curves in isogeny class * do not have Complex Multiplcation", or  "The curve/curves in isogeny class *  have Complex Multiplcation by an order / orders in the field *" where the * are filled in appropriately.
   2. In the properties box, replace the single discriminant by the field, e.g. $\Q(\sqrt{-3})$.
   3. In the table of curves, *if* the class is CM but not otherwise, add a column headed "CM discriminant" listing the CM discriminant of each curve.

I'm happy for this last point to be made into a separate issue.

**Comment by samuel-rice** [comment]
@JohnCremona I shall remember to add example pages in future, thanks.

In the cases of "no CM" and "potential CM", it seems these are both statements about the Geometric Endomorphism Ring, whereas "CM" is a property of the Endomorphism Ring, so maybe should stay next to that. Does this seem reasonable?

For relabelling the search box/search results - was it not the plan to change the search box and search results to allow CM to take the values "yes/no/potential" instead? @AndrewVSutherland 

I don't have the ability to edit knowls, but my gut feeling is that it's simpler to explain potential CM in the knowl for CM anyway.

If we could, I'd prefer a separate issue for isogeny class CM, just so I can focus on fewer things at once.

**Comment by JohnCremona** [comment]
I don't agree with your first statement.  In general (for any field of char.0) the endomorphism ring ER and  Geometric endomorphism ring GER determine one of three cases:

   1. Z=ER=GER:  not CM, not potential CM
   2. Z=ER<GER(= imag.quad.order): not CM, potential CM
   3. Z<ER=GER: genuine CM

The 3rd case cannot happen over Q, or over any field with a real embedding, since the ER always embeds into the base field.  So over Q (which is what this PR is about) we only have the first two cases.

Reading your comment again, perhaps that is what you meant and I misunderstood you.  But since the ER will always be Z, and we are adding a comment about whether or not we have potential CM, this depends on whether the GER is or is not Z.

I agree with the second point.  I'll edit the CM knowl so that we define potential CM too.

Fine to make a new issue for the isogeny class stuff.

**Comment by jvoight** [comment]
This looks like it's going well, I think it's a good idea to add potential CM to the knowl.  

Everyone should have the power to edit knowls (that's supposed to be the easiest thing to do!).  You just need an account on beta--David, Edgar, or Drew can set you up. 

I think this PR covers elliptic curves over the rationals.  Don't we now need to do something similar for elliptic curves over number fields?  A handful of cases will now be in JC's 3rd case.

**Comment by AndrewVSutherland** [comment]
@JohnCremona I think the confusion here might be that the most natural (and I think most common) definition of potential CM includes CM.  So in characteristic 0 an elliptic curve has potential CM if and only if its geometric endomorphism ring is larger than Z and it has CM if and only if its endomorphism ring is larger than Z.  I think these are the right definitions (they are, for example, invariant under base change).

**Comment by JohnCremona** [comment]
@AndrewVSutherland I see.  So, rather than the three mutually exclusive cases in my list you would just say "CM iff ER!=Z and pot CM iff GER!=Z".  That is nice and simple.  See my comment on the knowl (which I edited, adding a definition of potential CM -- which you may well now wnat to re-redit).  The comment is basically that however we word this some people will be confused so we had better make sure that our definitions are easy to see.  (e.g. "no elliptic curve defined over Q has CM" is a statement which would take many people by surprise).

@jvoight For examples, search for field=2.0.4.1 and CM discriminant=-4 (or -16 or perhaps some more).

**Comment by samuel-rice** [comment]
That is indeed the definition I was working with. Perhaps the line about complex multiplication ought to be in a merged cell to the right of both?

I was working under the assumption that it'd be simpler to add this for ECNFs once we've agreed on a layout.

**Comment by samuel-rice** [comment]
What do we think of the merged cells in that last commit?

**Comment by AndrewVSutherland** [comment]
@JohnCremona I think we can avoid jarring/confusing people by being judicious about what we say where.  My suggestion would be to avoid saying "no-CM" entirely.  When both End(E) and End(E_Qbar) are Z I'm not sure we need to say anything, since this is the generic case.  When End(E)=Z but End(E_Qbar)!=Z I would put (potential complex multiplication) in the geometric endomorphism ring line, and when End(E)!=Z I would put (complex multiplication) in the endomorphism ring line and not put anything in the geometric endomorphism line.

In the property box I might suggest just showing End(E_Qbar)\otimes Q, as we do for genus 2 curves (or maybe End(E_Qbar) if you want to be more precise),  but I'm happy to defer to you and/or JV on this.

**Comment by AndrewVSutherland** [comment]
Actually, now that I think about it, I would be fine with saying (no complex multiplication) on the geometric endomorphism line in the case End(E) = End(E_Qbar) = Z.  This would then mean that we say something in all three cases, but that something appears on only one of the two lines.

**Comment by samuel-rice** [comment]
I'm getting a lot of segfaults in PARI as I'm working in WSL, to the point where I can't view ECNF pages locally without omitting a lot of information. Would somebody else be able to modify ECNFs while I'm still diagnosing that problem?

**Comment by JohnCremona** [comment]
+1 to the latest suggestions on what to put in brackets for the three cases.

Not sure about the property box, where conciseness (is that a word?) is important.

**Comment by JohnCremona** [comment]
I like the way it is right now (!) so I will merge this.  I mean both the parenthetical info to the right of the geometric endo ring (present in all cases) and also the property box, which says either "no" or "yes (D=-3)" with the discriminant appropriate to the curve.

**Comment by AndrewVSutherland** [comment]
@JohnCremona Thanks!  I notice there are some capitalization issues (e.g. "Complex Multiplication" should be "complex multiplication" and the captions should use sentence case), but I can fix these in a later PR (there are a bunch of issues like this scattered about on various object pages and I was planning to check them all at the same time I address #486 (which is going to involve looking at every object page anyway).

**Pull request merged**
