### PR TITLE
Change to torsion structure instead of torsion order

### PR DESCRIPTION
**Pull request by vishalarul**
This commit is intended to address issue 2977 "List torsion structure instead of torsion order"
https://github.com/LMFDB/lmfdb/issues/2977

I have made this change in the elliptic curve search results page and the elliptic curve isogeny class page.

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
The affected pages are:

https://beta.lmfdb.org/EllipticCurve/Q/?all=1 vs
http://127.0.0.1:37777/EllipticCurve/Q/?all=1

and 

https://beta.lmfdb.org/EllipticCurve/Q/14/a/ vs
http://127.0.0.1:37777/EllipticCurve/Q/14/a/

**Comment by AndrewVSutherland** [comment]
The Travis failure is due to a test that needs to be changed (the check that 990h has the optimal curve has the torsion order hardwired in, 6 needs to change to [6] in the test (this should be fixed before this PR is merged).

**Comment by vishalarul** [comment]
I went and changed the hardwired 6 to be a [6] in the test.

**Comment by JohnCremona** [comment]
@vishalarul  I recommend that you make changes to a branch of your own and then the pull request will be from your branch to LMFDB's master branch.  No need to make any changes right now as I am reviewing this already.

**Comment by JohnCremona** [comment]
@vishalarul You have changed at least one knowl link to a knowl which do not exist.  There is no ec_torsion_structure, I think that should be ec.torsion_subgroup (which explains the structure and the notation).  That is in the search results template.  Please fix.

**Comment by vishalarul** [comment]
@JohnCremona I have made the knowl fix and am now creating the pull request from a branch of my own #3457. Maybe this pull request should be closed?

**Pull request closed without merging**
