### PR TITLE
Root angle search

### PR DESCRIPTION
**Pull request by roed314**
Addresses #4512.  Things to look at:

* Make sure that inputting `0.1-0.6` no longer gives a server error, and that various search inputs work on root angle.
* Check the two knowls that I've created

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
Still seems a little wonky:

- 0-1 results in 0.00 not -0.5-0.5, which I think is a bug
- 0-0.6 gives 0.0-0.5,-0.5--0.4 as expected, but 0-0.7 gives 0.0-0.5,-0.5--0.30000000000000004, which is correct (within epsilon) but a little startling

The knowls look good.

**Comment by roed314** [comment]
Do you also want `0-0` to give just the point `0.00`?  With the current strategy it's hard to distinguish between `0-0` and `0-1` since the first thing that's done is reduce everything mod 1.

**Comment by AndrewVSutherland** [comment]
It would probably make sense to convert a-a to a before reducing mod 1.

**Comment by roed314** [comment]
Are you okay with `0.4-0.2` being the same as `0.4-1.2` (namely the complement of `0.2-0.4`)?

**Comment by AndrewVSutherland** [comment]
I have no problem with this, it is what I would expect.  But I also would have no problem with displaying an error for intervals a-b with a>b if you are concerned that 0.4-1.2 would be confusing.

**Comment by roed314** [comment]
Ok, I basically rewrote `parse_floats` and `parse_mod1` so that they could both use an alternative to `parse_range2`, rather than trying to work around the limitations of that function.

Some consequences:

* Across the LMFDB, we now accept singletons for floats, which are converted into a small range (width `10^-10`)
* If you enter `1-` or `0-1` or something that covers more than a unit interval, your input is removed since it provides no constraint.
* Backward inputs like `0.4-0.2` raise an error.
* It does a better job of not changing inputs if they don't need to be changed, and not printing a silly number of digits.
* Small denominators (those dividing 4) are now privileged, and converted from a float into a fraction.  Type `0.25` for example.  Under the hood, it's still searching for these as a float range.

**Comment by AndrewVSutherland** [comment]
@roed314 Thanks for this, it is much improved!  The only issue I found with the new version is that the input 1-1.1 produces a strange error:

    http://127.0.0.1:37777/L/?hst=List&root_angle=1-1.1&search_type=List

whereas 1.0-1.1 works as expected.

**Comment by roed314** [comment]
It should be fixed now.

**Pull request merged**
