### PR TITLE
try both labels

### PR DESCRIPTION
**Pull request by edgarcosta**

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
Looks good

**Comment by edgarcosta** [comment]
I will merge once tests pass.
And then to web and dev.

**Comment by jwj61** [comment]
I haven't studied the logic of this -- I know the routing is complicated.

But, when new representations are added, they won't be in the old/new table.  That was supposed to be just for translating old labels to new ones.  Will that cause a problem when new representations are added?

**Comment by edgarcosta** [comment]
I hope this fixes it. The bug is indeed due to a rep not being in the table.

**Pull request merged**
