### PR TITLE
mostly cosmetic fixes (including some knowl id changes) and one bug f…

### PR DESCRIPTION
**Pull request by AndrewVSutherland**
cosmetic fixes, including some knowl id changes, and a small bug fix (no longer attempts to factor zero)

### CODE REVIEW

**Comment by JohnCremona** [comment]
Some comments:
 (1) st_group_dict is defined as a set, but used as a dict.  That does not look right. 
 (2) applying eval() to a string entered into a search box is a bad idea since this can cause arbitrary code to be run but the server!  I think that info['fld'] is already a string in the place this is used, so why is any conversion needed?
(3) I see the point of the zfactor() function, but it does not actually factor n when non-zero!  Ias that intentional?
I have not yet looked at the pages to judge the cosmetic element...

**Comment by AndrewVSutherland** [comment]
I'll fix these (some were remnants from changes Dan Yasaki had in progress that he transferred to me).  Should I submit a new pull request once I have done this?

Let me know if you spot anything else!




On August 4, 2015 2:50:06 PM EDT, John Cremona <notifications@github.com> wrote:
>Some comments:
>(1) st_group_dict is defined as a set, but used as a dict.  That does
>not look right. 
>(2) applying eval() to a string entered into a search box is a bad idea
>since this can cause arbitrary code to be run but the server!  I think
>that info['fld'] is already a string in the place this is used, so why
>is any conversion needed?
>(3) I see the point of the zfactor() function, but it does not actually
>factor n when non-zero!  Ias that intentional?
>I have not yet looked at the pages to judge the cosmetic element...
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/LMFDB/lmfdb/pull/314#issuecomment-127712698

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by JohnCremona** [comment]
A new pull request is not needed, just update your branch and the pull
request will notice.  I'll come back to this tomorrow...

**Comment by AndrewVSutherland** [comment]
Hi John,

(1) st_group_dict is in fact a dict, it's just a silly one (the key and 
value are always the same).  This is as it is in the current version, I 
just changed the name "st_temp" to the more informative "st_group_list". 
  I believe it was originally implemented this way just to match the 
other drop down lists: the key is the database query value and the value 
is the string displayed -- in the case of the Sato-Tate groups these two 
things happen to coincide but in general they don't.

(2) I got rid of the eval().  It is necessary to parse the string 
because these fields are all stored in the database as arrays of ints, 
not strings.  The search for these items in the current version of 
beta.lmfdb.org does not work at all because of this mismatch.

(3) Fixed zfactor() which should indeed factor nonzero inputs -- thanks 
for noticing!

The changes to (2) and (3) have been committed, I don't think (1) 
requires any change but let me know if you do.

Cheers,

Drew

**Comment by JohnCremona** [comment]
Sounds good.  I had notes that in general, input parsing was rather
primitive here (doing a search by label crashes if no object with the label
exists, even if you put in a trailing space!) but that should be fixed
independently once David Roe's general-purpose parsing module is complete.
I'll have another quick check and then expect to merge this -- thanks.

**Comment by JohnCremona** [comment]
OK!

**Pull request merged**
