### PR TITLE
Fixes for finishing renaming

### PR DESCRIPTION
**Pull request by roed314**
I've fixed a few bugs in the renaming process, and made the code changes required for the two renames currently in progress.

To test, wait until #2891 is pushed to web and then try to finish the rename process for [dq.character.dirichlet.source](http://localhost:37777/knowledge/edit/dq.character.dirichlet.source) and [content.how-to-cite](http://localhost:37777/knowledge/edit/content.how-to-cite).

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
@roed314 #2891 has been pushed to web.  Can you test and tell me when it is safe to merge this?

**Comment by roed314** [comment]
I found a problem with updating the authors.  I've fixed it with a new commit on this PR, but we should probably test renaming again.  Once #2898 is merged and pushed to web I can try the Finish Rename process again.

**Comment by roed314** [comment]
I also changed renaming so that it doesn't add the admin to the list of authors.

**Comment by roed314** [comment]
Merged in #2895 so that tests pass; that PR should be reviewed first.

**Comment by roed314** [comment]
I just merged in master to make this easier to review.

**Comment by roed314** [comment]
Note that I'm still waiting on #2898 to be merged and pushed to web in order to test the process again.

**Comment by AndrewVSutherland** [comment]
I merged #2898 and pushed it to web.

**Comment by roed314** [comment]
Okay, I've fixed the problem with authors getting removed on renaming.  From my perspective, it's ready to be merged.

**Comment by AndrewVSutherland** [comment]
Looks good (I can't seem to break it) -- meging.

**Pull request merged**
