### PR TITLE
Hmf l2

### PR DESCRIPTION
**Pull request by davidfarmer**
The zeros and plots of the L-function of a Hilbert modular form were broken. This seems
to be due to the url parsing expecting a different form that we currently use.

The Z-function plot and initial zeros should now appear on L/HMF pages:

http://localhost:37777/L/ModularForm/GL2/TotallyReal/2.2.5.1/holomorphic/2.2.5.1-31.1-a/0/0/

### CODE REVIEW

**Comment by davidfarmer** [comment]
I slightly messed up this pull request.  I accidentally added the changes to fix the HMF L-functions on
top of some, but not all, of the commits for toggling on the genus 2 L-function home pages.

I only wanted the final commit here (parsing of URL for L-function of HMF 	9d82089) to be in
this pull request.  That commit only adds a few lines to one file, and is independent of the
other commits.  Hopefully this is easy for someone who knows git better than I do.

**Comment by JohnCremona** [comment]
I'll take that as a challenge and see what I can do.

**Comment by JohnCremona** [comment]
Here is what I did:
# Move to my master branch (which was up-to-date with upstream):
git checkout master
# I have a remote called farmer already, so pull in its new branches:
git remote update farmer
# Create my own branch also called hmfL2:
git checkout -b hmfL2
# pull in the changes from the last commit (only!) of branch farmer/hmfL2:
git cherry-pick farmer/hmfL2
# push to my github:
git push origin hmfL2

Now I could close this pull request and make my own, though of course that would make me appear the author of this change (just as David did to Jeroen yesterday).

**Comment by JohnCremona** [comment]
I just merged #338 so will close this.

**Comment by JohnCremona** [comment]
See further remarks at #338.

**Pull request closed without merging**
