### PR TITLE
Styling of non-existent knowls, such as those at the top and bottom

### PR DESCRIPTION
**Pull request by davidfarmer**
of most elliptic curve pages.

### CODE REVIEW

**Comment by JohnCremona** [comment]
Any reason for keeping in the string "Create it"?  Otherwise good, I like the smaller size & colour!

**Comment by jwj61** [comment]
I think keeping "create it" sounds like a good idea -- clearer to someone who someone working on lmfdb who may not figure out the color convention.

**Comment by JohnCremona** [comment]
So for consistency should we reinstate "Create it" in the normal situation which we changed yesterday?  e.g. on http://beta.lmfdb.org/Genus2Curve/Q/169/a/169/1 ?

**Comment by JohnCremona** [comment]
Perhaps have '[create knowl]' instead of 'Create it', i.e. put the words in brackets and be more specific that clicking will create the knowl.

**Comment by davidfarmer** [comment]
I am okay with '[create knowl]' instead of 'Create it'.

What is the right way for me to make that change?

**Comment by davidfarmer** [comment]
I think we need the "Create it" in the case of top and
bottom knowl which have no useful title.

But in the case of knowls in regular text, a good example is
at the end of the Conductor knowl on

/Genus2Curve/Q/
,
the words "Create it" are obtrusive.  I don't think the
learning curve is too steep for seeing what knowls need
to be created -- assuming the new purple color is clear
enough.

**Comment by JohnCremona** [comment]
Make a new commit on top of the current one and push to your github, same branch name createit2.  Then github will automatically update the pull request to include this additional commit.

**Comment by JohnCremona** [comment]
PS I'm OK with not having the extra words normally, you are right that these can occur in the middle of text and the extra words would distract.

**Comment by davidfarmer** [comment]
I pushed the update.

**Comment by JohnCremona** [comment]
Good -- tested and about to merge...

**Pull request merged**
