### PR TITLE
307 for random pages

### PR DESCRIPTION
**Pull request by edgarcosta**
Various random routes are broken on beta, as apache caches the redirect, thus, you get always the same object.
I tried to make sure that every random route has a 307 as its redirect code.

### CODE REVIEW

**Review by SamSchiavone — APPROVED** [review]

**Comment by edgarcosta** [comment]
looks like we also need to disable cache:
```
    response = make_response(redirect(url_for(".by_label", label=label), 307))
    response.headers['Cache-Control'] = 'no-cache, no-store'
    return response
```

**Comment by AndrewVSutherland** [comment]
I fixed the travis failures (which had nothing to do with this PR).  Is this PR ready to merge?  I wasn't clear whether your content from 9 days was suggesting another commit was forthcoming or not.

**Comment by edgarcosta** [comment]
This is progress, but will still not fix the fact that on beta.lmfdb.org the random button will always give you the same object unless you set  `Cache-Control` to `no-cache, no-store`.

I will add a commit later on in the week to take care of that.

**Comment by edgarcosta** [comment]
I used the wrapper that we can easily redirect with cache disabled.

Locally, you won't be able to test this, but the only effect will be on beta, where clicking the random button will start to give different objects.

Tests pass on grace.

**Comment by AndrewVSutherland** [comment]
Can I merge this?

**Comment by edgarcosta** [comment]
yes

**Pull request merged**
