### PR TITLE
Use ideal labels

### PR DESCRIPTION
**Pull request by pascalmolin**
Use the nfideals numbering scheme John C pushed yesterday
+ move some character implementation in the character folder to facilitate integration of Samuele's mod-l characters

### CODE REVIEW

**Comment by pascalmolin** [comment]
All test pass, except the 2 failures and 4 errors also present on master

**Comment by davidfarmer** [comment]
Where should I look to see the new labels?

**Comment by pascalmolin** [comment]
These appear for example in the list of 127.0.0.1:37777/Character/Hecke/3.3.81.1
But I sould say that I consider this commit an "internal only" modification:  I have decided to make the small modification of getting rid of an old naming scheme I coined several years ago (based on two-elements representation of ideals).

Discussion about how the ideals should actually be displayed should now take place before I move on.

**Comment by davidfarmer** [comment]
When will you document the naming scheme?

Does the implementation of conrey characters duplicate other code?

**Comment by pascalmolin** [comment]
2017-06-13 12:47 GMT+01:00 davidfarmer <notifications@github.com>:

> When will you document the naming scheme?
>
@johncremona @aurelpage can I rely on one of you concerning this issue? It
would be nice indeed to have knowls on this naming scheme.

> Does the implementation of conrey characters duplicate other code?
>
No (this is just code moving from one file to another).

**Comment by JohnCremona** [comment]
@davidfarmer I will write a knowl about the labelling / sorting of ideals and prime ideals over number fields, as soon as @pascalmolin 's code is merged, just as we already do for Conrey labelling of Dirichlet characters.

**Comment by davidfarmer** [comment]
Accepting this pull request, and then immediately adding an issue and assigning it to @JohnCremona

**Pull request merged**
