### PR TITLE
Clickable plots

### PR DESCRIPTION
**Pull request by nmascot**
Make plots of elliptic and hyperelliptic curves enlargeable by clicking on them

### CODE REVIEW

**Comment by edgarcosta** [comment]
Thanks!

It works on Firefox, however, not in Chrome.
Chrome doesn't allow the user to (automatically) navigate to data URL.
A workaround is to use fancybox or something like that to have a popup effect, see: http://fancyapps.com/fancybox/3/ .
Anyway, this is not worth the effort at the moment.

I'm happy to merge this.

**Comment by edgarcosta** [comment]
Another alternative is to use what you suggested in #2335:
https://www.w3schools.com/howto/howto_css_modal_images.asp
but fancybox already has all that builtin, and it is easy to use.

**Comment by AndrewVSutherland** [comment]
@nmascot @edgarcosta What is the status of this PR?  It looks like there is a conflict that needs to be resolved before it can be merged.

**Comment by edgarcosta** [comment]
@AndrewVSutherland Tonight I will double check that I have indeed fixed the conflict

**Comment by edgarcosta** [comment]
I have resolved the conflict.

**Comment by AndrewVSutherland** [comment]
@edgarcosta Thanks.  BTW, it does work in chrome if you use open link in a new tab (or open image in a new tab).

**Pull request merged**
