### PR TITLE
avoiding database_names and collection_names -> try/except

### PR DESCRIPTION
**Pull request by edgarcosta**
Addressing #1170

### CODE REVIEW

**Comment by fredstro** [comment]
This patch seems ok.  All tests for elliptic modular forms pass.
Although for code-consistency I would have preferred new-style string formatting rather than '%s' and possibly a critical error message written to the logfile in addition to raising the exceptions but these are minor issues.

**Comment by fredstro** [comment]
I just noticed one problem (which should have been a problem before this pull request as well)
When there is an error we try to write to the log with emf_logger but this is not defined. 
It might be easier if you could just add a line
from lmfdb.modular_forms.elliptic_modular_forms import emf_logger at the top of the file

**Comment by jwj61** [comment]
@fredstro  Add that to which file?

**Comment by fredstro** [comment]
To lmfdb/modular_forms/elliptic_modular_forms/backend/__init__.py

**Pull request merged**
