### PR TITLE
Restrict number of components for ST groups to 10^20

### PR DESCRIPTION
**Pull request by AndrewVSutherland**
Restricts the maximum size of ST groups mu(n) to 10^20 to avoid attempting to factor a large number.  Also adds ST groups as friends on Dirichlet character pages (addressing #1184).

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
added some more tests and fixed a few more large modulus issues.  all tests now pass (except one known classical mf issue)

**Comment by AndrewVSutherland** [comment]
In addition to addressing Sato-Tate groups mu(n) with n up to 10^20, this PR ensures that Dirichlet characters of modulus up to 10^20 now work correctly (as claimed on www.lmfdb.org/Character/Dirichlet/).  Previously characters with modulus > 2^64 did not work, compare

http://www.lmfdb.org/Character/Dirichlet/99999999999999999999/
http://www.lmfdb.org/Character/Dirichlet/99999999999999999999/2

with

http://127.0.0.1:37777/Character/Dirichlet/99999999999999999999/
http://127.0.0.1:37777/Character/Dirichlet/99999999999999999999/2

also handles characters with order > 2^64, such as

http://127.0.0.1:37779/Character/Dirichlet/99999999999999999931/2

**Comment by JohnCremona** [comment]
Quick question -- is there a reason to write Xrange instead of using srange or xsrange?  The ones with s in them are Sage functions and yield Sage integers.

**Comment by AndrewVSutherland** [comment]
No, I will switch to xsrange and remove Xrange.

**Comment by JohnCremona** [comment]
Good!  Just running tests, the pages and code look fine.

**Comment by JohnCremona** [comment]
Running all tests revealed a couple of things -- not relevant for this patch: some extraneous print output in some ecnf tests, and a failed test /home/jec/lmfdb/lmfdb/modular_forms/elliptic_modular_forms/test_emf.py
No reason not to merge this one though.

**Comment by AndrewVSutherland** [comment]
@JohnCremona the failure in test_emf.py is due to bad data in modularforms2 (see #1248).

**Pull request merged**
