### PR TITLE
Mod l mf

### PR DESCRIPTION
**Pull request by sanni85**
In this pull request is contained the re-design done in the small workshop at Warwick on mod l modular forms.
http://beta.lmfdb.org/ModularForm/GL2/ModL/   at the moment returns an error: this is due to the very large number of modifications to the database structure. This is solved with this pull request.

Examples of changes:  
/ModularForm/GL2/ModL/?label=3.1.0.1.1      
 /ModularForm/GL2/ModL/?label=13.1.0.1.1

Not all the search functionalities provided do work (only the one on q-expansion has not been implemented yet), the downloads do work. Lots of work need to be done: if this pull request is merged the work can be shared more easily.

### CODE REVIEW

**Comment by sanni85** [comment]
the new database structure is documented on https://github.com/sanni85/Mod-l-modular-forms
and will be documented in the inventory too in the next 10 min

**Comment by AndrewVSutherland** [comment]
On the page http://127.0.0.1:37777/ModularForm/GL2/ModL/5.3.2.1.1 the links to the form and character both appear to be broken (actually all the character links look wrong, e.g. on http://127.0.0.1:37777/ModularForm/GL2/ModL/3.1.0.1.1 the link is also broken).

The "By weight grading" links do not appear to actually filter the search at all, they all return the same 264 results.

The "By level" links on the main page for the ranges above 30 all return no results, is this expected?  Unless you are planning to add this data soon, I might remove these links until the data is available.

**Comment by sanni85** [comment]
The browse part now works, some search was giving no result because the data range for now is very limited. After the last commit,  the maximum of level and weight grading are returned from the database so no empty search should be returned. I have not fixed the range of characteristics: that is our aim and more data will be added soon.

The links to classical forms are broken because of a data production issue that will be fixed it soon.
The links to characters are now hidden and the problem there is related to labels of Dirichlet characters mod l and relative pages (which do not exist for now)... We (Anna, Bortosz and me) are going to send an email about this soon.

**Comment by sanni85** [comment]
The only two forms were the links are correct are the two "favourite" ones:
 http://localhost:37777/ModularForm/GL2/ModL/?label=3.1.0.1.1
http://localhost:37777/ModularForm/GL2/ModL/?label=13.1.0.1.1

**Comment by JohnCremona** [comment]
OK, I will merge this since it does not affect any "live" pages.  For the future why don't you (and the others) work on a shared branch and only ask for it to me merged into master when it is ready for review by others?

**Pull request merged**
