### PR TITLE
Search number fields by p-adic completions

### PR DESCRIPTION
**Pull request by jwj61**
This allows users to search for number fields based on p-adic completions (see main number field search page for testing) resolving issue #4537 .  As the knowl there explains, one can enter a single label of a p-adic field, or a list.  In the latter case, the fields in the search results will match all of p-adic fields listed (they can be for different p or some with the same p).

On the page for a p-adic field, if there are any number fields which have it as a completion, there is a friends link to search for them.  Any low degree p-adic field will have some.  An example where there is **no** friends link is

http://127.0.0.1:37777/padicField/19.15.14.2

The search parsing checks that the labels match the right general format, but does not check to see if they are labels of local fields in the database (if it is not in the database, the search results will be empty).

For the knowl for the number field search page, it currently uses

https://beta.lmfdb.org/knowledge/show/nf.place

but before noticing this, I wrote the more detailed

https://beta.lmfdb.org/knowledge/show/nf.padic_completion

We can switch it (which only involves editing a knowl), or delete the new knowl.

### CODE REVIEW

**Comment by JohnCremona** [comment]
I think this is going to be very useful.  I suspect that few users will know the labels of p-adic fields so the links will be used more than the search itself (I guess).  I suspect that further feature requests will follow, e.g. on a number field home page, links to its completions (at small primes -- this exists for bad primes in the "local algebras for ramified primes" section, but could be extended) and something like a link to "other fields with the same completion at (some) primes(s).  But that's no reason to delay this.

I can see a case for having both knowls (one for a place and one for a completion), each referencing the others.  On the search page, a knowl for what a completion is seems more appropriate.

Thinking about the Archimdean analogue, of course the search on Signature does wverything but requires a second's thought e.g. to remember that real quadratic is signature [2,0] not [0,2].  Is there a simple way to allow "totally real" and "totally complex" as options for the signature?  -- OK, this is a separate issue!

**Comment by jwj61** [comment]
If the signature box was replaced with a pair for the number of real and number of complex places, one could easily search for totally real and totally complex fields.

**Comment by JohnCremona** [comment]
> If the signature box was replaced with a pair for the number of real and number of complex places, one could easily search for totally real and totally complex fields.

You mean to replace the single Signature box with two?   That sounds ok to me, especially if we could fit them into the same space -- not easy.  This gives greater flexibility thatn what we now have, as you suggest, since you could specify 0 for one of the two and leave the other open.  (Next someone will ask to be able tosearch on r1+r2-1, the unit rank...)

Anyway, that's a separate issue / feature request.  Ready to merge this one?

**Comment by AndrewVSutherland** [comment]
The p-adic field pages on https://www.lmfdb.org are currently broken because this PR was pushed to web earlier by @edgarcosta and it appears there are schema changes to lf_fields and nf_fields that this PR depends on that have not been made to the production database.  It looks like I need to update both of these tables?  Is there anything else that needs to be done?

**Comment by edgarcosta** [comment]
I'm fixing this now

**Comment by edgarcosta** [comment]
Both www.lmfdb.org is now serving 053b73bbb90483333fc6e7053e4811676dfa4bf3.

Let me know when it is okay to reenable the automatic fetching and restart

**Comment by AndrewVSutherland** [comment]
lf_fields has been updated and nf_fields is in progress.  I'll let you know when it finishes.

**Comment by AndrewVSutherland** [comment]
@edgarcosta lf_fields and nf_fields have both been copied over, we should be able to switch www.lmfdb.org back to web.

**Pull request merged**
