### PR TITLE
Displaying the polynomial whose root the root is on embedded MF page.

### PR DESCRIPTION
**Pull request by rbommel**
Hopefully, this solves issue #3012. See that issue for examples of pages that changed.

### CODE REVIEW

**Comment by davidfarmer** [comment]
I will evaluate this pull request.

**Comment by AndrewVSutherland** [comment]
@davidfarmer Are you still planning to review this?  We are trying to get all the oustanding PR's merged in preparation for the move to Sage 9.

**Comment by davidfarmer** [comment]
This change does not address the fundamental issue in issue  #3012 .
The knowl on "Root" is still confusing, and putting the polynomial that the
root is a root of, is still cryptic.  I think it will take several changes to address
the issue.

I don't think it is helpful to make this one change, so I will close this pull request
so that it does not interfere with the move to Sage 9.

**Comment by AndrewVSutherland** [comment]
@davidfarmer Thanks.  Issue #3012 is tagged with the 1.2 milestone, so it will be revisited in the not too distant future.

**Comment by edgarcosta** [comment]
This is an improvement regardless

**Pull request merged**
