### PR TITLE
Whitelisting web

### PR DESCRIPTION
**Pull request by edgarcosta**
The goal of this PR is to limit the pages that we display on www.lmfdb.org.
If such a page is not whitelisted, then the address will be redirected to [beta.lmfdb.org](beta.lmfdb.org)

I'm at the moment running a modified version of this branch on https://red.lmfdb.xyz, where I replaced the `www.lmfdb.org` on line 226 of `lmfdb/app.py` with `red.lmfdb.xyz`.

Please look at https://red.lmfdb.xyz/forcebetasitemap and double check that I didn't miss any route.

I'm also currently doing a recursive wget on red.lmfdb.xyz, and so far these are redirects that I have hit:
```
Location: https://beta.lmfdb.org/Representation [following]
Location: https://beta.lmfdb.org/zeros/first/ [following]
Location: https://beta.lmfdb.org/L/ModularForm/GSp4/Q/Maass/1/1/12.46875_4.720951/1.34260324/ [following]
Location: https://beta.lmfdb.org/\"" [following]
Location: https://beta.lmfdb.org/L/ModularForm/GL3/Q/Maass/1/1/16.40312_0.171121/-0.4216864/ [following]
Location: https://beta.lmfdb.org/L/ModularForm/GL3/Q/Maass/4/1/8.239796_2.641226/1.066042%20+/ [following]
Location: https://beta.lmfdb.org/L/ModularForm/GL3/Q/Maass/4/1/9.632444_1.374060/0.15012282/ [following]
Location: https://beta.lmfdb.org/L/ModularForm/GL3/Q/Maass/4/1/8.954662_2.936591/0.36025530/ [following]
Location: https://beta.lmfdb.org/L/ModularForm/GL4/Q/Maass/1/1/16.89972_2.272587_-6.03583/0.55659019/ [following]
Location: https://beta.lmfdb.org/L/ModularForm/GSp4/Q/Maass/1/1/19.81936_8.531078/2.06692296/ [following]
Location: https://beta.lmfdb.org/L/browseGraph/?group=GSp4&level=1 [following]
Location: https://beta.lmfdb.org/L/browseGraph/?group=GL4&level=1 [following]
Location: https://beta.lmfdb.org/L/browseGraph/?group=GL3&level=1 [following]
Location: https://beta.lmfdb.org/L/browseGraph/?group=GSp4&level=1 [following]
Location: https://beta.lmfdb.org/L/browseGraph/?group=GL4&level=1 [following]
Location: https://beta.lmfdb.org/L/browseGraph/?group=GL3&level=1 [following]
Location: https://beta.lmfdb.org/Lattice/2.1.2.1.1 [following]
Location: https://beta.lmfdb.org/Lattice/3.1.2.1.1 [following]
Location: https://beta.lmfdb.org/Lattice/4.1.2.1.1 [following]
Location: https://beta.lmfdb.org/Lattice/8.1.1.1.1 [following]
Location: https://beta.lmfdb.org/Lattice/24.1.1.24.1 [following]
Location: https://beta.lmfdb.org/Motive/Hypergeometric/Q/ [following]
Location: https://beta.lmfdb.org/L-function/ [following]
Location: https://beta.lmfdb.org/Character/Hecke/ [following]
```

### CODE REVIEW

**Comment by JohnCremona** [comment]
Is it necessary to list *all* valid routes?  This means that whenever a new route is created (to be seen on prod) we'll need to remember to ad it to the whitelist.  It would be nice if it were possible to have the same end effect while only listing the top-level prefix part of the URL, i.e. the part defined in each module's init file.

**Comment by edgarcosta** [comment]
Unless I'm misunderstanding you, I think that is what we did.
We white list a bunch of top routes, and a URL is whitelisted if matches one of those prefixes or is the bread of one of those routes.

**Comment by JohnCremona** [comment]
I misunderstood. Apologies.  OK!

**Comment by roed314** [comment]
It might be useful to have `/sitemap` be the routes which aren't redirected, so that it's easier to pick out things that don't belong on it.

Great job with this though!

**Comment by edgarcosta** [comment]
@roed314 , I agree with you! Here you have it: https://red.lmfdb.xyz/whitelistedsitemap

**Comment by roed314** [comment]
The docstring for `whitelistedsitemap` has a typo, but otherwise this looks good to me.

Some comments on the white listed items:
* https://red.lmfdb.xyz/Field/history and https://red.lmfdb.xyz/Group/history look pretty barren to me.  Should these be on `lmfdb.org`?
* We get an error on https://red.lmfdb.xyz/L/browseGraphChar/
* https://red.lmfdb.xyz/ModularForm/GL2/Q/Maass/Tables looks very strange.  I just get a `Processing...` message.
* Half integral weight forms seem to have gotten through since they have a whitelisted prefix: https://red.lmfdb.xyz/ModularForm/GL2/Q/holomorphic/half/
* https://red.lmfdb.xyz/api2api.css produces a server error
* https://red.lmfdb.xyz/inventory/controlpanel/ and https://red.lmfdb.xyz/inventory/rescrape/ and https://red.lmfdb.xyz/knowledge/comment_history and https://red.lmfdb.xyz/users/ (plus subroutes) seem to require a login, which won't be possible on prod
* I don't know if we want to have https://red.lmfdb.xyz/knowledge/broken_links available on prod
* https://red.lmfdb.xyz/knowledge/test probably shouldn't be live on prod
* https://red.lmfdb.xyz/search seems to give a link to a Google custom search, but it doesn't work for me.  I don't know if this route is embedded somewhere else?

**Comment by AndrewVSutherland** [comment]
The empty history knows should not be whitelisted.

**Comment by edgarcosta** [comment]
Typo has been fixed.
I checked the log of the recursive wget, and I have not hit any other link that has been redirected to prod.

> https://red.lmfdb.xyz/Field/history and https://red.lmfdb.xyz/Group/history look pretty barren to me. Should these be on lmfdb.org? 

But we want to allow https://red.lmfdb.xyz/Field/ and https://red.lmfdb.xyz/Group.
On the same note, in hindsight, I feel we should use https://red.lmfdb.xyz/NumberField/{Local, Global} and instead of https://red.lmfdb.xyz/{Local,Global}NumberField/

> We get an error on https://red.lmfdb.xyz/L/browseGraphChar/
I think that route requires GET/POST arguments.

> Half integral weight forms seem to have gotten through since they have a whitelisted prefix: https://red.lmfdb.xyz/ModularForm/GL2/Q/holomorphic/half/

Maybe we need to blacklist that one.

> https://red.lmfdb.xyz/api2api.css produces a server error

That is an error on our part, we need to change `@api2_page.route("api.css")` -> `@api2_page.route("/api.css")` and fix the template.

> https://red.lmfdb.xyz/inventory/controlpanel/ and https://red.lmfdb.xyz/inventory/rescrape/ and https://red.lmfdb.xyz/knowledge/comment_history and https://red.lmfdb.xyz/users/ (plus subroutes) seem to require a login, which won't be possible on prod

I'm not sure about the last one, do we really need login to see users pages?

> I don't know if we want to have https://red.lmfdb.xyz/knowledge/broken_links available on prod
https://red.lmfdb.xyz/knowledge/test probably shouldn't be live on prod

Perhaps...

> https://red.lmfdb.xyz/search seems to give a link to a Google custom search, but it doesn't work for me. I don't know if this route is embedded somewhere else?

We should disable that. There was an issue long time ago that we should fix it, and then we decided to remove that from the front page. #2389

**Comment by AndrewVSutherland** [comment]
@edgarcosta Sorry, you are right, we should just remove the history routes from the code, not change the whitelisting.

**Comment by AndrewVSutherland** [comment]
I think the outstanding issues/question all relate to either separate code changes that should be made or the question of whether to blacklist half integral weight modular forms in production (which I think we should, there was never a reason to expect that white-listing prefixes was going to address everything, but it does cover 99 percent of the cases).

@edgarcosta Do you want to add the ability to black-list a URL with a white-listed prefix to this PR (and include https://red.lmfdb.xyz/ModularForm/GL2/Q/holomorphic/half/ in it)?  Or would it be easier to do that in a separate PR after this one is merged?

**Comment by edgarcosta** [comment]
I would honestly prefer to address that in a different PR.

The recursive hasn't finished yet, but now I have several redirects for the
route `/L/SymmetricPower/4/*` should we bound the degree or simple accept
`/L/SymmetricPower/'?

**Comment by AndrewVSutherland** [comment]
I think it's OK to whitelist /L/SymmetricPower/ since we don't display much (no zeros, no special values, just Selberg data and very low precision Dirichlet coeffs) when the conductor is at all large, and I think this already covers all 5th powers and higher, and all 4th powers of anything other than 11a, for example, see

https://www.lmfdb.org/L/SymmetricPower/4/EllipticCurve/Q/11/a/
https://www.lmfdb.org/L/SymmetricPower/5/EllipticCurve/Q/11/a/
https://www.lmfdb.org/L/SymmetricPower/4/EllipticCurve/Q/14/a/

In addition, for all of these symmetric power L-functions, which are computed on the fly, the reliability knowl makes it clear that the information on these pages has not been computed rigorously, see

https://www.lmfdb.org/L/SymmetricPower/4/EllipticCurve/Q/11/a/Reliability

for example. 

I think it would be weird to be browsing the symmetric square of 11a on the production website and be clicking on successively higher powers and then suddenly get redirected to the beta web site.  In general, we should not have links that appear on a production page that lead you to a beta page.  The purpose of the whitelisting is to prevent beta pages from being served by the production site when "beta" is changed to "www" in the URL.

If you agree, go ahead and whitelist https://www.lmfdb.org/L/SymmetricPower/ in this PR and I will merge it.

**Comment by edgarcosta** [comment]
I agree, and I have just pushed the change.

the log on the recursive wget has not displayed any other new route that
has been redirected to beta.lmfdb.org.

**Pull request merged**
