### PR TITLE
Tamagawa number for genus 2

### PR DESCRIPTION
**Pull request by rbommel**
This is an attempt to get the Tamagawa numbers for genus 2 on the web page. Probably there are a lot of advanced functions of which I don't know the existence, that still might need to be implemented.

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
Thanks for this -- I will review it later today.

**Comment by rbommel** [comment]
Hi Andrew,

No problem. Probably, there are still a lot of things that should be 
done. But I managed to get the numbers in the database with Jeroen 
Sijsling's help, and it displays something now.

Regards,
Raymond

**Comment by AndrewVSutherland** [comment]
I think this looks good.  I think we will eventually want to display the Tamagawa numbers in a "local data" table that includes information about the reduction types as we do for elliptic curves, but that doesn't need to happen right now.

We will want to update the data quality knowl http://beta.lmfdb.org/knowledge/show/dq.g2c.source to indicate the source of this data.  How was this data computed?  Is there a reference we can cite?

**Comment by rbommel** [comment]
Thanks!

The data was computed with code I built on top of Magma's RegularModel
code (mainly due to Steve Donnelly, I understood). Right now, there is
no published source that can be cited for my part, but I am preparing a
preprint/article on all of my BSD calculations for hyperelliptic curves
of genus 2 and 3. This might take some more time as a lot of polishing
is needed.

**Comment by JohnCremona** [comment]
@rbommel Please add yourself to the Contributors page by editing the file CONTRIBUTORS.yaml and making a Pull Request.  Thanks!

**Pull request merged**
