### PR TITLE
3rd wave of python3 print fixing in scripts

### PR DESCRIPTION
**Pull request by fchapoton**
final wave of correction for python3-compatible prints in scripts

### CODE REVIEW

**Comment by JohnCremona** [comment]
These all look fine to me and completely harmless though I do have one query:  surely it is not necessary to have the import from future for these changes?  I have been using print as a functions for a long time now even with Sage on python 2.  I would suggest removing the imports before merging.  (I also would not mind if this PR was not merged as it only concerns scripts.)

**Comment by roed314** [comment]
@JohnCremona I just checked and the print function does work without the import, though I'm not sure exactly how.

**Comment by JohnCremona** [comment]
@roed314 Well I don't pretend to be a python expert but I have been using print() for years now, long before Sage's recent beta releases which are Python 3.  I also use (for example) print("x={}".format(1)) instead of print("x=%s" % (1)) or similar.

I think it is because Sage (looking at 8.9) *already* imports print_function (it is in sage.all.py).  Perhaps @fchapoton (who has masterminded Sage's upgrade to Python 3) did not know that the LMFDB code runs under Sage.

If pyflakes 3 is happy without the import functions I think we can remove them.

**Comment by roed314** [comment]
Looks good to me.

**Pull request merged**
