### PR TITLE
Minimal change, trying to speed up /EllipticCurve/Q

### PR DESCRIPTION
**Pull request by jvoight**
Currently /EllipticCurve/Q is slow to load.  Right now, it calls "counts" in order to get ranges for browse.  I hard coded these.  I have slightly improved performance on my local copy, but it's hard to tell if this will make a difference when it goes to the cloud/Warwick.  I'd like to try, and I'm doing this in stages with the minimal change here.  

If this doesn't work, we could then try replacing this code which computes something with instead hard coded lines in the template.  (For example, what is happening in the function zip?)  Since this page is going to be loaded a zillion times, we really shouldn't be doing anything nontrivial.

### CODE REVIEW

**Comment by jvoight** [comment]
See issue #1199.

**Comment by jvoight** [comment]
I'm somewhat skeptical now that this will make a real difference, because HMF pages use counts and they're plenty zippy.

**Comment by jwbober** [comment]
I thought think these counts may be cached, so that they only result in one
database query per webserver process. Then it only takes a while
occasionally.

This is different than #1199, which is really an improper url that I
accidentally accessed.

I'm somewhat skeptical now that this will make a real difference, because
HMF pages use counts and they're plenty zippy.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/LMFDB/lmfdb/pull/1243#issuecomment-217734479>

**Comment by jvoight** [comment]
I'm going to close this since I don't think it will help--there's something else going on.

**Comment by JohnCremona** [comment]
See my comment on another ticket. Solved by adding a new index.

**Comment by jvoight** [comment]
Yup, was there with @AndrewVSutherland helping him by pointing out all of the dead ends.  :)

**Pull request closed without merging**
