### PR TITLE
Handling long Artin labels, resolves #4108

### LINKED ISSUE #4108: Handling long Artin rep labels
On Artin representation pages like [this one](https://beta.lmfdb.org/ArtinRepresentation/64.91641670748848482832403196711945603240247718111273033244589178562712452372568054853495805267834328481580386515777517380942993629003169127244600785859214182603634034597536619998685360883426251038869742819115533880506609428884855573755881411446556815069418421014037949117475102106370659846354282996796928548392095158824994261231634684500171550501405225850346102377743167791739485384057130734154900626854500288026058857501770814530644432993058036873304718121461267084345344.168.a) the label of the Artin representation is so long that it makes the page hard to read (in addition to horizontal scrolling it pushes the proporty box far down the screen.  There is also a problem with number field pages that reference Artin representations with very long labels, like [this one](https://beta.lmfdb.org/NumberField/8.0.5620066455663197695561554590870531303687507769819136.1).

We don't want to change the labels (they have already been changed once), we just need to handle displaying them in a reasonable way.  We already have a mechanism for displaying very large integers using "bigint knowls" and it would make sense to do something similar here.  Concretely, the suggestion would be to display to replace the middle of the conductor part of the label with "..." so that it would appear as
```
64.916...344.168.a
```
except in the header, where it would appear as it currently does (and run of the edge of the screen but at least be visible with horizontal scrolling).  Where the conductor is displayed we can use a "bigint" knowl that shows the full conductor when clicked, but the shortened labels should not be knowls (they may already be links).

### PR DESCRIPTION
**Pull request by AndrewVSutherland**
This is running on https://blue.lmfdb.xyz.  A good place to start is

[old large conductor search results](https://beta.lmfdb.org/ArtinRepresentation/?Hide=0&dimension=40-70&conductor=10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000-)
[new large conductor search results](https://blue.lmfdb.xyz/ArtinRepresentation/?Hide=0&dimension=40-70&conductor=10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000-)

The changes are visible on the search pages, the object pages for artin reps and their Galois orbits, and also on the number field pages.  Some examples:

[old artin rep page](https://beta.lmfdb.org/ArtinRepresentation/70.515032279716534633102079631518330199783418041514749767510985855869341934761392210495237217330955785246179923266129287533183612995632780458627572856510443047134047818251730643809097369404567433725336703991055588343559968131942505027958961921166781166866931564372307126496377543256137691901011658304407993998315326936170603506781758080021346693412756396337287262843898068900680029281949265589057636602511343997921012622601820956634919199639399925438562008265433303784885955726356758628022564672406163550515930753379843702784.120.a.a)
[new artin rep page](https://blue.lmfdb.xyz/ArtinRepresentation/70.515032279716534633102079631518330199783418041514749767510985855869341934761392210495237217330955785246179923266129287533183612995632780458627572856510443047134047818251730643809097369404567433725336703991055588343559968131942505027958961921166781166866931564372307126496377543256137691901011658304407993998315326936170603506781758080021346693412756396337287262843898068900680029281949265589057636602511343997921012622601820956634919199639399925438562008265433303784885955726356758628022564672406163550515930753379843702784.120.a.a)

[old Galois orbit page](https://beta.lmfdb.org/ArtinRepresentation/70.515032279716534633102079631518330199783418041514749767510985855869341934761392210495237217330955785246179923266129287533183612995632780458627572856510443047134047818251730643809097369404567433725336703991055588343559968131942505027958961921166781166866931564372307126496377543256137691901011658304407993998315326936170603506781758080021346693412756396337287262843898068900680029281949265589057636602511343997921012622601820956634919199639399925438562008265433303784885955726356758628022564672406163550515930753379843702784.120.a)
[new Galois orbit page](https://blue.lmfdb.xyz/ArtinRepresentation/70.515032279716534633102079631518330199783418041514749767510985855869341934761392210495237217330955785246179923266129287533183612995632780458627572856510443047134047818251730643809097369404567433725336703991055588343559968131942505027958961921166781166866931564372307126496377543256137691901011658304407993998315326936170603506781758080021346693412756396337287262843898068900680029281949265589057636602511343997921012622601820956634919199639399925438562008265433303784885955726356758628022564672406163550515930753379843702784.120.a)

[old number field page](https://beta.lmfdb.org/NumberField/8.0.5620066455663197695561554590870531303687507769819136.1)
[new number field page](https://blue.lmfdb.xyz/NumberField/8.0.5620066455663197695561554590870531303687507769819136.1)

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
@jwj61 I think I implemented everything we discussed but let me know if you spot anything I missed or want any further changes.

**Comment by edgarcosta** [comment]
Should one also tweak the title?

**Comment by AndrewVSutherland** [comment]
@edgarcosta When we discussed it the plan was to note do this, the feeling being that it was better to show the full label in one place, and in the title it has the virtue of not interfering with the material on the page.

But I could still be convinced to abbreviate them in the title as well.

**Comment by jwj61** [comment]
The title does not mess up the display of the rest of the page, so why not show it in all of its glory?  (Plus, it fits when the screen is displayed across an array of monitors).

**Comment by edgarcosta** [comment]
Sounds good!

**Pull request merged**
