### PR TITLE
Wrong table name

### PR DESCRIPTION
**Pull request by edgarcosta**
This is used for the conversion of old labels to new labels in EC over numberfields

### CODE REVIEW

**Comment by edgarcosta** [comment]
This fixes: http://beta.lmfdb.org/Genus2Curve/Q/2457/b/

**Comment by JohnCremona** [comment]
I made that table for a once-off conversion, I think -- did not know that the old-style labels were in use anywhere.  Surely it would be better to convert the labels in wherever they are used (somewhere in Genus 2 data?

**Comment by AndrewVSutherland** [comment]
@JohnCremona Agreed, we can easily change all the references in the genus 2 curve data (I'd be happy to do this).  @edgarcosta is this conversion table used anywhere else?

**Comment by edgarcosta** [comment]
1- This is the only place.

2- Please don't change the references. These only seem to show up in lfunc_instances, and they will disappear once I merge some of the genus 2 curves L-functions with EC over quadratic fields.
(this is one of the reasons why I wanted to add trace hashes to EC over quadratic fields)

**Comment by AndrewVSutherland** [comment]
@edgarcosta the pages

If I checkout edgarcosta/iqfcase the pages

http://127.0.0.1:37777/Genus2Curve/Q/2457/b/
http://beta.lmfdb.org/Genus2Curve/Q/2457/b/

look identical to me.  What got fixed?

**Comment by edgarcosta** [comment]
If you try to click on one of the elliptic curves you will get an error:
```
Exception on /EllipticCurve/2.0.3.1/[273,256,1]/a/ [GET]
Traceback (most recent call last):
  File "/scratch/sage/sage-8.3/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/scratch/sage/sage-8.3/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/scratch/sage/sage-8.3/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/scratch/sage/sage-8.3/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/scratch/sage/sage-8.3/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/ecnf/main.py", line 310, in show_ecnf_isoclass
    conductor_label = convert_IQF_label(nf,conductor_label)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/ecnf/WebEllipticCurve.py", line 31, in convert_IQF_label
    newlab = db.ec_IQF_labels.lucky({'fld':fld, 'old':newlab}, 'new')
AttributeError: 'PostgresDatabase' object has no attribute 'ec_IQF_labels'
[2018-10-18 16:33:23 UTC] 500 error on URL http://beta.lmfdb.org/EllipticCurve/2.0.3.1/[273,256,1]/a/ ("'PostgresDatabase' object has no attribute 'ec_IQF_labels'",)
```

**Pull request merged**
