### PR TITLE
Change self twist field column heading in inner twist table for CMFs

### PR DESCRIPTION
**Pull request by AndrewVSutherland**
This PR addresses #2994.

### CODE REVIEW

**Comment by edgarcosta** [comment]
The single line change looks good to me. But I won't review the content.

**Comment by AndrewVSutherland** [comment]
It would be good for @davidfarmer to review and close the issue if he is satisfied.  I also changed the knowl content.

**Comment by davidfarmer** [comment]
I think this is clearer, and less confusing when not all rows have an entry.  Will merge.

Now the knowl cmf.self_twist_col should be renamed to cmf.self_twist .
The knowl should also mention that it is talking about holomorphic GL(2) modular forms.

**Comment by AndrewVSutherland** [comment]
@davidfarmer I renamed the knowl to cmf.self_twist_field (the knowl cmf.self_twist defines a self twist and is already referenced by this knowl).  The knowl does refer to newforms, but I will move this to to the first sentence to make it clearer (after the rename finishes).

**Pull request merged**
