### PR TITLE
Split ors

### PR DESCRIPTION
**Pull request by roed314**
Add the ability to split the `$or` clause of a query into multiple queries which are then combined and sorted in Python.  This speeds up searches for Galois groups because it causes Postgres to use the correct indexes.

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
There are two CMF Travis errors -- I don't know why/how this change would have caused them but we need to figure this out before we can merge this.

**Comment by AndrewVSutherland** [comment]
On the plus side, I just tested this and Galois group searches are now very snappy, well done!

**Comment by AndrewVSutherland** [comment]
@roed314 I just confirmed that ./test.sh lmfdb/classical_modular_forms succeeds on master but fails on this branch, so there is definitely something here that needs to be investigated.

**Comment by roed314** [comment]
I agree; I'm trying to figure out what's causing the problem now.

**Comment by roed314** [comment]
I found the problem and pushed a fix; it was an issue with searching with `limit=None`.

**Comment by roed314** [comment]
This travis failure is real too.  I'll fix it later this evening.

**Pull request merged**
