### PR TITLE
Fix critical issue #1207 in classical modular forms

### PR DESCRIPTION
**Pull request by AndrewVSutherland**
This is a simple one line fix, the code was failing because the rational coefficient field has no method .relative_polynomial_latex. 

Note: test_non_triv_character fails, but it failed before this change as well, I will raise a separate (non-criticla) issue for this.

### CODE REVIEW

**Comment by fredstro** [comment]
It is,  but not necessarily as you wrote it...
The underlying problem is that the coefficient field of a webnewform should
be a WebProperty which has a value which is a usual  number field but
intrinsically is "our version of" a web number field which means in
particular that it has the property relative_polynomial_latex.
It is not a problem that the field is the rational field but rather that
the field was not initialized properly ftom the database,  most likely
because of an incomplete database record.
This means of course that the problem could also appear for higher degree
fields.
The best fix to avoid a critical fail would be to test for the property
before calling the template or by using a python getattr with a default
value.
Fredrik

**Comment by AndrewVSutherland** [comment]
@fredstro Just to be clear, you are not saying that http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/49/8/?group=0 is now incorrect, rather you are saying that this bug is indicative of an underlying problem that could be causing trouble elsewhere, right?   Assuming that is the case, I think this fix does make things "less bad" for release 1.0 and should not be reverted.  Certainly the change I made is not going to break anything that is not already broken.

I don't think we should be making any further code changes before May 10 unless there are truly necessary (i.e. they correct a crash or prevent incorrect data being displayed), it is just too risky.  We may need to defer the "best fix" to a later date when we have time to thoroughly test (and ideally we would test on beta first before moving to production).

But it certainly would be a very good idea to understand exactly why the field is not being initialized properly and to know whether this affects other pages. If it does, then we will have to make a judgement call as to whether it is better to try and fix it or to simply hide those pages.

Is there perhaps an automated way you could test this?

**Comment by fredstro** [comment]
Well, it is certainly no point in reverting this but since it might "mask"
other problems it shoukd be taken care of more thoroughly at dome later
point. ..
Fredrik

**Comment by fredstro** [comment]
Stephan Ehlen @sehlen should probably take a look at it since the backend
is based on his code.

**Pull request merged**
