### PR TITLE
Isogeny classes of abelian varieties

### PR DESCRIPTION
**Pull request by roed314**
Adds a new section on isogeny classes of abelian varieties over finite fields.

### CODE REVIEW

**Comment by JohnCremona** [comment]
Quick question:  the list of changed files includes 4 related to citations which I updated on master yesterday.  Why?

**Comment by roed314** [comment]
Probably because I pulled in changes from upstream master.  Was that not
the appropriate thing to do?  I could pull in changes from beta instead.
David

**Comment by roed314** [comment]
Also note that Christelle just fixed a few problems so that the tests pass, so I should should merge those into this pull request.  I'll wait to hear back about whether you want me to undo pulling in upstream master and pull upstream beta instead.

**Comment by JohnCremona** [comment]
No you should always base on master.  Beta branch only ever gets updated
from master.

I will not be able to look at or test this for several days but there are
other reviewers who might.

**Comment by roed314** [comment]
I understand: it's a big chunk of code to look at!

I've pulled in Christelle's fixes to the tests, so I'm not currently aware of any outstanding issues.

**Comment by edgarcosta** [comment]
You should try to make pyflakes happy.
I think the only serious issue is:
> ./lmfdb/abvar/fq/stats.py:58: undefined name 'counts'

https://github.com/roed314/lmfdb/blob/3a55364265c2034a39e6b9cce827fae3b54b3fa3/lmfdb/abvar/fq/stats.py#L58

**Comment by roed314** [comment]
Thanks Edgar; I've fixed the pyflakes issues and updated the upload script.

**Comment by roed314** [comment]
I know that this is a big chunk of stuff to review.  Is there anything we can do to help out?

**Comment by JohnCremona** [comment]
As it is a big new addition, it would be helpful to write briefly about what is in the new package and what state is it in.  What features have, or have not yet, been implemented.  Whether there is already plenty of data in the database, or just a little for testing.  Some sample URLs to look at.

Right now I have your branch running locally, have clicked on the new link /Fq  and will have a browse.

**Comment by AndrewVSutherland** [comment]
@JohnCremona Thanks John, I'm looking at Edgar's 301 -> 307 PR now and then I was also going to look at this.  I agree that it would be helpful to know what we should be looking at/for.

**Comment by JohnCremona** [comment]
At first glance you people have done a great job.  Thanks for completing https://github.com/LMFDB/lmfdb-inventory/blob/master/db-abvar.md, and I see from http://beta.lmfdb.org/api/ that there are 1367543 objects in the beta db already!

**Comment by JohnCremona** [comment]
Since this is new and only to be visible in beta mode for now, I intend to merge it unless I find something really bad (which I don't expect) since that way it will be much easier to get more feedback and continue development.

A couple of minor things (**not** needing to be fixed before this gets merged into beta):

@ at http://localhost:37777/Variety/Abelian/Fq/ the introductory paragraph repeats the contents of the knowl about extent of the data, and appears to include a self-referential reference.  This could be abbreviated.

@ After a search, e.g. clicking on the number 50356 in the table for (3,13) I get -- of course -- 50 hits.  The "download" buttons at the bottom download all of these which is rather a lot.  On some other pages there's a limit -- did you put in a limit?

I can see that there will be more knowls to be written.  This will be easier when it is on beta.

**Comment by JohnCremona** [comment]
If I search for q in the range 1000-2000 and dimension 1-3 there are no hits, but these are in the range q^{g(g-1)/2)<10^7 .  Have I misunderstood something?

**Comment by AndrewVSutherland** [comment]
Having played with it a bit, I agree with John's comments; this is looks like a great addition and I'm fine with merging it to beta as it stands (I'll leave this to John, since he said he was planning to do so).

Having said that, I did notice a few things in addition to the points John noted above::

- If I enter in the suggested text "e.g. [2,2.9.ag_z,4T1]" for decomposition type it complains that it is invalid.
- If I enter [2.2,2.2] into the decomposition type it behaves as expected, but if I enter [2.2,2.3] it returns the entire database, and the same is true if I enteer [2.2,3.2] (which should surely match nothing, right?).
- The bread crumbs should track the URL prefix, as it does in elliptic curves and genus 2 curves (for example).  If I go to the URL http://127.0.0.1:37777/Variety/Abelian/Fq/2/ it fills in the field cardinality as it should, but the bread crumbs don't show this, where as if I go to http://127.0.0.1:37777/EllipticCurve/Q/14/ not only does 14 get filled into the conductor, the bread crumbs show this.  In general, the bread crumbs should track the parsing of the label/URL.
- There are definitely knowls that need to be added (e.g. angle rank, primitive, number field, ...).  As John says, it will be easier to edit knowl content once it is merged, but you will need to update the code/html to put the knowl links in (you could do that now, or you could do it in a later PR after this is merged).
- Home pages of objects in the LMFDB should have a property box (you don't need to do this right now, but it will need to be done eventually).

Also, a few feature requests (which obviously don't need to be addressed now):

- Link to a random abelian variety on the front page
- For the simple and primitive options, rather than making it yes/no it would be nice to have three choices, (e.g. simple/split/both), as you do with Jacobian and principally polarized.
- It would be nice to have Galois group as a search parameter
- A graph of the netwon polygon would be cool.

**Comment by roed314** [comment]
Thanks for the feedback!  We'll take a look.

**Comment by JohnCremona** [comment]
Drew's suggestions all good.  Some are easy so Let me give you a chance to deal with some right now

**Comment by roed314** [comment]
Sounds good.  I'll work on them now and update you once I have.

**Comment by roed314** [comment]
Alright, here's the status.

- In answer to your original question about the state of the database, we have complete data for a set of pairs (g,q), though the criterion listed in the completeness knowl is incorrect.  For g=1, the maximum q is 499; for g=2, max q is 211; for g=3, max q is 13; for g=4, max q is 5; for g=5, max q is 3; and for g=6 only q=2 is available.  For each isogeny class, we have it's Weil polynomial and various data computed from it.  I can elaborate if desired.
- I've changed the intro paragraph, though the completeness knowl is still self referential.
- I've added a limit for download links to appear (copying the code in elliptic curves), though the limit is 100000.
- We removed the ability to search for Galois group in the decomposition but neglected to update the example.  That has now been remedied, and the new example works.
- I fixed a bug in the decomposition search; it will now raise an error if you try to search for [2.2,2.3] (corresponding to two values of q).  But [2.2,3.2] works.
- I've updated the bread crumbs code, though I'm not completely sure what the behavior should be so feel free to let me know if it needs further work.
- I've left the knowls for later, since I'd like to get a list of what needs to be added and then do it all at once.
- I've added a link to a random isogeny class.
- I've updated the simple and primitive options (I'd already been intending to make that change).

Here's what remains to be done, which I probably won't manage to do very soon.
- Add knowls
- Add search by Galois group and number field
- A property box
- graphs of Newton polygons.  There aren't that many that appear, so it should be feasible to generate the graphs and serve them statically.  Is there an example somewhere in LMFDB of static image files being included?
- I wouldn't be surprised if there were more bugs in the decomposition search, or the newton polygon search.  More testing would be nice.
- Lots more features to add!

**Comment by JohnCremona** [comment]
Thanks for reacting vey quickly to our comments.  I'll look at it again as soon as I can.

**Comment by AndrewVSutherland** [comment]
@roed314 See the Sato-Tate groups pages (e.g. http://www.lmfdb.org/SatoTateGroup/1.4.10.1.1a) for examples of static images (and dynamic ones, e.g. http://www.lmfdb.org/SatoTateGroup/0.1.7).  The static images are just small .png images stored as base64-encoded strings in mongo db (see http://www.lmfdb.org/api/sato_tate_groups/st_groups/).

**Comment by JohnCremona** [comment]
Testing again now...

**Comment by JohnCremona** [comment]
Running test.sh I do get some errors:

> Check that length_A_counts and length_C_counts work ... ok
> Check that the field gets displayed correctly ... ok
> Check that display_galois_group works ... ok
> Check that display_number_field works ... ok
> Check that the Frobenius angles display correctly ... ok
> Check that is_ordinary is computed correctly ... ok
> Check that is_simple is computed correctly ... ok
> Check that is_supersingular is computed correctly ... ok
> Check that the Frobenius angles display correctly ... ok
> Check that display_slopes works ... ok
> Check the error message for a bad label url ... ERROR
> Check that the Variety/Abelian/Fq search & browse page works. ... ok
> Check that we can search by base field ... ok
> Check that various search combinations work. ... Dbread2 [('Abelian Varieties', '/Variety/Abelian/Fq/'), ('Fq', '/Variety/Abelian/Fq/'), ('1', '/Variety/Abelian/Fq/1/'), ('7', '/Variety/Abelian/Fq/1/7/')]
> ok
> Check that we can search by dimension ... Dbread1 [('Abelian Varieties', '/Variety/Abelian/Fq/'), ('Fq', '/Variety/Abelian/Fq/'), ('2', '/Variety/Abelian/Fq/2/')]
> ok
> Check that we can search by initial coefficients of the polynomial ... ok
> Check that we can search by newton polygon ... ERROR
> Check that we can search by the point counts of the abelian variety ... ok
> Check that we can search by the point counts of the curve ... ok
> Check that we can search by p-rank ... ok
> Check that we can look at simple abelian varieties only ... FAIL
> Check that we can change the table range ... ok
> 

Can you fix these before I merge?  [BTW I see that there's a failure in test_hmf which is my responsibility to change at some point -- I only mean fix things in abvar).

Also some of the test searches are rather slow -- I see that you have documented what indexes you have put in i nthe inventory, so can you double check that you have a suitable index for all the searches used in the test?

**Comment by roed314** [comment]
Alright, I fixed the test errors in abvar.

I'm not sure what's going on with the slow tests.  Some of them are doing multiple checks in the same function, but I haven't gone through to make sure the indexes are all present.

**Comment by JohnCremona** [comment]
OK -- I am going to merge this now into master and then beta.  Then you can invite people to go to beta.lmfdb.org and send feedback.

**Comment by JohnCremona** [comment]
Only after merging did I notice that the pR was into beta already and not into master.
@roed314 our convention (weird but tradition) is the the development branch stuff gets merged into first is "master";  every so often master gets merged into "beta" and then "prod".
It should not matter as soon as I merge beta into master now, since we are used to master always begin the most up-to-date.

**Comment by roed314** [comment]
Got it. Thanks for the review!

**Pull request merged**
