### PR TITLE
Remove unneeded search parameters from some urls

### PR DESCRIPTION
**Pull request by jwj61**
Deals with global fields, local fields, Galois groups, and Artin representations.  In each case, look at the url after do a search or refining a search.  With Galois groups, there is almost no change (if you specify only the degree, then the only difference is whether or not t is in the url).  This addresses issue #2277 for these areas.

### CODE REVIEW

**Comment by jwj61** [comment]
Codecov shows a difference on web_ec.py even though this pull request doesn't touch that file.  Maybe it has been changed since the last check done by codecov?

**Comment by edgarcosta** [comment]
Most likely last time, the `test_random(self)` grabbed an curve with `len(isodegs) > 3`.

**Comment by JohnCremona** [comment]
Fantastic (and fast!).  I will take a look.

I have also noticed some strange tiny fluctuations in coverage in files not touched by a PR.  @edgarcosta must be right about it coming from random tests.  We can ignore it surely.

**Comment by AndrewVSutherland** [comment]
Looks good, just one comment: it might be nice to also strip out options that are set to there default value, for example, if I search for Galois groups of degree 3 I get the shortened URL

http://127.0.0.1:37777/GaloisGroup/?start=0&paging=0&parity=0&cyc=0&solv=0&prim=0&n=3&count=50

but the URL

http://127.0.0.1:37777/GaloisGroup/?n=3

does exactly the same thing.

**Comment by jwj61** [comment]
I will look into it.

**Pull request merged**
