### PR TITLE
Allow multiplication and exponentiation in input boxes, 4268

### PR DESCRIPTION
**Pull request by tahulse**
Modified search_parsing.py to allow inputs involving multiplication and exponentiation. This uses regex to verify the inputted text only uses [0-9], (),^,* symbols and then attempts a sage_eval(). If sage_eval() succeeds, the search is run with that, otherwise an error is displayed.

See issue #4268

### CODE REVIEW

**Comment by JohnCremona** [comment]
I am very nervous about applyong sage_eval to input text.  It feels dangerous.  But while Sage's Integer() and ZZ() do not allow expressions, gp does:

sage: ZZ(gp('2^3 * 3^2'))                                                                                                                             
72

and you can catch non-integral values as they will raise a type error (as you see if you replace * by / above). So perhaps that is safer.

**Comment by AndrewVSutherland** [comment]
I like @JohnCremona's suggestion.  While the regex check makes me comfortable that calling sage_eval is safe in this instance, if there is a simple alternative that avoids sage_eval entirely (which it a appears there is) that would be better (otherwise in the future anytime someone gets paranoid and does a git grep for "sage_eval" they have to go through the exercise of convincing themselves that this particular usage is safe).

But rather than worrying about catching non-integral values, I would just keep the regex check in and change the call to sage_eval to ZZ(gp(...)) (belts and braces).

**Comment by edgarcosta** [comment]
isn't calling `gp` like calling `sage-eval` but for gp inside sage?

```
sage: gp('a = 3 + 5;')
8
sage: gp('a')
8
```

**Comment by tahulse** [comment]
I can use whatever function you'd like me to use.

**Comment by tahulse** [comment]
I am pretty new to this so I don't know if the second commit I just submitted was done correctly. Please let me know if I should do this differently. Thanks.

**Comment by JohnCremona** [comment]
> isn't calling `gp` like calling `sage-eval` but for gp inside sage?
> 
> ```
> sage: gp('a = 3 + 5;')
> 8
> sage: gp('a')
> 8
> ```

This is a  good point.  If we were to pass the string directly to gp with no parsing then we would be asking for trouble since someone might type factor(nextprime(10^100)*nextprime(10^101)) in the box.  But the current code only sends the strong to gp if it matches the MULT_PARSE regex which only allows digits parentheses, * and ^ (not even + and -).  gp() will still fail on an input like 2^(2^100) and will raise a TypeError.  

I think the try/except block should catch the TyppeError explicitly -- it is bad practice to have "except:" on its own.  Although lmfdb/ does have 146 instances of this, many of which were put there by people who should know better....

**Comment by edgarcosta** [comment]
Here is my suggestion:
```
sage: import ast
....: class PowMulNodeVisitor(ast.NodeTransformer):
....:     def visit_BinOp(self, node):
....:         if isinstance(node.op, ast.Pow):
....:             return  self.visit(node.left) ** self.visit(node.right)
....:         elif isinstance(node.op, ast.Mult):
....:             return  self.visit(node.left) * self.visit(node.right)
....:     def visit_Constant(self, node):
....:         return ast.literal_eval(node)
....:
....: foo = ast.parse('2^3 * 3^2'.replace('^', '**'), mode='eval')
....: bar = PowMulNodeVisitor().visit(foo).body
....: print(type(bar) , bar)
<class 'int'> 72
sage: foo = ast.parse('5*(2^(2^3))'.replace('^', '**'), mode='eval')
....: bar = PowMulNodeVisitor().visit(foo).body
....: print(type(bar) , bar)
<class 'int'> 1280
```

this will certainly choke at 2^(2^100), without modifying `visit_BinOp`

**Comment by edgarcosta** [comment]
I have implemented what I proposed, and but a limit on not powering things that will lead to more than 3000bits.
You can try it out here:
http://localhost:37777/ModularForm/GL2/Q/holomorphic/?hst=List&level=2*7%5E2&search_type=List

I have also added a test.

**Comment by AndrewVSutherland** [comment]
@edgarcosta The test you added is causing a failure

`_______________________________________________________________________ CmfTest.test_expression_level _______________________________________________________________________

self = <lmfdb.classical_modular_forms.test_cmf.CmfTest testMethod=test_expression_level>

    def test_expression_level(self):
        # checks we can search on 2*7^2
>       self.check('/ModularForm/GL2/Q/holomorphic/?hst=List&level=2*7%5E2&search_type=List', '98.2.a.a')
E       TypeError: check() missing 1 required positional argument: 'text'

lmfdb/classical_modular_forms/test_cmf.py:666: TypeError
`

**Pull request merged**
