### PR TITLE
Fixed capitalization and alpha -> nu (minor display issues).

### PR DESCRIPTION
**Pull request by jvoight**

### CODE REVIEW

**Comment by edgarcosta** [comment]
This looks good to me.
The test failure is on Elliptic Curves, and this PR didn't touch that.

**Comment by AndrewVSutherland** [comment]
The EC test failure is:

E       AssertionError: assert 'smallest conductor among those of rank 2' in '<!DOCTYPE html>\n<html lang="en">\n  <head>\n    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">\...>2019-03-20 13:44:38 +0000\n</a>\n      &middot;\n      SageMath version 8.3\n    </div>\n</div>      </body>\n</html>'
E        +  where '<!DOCTYPE html>\n<html lang="en">\n  <head>\n    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">\...>2019-03-20 13:44:38 +0000\n</a>\n      &middot;\n      SageMath version 8.3\n    </div>\n</div>      </body>\n</html>' = <Response 90214 bytes [200 OK]>.data
E        +    where <Response 90214 bytes [200 OK]> = <bound method FlaskClient.get of <FlaskClient <Flask 'lmfdb.app'>>>('/EllipticCurve/Q/?label=%5B0%2C1%2C1%2C-2%2C0%5D&jump=curve+or+isogeny+class+label', follow_redirects=True)
E        +      where <bound method FlaskClient.get of <FlaskClient <Flask 'lmfdb.app'>>> = <FlaskClient <Flask 'lmfdb.app'>>.get
E        +        where <FlaskClient <Flask 'lmfdb.app'>> = <lmfdb.elliptic_curves.test_browse_page.HomePageTest testMethod=test_jump>.tc
lmfdb/elliptic_curves/test_browse_page.py:10: AssertionError

Which is certainly not caused by this PR, merging.

**Comment by JohnCremona** [comment]
The page http://beta.lmfdb.org/EllipticCurve/Q/389/a/1 caused the failure because the test text was in the top knowl which has been edited.  I will change the test to something else -- tests should not rely on knowls not being edited!

**Comment by JohnCremona** [comment]
Test failure fixed in #2806

**Pull request merged**
