### PR TITLE
A hack for placement of code blurbs in genus 2 curves 

### LINKED ISSUE #2518: Placement of code blurbs
When you click the Magma code to appear on the genus 2 pages, it awkwardly justifies the data below it:
screen shot 2018-06-27 at 4 03 59 pm

(It seems better behaved on other pages, e.g. elliptic curves over number fields.)

### PR DESCRIPTION
**Pull request by edgarcosta**
This resolves #2518 by adding a phantom column

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
This seems to fix the problem in the automorphism group section, but not in the invariants section (tested on chrome).

**Comment by edgarcosta** [comment]
On the first commit I was only trying to fix the Aut table issue.
Check out the new commit where I move code blurbs to end of the row, just like in EC and NF.

**Comment by AndrewVSutherland** [comment]
I like this a lot, why not do the same for the aut table? (in general, whenever there is space to do so, I think it is clearer when the code blurb is to the right rather than above or below).

**Comment by edgarcosta** [comment]
Because the code blurb is quite long.
In my screen would overflow.

**Pull request merged**
