### PR TITLE
Lots of updates to abelian varieties

### PR DESCRIPTION
**Pull request by roed314**
* Adds new search options and more data (twists, endomorphism algebras, sizes of some isogeny classes, number of jacobians and hyperelliptic jacobians....)
* Adds statistics and dynamic statistics pages
* New search_boxes utility file to make it easier to rearrange search boxes
* Javascript show and hide advanced search options
* New counts interface (similar to dimension table for CMFs); removed table from front page.  Added interesting examples.

### CODE REVIEW

**Comment by roed314** [comment]
I will look into the test failures tomorrow afternoon.

**Comment by edgarcosta** [comment]
BTW, this branch is running on abvar.lmfdb.xyz

**Comment by roed314** [comment]
Okay, I just uploaded some data changes pushed some more code changes.  I think we should merge this once tests pass, and address any additional issues in future PRs.

**Comment by roed314** [comment]
Fixed the pyflakes problems....

**Comment by roed314** [comment]
When I try to run tests locally, it also gets stuck on `lmfdb/abvar/fq/test_av.py::AVTest::test_av_download`.  But when I try to load the pages in that test in my browser it downloads them without trouble.  So I'm confused....

**Comment by edgarcosta** [comment]
I have already copied the table to prod

**Comment by edgarcosta** [comment]
I have already copied the table to prod

**Pull request merged**
