### PR TITLE
Server sider cursors

### PR DESCRIPTION
**Pull request by edgarcosta**
We now provide buffered searches, when the user doesn't specify a limit constraint.
This also speeds up significantly rewrite, and hopefully fully addresses #2881, rewriting `nf_fields` should take about a day based on some measurements on the "writing" to disk part:
We averaged   0.0006s on the first 1.6 million records, 0.003s for several degree 16, and 0.008s for the last couple thousand records.

For example, now 
```
for rec in db.nf_fields.search():
    print  rec
    break
```
is instantaneous, while in the past it first fetched all the records into memory.

Compare against with the current code (this will take about 1min):
```
for rec in db.gps_small.search():
    print  rec
    break
```

### CODE REVIEW

**Comment by jwj61** [comment]
Just started a nf rewrite using this (and the scare quotes fix).

**Comment by roed314** [comment]
I worked on this with Edgar today and the changes are all fine with me.

**Comment by AndrewVSutherland** [comment]
The example you gave is far from instantaneous for me (running on legendre).  I started it 2-3 minutes ago and it is still running

`~/github/lmfdb$ git checkout edgarcosta/server_sider_cursors 
M	lmfdb/genus2_curves/main.py
Previous HEAD position was ee09eaf... Fix typo in insert_many
HEAD is now at 6b75ecd... formatting for David
~/github/lmfdb$ sage
┌────────────────────────────────────────────────────────────────────┐
│ SageMath version 8.3, Release Date: 2018-08-03                     │
│ Type "notebook()" for the browser-based notebook interface.        │
│ Type "help()" for help.                                            │
└────────────────────────────────────────────────────────────────────┘
sage: from lmfdb import db
INFO:LMFDB@2019-04-09 06:58:21,649: Configuration = {'postgresql_options': {'user': 'editor', 'host': 'localhost', 'password': '****', 'port': 5432, 'dbname': 'lmfdb'}, 'logging_options': {'slowcutoff': 0.1, 'logfile': 'flasklog', 'editor': 'drew', 'slowlogfile': 'slow_queries.log'}, 'flask_options': {'debug': False, 'host': '127.0.0.1', 'port': 41001}} 
INFO:LMFDB@2019-04-09 06:58:22,654: Connecting to PostgresSQL server as: user=editor host=localhost port=5432 dbname=lmfdb... 
INFO:LMFDB@2019-04-09 06:58:22,671: Done!
 connection = <connection object at 0x7fba8fabea10; dsn: 'user=editor host=localhost password=xxx port=5432 dbname=lmfdb', closed: 0> 
INFO:LMFDB@2019-04-09 06:58:22,696: User: editor 
INFO:LMFDB@2019-04-09 06:58:22,697: Read only: False 
INFO:LMFDB@2019-04-09 06:58:22,697: Super user: False 
INFO:LMFDB@2019-04-09 06:58:22,698: Read/write to userdb: True 
INFO:LMFDB@2019-04-09 06:58:22,698: Read/write to knowls: True 
sage: for rec in db.nf_fields.search():
....:     print rec
....:     break
....: 
`

**Comment by AndrewVSutherland** [comment]
@edgarcosta FYI, on proddb it took 90 seconds to print the first record of nf_fields (using the old code, not this PR), but on legendre (using your PR) it actually looks like it is stuck waiting on something (it is not using any CPU time).

If I try ec_curves instead it is instantaneous (versus 15 seconds on proddb).

I don't think the problem with nf_fields is not related to your PR, but there is definitely a problem, the number field database appears to be completely locked up right now, number field queries on beta are throwing server errors, as are pages that try to access the number fields table like http://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/124/1/i/a/

**Comment by AndrewVSutherland** [comment]
I restarted postgres and beta is now functioning again (and I can confirm that the first record is returned by db.nf_fields.search instantaneously.  I think this PR is good to go but let's hold off merging until we understand what happened (possibly related to #2913 ?).

@jwj61 if you had a rewrite running I'm sure it got nuked (but it was clearly stuck in any case).  @edgarcosta @roed314 we should try to understand exactly what happened here -- I;m guessing it was triggered by some combination of the rewrite @jwj61 has been trying to get done on nf_fields, the recent changes to db backend, and/or this PR (and the testing therreof).

**Comment by jwj61** [comment]
Looking at the dumped files, they do seem to be sorted by id, the integer which links them.  But, they are not matched.  Some data will need to be recomputed.  Even for fields where the id is present on both sides, we can't be sure they actually go together if the numbering got off track at some point.

**Comment by edgarcosta** [comment]
I agree with Drew's, but the key thing to realize is that during all that time that you waited for the first record, you were loading all of it into memory.
I did it twice, and the second time was about 10s faster:
```
sage: print datetime.datetime.now()
2019-04-09 20:44:03.527926
sage: for rec in db.nf_fields.search():
....:     print rec
....:     print datetime.datetime.now()
....:     break
....:
INFO:nf_fields@2019-04-09 20:45:14,250: SELECT "disc_rad", "iso_number", "disc_abs", "class_number", "label", "coeffs", "class_group", "degree", "used_grh", "cm", "r2", "galt", "ramps", "disc_sign" FROM "nf_fields" ORDER BY "degree", "disc_abs", "disc_sign", "iso_number" ran in  69.051432848s  [database.py:383]
INFO:nf_fields@2019-04-09 20:45:14,251: Replicate with db.nf_fields.analyze({}, 1, None, 0) [database.py:385]
{u'galt': 1, u'cm': False, u'degree': 1, u'used_grh': False, u'ramps': [], u'label': u'1.1.1.1', u'disc_sign': 1, u'r2': 0, u'iso_number': 1, u'disc_rad': 1, u'disc_abs': 1, u'coeffs': [0, 1], u'class_number': 1, u'class_group': []}
2019-04-09 20:45:14.252298
```
but you can also see in the log:
http://legendre.mit.edu/munin/static/dynazoom.html?plugin_name=PostgreSQL%2Fproddb%2Fmemory&start_iso8601=2019-04-09T15%3A49%3A28-0400&stop_iso8601=2019-04-09T17%3A17%3A13-0400&start_epoch=1554839368&stop_epoch=1554844633&lower_limit=&upper_limit=&size_x=800&size_y=400&cgiurl_graph=%2Fmunin-cgi%2Fmunin-cgi-graph

the memory use of that sage process taking ~6GB

**Comment by edgarcosta** [comment]
I don't understand why fetching the whole table in `legendre` is so much slower than in `proddb`, in either case, if you are not connected locally the bottleneck will be bandwidth, and this PR will balance that by buffering the incoming data.

Regarding the locks yesterday, I have no clue who created them, as the server was restarted.
Anyhow, would you mind testing the PR again?

**Comment by edgarcosta** [comment]
@jwj61, were you editing nf_fields in any other way? or were you just running the rewrite?

**Comment by jwj61** [comment]
No, the last attempt was last night which was killed when it stalled and the postgres server was restarted.  Should I try restarting it with this?

**Comment by edgarcosta** [comment]
@jwj61,  can you tell which script are you using, and can I be the one running it? to see if I understand what goes wrong, and it this plays any role in it

**Comment by jwj61** [comment]
/scratch/home/jj/nf-lmfdb/modify.py which I run with sage -python

**Comment by edgarcosta** [comment]
I will start to run that now and monitor it, and if it gets grid locked we will have a clue of what happened

**Comment by edgarcosta** [comment]
Rewrite has been successful, and it took about 7h.

So I think we can go along and merge this PR.

For what went wrong earlier on, I only have somewhat tinfoil hat explanation.

First, from the logs, we know that the rewrite was done with reloading the data and creating all the indexes by 3 am, and since then I assume that the script was waiting for its access exclusive lock to rename the tables.

Now lock attribution works in queues, and since that the access exclusive lock is the possible strongest lock, no one else can do anything with nf_fields until the rewrite is done with its lock, even if it never gets it.

Now, why was there some lock on the server?
Most likely us while testing this PR did something like 
```
for rec in db.nf_fields.search():
    print  rec
    break
```
and did keyboard interrupt and never closed the connection, and thus the lock was left on the Postgres server.

I was able to recreate such behavior using the table mf_hecke_lpolys.

**Comment by jwj61** [comment]
Great.  I will test it right away since I commented out one of the modifications (to be 100% sure it wasn't slowing things down).

**Comment by edgarcosta** [comment]
ps: This PR doesn't fix the issue of leaving locks around while the connection has not yet been closed

**Comment by edgarcosta** [comment]
@jwj61, I have just pushed one more commit that fixes a bug that I found today that is extremely relevant for tables with extras, please make sure that your rewrite is using this latest commit, otherwise you will need to add primary keys by hand

**Comment by jwj61** [comment]
OK, I just pulled this and started it.

**Comment by edgarcosta** [comment]
@jwj61, it has been 48h since you started the rewrite, and from the DB side, everything seems to have worked out alright, at least you are spending  99% of your time on doing math instead of waiting for data.

**Comment by jwj61** [comment]
It seems that pari in sage gets bogged down after too many calls, so I killed it and restarted the computation a different way, and it finished in less than a day.  

The counts table gets wiped out by a rewrite.  I don't know if it should be rebuilt automatically.

**Pull request merged**
