### PR TITLE
Datapage

### LINKED ISSUE #4969: Server error on bad HGM label
The URL https://beta.lmfdb.org/Motive/Hypergeometric/Q/banana throws a server error.

### PR DESCRIPTION
**Pull request by roed314**
This PR adds "Underlying data links" to most homepages in the lmfdb, as described in #4662.  It is available at [purple](https://purple.lmfdb.xyz) for experimentation.

When the page depends only one table, we just give a link to the appropriate `api_query` search result.  When there are multiple underlying tables (e.g. elliptic curves, classical modular forms, abstract groups), there is a new page which shows the entries in these different that contribute to the page.

Some things I'd like feedback on:
* I ignored the links that were already present and just added "Underlying data" at the bottom.  In some cases, this may overlap with links like "Download all stored data to text".  I'm not sure whether to include both or to remove one or the other.
* There are some homepages where I didn't add "Underlying data" links, mainly isogeny classes of various kinds where there was no separate table (e.g. isogeny classes of elliptic curves).  I'm open to adding something here, either giving just one entry from the isogeny class or all entries.
* I chose not to include data from things that felt more like "friends" than part of the object.  So, for example, I don't include an entry from `nf_fields` for the coefficient field of a modular form.  I also may have missed tables that should have been included.  I'm happy to add more tables.

Since it was a simple fix, this PR also resolves #4969 and fixes a bug in the "Random subgroup" button [here](https://purple.lmfdb.xyz/Groups/Abstract/?search_type=Subgroups).

### CODE REVIEW

**Comment by JohnCremona** [comment]
This looks very promising, and I have been playing with it, so I have some minor comments.

Having the schema available for all tables on the database data page is surely essential.  I saw it for a BMF but not for an EC/Q (e.g. https://purple.lmfdb.xyz/EllipticCurve/Q/data/238590.e4)  By the way, I like that URL system.  Is that because more than one table is in play?  I can see that if I click on the name of one of the tables there, e.g. ec_curvedata, then I get that subset of the data and now "show schema" appears.  Please can you put "show schema" next to each table on the main data page too?

Also concerning schemas: I see that the descriptions of what each column actually represents can be seen as a knowl linked to the column name.  I would like that to be visible for all columns in the "show schema" table, as a column, if that is possible.  (The knowl opening does not work too well for items near the bottom of the table, since the opened knowl is invisible).

I have only looked at BMF, ECQ and ECNF so far.   Could there be a data page for an entry in the bmf_forms table, e.g. for https://purple.lmfdb.xyz/ModularForm/GL2/ImaginaryQuadratic/2.0.23.1/72.11?

**Comment by roed314** [comment]
Getting the schema to show for each table is currently technically challenging because of the way the javascript was written (it assumed that there was only one "show schema" link per page), but will think about whether there's a good way to make it work.

My worry about showing the contents of the knowl as a separate column is that it could be long.  Certainly many descriptions are very short at the moment, and there's a lot of unused horizontal space.  Maybe truncate it if it gets too long?

What would you like the data page for https://purple.lmfdb.xyz/ModularForm/GL2/ImaginaryQuadratic/2.0.23.1/72.11 to show?  There are data pages for bmf forms, just not bmf spaces since I didn't know what the appropriate tables to show there would be.  See https://purple.lmfdb.xyz/ModularForm/GL2/ImaginaryQuadratic/2.0.23.1/72.11/a/ for example.

**Comment by JohnCremona** [comment]
Yes, some descriptions will be long.  Perhaps truncate after N characters (from some N) but if truncation was needed have some kind of "show more" indication?

Also, if this is not too circular, the ability to download a table's schema with the descriptions would be nice (if not already possible).

The page https://purple.lmfdb.xyz/ModularForm/GL2/ImaginaryQuadratic/2.0.23.1/72.11 shows data from the row of  table bmf_forms with label column '2.0.23.1-72.11', which contains
sage: db.bmf_dims.lucky({'label': '2.0.23.1-72.11'})                
{'gl2_dims': {'2': {'new_dim': 1, 'cuspidal_dim': 7}},
 'field_absdisc': 23,
 'label': '2.0.23.1-72.11',
 'field_label': '2.0.23.1',
 'level_norm': 72,
 'level_label': '72.11',
 'gl2_new_totaldim': 1,
 'gl2_cusp_totaldim': 7}

**Comment by roed314** [comment]
I've added a link to https://purple.lmfdb.xyz/ModularForm/GL2/ImaginaryQuadratic/2.0.23.1/72.11.  Let me know if that looks right.  It seems to have two identical rows there....

**Comment by roed314** [comment]
Where would you want the schema download to go?  As comments in the yaml file wouldn't be too hard, but json doesn't have comments.

**Comment by roed314** [comment]
Ok, I think it won't be too hard to add schemas to the html (when multiple tables are shown).  I'll work on that tomorrow (later today for you).

If we added a column with the contents of the knowl (and possibly a "show more" link?), I think we still need the column name to be a knowl so that you can get the "edit" and "permalink" buttons.  That feels a little weird then, but I don't have a better suggestion at the moment.

**Comment by roed314** [comment]
Also note that #4812 suggests adding an example of the contents as another column to the schema table, which would use up some of the extra horizontal space.

**Comment by JohnCremona** [comment]
> I've added a link to https://purple.lmfdb.xyz/ModularForm/GL2/ImaginaryQuadratic/2.0.23.1/72.11. Let me know if that looks right. It seems to have two identical rows there....

Thanks!  The duplicate rows are a data glitch I only just notced and have made issue #4972 .  Otherwise looks perfect.

**Comment by JohnCremona** [comment]
> Also note that #4812 suggests adding an example of the contents as another column to the schema table, which would use up some of the extra horizontal space.

OK, we can move the rest of this discussion to #4812

**Comment by roed314** [comment]
Any thoughts on the bullet points in the original post?

**Comment by JohnCremona** [comment]
> Any thoughts on the bullet points in the original post?

   1. I think we can remove the old data download links, assuming that we can download from the new pages. Some editorial input needed here.
   2. Fine by me to leave these out. We are not hiding any data.  There has always been a case for a table for isogeny class data for elliptic curves, but I ve never been convinced that anything would be gained. Not yet anyway.
   3. Omitting friends seems right to me.
Just my opinion!

**Comment by edgarcosta** [comment]
Regarding (1), I would keep both links there, as usually some data already has been processed to make into a single coherent JSON, e.g., CMFs.

**Comment by AndrewVSutherland** [comment]
I'm generally very happy with this, my only complaint/suggestion is that I think that the difference in how objects are handled when they have data in more than one table vs just one table is confusing, and (related) I would change the bread.  Compare the two links one arrives at if you go to an elliptic curve page and click the "Underlying data" download link:

- ECQ: https://purple.lmfdb.xyz/EllipticCurve/Q/data/11.a1 (bread is Elliptic curves -> Q -> data-11.a1)
- ECNF: https://purple.lmfdb.xyz/api/ec_nfcurves/?label=2.0.10691.1-1.0.1-a1 (bread is database -> ec_nfcurves)

In the second case the bread does not show the path that was taken to reach the page, and its confusing that the URLs are so different, I think it would be better to use the same type of URL in both cases.  In the first case I think the bread should include the object's home page, e.g. Elliptic curves  -> Q -> 11 -> a -> 1 -> data (and maybe the URL should also look like this?

**Comment by AndrewVSutherland** [comment]
I think Elliptic curves -> Q -> 11.a1 -> data would also be fine.  Also, on https://purple.lmfdb.xyz/EllipticCurve/Q/data/11.a1 I think the list of rows in ec_torsion_growth should be a bullet list not a numbered list (being the 3rd entry in the list really doesn't mean anything).

**Comment by roed314** [comment]
Alright, here's what I'm going to do:
* Add schema links for each table
* Change the ordered list to an unordered list
* Never use `API.api_query`; instead always make a new data route
* Change the bread so that there's a single link back to the object, e.g. `Elliptic Curves -> Q -> 11.a1 -> data`.

I'm going to work on group computations for a bit (since I want to get them started running), but will try to come back to this soon.

**Comment by roed314** [comment]
Ok, I think I've implemented the changes requested by @AndrewVSutherland and @JohnCremona.

**Comment by JohnCremona** [comment]
Thanks, @roed314 I think you have done everything!

**Comment by edgarcosta** [comment]
This looks good to me.
We can always tweak things further later on.

**Pull request merged**
