### PR TITLE
fix empty nf search label bug

### PR DESCRIPTION
**Pull request by JohnCremona**
A tiny fix this:  go to http://www.lmfdb.org/NumberField/ and click on the Go button without entering anything, and you get a server error, because of a small error which this fixes.  Now you just get the same page back again which seems OK to me.

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
@JohnCremona This works, but I notice that test_search_poly_mean2parser now fails.

**Comment by JohnCremona** [comment]
Sorry, I clearly did not test thoroughly.  Let me do that and fix it while you glance at PR#1772.

**Comment by jwj61** [comment]
Do you want me to fix this?

**Comment by JohnCremona** [comment]
Thanks @jwj61 but I just did -- a redirect is needed since (in effect) we have removed spaces from the URL.

**Comment by AndrewVSutherland** [comment]
@JohnCremona I expect this is now fine and can be merged, but the numberfields database appears to be busy at the moment so I can't test (I assume @jwj61 is working on #1697, which may involve some updating a lot of records), http://beta.lmfdb.org/NumberField/ times out).

**Comment by jwj61** [comment]
Yes, although it is using rewrite which only does read on the fields database.  In any case, that is finished.

**Comment by AndrewVSutherland** [comment]
Looks good now.

**Pull request merged**
