### PR TITLE
Sage version check at startup

### PR DESCRIPTION
**Pull request by AndrewVSutherland**
prints/logs a warning if starting the LMFDB with a Sage version older than LMFDB_SAGE_VERSION (currently set to 7.1)

### CODE REVIEW

**Comment by JohnCremona** [comment]
Thanks for implementing this.  However, converting to float will not work in two ways: the minor version might be >9 (e.g. version 7.10), not likely perhaps but has happened;  and if I were running a development version I might find (as I just did):
sage: sage.version.version
'7.3.beta8'

I think it would work to do a lexicographical compare on 
sage: [int(c) for c in sage.version.version.split(".")[:2]]

By the way, the Sage version is obtained and used elsewhere already: in base.py (where instead of the --better-- sage.version.version we have sage.env.SAGE_VERSION which has to be imported) for display in the footer of every page.  And in lmfdb/modular_forms/elliptic_modular_forms/__init__.py we already extract the major and minor versions in code similar to the above .

Sorry, it would have been quicker for me to have amended the PR than write all this!

**Comment by JohnCremona** [comment]
There's also Fredrik's install-deps.sh script, which I am not sure anyone actually uses...

**Comment by JohnCremona** [comment]
Shall I make an updated version of the patch and let you test it?  I don't have an old enough version of Sage around to test on anyway ;)

**Comment by AndrewVSutherland** [comment]
@JohnCremona I can amend my PR as you suggest, let me test and then I'll commit.

**Comment by AndrewVSutherland** [comment]
@JohnCremona Done - it warns on Sage 6.5 but not on Sage 7.1 or 7.2.

**Comment by JohnCremona** [comment]
That was quick!

**Comment by JohnCremona** [comment]
BTW, it works fine with version 7.3.beta8!

**Pull request merged**
