### PR TITLE
Create table like

### PR DESCRIPTION
**Pull request by roed314**
This utility function was a feature request last week.  To test:
```
sage: db.create_table_like('av_test', 'av_fqisog')
sage: db.drop_table('av_test')
```

I also fixed a bug in `db.create_table` resulting from the change of default from jsonb to arrays.

### CODE REVIEW

**Comment by roed314** [comment]
Test failures are due to data changes in abelian varieties.  Once #2895 is merged I'll pull the changes into here and the tests can be rerun.

**Comment by roed314** [comment]
Merged in #2895 so that tests pass; that PR should be reviewed first.

**Comment by roed314** [comment]
The test failure seems to be us being blocked by `magma_free` again....

**Comment by AndrewVSutherland** [comment]
I like it.  One thing I noticed while testing which is not directly relevant to this PR is that after you drop a table the db object still knows about it until you restart sage -- dtopped tables should be removed from the ephemeral state of the db object as well being removed from the database unless there is a good reason to keep the state around?

**Comment by AndrewVSutherland** [comment]
I'll leave this open for the moment in case you want to add a commit (but its fine if you don't).

**Comment by roed314** [comment]
I've added a `delattr` at the end of `drop_table`.

**Comment by AndrewVSutherland** [comment]
@roed314 thanks, merging.

**Pull request merged**
