### PR TITLE
Short char bc

### PR DESCRIPTION
**Pull request by nmascot**
Fix to ticket Dirichlet character breadcrumbs #410. Also changed breadcrumbs for Hecke character since they are even longer, cf. Character/Hecke/3.1.44.1/61.-22a0+1a1/1.

### CODE REVIEW

**Comment by nmascot** [comment]
Made the modulus more readable in breadcrumbs, e.g. 61.-22a0+1a1 now reads <61,a-22>.

NB Hecke characters are still buggy and uncomplete so I'll stop working on them now and concentrate on stuff for 1.0.

**Comment by davidfarmer** [comment]
Why was this line added?
 
from lmfdb.WebNumberField import WebNumberField 

I don't see that the other changes use it.

**Comment by JohnCremona** [comment]
The redundant line needs to be removed.  Otherwise it's an improvement, I think, though it should be discussed more widely (unless this was already in response to a discussion which asked for it!).  On my laptop the page http://localhost:37777/Character/Hecke/3.1.44.1/61.-22a0+1a1/1  has breadcrumbs which take up too much space:  after Mod the rest is overwritten by the search box at the leftextremity of what is in the top right corner.  (Only when logged in since my full name takes up space, so perhaps that is oK).

**Comment by JohnCremona** [comment]
Nicolas, if you remove the redundant line and update your branch then I will merge this.

**Comment by nmascot** [comment]
Had to delete this branch (little problem with github). Sending a new pull request now.

**Pull request closed without merging**
