### PR TITLE
Yoshida lift

### PR DESCRIPTION
**Pull request by rupertm2**
This is the file which computes the data from Issue #2195 . There is documentation in the file.

### CODE REVIEW

**Comment by JohnCremona** [comment]
Questions:  were you intending to use this once and for all -- in which case being in the scripts/ directory would be better -- or for it to be used on the fly at some stage?
More importantly, is there the intention of using the output to actually link to the Siegel MF (which would have to be in the database)?  That would be great, if possible, as we could list on the page of all or some HMFS the link to its lift.  If the SMFs are not in the database is your intention still to list these parameters in a section on the home page of a HMF?

**Comment by rupertm2** [comment]
> were you intending to use this once and for all -- in which case being in the scripts/ directory would be better -- or for it to be used on the fly at some stage?

Once and for all was my intention, I thought I had put it in the scripts/ folder. I'll double check.

> More importantly, is there the intention of using the output to actually link to the Siegel MF (which would have to be in the database)? That would be great, if possible, as we could list on the page of all or some HMFS the link to its lift.

This is precisely what I was hoping to do, making and series of SMF home pages for Yoshida lifts, and maybe other lifts, and linking the pages together. I'm thinking it would be very useful to know if your SMF is some kind of lift or not. I'll have to wait for the HMFs to be worked out to accurately and consistently produce the data and format, but this is the goal. I also object to on the fly calculations since I'll *shorty* be able to calculate some fourier coefficients for Yoshida lift of HMFs, but I think it may take a substantial amount of time.

**Comment by JohnCremona** [comment]
Good!  And your file is already in the scripts directory, sorry about that.

**Comment by JohnCremona** [comment]
Before we merge this -- which is not at all controversial, being a script -- could you run pyflakes on it and fix the warnings?  (It should be enough to run ./test.sh since it runs pyflakes first, then kill it before it does the longer tests).  It's a little tedious you have to import from sage.all (various things) -- I think prime_range only perhaps, if you change occurrences of valuation(x,y) to x.valuation(y).  It also warns that you assign to I on line 25 but never use it.  Probably harmless but these checks can find typos which lead to bugs.

**Comment by AndrewVSutherland** [comment]
+1 for fixing the pyflakes warnings, otherwise we get to see them again every time we test a new PR

**Comment by rupertm2** [comment]
> could you run pyflakes on it and fix the warnings?

Done and now showing no warnings for me.

**Pull request merged**
