### PR TITLE
Unreachable code in lfunction.py (LGTM)

### PR DESCRIPTION
**Pull request by davidlowryduda**
I've continued to use LGTM for static code checking. It recognized several instances of unreachable and unused code in lfunction.py.

This pull request has 3 commits. The first two commits each correspond to removing unreachable code. 

The third commit is larger, but only because I made the code compatible for both python2/3 and did some basic linting (in part because my py2to3 conversion utility does some basic linting as well). It's full of whitespace correction, maps-->list(maps), and things of that nature.

I also note that I commented out the tensor product code at the end, as it's not being used anywhere. But I didn't remove it, since the code suggests that it should be reconsidered when #500 is handled. I notice that #500 is currently closed, so I was tempted to fully remove the code --- but I didn't.

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
I don't think these are the kind of changes we want to be making right now with Release 1.1 imminent.  In cases where LGTM identifies an actual bug I'm all in favor of fixing it, but making blanket code changes that are mostly (but not all) formatting changes introduces risks that I don't think we should be taking -- it is very hard for anyone reviewing a PR like this to be sure that all the changes are truly harmless and our test coverage is too low to have confidence that we will catch everything.

I'm fine with commenting out the unused tensor product code and commenting out (or adding a comment immediately above) the identified unreachable code if you want to submit a new PR that does just this.

**Comment by JohnCremona** [comment]
(written before reading @AndrewVSutherland 's comment)

LGTM (I find it helps to use the facility of github to hide whitespace diffs when viewing the changes).

If we are going to start to make changes based on LGTM suggestions, which I think is a good thing, then developers need to know *why* some of these changes have been made (not the whitespace ones).  Perhaps a good practice would be to include with such PRs a link to the appropriate LGTM page.

And I really do not care about whitespace / layout changes.

**Comment by JohnCremona** [comment]
To be fair to @davidlowryduda (who had some encouragement from me), I'm note sure how people who were not at the recent Princeton meeting are supposed to know that "release 1.1 is imminent".

**Comment by jwj61** [comment]
Also, the unreachable code in the first commit has a comment saying that the part currently being used is a temporary fix, which implies someone intends to come back later and use the part you deleted.

**Comment by AndrewVSutherland** [comment]
@JohnCremona, @davidlowryduda Apologies if my comment came across the wrong way, I think it's a great idea to be using LGTM to try to find bugs and I would encourage this to continue! 

Independent of our release schedule, making apparently innocuous linting/formatting changes that touch lots of code is something that is best done either in conjunction with work on a specific section of the LMFDB when we know there will be a lot of testing done anyway, or during a planned interval when we make a conscious decision to hold off pushing code to web for an extended period of time (if/when we decide to switch to Python 3 we will definitely want to do this).

**Comment by davidlowryduda** [comment]
@AndrewVSutherland  I understand. I don't know anything about the upcoming 1.1 release, but I'll keep that in mind.

What I think I'll do is submit a new PR without any linting. But I think I might still include python2/3 compatibility, since it's on my mind. What would you think about that @AndrewVSutherland ?

**Comment by JohnCremona** [comment]
I think that a reasonable way forward is this.  Let's try and avoid *any* automatic reformatting.  LGTM is about a lot more than that.
* LGTM lists (currently) 611 Alerts.  This includes 132 Errors, 203 Warnings and the rest are Recommendations.
* We should attend to these in order of severity, fixing the Errors first.  Even some of these do not seem serious to me (e.g. some has wrapped a block of code inside "if False:" as a quick way of commenting it out.)
* We can allocate subsets of these to different people (e.g. someone other than me should handle the javascript ones)
* If there are some common errors being picked up we should think about preparing some kind of style guide for the future.

It would be good if we ever got to the point where our code was 100% LGTM-clean, as then we could maintain that in the same way that we use pyflakes.  But that might be too much to hope for.

**Comment by davidfarmer** [comment]
Small and possibly obvious comment:

A pull request that primarily addresses code layout (i.e., mostly white space adjustments)
should only contain such changes.  This current pull request also includes commenting
out some tensor product code, which I assume was some of the unreachable code.
I find it hard to evaluate the changes because my brain has to be alert for actual content
changes amidst a bunch of straightorward changes.

I am okay with these layout changes, but I'd like to see the tensor products code left as-is
until someone is ready to actually to actually tackle tensor products as a separate project.

**Pull request closed without merging**
