### PR TITLE
First try at number field statistics

### PR DESCRIPTION
**Pull request by jwj61**
This adds a stats page for number fields.  On one hand, this is a glaring omission.  On the other hand, it quickly becomes unwieldy.  Consider this a rough draft open for comments/suggestions.

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
Nice, I like it!  A few suggestions:
- It would be nice to have column totals (with links) in addition to the row totals you currently have.
- Class numbers have been computed for (%) of the fields in the database is missing a number before the %.
- I might be interesting to have the class number stats broken down by field degree, as you do with all the others.
- Breaking down the Galois groups by t-number seems a bit over the top (you have to scroll horizontally a long way, and it makes the page pretty slow to load).  I might suggest either putting this on a separate page, or maybe just summarize by cardinality of the Galois group?
- An additional table that would be very interesting to me is one with columns for primes p < 100 (say) and rows for degrees that lists fields of a given degree  ramified only at a given prime.  Ideally it would  also identify table entries where the list is known to be complete (most of them I would guess).

**Comment by jwj61** [comment]
Thanks for looking at this.

Would column totals be of interest for signatures?  You pretty quickly get a mix of totally complex fields for one degree, and just slightly complex fields for other degrees.  For Galois groups, it makes less sense.  The first column would basically be cyclic groups, but after that you are getting an odd mix.

I hope to work on it this week and will comment when I think it is ready for another look.

**Comment by AndrewVSutherland** [comment]
You're right, totals on t-number make absolutely no sense, I was thinking of totals by cardinality of the Galois group (which would make sense), sorry about that.  As far signatures, well, I don't know, but certainly fields with no real places are collectively interesting, and I could imagine being interested in fields that have a fixed number of real places (maybe I have a theorem that lets me do something with each real archimedean place).

**Comment by jwj61** [comment]
I think this is now a realistic candidate for merging.  Tables are big, but not 1900 columns wide.

There are more row/column totals in tables, but some searches like multiple signatures are currently not supported by the number field search page.  (A cure for that would be to replace the signature box with r_1 and r_2 boxes, but that is a different issue.)

I don't think people really think of fields by size of Galois group since that is so heavily influenced by the degree of the field.  Instead, we have small degree fields where people might know the t-numbers, and for familiar families of groups.

**Comment by AndrewVSutherland** [comment]
Looks good, I like the changes you made.

**Pull request merged**
