### PR TITLE
Backend features

### PR DESCRIPTION
**Pull request by roed314**
This PR makes three changes:

* Add functions for working with locks: the ability to show existing locks and check if locks exist before calling various functions.
* Change the default separator from tab to `|`
* Add functions for moving columns between search and extras tables.

### CODE REVIEW

**Comment by edgarcosta** [comment]
I approve the changes and I have fixed the merge conflict.
I will merge once the tests pass.

**Comment by roed314** [comment]
I just merged #3528, and hopefully that will fix the test errors on this page.  How do I get travis to rerun tests, since the underlying master has changed?

**Comment by AndrewVSutherland** [comment]
I restarted the build for you (which you can do by clicking on the (easy to miss) "restart build" link on the Travis page.  The only test failure I saw was test_artin so I think this is probably fine to merge, but I'll let it run again.

**Comment by roed314** [comment]
Thanks!  The problem was that I needed to be logged in to travis.

**Pull request merged**
