### PR TITLE
Addressing #4025

### LINKED ISSUE #4025: Downloading new space
```
Exception on /ModularForm/GL2/Q/holomorphic/download_full_space/1369.2 [GET]
Traceback (most recent call last):
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lmfdb/lmfdb-git-web/lmfdb/classical_modular_forms/main.py", line 571, in download_full_space
    return CMF_download().download_full_space(label)
  File "/home/lmfdb/lmfdb-git-web/lmfdb/classical_modular_forms/download.py", line 335, in download_full_space
    data['newforms'] = sum([[form['label'] for form in forms] for spc, forms in space.decomp], [])
  File "/home/lmfdb/lmfdb-git-web/lmfdb/classical_modular_forms/download.py", line 335, in <listcomp>
    data['newforms'] = sum([[form['label'] for form in forms] for spc, forms in space.decomp], [])
TypeError: 'NoneType' object is not iterable
[2020-09-11 12:23:54 UTC] 500 error on URL https://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/download_full_space/1369.2
```

### PR DESCRIPTION
**Pull request by edgarcosta**
@alexjbest, please check it out

This resolves #4025 (so that github closes the issue for me)

### CODE REVIEW

**Comment by edgarcosta** [comment]
There is an issue when newspaces are empty: http://localhost:37777/ModularForm/GL2/Q/holomorphic/13/2/

**Comment by edgarcosta** [comment]
@alexjbest, I think this fixes the issue

**Comment by edgarcosta** [comment]
This resolves 4025 (so that github closes the issue for me)

**Comment by edgarcosta** [comment]
This resolves #4025 (so that github closes the issue for me)

**Comment by alexjbest** [comment]
I'm confused, I thought the point was that no newforms would be downloaded unless the list would be complete for the space.
1369.2 still includes newforms for me here?

**Comment by edgarcosta** [comment]
This is what I get:
```
# Stored data for newspace 13.2, downloaded from the LMFDB on 18 September 2020.
{"level": 13, "weight": 2, "label": "13.2", "oldspaces": [], "newspaces": ["13.2.a", "13.2.b", "13.2.c", "13.2.e"], "newforms": ["13.2.e.a"], "dimgrid": {"M": {"all": 13, "new": 13, "old": 0}, "S": {"all": 2, "new": 2, "old": 0}, "E": {"all": 11, "new": 11, "old": 0}}}
```

and

```
# Stored data for newspace 1369.2, downloaded from the LMFDB on 18 September 2020.
{"level": 1369, "weight": 2, "label": "1369.2", "oldspaces": [[37, 2]], "newspaces": ["1369.2.a", "1369.2.b", "1369.2.c", "1369.2.e", "1369.2.f", "1369.2.h", "1369.2.j", "1369.2.k", "1369.2.l", "1369.2.n", "1369.2.o", "1369.2.q"], "dimgrid": {"M": {"all": 79023, "new": 78873, "old": 150}, "S": {"all": 77044, "new": 76964, "old": 80}, "E": {"all": 1979, "new": 1909, "old": 70}}}
```

**Comment by alexjbest** [comment]
Weird looks like my browser was caching the old one, incognito mode and it
worked!
LGTM then

**Pull request merged**
