### PR TITLE
Minor fix to genus 2 curve page formatting

### PR DESCRIPTION
**Pull request by AndrewVSutherland**
For @JohnCremona, remove <h3> subheading level from bottom level one-line displays so that they are not displayed all in green (now only knowl links are).

### CODE REVIEW

**Comment by JohnCremona** [comment]
Looks good.  For a curve with no rational points the whole phrase "There are no rational points"  is the knowl link; possibly better if only the last 2 or 3 words were (excluding "There are")?

e.g. "http://localhost:37777/Genus2Curve/Q/336/a/172032/1

**Comment by AndrewVSutherland** [comment]
@JohnCremona I changed the knowl link as you suggested (and added a period).

**Comment by AndrewVSutherland** [comment]
@JohnCremona I think this is ready to merge, but let me know if there is anything else you think should be changed.

**Comment by JohnCremona** [comment]
Sorry -- thought I had done this already

**Pull request merged**
