### PR TITLE
main -> dev

### PR DESCRIPTION
**Pull request by AndrewVSutherland**

### CODE REVIEW

**Comment by roed314** [comment]
@AndrewVSutherland I don't think the prime_square and powerful options will work (see my comment on the last PR).  I can take a look in a few minutes (trying to finish up some things on olive.lmfdb.xyz).

**Comment by roed314** [comment]
Yep, that's right; currently powerful and prime_square will have no effect.  I'll fix it.

**Comment by AndrewVSutherland** [comment]
Already done and it does work

**Comment by roed314** [comment]
Ok, cool.  I guess I needed to restart my sage, since the list of search columns is cached.

**Comment by AndrewVSutherland** [comment]
Ah, I think you mean on prod, yes they won't work there until the tables are copied over.  I can take of that tonight.

**Comment by roed314** [comment]
`level_is_prime_square` seems to mean an even power of a prime, which isn't what I would expect from the name.

**Comment by AndrewVSutherland** [comment]
It should mean square; I probably made a mistake when adding the columnSent from my iPhoneOn May 18, 2024, at 2:36 PM, roed314 ***@***.***> wrote:﻿
level_is_prime_square seems to mean an even power of a prime, which isn't what I would expect from the name.

**Comment by AndrewVSutherland** [comment]
Fixed.

**Comment by AndrewVSutherland** [comment]
The updated tables have been copied to prod.

**Pull request merged**
