### PR TITLE
remove obvious suffixes in error message

### PR DESCRIPTION
**Pull request by edgarcosta**

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
I don't think this will fix the problem.  In the case where I ran into this problem the table name ends in _counts_tmp, not _counts.

```
ValueError: Temporary table ec_nfcurves_counts_tmp already exists. Run db.ec_nfcurves_counts.cleanup_from_reload() if you want to delete it and proceed.
```

Instructs the user to run db.ec_nfcurves_counts.cleanup_from_reload(), but this won't work, you need to run db.ec_nfcurves.cleanup_from_reload().

**Comment by edgarcosta** [comment]
From the block
```
raise ValueError(
    "Temporary table %s already exists. "
    "Run db.%s.cleanup_from_reload() if you want to delete it and proceed."
    % (tmp_table, table)
)
```
we know that originally the function was called with:
`table = ec_nfcurves_counts`
and 
`tmp_table = ec_nfcurves_counts_tmp`

now before the error is raised `ec_nfcurves_counts` would get converted to `ec_nfcurves`

**Comment by AndrewVSutherland** [comment]
OK.  What is the best way to test this?

**Comment by edgarcosta** [comment]
```
sage: db.test_xyz.copy_to('test.dump', 'test_extra.dump', 'test_counts.dump')
Exporting test_xyz...
	Exported test_xyz in 4.854 secs to test.dump
	Exported test_xyz_extras in 5.979 secs to test_extra.dump
	Exported test_xyz_counts in 0.038 secs to test_counts.dump
Exported test_xyz in 10.872 secs
sage: db._clone('test_xyz_counts', 'test_xyz_counts_tmp')
sage: db.test_xyz.reload('test.dump', 'test_extra.dump', 'test_counts.dump')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-84b28848134c> in <module>
----> 1 db._clone('test_xyz_counts', 'test_xyz_counts_tmp')
      2 db.test_xyz.reload('test.dump', 'test_extra.dump', 'test_counts.dump')

~/Dropbox (Personal)/projects/LMFDB/lmfdb/lmfdb/backend/base.py in _clone(self, table, tmp_table)
    915                 "Temporary table %s already exists. "
    916                 "Run db.%s.cleanup_from_reload() if you want to delete it and proceed."
--> 917                 % (tmp_table, table)
    918             )
    919         creator = SQL("CREATE TABLE {0} (LIKE {1})").format(Identifier(tmp_table), Identifier(table))

ValueError: Temporary table test_xyz_counts_tmp already exists. Run db.test_xyz.cleanup_from_reload() if you want to delete it and proceed.
```

**Comment by AndrewVSutherland** [comment]
Thanks!

**Pull request merged**
