### PR TITLE
make Higher Genus w/autos data available on beta sidebar

### PR DESCRIPTION
**Pull request by jenpaulhus**
This pull is to request that the Higher Genus data go from alpha to beta testing.  It adds a link on the sidebar under "Higher Genus" 
http://127.0.0.1:37777/HigherGenus/C/Aut

Also, in higher_genus_w_automorphisms/_init_.py  I removed the second link to the old URL for this page (lower case "a" in Aut).

Most of my code is here: https://github.com/jenpaulhus/group-actions-RS
A preprint of what I've done so far is here: http://www.math.grinnell.edu/~paulhusj/Paulhus-lmfdb.pdf

### CODE REVIEW

**Comment by JohnCremona** [comment]
Jen, you need to put back the "status:" line changing "future" to "beta" as otherwise the new entry appears even when not running in beta mode.
I did not much like the abbreviation "w/" and tried changing to "with" .  In my browser it appears as "with" on one line and "automorphisms" on the next, which is OK for now.

I would be happy to merge this after making the one change to status -- then we can get more people to look at these pages!

**Comment by AndrewVSutherland** [comment]
What if we just replaced "w/automorphisms" with "families"?  I realize this is less informative, but it would fit better and still be accurate.

On a separate note, I have reviewed much of the work Jen has done on this and I think it looks good and is ready for beta status.

**Comment by JohnCremona** [comment]
I'm fine with families.

**Comment by jenpaulhus** [comment]
I've now added the status: beta line to sidebar.yaml  and changed the link name from "w/ automorphisms" to "Families".  I wasn't a fan of "w/autos" either, but "families" does feel a little vague.  Some other possible ideas could be "automorphisms" only  or "group actions".

**Comment by jenpaulhus** [comment]
Here it is with "Group Actions" instead. The sidebar renders a little strange locally for me so I can't tell if it will fit. It should, its exactly the same length as "/NumberFields" which fits.

**Comment by davidfarmer** [comment]
"Families" may seem vague to the experts, but I like it because
it conveys the general idea, and those who care will understand
it well enough.   Titles don't have to be precise mathematical
statements.

**Comment by AndrewVSutherland** [comment]
On my system "Group Actions" splits onto two lines; in view of @davidfarmer's comment I suggest  we just stick with "Families".

**Comment by JohnCremona** [comment]
Agreed (it's on 2 lines for me too).

**Comment by jenpaulhus** [comment]
Ok, sounds good. Do you need me to make the change back and push the branch again or are you easily able to merge from one commit back before I changed it to Group Actions?
4cf046bc0416bde5b5428e8ad803376f124668f7

**Comment by JohnCremona** [comment]
I'm not sure how to do that on GitHub -- probably easier for you to revert the last change.

**Comment by jenpaulhus** [comment]
Last commit should be back to "Families".

**Comment by JohnCremona** [comment]
OK, looks good -- @AndrewVSutherland will you do the honours?

**Comment by edgarcosta** [comment]
There are two issues with formatting.
"Higher Genus" is still under future, and we are also missing colspan above "Higher Genus", that messes up the css for :hover, over "Families":
screen shot 2016-08-04 at 14 12 20
screen shot 2016-08-04 at 14 11 47

Now going offtopic, why are we marking the previously visited links on the sidebar?
This is only noticeable on the ones that do not involve mathjax.
screen shot 2016-08-04 at 14 15 37



Cheers,
Edgar

**Comment by AndrewVSutherland** [comment]
We want Higher Genus under future, otherwise it will show up on www.lmfdb.org with nothing below it.

**Comment by edgarcosta** [comment]
Sounds good to me.

**Comment by JohnCremona** [comment]
Surely having Higher Genus under beta would also work?

**Comment by AndrewVSutherland** [comment]
Oops, I meant beta -- I just fixed this and the colspan issue Edgar noticed.

**Comment by AndrewVSutherland** [comment]
@edgarcosta And I agree we shouldn't be marking previously visited links on the side bar, I'll see if I can tweak this.

**Comment by AndrewVSutherland** [comment]
@edgarcosta The colors you are seeing are not previously visited links, there are links that have beta status, and I think it makes sense to keep them highlighted.

**Comment by edgarcosta** [comment]
Ups... Sorry for the trouble

**Pull request merged**
