### PR TITLE
Shorter header

### PR DESCRIPTION
**Pull request by davidfarmer**
Made the header shorter.

Changed the CSS, but also had to change the some of the header markup so that it
would look good on both www and beta.

I checked pages with both short and long titles and breadcrumbs, but could have missed something.

Addresses issue #2629.

(First commit was on legendre before I set up my identity.  Hope that doesn't mess anything up.)

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
This looks good to me, I checked a bunch of pages and tried it on both chrome and firefox, but I'll wait for Travis to finish before merging.

**Comment by AndrewVSutherland** [comment]
I'm happy to merge this, but I will hold off until end of day tomorrow in case anyone else wants to take a look or comment.

**Comment by JohnCremona** [comment]
Looks good to me.

**Comment by edgarcosta** [comment]
Do you also see the empty space on the right-hand side of the header?

screen shot 2018-10-03 at 18 26 24

I tried to fix that, but honestly I would have expected the right number to be 205px and not 210px

**Comment by davidfarmer** [comment]
If you are referring to the space between the "Login" and
"Hide Menu" and the right edge of the screen, that was intentional
but maybe not such a great idea.

Fix it by changing the "210" in line 208 of the CSS file.

**Comment by davidfarmer** [comment]
I am okay with eliminating that space.

**Comment by edgarcosta** [comment]
208px is too much:
screen shot 2018-10-03 at 19 10 09
vs 210px:
screen shot 2018-10-03 at 19 10 33

**Comment by edgarcosta** [comment]
Oh, I see, you were trying to align with the boxes below in the main page.
That doesnt't look good to me, specially away from the main page.

On a smaller note, I also find the alignment of the logo with the menu a bit weird.
One way could reduce the sidebar to 180px (the vertical cells to 25px) and the padding-left of the logo to 20px. (but this would require more tweaking, and I would leave it for later)
screen shot 2018-10-03 at 19 26 39

**Pull request merged**
