### PR TITLE
Fix the three error problem

### PR DESCRIPTION
**Pull request by BarinderBanwait**
cf #4165 - Still more to do regarding more informative error message, which i'm working on

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
There is  a minor pyflakes complaint that should be addressed:

```
./lmfdb/characters/main.py:168:5 local variable 'err' is assigned to but never used
```

**Comment by AndrewVSutherland** [comment]
Looks good other than the pyflakes issue.  It might help to make the error message a little more specific (e.g. "coprime natural numbers") to explain why 4.2 and 4.5 are invalid labels.

**Comment by BarinderBanwait** [comment]
i'll address the pyflakes issue as well as improving the error message; i wanted to use the regular expression model used in the number field case, which gives a dichotomy of invalid label vs label not in database, will do this today

**Comment by BarinderBanwait** [comment]
The last commit makes some changes to `label_to_number`; instead of returning 0 whenever there is anything wrong with the label, it now returns a ValueError with the appropriate message for why that label is invalid. This then gets passed up the stack and flashed on the screen when the user tries to search for 'banana' or '4.2' or '4.6'.

**Comment by AndrewVSutherland** [comment]
tests passed on grace

**Pull request merged**
