### PR TITLE
Weil poly

### PR DESCRIPTION
**Pull request by roed314**
Making queries on `is_jac` and `is_pp` faster and fixing a bug in searches for `initial_coefficients`.

### CODE REVIEW

**Comment by edgarcosta** [comment]
I have asked Travis to try again, not sure why the mongodb cursor disappeared.

**Comment by davidlowryduda** [comment]
Generically, not just anyone can ask Travis to try again, right? Did you use a superpower to rerun it? Concerning the error, I wonder if this has to do with #2281?

**Comment by edgarcosta** [comment]
Nothing has been changed yet, and travis can still access m0. And I check for that with:
```
$ printf "db\nexit" | mongo m0.lmfdb.xyz
MongoDB shell version: 3.2.16
connecting to: m0.lmfdb.xyz/test
test
bye
```
Further, most of the tests pass except siegel modular forms.

**Comment by edgarcosta** [comment]
It failed again, nothing to do with abvar:
```
INFO:LMFDB@2017-09-26 14:03:55,966: configuration: {'mongo_client_options': {'host': 'm0.lmfdb.xyz', 'port': 27017, 'replicaset': None, 'read_preference': Nearest(tag_sets=None, max_staleness=-1)}, 'logging_options': {'logfile': 'flasklog'}, 'flask_options': {'debug': False, 'host': '127.0.0.1', 'port': 37777}} 
WARNING:LMFDB@2017-09-26 14:03:55,966: authentication: no password -- fallback to read-only access 
INFO:LMFDB@2017-09-26 14:03:55,966: attempting to establish mongo db connection on port 27017 ... 
INFO:LMFDB@2017-09-26 14:03:55,967: using pymongo version 3.5.1 
INFO:LMFDB@2017-09-26 14:03:56,271: mongodb version: 3.2.16 
INFO:LMFDB@2017-09-26 14:03:56,271: _mongo_C = (MongoClient(host=['m0.lmfdb.xyz:27017'], document_class=dict, tz_aware=False, connect=True, replicaset=None, read_preference=Nearest(tag_sets=None, max_staleness=-1)),) 
INFO:LMFDB@2017-09-26 14:03:56,272: _mongo_C.address = ('m0.lmfdb.xyz', 27017) 
INFO:LMFDB@2017-09-26 14:03:56,272: _mongo_C.nodes = frozenset([('m0.lmfdb.xyz', 27017)]) 
INFO:LMFDB@2017-09-26 14:03:56,272: _mongo_C.read_preference = Nearest(tag_sets=None, max_staleness=-1) 
INFO:LMFDB@2017-09-26 14:03:56,400: MongoClient conection is reading from: ('m0.lmfdb.xyz', 27017) 
Verify that every sample form home page loads OK (should take under 10s on atkin) ... ERROR
Test the top level browse pages ... ok
Test dimension table pages ... ok
Test sample page with defining equation and explicit formula too large to display ... ok
Test 3 random sample pages ... ok
Test eigenvalue, Fourier coefficient, and modulus selction on a sample page with coefficent field Q ... ok
Test eigenvalue, Fourier coefficient, and modulus selction on a sample page with quadratic coefficent field ... ok

======================================================================
ERROR: Verify that every sample form home page loads OK (should take under 10s on atkin)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/LMFDB/lmfdb/lmfdb/siegel_modular_forms/test_siegel_modular_forms.py", line 104, in test_all_sample_pages
    for s in data:
  File "/home/travis/SageMath/local/lib/python2.7/site-packages/pymongo/cursor.py", line 1132, in next
    if len(self.__data) or self._refresh():
  File "/home/travis/SageMath/local/lib/python2.7/site-packages/pymongo/cursor.py", line 1075, in _refresh
    self.__max_await_time_ms))
  File "/home/travis/build/LMFDB/lmfdb/lmfdb/base.py", line 155, in retry
    return func(*args, **kwargs)
  File "/home/travis/SageMath/local/lib/python2.7/site-packages/pymongo/cursor.py", line 947, in __send_message
    helpers._check_command_response(doc['data'][0])
  File "/home/travis/SageMath/local/lib/python2.7/site-packages/pymongo/helpers.py", line 207, in _check_command_response
    raise CursorNotFound(errmsg, code, response)
CursorNotFound: Cursor not found, cursor id: 1209298548629
-------------------- >> begin captured logging << --------------------
MARKDOWN: DEBUG: Successfuly imported extension module "markdown.extensions.wikilinks".
MARKDOWN: DEBUG: Successfully loaded extension "markdown.extensions.wikilinks.WikiLinkExtension".
LMFDB: INFO: configuration: {'mongo_client_options': {'host': 'm0.lmfdb.xyz', 'port': 27017, 'replicaset': None, 'read_preference': Nearest(tag_sets=None, max_staleness=-1)}, 'logging_options': {'logfile': 'flasklog'}, 'flask_options': {'debug': False, 'host': '127.0.0.1', 'port': 37777}}
LMFDB: WARNING: authentication: no password -- fallback to read-only access
LMFDB: INFO: attempting to establish mongo db connection on port 27017 ...
LMFDB: INFO: using pymongo version 3.5.1
LMFDB: INFO: mongodb version: 3.2.16
LMFDB: INFO: _mongo_C = (MongoClient(host=['m0.lmfdb.xyz:27017'], document_class=dict, tz_aware=False, connect=True, replicaset=None, read_preference=Nearest(tag_sets=None, max_staleness=-1)),)
LMFDB: INFO: _mongo_C.address = ('m0.lmfdb.xyz', 27017)
LMFDB: INFO: _mongo_C.nodes = frozenset([('m0.lmfdb.xyz', 27017)])
LMFDB: INFO: _mongo_C.read_preference = Nearest(tag_sets=None, max_staleness=-1)
LMFDB: INFO: MongoClient conection is reading from: ('m0.lmfdb.xyz', 27017)
--------------------- >> end captured logging << ---------------------
```

I will try to run the checks locally and report back.

**Comment by AndrewVSutherland** [comment]
I just ran ./test.sh lmfdb/siegel_modular_forms on atkin and it worked fine; it was noticeably slower than it usually is, it took 271s, whereas is normally takes will under a minute.

**Comment by AndrewVSutherland** [comment]
The abvar tests all pass when I run it manually, and the changes look good.  I'm not sure what Travis's problem is, but it isn't related to this PR, I'm going to go ahead and merge.

**Comment by edgarcosta** [comment]
Thanks!

I think it has to do with some number field queries + wiredTiger.

I will open an issue once I can pin it down.

**Comment by AndrewVSutherland** [comment]
@roed314 The only thing I think is potentially still outstanding for abvar is URL shortening (see issue #2277).  Are you planning to address this?  Is there anything else that  is still pending?  I'd like to see abelian varieties in production soon, and I think we are basically there.

**Comment by roed314** [comment]
I can address that, though I think it will require some fiddling with the templates.

I'm having some problems doing local development though. When I try starting lmfdb, I get the following:
```
Davids-MacBook-Pro:lmfdb roed$ sage -python start-lmfdb.py --debug
INFO:ec@2017-09-26 13:22:56,976: Initializing elliptic curves blueprint [__init__.py:8]
INFO:emf@2017-09-26 13:22:56,979: Initializing elliptic modular forms blueprint with Sage version 8.0.beta5, emf version 1.3 [__init__.py:24]
INFO:artin@2017-09-26 13:22:57,367: Initializing Artin representations blueprint [__init__.py:10]
INFO:tensor_products@2017-09-26 13:22:57,453: Initializing tensor products blueprint [__init__.py:10]
INFO:LMFDB@2017-09-26 13:22:57,582: configuration: {'mongo_client_options': {'host': 'm0.lmfdb.xyz', 'port': 27017, 'replicaset': None, 'read_preference': Nearest(tag_sets=None, max_staleness=-1)}, 'logging_options': {'logfile': 'flasklog'}, 'flask_options': {'debug': True, 'host': '127.0.0.1', 'port': 37777}} 
WARNING:LMFDB@2017-09-26 13:22:57,583: authentication: no password -- fallback to read-only access 
INFO:LMFDB@2017-09-26 13:22:57,583: attempting to establish mongo db connection on port 27017 ... 
INFO:LMFDB@2017-09-26 13:22:57,583: using pymongo version 3.4.0 
INFO:LMFDB@2017-09-26 13:23:27,656: connection attempt failed: m0.lmfdb.xyz:27017: timed out 
INFO:LMFDB@2017-09-26 13:23:27,657: ... done. 
INFO:werkzeug@2017-09-26 13:23:27,662:  * Running on http://127.0.0.1:37777/ (Press CTRL+C to quit) 
INFO:werkzeug@2017-09-26 13:23:27,663:  * Restarting with stat
```

Since I've pulled from upstream master yesterday, the port seems to have changed from 37010 to 27017.  There's no corresponding change in the `warwick.sh` script.  I tried using `37010:localhost:27017`, `27017:localhost:27017` and `27017:localhost:37010` in the port forwarding command, with no success.

Any idea what's going on?

**Comment by edgarcosta** [comment]
Yes, we were trying to make everyone's life easy and have you guys read the data directly from the cloud, but then we had this small issue: https://github.com/LMFDB/lmfdb/issues/2281

Quick fix have a file called `mongoclient.config` (in the root dir of the repo) with:
```
[db]
port = 37010 
host = localhost
replicaset =
read_preference = NEAREST
# socketTimeoutMS = 30000
# connectTimeoutMS = 20000
#serverSelectionTimeoutMS = 30000
```

**Comment by roed314** [comment]
Thanks, that worked.

**Comment by roed314** [comment]
URL shortening is now https://github.com/LMFDB/lmfdb/pull/2287

**Pull request merged**
