### PR TITLE
Make user profiles public

### PR DESCRIPTION
**Pull request by roed314**

### CODE REVIEW

**Comment by roed314** [comment]
Test failure is from having more data in BMFs and is unrelated to this PR.

**Comment by edgarcosta** [comment]
This looks good to me, but I will let one of the editors decide if they want to merge this

**Comment by AndrewVSutherland** [comment]
I think this is fine, but I will wait until Monday to merge this in order to give anyone who has concerns a chance to raise them.

The information on the user profile page contains (1) the name the user entered into the "Full name" field of their profile, (2) the URL they entered for their home page, (3) any text they entered in the "About You" text box, and (4) a list of the knowls they have edited.  Note that (1) and (4) are already visible in the knowl history of the knowls the user has edited, so it is really only (3) and (4) that will now be visible to everyone rather than just users who are logged in.

A quick scan of the contents of (3) shows that it is empty in most cases and innocuous (at worst out of date) in all others, but I invite anyone who would like to update their profile to do so (click on your name in the upper right corner while logged in to access your profile).  If you have forgotten your password email me or @edgarcosta or @roed314 and one of us can reset it for you.

**Comment by AndrewVSutherland** [comment]
@roed314, @edgarcosta any idea why the abvar test is failing?

**Comment by edgarcosta** [comment]
The test failure is on the BMFs:

```
 =================================== FAILURES ===================================
_____________________________ BMFTest.test_search ______________________________

self = <lmfdb.bianchi_modular_forms.test_bmf.BMFTest testMethod=test_search>

    def test_search(self):
        r"""
        Check that various search combinations work.
        """
        self.check_args(base_url+"?field_label=2.0.7.1&level_norm=322&count=10", 'Results (4 matches)')
>       self.check_args(base_url+"?start=0&count=100&field_label=&level_norm=&dimension=&include_base_change=off&include_cm=only&count=100", '/ModularForm/GL2/ImaginaryQuadratic/2.0.7.1/16384.9')

lmfdb/bianchi_modular_forms/test_bmf.py:60: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <lmfdb.bianchi_modular_forms.test_bmf.BMFTest testMethod=test_search>
path = '/ModularForm/GL2/ImaginaryQuadratic/?start=0&count=100&field_label=&level_norm=&dimension=&include_base_change=off&include_cm=only&count=100'
text = '/ModularForm/GL2/ImaginaryQuadratic/2.0.7.1/16384.9'

    def check_args(self, path, text):
>       assert text in self.tc.get(path, follow_redirects=True).get_data(
            as_text=True
        ), "%s not in the %s" % (text, path)
E       AssertionError: /ModularForm/GL2/ImaginaryQuadratic/2.0.7.1/16384.9 not in the /ModularForm/GL2/ImaginaryQuadratic/?start=0&count=100&field_label=&level_norm=&dimension=&include_base_change=off&include_cm=only&count=100

lmfdb/tests/__init__.py:41: AssertionError
```

that job is testing these files:
```
lmfdb/abvar/fq/test_av.py lmfdb/abvar/fq/test_browse_page.py lmfdb/number_fields/test_numberfield.py lmfdb/bianchi_modular_forms/test_bmf.py
```

**Comment by roed314** [comment]
Yeah, #4629 should fix the test failure.

**Comment by JohnCremona** [comment]
I am happy that the "About you" box for me contains (or displays) "None"!

I had forgotten that from this profile page on beta I can change the colour scheme -- and I did, and it changed, but now I cannot change it back.  Correction -- when you click on another colour it does not always appear to change, but you do see the new colour after refreshing the page.

**Comment by AndrewVSutherland** [comment]
@JohnCremona Depending on your browser, you may need to do shift-refresh or ctrl-refresh to see the color change.

**Pull request merged**
