### PR TITLE
commenting out ensure_index

### PR DESCRIPTION
**Pull request by edgarcosta**
See #1169 

Am I breaking something in the knowls or users?

### CODE REVIEW

**Comment by JohnCremona** [comment]
I cannot think of any reason to have those there.  But I also thought that the (now deprecated) ensure_index function was harmless in that if that index existed it did nothing at all.  Once created, surely any index automatically updates itself as data changes?
The tests pass ok.

**Comment by jwj61** [comment]
I was just about to click merge

**Comment by JohnCremona** [comment]
@jwj61 sorry to spoil your fun.  There will be a much more trivial one for you to click on in a minute.

**Comment by edgarcosta** [comment]
@JohnCremona It indeed should be harmless, and instantaneous. However, with the current topology, each one of those ensure_index is quite expensive, as it needs to go through the tunnel, each createIndexes end up consuming 0.15s to 0.25s. 

For each get_knowls() there are 4 of those, and get_knowls() gets called everytime you do get_knowl(). 
Further, there are pages that do get_knowls() a lot of times, for example:  /L/Genus2Curve/Q/681115/a/
ends up doing 22 calls to get_knowls(), in the particular case I was testing it on my desktop all those added up 19.744s.

for some gory details: https://gist.github.com/edgarcosta/c138283aa0c945cc3efde0541ff235d9

**Comment by JohnCremona** [comment]
I think it is a Very Good Thing that you are noticing and eliminating all these inefficiencies.  I'm sure there will be more.  Thanks.

**Pull request merged**
