### PR TITLE
added Bristol 2016 workshop and changed workshops to activities to ke…

### PR DESCRIPTION
**Pull request by alinabucur**
…ep EPSRC happy and breadcrumbs to "Acknowledgments" and "Activities" pages.

### CODE REVIEW

**Comment by JohnCremona** [comment]
Can you also add (as an Activity)

Focussed working group on classical modular forms database, Warwick 14-18 December 2015

as something supported by the EPSRC grant?  Thanks.

**Comment by alinabucur** [comment]
@JohnCremona  @arbooker 
John, 
Andy Booker did not want the small group meeting listed here. I will let you guys reach consensus, and then I'd be happy to add.

**Comment by alinabucur** [comment]
Updated the pull request to solve issue #614 and corrected minor typos.

**Comment by JohnCremona** [comment]
OK fair enough.

**Pull request merged**
