### PR TITLE
fixing configuration and command line arguments

### PR DESCRIPTION
**Pull request by edgarcosta**
- one can again use optional command-line arguments `--enable-profiler`
- these that precedence on whatever is read from the config file
- added the option `--disable-debug` to disable debug mode
- if there is no config file, we create one with all the default options, but the values passed via the command line optional take precedence over the default ones.
For example, running `sage -python start-lmfdb.py --disable-debug --port 5555 --color=17` for the first time will result in
```
[core]
debug = False
color = 17

[web]
port = 5555
...
```

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
If I have debug = true in config.ini using --disable-debug does not disable debug mode (but if debug = false using --debug does turn debug on as it should).  Otherwise looks good.

**Comment by edgarcosta** [comment]
this should be fixed now

**Comment by AndrewVSutherland** [comment]
disable-debug is still not working for me

**Comment by edgarcosta** [comment]
I removed that option and just fixed a bug that happened when you import from the interactive shell.

**Comment by jwj61** [comment]
This does not seem to be working.    Starting with sage -python start-lmfdb.py --debug does not put me in debug mode.

**Pull request merged**
