### PR TITLE
Add label to properties box of artin rep, galois groups, local fields

### PR DESCRIPTION
**Pull request by jwj61**
Can check on the home pages of each type of object.  Also added learnmore for artin rep labels, and removed colons from Galois groups properties boxes.

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
@jwj61 Looks good.  I notice that on the Artin reps home page you have knowls on all the search parameters except ramified and unramified primes -- maybe worth adding these? (unlike the "Invariants" situation, on the search page there is nowhere else to find the definition of these terms)

**Comment by JohnCremona** [comment]
In the example (which I got to using the random function!) http://localhost:37777/ArtinRepresentation/2.2e4_5_131.4t3.2c1  in the "Roots of defining polynomial" there is redundant discussion of an extension of Q_{37} with generator a having polynomial x-1.  It would be nice to special-case this.  (Not necessarily in this PR.)

I agree with @AndrewVSutherland about needing knowls for ramification.  In the knowls artin.conductor and artin.lfunction there is a reference to primes being ramified and these could then cross-reference the new knowl.  (The second of those has many terms which could be links to other knowls, such as the Inertia group, and more).

**Comment by jwj61** [comment]
I am a little concerned with the de facto change in merging criteria.  It used to be pretty much: merge if it improves the site.  I can understand that people see new things when reviewing a pull request, but I would put those in the issue tracker.

This pull request is about putting object labels in the properties box.  It was not merged, and the comments are unrelated to that.  It seems merging this is now contingent on making other changes, or at least debating whether those changes should be made.  Neither of those things should be necessary when making a change.

The suggested changes are now in other pull requests.

**Comment by JohnCremona** [comment]
@jwj61 Please don't overreact -- when I review something and spot something which might make it *even better* it seems most natural to make that comment on the PR itself, but I do not thereby mean that the thing I suggest is a prerequisite to merging.  The person who made the PR might if convenient add a new commit to the same PR, or make it a new issue,or just disagree.  Fine.

To show I mean it I am merging this one now, and then will review #1520 (thanks!) for which the code looks good.

**Comment by AndrewVSutherland** [comment]
@jwj61 I was only waiting to merge in case you wanted to respond to my question/suggestion, I certainly did not mean to insist that you make a change and I apologize if I gave that impression.  I'm happy to merge it as is, and I see that John Cremona has already done so.

**Pull request merged**
