### PR TITLE
Removing all mention or usage of emails

### PR DESCRIPTION
**Pull request by edgarcosta**
Starting to address #2281 

@JohnCremona Could you check that the registration page looks okay?

### CODE REVIEW

**Comment by JohnCremona** [comment]
OK I'll take a look.

**Comment by JohnCremona** [comment]
I cannot connect to m0.lmfdb.xyz.  I don't think I am the only one.  What's up?

**Comment by JohnCremona** [comment]
Using the ssh tunnel to lmfdb.warwick (from home).  I cannot login when running the website locally.  I know the username and password are correct since they work on beta.  I don't know the reason.  This is not caused by this branch, I also cannot login when running the master branch locally.  I think that this used to be possible -- can anyone confirm or otherwise?

**Comment by edgarcosta** [comment]
1- I have closed the m0 port as a response to #2281.
Only now I had time to work on this.
Once I manage to get to my gate and get some stable internet I will replace
all the emails in the DB by email@example.org
And later on when this is merged I will delete those entries as we agreed.

2- what is the error that you get? Are you trying to login as webserver? I
will also try to see how it goes.

**Comment by JohnCremona** [comment]
So right now anyone running master with default config will fail since the new default is to use m0 but that fails!  

The login failure I get is just "wrong password" but the same password is OK on beta and that is using the same database.  But the current master branch has the new bcrypt code which beta does not so that might be the problem.

In the short term I suggest replacing the default config back to using localhost and 37010 so the tunnel works as before.  OK?

**Comment by JohnCremona** [comment]
@csbrady-warwick is behind the log message which appears when I failed to log in:
WARNING:users@2017-10-06 19:48:02,606: user cremona logged in with old style password, but update was not possible [pwdmanager.py:188]
I think this must be an authentication failure.  I am using a passwords.yaml file which still has the old admin password in it.

**Comment by JohnCremona** [comment]
I still cannot check the registration page since when running locally I am not authenticated on the userdb.  Unless someone has a way round that (temporairly for this test) we'll have to merge this into master and beta and then see how the new user registration looks then.

**Comment by edgarcosta** [comment]
Port opened and all emails set to email@example.org, just in case I forgot
something stupid.
I saved the old emails, but I don't plan to use them for anything.

Cheers,
Edgar

**Comment by edgarcosta** [comment]
@JohnCremona I would just merge it and test it afterward. It is not like we have someone registering every second :)

**Pull request merged**
