### PR TITLE
Random fix

### PR DESCRIPTION
**Pull request by edgarcosta**
1- I wrote a generic "get random object" with [$sample (aggregation)](https://docs.mongodb.org/manual/reference/operator/aggregation/sample/).

2- I used the new generic "get random object to replace:
```
    n = get_stats().counts()['collection name']		
    n = randint(0,n-1)		
    random_oject = getDBConnection().collection.find()[n]
```
as we should avoid at all costs anything similar to `getDBConnection().collection.find()`.

### CODE REVIEW

**Comment by JohnCremona** [comment]
Thank you for working out how to do that; I asked around but could not find or did not recognise the aggregate function.  Once I had done it once the old way for elliptic curves, others copied...

**Comment by JohnCremona** [comment]
My testing was with pymongo 2.8.

**Comment by edgarcosta** [comment]
> My testing was with pymongo 2.8.

Same here, but things change a bit for pymongo 3.0, I tried to take that into account

**Comment by JohnCremona** [comment]
I just tested after upgrading pymongo (to 3.2.2) I get errors from the random_object_from collection function.  I will try to fix that.  It works OK with 2.8 which is the version forced by our requirements.txt but I was wondering why we put that in (I cannot remember).
Done.  Pull request coming up.

**Pull request merged**
