### PR TITLE
Toomanyzeros

### PR DESCRIPTION
**Pull request by edgarcosta**
Replaces the ugly message when someone wants to download too many zeros with a knowl.

I have also messed up the creation of the knowl. Could someone delete this knowl for me: http://www.lmfdb.org/knowledge/show/dq.zeros.toomany ?

### CODE REVIEW

**Comment by jwj61** [comment]
Before I delete it I want to confirm, the knowl dq.zeros.toomany is not referenced anywhere, right?

**Comment by edgarcosta** [comment]
Yes, it doesn't show up anywhere.

I was the one who created it today, and messed up the id.

**Comment by jwj61** [comment]
Knowl deleted (on beta)

**Comment by JohnCremona** [comment]
Thanks JJ.  I tried to do something cleaner about this download page a while back but got bogged down in details and never finished.  I cannot test right now but will later in the week if no-one else does.

**Comment by jwj61** [comment]
I was testing this.  When I click on the link it provides, http://warwick.lmfdb.org/data/zeros/zeta/ I get that the address cannot be reached.  I realize this is inside the knowl, so can be changed independently of the pull request, but we should probably get it fixed before pulling.

**Comment by edgarcosta** [comment]
fixed.

**Pull request merged**
