### PR TITLE
this enables tests against proddb.

### PR DESCRIPTION
**Pull request by edgarcosta**
I also had to do a minor edit on `lmfdb/utils/config.py` to avoid running `lmfdb/__init__.py` when  importing `lmfdb.backend.config`.

### CODE REVIEW

**Comment by edgarcosta** [comment]
@AndrewVSutherland, could you double-check that the name of the secret is LMFDB_CI_ACCESS?

Comparing to my fork, it seems that this PR doesn't see it.

Screen Shot 2021-06-27 at 14 16 33

**Comment by AndrewVSutherland** [comment]
@edgarcosta I can confirm that it LMFDB_CI_ACCESS is a "repository" secret (but not an "environment" or "organization" secret, let me know if I need to change this).

**Comment by edgarcosta** [comment]
@AndrewVSutherland, the best I can do at the moment is the following:
- on pull requests tests against devmirror
- after we merge the PR, it tests against devmirror and proddb

**Comment by edgarcosta** [comment]
I will go ahead and merge this to be sure that I'm not wrong regarding the tests after merge.

**Pull request merged**
