### PR TITLE
Knowls

### PR DESCRIPTION
**Pull request by christellevincent**
I just created a bunch of knowls and added links to them on our three template pages. Most of the knowls are in the category av (abelian variety) except for a few ag knowls (ag.base_field, ag.dimension, ag.base_change, ag.primitive, ag.fq.point_counts) and two lf knowls (lf.newton_polygon and lf.newton_slopes)

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
I doubt this has anything to do with the changes in this PR, but when I four errors when I run test_av.py:

FAIL: Check that display_galois_group works
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/drew/github/lmfdb/lmfdb/abvar/fq/test_av.py", line 89, in test_display_gal_gp
    self.not_check_args("/Variety/Abelian/Fq/2/27/f_n",'Galois group of')
  File "/home/drew/github/lmfdb/lmfdb/abvar/fq/test_av.py", line 9, in not_check_args
    assert not(text in self.tc.get(path, follow_redirects=True).data)
AssertionError

======================================================================
FAIL: Check that is_ordinary is computed correctly
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/drew/github/lmfdb/lmfdb/abvar/fq/test_av.py", line 54, in test_is_ordinary
    self.check_args("/Variety/Abelian/Fq/3/3/ad_i_aq",'class is ordinary')
  File "/home/drew/github/lmfdb/lmfdb/abvar/fq/test_av.py", line 6, in check_args
    assert text in self.tc.get(path, follow_redirects=True).data
AssertionError

======================================================================
FAIL: Check that is_simple is computed correctly
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/drew/github/lmfdb/lmfdb/abvar/fq/test_av.py", line 46, in test_is_simple
    self.check_args("/Variety/Abelian/Fq/4/3/ab_d_ad_g",'isogeny class is simple')
  File "/home/drew/github/lmfdb/lmfdb/abvar/fq/test_av.py", line 6, in check_args
    assert text in self.tc.get(path, follow_redirects=True).data
AssertionError

======================================================================
FAIL: Check that is_supersingular is computed correctly
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/drew/github/lmfdb/lmfdb/abvar/fq/test_av.py", line 61, in test_is_supersingular
    self.check_args("/Variety/Abelian/Fq/2/7/a_a", 'class is supersingular')
  File "/home/drew/github/lmfdb/lmfdb/abvar/fq/test_av.py", line 6, in check_args
    assert text in self.tc.get(path, follow_redirects=True).data
AssertionError

**Comment by AndrewVSutherland** [comment]
The knowls all seem to come up fine, so I'm happy to merge this but I'll wait until you have a chance to check the test failures in case you want to make any changes.

One small suggestion: on the search results page I might suggest abbreviating some of the titles that are spelled out in full on the main search page, e.g. "isogeny factors" instead of "isogeny factors decomposition" and "points on variety" instead of  "point count of the abelian variety", so that the search boxes don't get pushed so far to the right.

If anyone is confused they can always click the knowls to get the details.

**Comment by christellevincent** [comment]
Now the tests should all pass and I also implemented the suggested improvement to the search results page; that is a really smart idea, thanks!

**Comment by AndrewVSutherland** [comment]
Looks good!

**Pull request merged**
