### PR TITLE
Add links in EC/Q stats table

### PR DESCRIPTION
**Pull request by BarinderBanwait**
This PR addresses issue #4166 ; it uses the `StatsDisplay` object suggested by @roed314. I've tried to stay true to the original stats page, though there are two differences:

1. The rank table does not contain stats on isogeny classes. Speaking with @edgarcosta yesterday, it seems this is best handled from the backend, so I'll leave this for David/Edgar.

2. The display of the torsion structures (displaying torsion groups of the same order vertically) has not been preserved. It is however now similar to tables in other stats pages.

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
@BarinderBanwait There is a test failure at line 22 of lmfdb/elliptic_curves/test_browse_page.py that should be fixed (the error is complaining that "Distribution of rank not in the /EllipticCurve/Q/stats")

**Comment by BarinderBanwait** [comment]
Yep, just looking at that now! Actually there are several other test failures as well, in `EllCurveTest`. 

But the one you mentioned, "Distribution of rank" not on the webpage: actually it is on the webpage, but it's just that now 'rank' is a knowl, so i guess it's not finding it. If I change the test to check for "Distribution of <a title="Rank of an elliptic curve over a number field [ec.rank]" knowl="ec.rank" kwargs="">rank</a>" then I imagine that will pass; is this an acceptable solution?

**Comment by JohnCremona** [comment]
Yes, just change the expected string in the test to what is actually on the page now.  You can use View Source-- it has to be exact.

**Comment by BarinderBanwait** [comment]
Right, thanks for confirming John, I'll change the expected string as above.

**Comment by AndrewVSutherland** [comment]
The links in the torsion and sha tables don't work, I think you need to add query formatters for these (see G2C_stats in genus2_curves/main.py, for example).

**Comment by BarinderBanwait** [comment]
Oh dear, I should have checked those :grimacing: taking a look now ...

**Comment by BarinderBanwait** [comment]
Query formatters added, links now seem to work.

Are there unit tests to check that the links in the stats pages work? I couldn't find them anywhere. If not, it might be good to do this uniformly across all stats pages if possible

**Comment by AndrewVSutherland** [comment]
Looks good, happy to merge this once tests pass.

I agree that it would be great to have a general method to test all the stats pages (maybe one link per table), perhaps something for @roed314 to think about.

**Pull request merged**
