### PR TITLE
Cmf search boxes

### PR DESCRIPTION
**Pull request by roed314**
Update search boxes code to be able to handle classical modular forms, switch to using it there.

### CODE REVIEW

**Comment by roed314** [comment]
Fixing some abvar issues....

**Comment by roed314** [comment]
The Sage 8.8 job finished successfully, the 9.0 job exceeded Travis' time limit.

**Comment by edgarcosta** [comment]
The worrisome part that both tests taking so long!
The Sage 8.8 test took 48min 38s, very close to timing out.
I have restarted the 9.0

**Comment by roed314** [comment]
Strange.  The restarted Sage 9.0 test only took 13 minutes.

**Comment by edgarcosta** [comment]
I will review this

**Comment by edgarcosta** [comment]
The only thing that seems amiss is the refine search for traces, e.g.:
http://localhost:37777/ModularForm/GL2/Q/holomorphic/?hst=Spaces&dim=1-&num_forms=55&search_type=SpaceTraces

**Comment by roed314** [comment]
I fixed the error you noted and finished PRs for all sections of the LMFDB except Maass forms (which I don't plan on doing).  You can see them all merged together at https://olive.lmfdb.xyz/.

**Comment by AndrewVSutherland** [comment]
https://olive.lmfdb.xyz/Genus2Curve/Q/ leads straight to search results, it should go to the front browse page.

**Comment by edgarcosta** [comment]
@AndrewVSutherland there was a typo, it has been fixed

**Comment by edgarcosta** [comment]
I think we are good to merge once the tests pass

**Comment by AndrewVSutherland** [comment]
Why is there a grey background on the column headers?  This isn't in the current UI and makes them harder to read, compare:

https://olive.lmfdb.xyz/EllipticCurve/Q/?search_type=List&all=1
https://www.lmfdb.org/EllipticCurve/Q/?all=1

This PR should not be making changes to the UI other than uniformization.

If we want to make changes to the look and feel in the future, this PR will make it easier to do so uniformly but we should not be making such changes now as part of an infrastructural change.

**Comment by edgarcosta** [comment]
Should `Bad p` for CMFs also match the new standard "include/exclude/exactly/subset of" ?

**Comment by edgarcosta** [comment]
Another minor thing, we need to delete the `e.g.` from `e.g. wt. 1 only` in the browse page

**Comment by AndrewVSutherland** [comment]
I think so, since this gives strictly more functionality (include = superset of, but we also get exclude which is new functionality).

The number field case is a more complicated, since we do want to have the ability to specify both ramified and unramified primes (so we should probably keep subset of / superset of / exactly for ramified primes on number field searches)

**Comment by edgarcosta** [comment]
> Why is there a grey background on the column headers? This isn't in the current UI and makes them harder to read, compare:
> 
> https://olive.lmfdb.xyz/EllipticCurve/Q/?search_type=List&all=1
> https://www.lmfdb.org/EllipticCurve/Q/?all=1
> 
> This PR should not be making changes to the UI other than uniformization.
> 
> If we want to make changes to the look and feel in the future, this PR will make it easier to do so uniformly but we should not be making such changes now as part of an infrastructural change.

I have just changed the color on olive, so we compare it in the same color scheme.
I don't see an different in the background. 
ps: olive is running a couple of prs ahead #3758

**Comment by AndrewVSutherland** [comment]
@edgarcosta If this is just a side effect of the color scheme, that's fine then (but maybe we should consider tweaking the olive color scheme)

**Comment by edgarcosta** [comment]
We should create an issue for trying to fix or a create a couple of color
schemes so they are a bit more usable in these kind of comparisons, but at
the same time, I don't think that is high priority

**Comment by JohnCremona** [comment]
Is olive configured to always run current master branch?

**Comment by AndrewVSutherland** [comment]
@JohnCremona No. It's being used to demo this PR

**Comment by edgarcosta** [comment]
This can be merged after the tests pass.

If so, we should create a ticket regarding the tweaking of Bad p.
But perhaps that makes more sense after PRs have been merged.

**Comment by roed314** [comment]
Yeah, there are various changes to select boxes that I'd like to address, possibly in a follow up ticket.

**Pull request merged**
