### PR TITLE
missing self arguments

### PR DESCRIPTION
**Pull request by fchapoton**
add some missing self arguments in keywords, as suggested by `mypy`

### CODE REVIEW

**Comment by roed314** [comment]
I agree that there's something to be fixed here.  I [think](https://docs.python.org/3/library/unittest.html#unittest.TestCase) having `def runTest(self): pass` disables scanning for tests.  I'm not sure why we want to do that; should we instead delete all these functions and use the default `runTest` from `unittest.TestCase`?

**Comment by fchapoton** [comment]
I have no idea. There only a few definitions of `runTest` :
```

lmfdb/classical_modular_forms/cmf_test_pages.py:    def runTest(self):
lmfdb/classical_modular_forms/test_cmf.py:    def runTest(self):
lmfdb/classical_modular_forms/test_cmf2.py:    def runTest(self):
lmfdb/ecnf/ecnf_test_pages.py:    def runTest(self):
lmfdb/genus2_curves/g2c_test_pages.py:    def runTest(self):
lmfdb/groups/abstract/groups_test_pages.py:    def runTest(self):
lmfdb/siegel_modular_forms/smf_test_pages.py:    def runTest(self):

```

**Comment by fchapoton** [comment]
should I change the PR to remove all these methods ?

**Comment by roed314** [comment]
That sounds good.  We can see what happens with the tests.

**Comment by edgarcosta** [comment]
I should have said that these tests are not run by default, as these are the tests that test **all** webpages of some kind

**Comment by fchapoton** [comment]
so should I step back to just adding the missing ``self`` ?

**Comment by fchapoton** [comment]
Voilà

**Pull request merged**
