### PR TITLE
EC/Q code updates

### PR DESCRIPTION
**Pull request by JohnCremona**
Fairly minor updates in preparation for some data uploading.

   1. columns 'anlist' and 'aplist' now exist for all curves, not just #1 in each class, so in elliptic_curve/web_ec.py we do not need to fetch them separately for other curves.  For safety until new data is pushed to production the old behaviour is still there if needed.
   2. Optimality has now been proved for curve #1 in each class of conductor<250000 (was 60000).  All occurrences of 60000 have been replaced by a macro now set to 250000 for ease of later upgrading.
   3. No error is triggered for curves with no torsion growth data (which exists for N<400000 but not yet for the new data about to be uploaded).

Test by looking at curve and class pages for 60000<N<250000, e.g. http://localhost:37777/EllipticCurve/Q/100016p/  and any curve in that class (section Modular Invariants).

(+ some script updates not affecting the website)

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
Looks like Travis failed in EC torsion growth test.  As soon as this is fixed I'll review and merge.

**Comment by JohnCremona** [comment]
Embarrassing not to have run my own test suite... should be fixed now!

**Comment by AndrewVSutherland** [comment]
Looks good, I'll merge and push to beta as soon as Travis finishes.

**Comment by JohnCremona** [comment]
Hold on for another commit, as I have just fixed the issue for L-functions not yet existing for newly added curves...

**Comment by JohnCremona** [comment]
OK.  To test the last commit go to http://localhost:37777/EllipticCurve/Q/400002c1/ and see that it says "L-function not available" under Related objects, instead of there being a broken link.  Check also that for a random elliptic curve the usual L-function link is still there and works.

**Comment by AndrewVSutherland** [comment]
Good catch, I just tested the new commit and it looks good, just waiting on travis now.

**Comment by JohnCremona** [comment]
Good to go.  Now I can do some more curve uploading.

**Pull request merged**
