### PR TITLE
Large update to finite groups

### PR DESCRIPTION
**Pull request by roed314**
Can be viewed on https://groups.lmfdb.xyz, and if you want to see the files changed on top of #5521, you can visit [this PR](https://github.com/roed314/lmfdb/pull/374/files) on my LMFDB repo.

### CODE REVIEW

**Comment by roed314** [comment]
Note that this branch contains the modular curves PR (since there would have been merge conflicts otherwise), so reviewing it will get easier once that PR has been merged into master.

**Comment by roed314** [comment]
I disabled a bunch of subgroup search tests while I wait for null counts to be refreshed so that I can see what other tests are failing.

**Comment by roed314** [comment]
Reenabled subgroup tests, and hoping that all tests pass now....

**Comment by AndrewVSutherland** [comment]
Looks like there is one test that is still failing:
```
FAILED lmfdb/groups/abstract/test_browse_page.py::AbGpsHomeTest::test_subgroup_solvable_search
```

**Comment by AndrewVSutherland** [comment]
I'm not sure why the abstract groups test seems to be hanging (possibly devmirror hasn't got all the indexes for the new group tables built?), but it succeeds when I run it locally, so as far as I am concerned, tests pass.

**Pull request merged**
