### PR TITLE
Fixes issue #5469

### PR DESCRIPTION
**Pull request by sarangop1728**

### CODE REVIEW

**Comment by roed314** [comment]
This has test failures.  For example, http://localhost:37777/Variety/Abelian/Fq/?newton_polygon=1%2F3 no longer contains the string "You cannot specify slopes on their own".  @sarangop1728, I'm happy to talk about this in person tomorrow.

**Comment by AndrewVSutherland** [comment]
@roed314 @sarangop1728 I think this PR should be fixed or closed.

**Comment by roed314** [comment]
@sarangop1728, are you interested in finishing this, or are you too busy?

**Comment by sarangop1728** [comment]
Hi @roed314. I remember that you helped me fix this at the LMFDB workshop on Shimura curves. (The issue seems to be resolved, search for:  x^50+311). I believe you submitted the PR. Looks like we forgot to close the issue.

**Pull request closed without merging**
