### PR TITLE
Belyi database

### PR DESCRIPTION
**Pull request by michaelmusty**
Hi,

We (@jvoight, @SamSchiavone, @edgarcosta, @JRSijsling) have our first version of a database of Belyi maps ready to be included in beta. Some of the functionality includes:
- searching by degree, group, genus
- random Belyi maps
- including Passports of Belyi maps as friends
- including number fields and groups as friends when available in the current lmfdb
- breadcrumbs
- some basic statistics

The data is organized by passports, so the user can examine the Galois orbits within a passport. For example, see
http://localhost:37777/Belyi/7T6-[7,4,4]-7-421-421-g1
This passport has 3 Galois orbits of Belyi maps. The curves and equations for these Belyi maps can then be accessed by the links on that page or by the following:
http://localhost:37777/Belyi/7T6-[7,4,4]-7-421-421-g1-a
http://localhost:37777/Belyi/7T6-[7,4,4]-7-421-421-g1-b
http://localhost:37777/Belyi/7T6-[7,4,4]-7-421-421-g1-c

We have included more examples like this in "Some of our favorite examples".

Some shortcomings of our code (so far) are as follows:
- curves and maps displayed can be quite large
- we have not yet implemented knowls, and we will start to take care of this once it gets merged to beta
- no effort has been made to link friends in the elliptic curves database or in the genus 2 curves database

However, it is our hope that the benefits outweigh these shortcomings enough to be included in the beta version of the lmfdb.

Let us know if you have comments or concerns and we will try to address them.

Thank you for your consideration.

Sincerely,
Michael Musty

### CODE REVIEW

**Comment by michaelmusty** [comment]
It appears the Travis build is failing because the link https://hobbes.la.asu.edu/lmfdb-14/ is down.

**Comment by jwj61** [comment]
Hobbes is now back up.  Apache crashes periodically, and I don't know why

**Comment by edgarcosta** [comment]
@JohnCremona and @AndrewVSutherland or @jwj61, do you think it would be possible to get this merged this to Beta sometime this week? 
Perhaps with the caveat that we need to fix certain things?
Or is there anything significant that we need to address right now?


There are a couple of reasons for getting this to beta:
- We would like to display this at ANTS in the rump session (and there we will hopefully get more comments)
- Furthermore, with the exception of Jeroen, we will all be at ANTS, and whatever issues you raise now we can discuss and fix them next week.
- I would like to start to work on the conversion of Belyi to Postgres, and for me, it makes more sense to do it once it gets merged into master.

**Comment by jwj61** [comment]
I think it is good enough to merge into beta

**Comment by jwj61** [comment]
You know you can work on knowls without it being merged.  The bottom of the knowledge page has a place to enter the knowl identifier, and then click to make a new knowl, then fill it in.

**Comment by JohnCremona** [comment]
Looks good to me.  Note that you do *not* have to wait until code is merged before working on knowls, that is a myth.

**Pull request merged**
