### PR TITLE
Improving genus 2 lookup

### PR DESCRIPTION
**Pull request by edgarcosta**

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
The search -x^5+x+1 works on beta but not in this PR.

[[1,1,0,0,0,1],[]] does not work nor does [1,1,0,0,0,1] or X^5+X+1 or [x^5+x+1,0] or x^5+x+1,0.  I'm not sure which of these are intended to work but I think at least the first one should.

**Comment by roed314** [comment]
There's also an extraneous `print(c)` added here.

**Comment by AndrewVSutherland** [comment]
[[12, 0, -3, 0, -1],[0, 0, 0, 1]] doesn't work, even though -x^4-3x^2+12,x^3 and [-x^4-3x^2+12,x^3] do, as does [[0, 0, 0, 0, 1, 1],[1, 1, 0, 1]].

**Comment by edgarcosta** [comment]
note to self, it is the negative numbers. add a a possibility of a minus to
the regex

**Comment by edgarcosta** [comment]
it works now

**Pull request merged**
