### PR TITLE
Tweaking some colors

### PR DESCRIPTION
**Pull request by roed314**
This PR resolves the color issues pointed out in #2883.

### CODE REVIEW

**Comment by roed314** [comment]
Merged in #2895 so that tests pass; that PR should be reviewed first.

**Comment by JohnCremona** [comment]
I am happy with the change to the isogeny class display, and the characters look OK to me but @davidfarmer should look too.

**Comment by davidfarmer** [comment]
The checkerboard looks better, and I can see the difference between the black and other
color when primitive and imprimitive are both shown.  However, the cost is that we typically
do not use black when something is clickable.

I'll let someone else merge after the pull request this depends on is merged.

We still need to rethink the way primitive/ and imprimitive are highlighted.  The current
interface is misguided.  To highlight/imprimitive, you have to hover while your eyes are
looking elsewhere.  And then the highlighting disappears if you then move to click
on something that was highlighted.

I don't know of other cases where such toggling is an option.  Do we need that elsewhere?
Or should it be eliminated here?  Or are Dirichlet characters special?

**Comment by JohnCremona** [comment]
Since #2895 has already been merged I am merging this.

**Pull request merged**
