### PR TITLE
Mod l modular forms

### PR DESCRIPTION
**Pull request by sanni85**
This is the first pull request to add mod l modular forms.

Several things do work, and some need more work: search by group, search by q expansion coefficients and download of search results do not work, all the rest do work.

No test made for this new block. All tests in actually work.

### CODE REVIEW

**Comment by davidfarmer** [comment]
Are there specific URLs I should look at, or should I just start browsing from the sidebar?

You can wait to fix it in the next pull request, but to connect to the database you should do

from lmfdb.base import getDBConnection

instead of lines 19-25 of  lmfdb/import_scripts/modlmf/modlmf.py

Line 218 of lmfdb/modlmf/main.py should use a sage function to list the first few primes.

**Comment by sanni85** [comment]
All done. There are only two forms in, they are linked in the browse page as favourite.
The code will handle forms with coefficients not in a prime field. Today I could not add them for the connection issues.....  
Anyway this is a starting point for other people to help out.

**Comment by davidfarmer** [comment]
On this page:
/ModularForm/GL2/mod_l/
the breadcrumbs should be
Home --> Modular form --> mod \ell

**Comment by davidfarmer** [comment]
In lmfdb/modlmf/modlmf_stats.py the knowl should be done with curly brackets,
not with an "a" tag.

**Comment by davidfarmer** [comment]
On /ModularForm/GL2/mod_l/ put a search button at the bottom left.

**Pull request merged**
