### PR TITLE
code changes for hmf collection name changes

### PR DESCRIPTION
**Pull request by JohnCremona**
After this, all HMF code should work whether there exist collections forms or forms.search or both (and similarly with the rand and stats derived collections).  Currently the beta database has both; after this has been tested & merged and pushed to beta I will try temporarily renaming the forms.search* collections and if that works OK as expected they can be dropped.  (forms is now  a direct copy of forms.search).

### CODE REVIEW

**Comment by JohnCremona** [comment]
Strange -- one failing test:  test_download (lmfdb.genus2_curves.test_genus2_curves.Genus2Test) ... works fine for me locally.  I clicked on "restart build" on travis so the tests will re-run, but I'm not sure if this github page will get updated.  We'll see.

**Comment by JohnCremona** [comment]
OK that must have been some one-off glitch.

**Comment by edgarcosta** [comment]
We fixed that bug over the weekend

**Comment by JohnCremona** [comment]
Thanks for the explanation! 
I will push this to beta and then  move (i.e. rename) the hmfs collections forms.search* since after this code change that should work.  If something is wrong I'll move them back so there's a chance that HMF functionality on beta will break.  Not for another 25 minutes though as I just missed the 15-minute slot.

**Pull request merged**
