### PR TITLE
Fix more tests following refactoring

### PR DESCRIPTION
**Pull request by JohnCremona**
After this there are still 2 FAILs (both in lmfdb/test_tensor_products.py) and 2 ERRORs (both in lmfdb/test_lfunction.py) but progress is progress.

### CODE REVIEW

**Comment by davidfarmer** [comment]
I get:
FAILED (SKIP=3, errors=3, failures=2)
Is that okay?

**Comment by JohnCremona** [comment]
I'm sure I only had 2 errors.  Perhaps something new has happened.   I'll look again.  One day we'll have to see about the 3 which are being skipped too.

**Comment by davidfarmer** [comment]
I don't have gap installed on my laptop, so that may be the difference.  Will merge now.

**Comment by JohnCremona** [comment]
For the record, I get (using Sage 6.9 with all the recommended extras):
FAILED (SKIP=3, errors=2, failures=2)
I am trying again after merging the current master into this branch to make sure that nothing new has cropped up.

**Comment by JohnCremona** [comment]
Same result using the merged version.

**Pull request merged**
