### PR TITLE
main -> web

### PR DESCRIPTION
**Pull request by roed314**

### CODE REVIEW

**Comment by roed314** [comment]
@edgarcosta Are the BHKSSW and Stein-Watkins files available on production to support the [new dataset pages](https://beta.lmfdb.org/datasets/)?

@AndrewVSutherland @jvoight @jwj61 @jenpaulhus Are you guys happy with the new [database](https://beta.lmfdb.org/api/options) and [dataset](https://beta.lmfdb.org/datasets/) pages going into production?  Since I was the author on the PRs that created them, I don't feel comfortable unilaterally pushing to production.

One motivation to merge this now is to silence the [flasklog errors](http://prodweb1.lmfdb.xyz/static/flasklog.txt) that were fixed by #6293.

**Comment by AndrewVSutherland** [comment]
I can take a look this afternoon (NZ time).

**Comment by edgarcosta** [comment]
@roed314 no. Are you referring to `data/bhkssw_split/ `and `data/stein_watkins_ecdb`?
we are missing the folders:
```
> bhkssw_ecdb
> bhkssw_split
> maass_forms
> stein_watkins_ecdb

**Comment by roed314** [comment]
These need to be copied to prodweb1 and prodweb2, right?  Can I just scp them from grace?

**Comment by edgarcosta** [comment]
it is more complicated than that, as it is an external disk that is read-only. I should be able to take care of it today also NZ afternoon time

**Comment by roed314** [comment]
We only need `bhkssw_split` (see #6297 which is related).

**Comment by edgarcosta** [comment]
@roed314 what about?
```
elliptic_curves/elliptic_curve.py:998:        filepath = os.path.join(os.path.expanduser('~/data/bhkssw_ecdb/' + info['filename']))
```

**Comment by roed314** [comment]
That is commented out now after #6297.

**Comment by edgarcosta** [comment]
the data is there

**Pull request merged**
