### PR TITLE
Work on backslashes

### PR DESCRIPTION
**Pull request by roed314**
When starting the LMFDB under Python 3, we get a ton of deprecation warnings due to improperly escaped backslashes.  This PR makes a bunch of strings raw strings to address this.

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
I already fixed all these in the genus 2 code (except for one case I missed and just fixed in a PR I about to submit).  Did you pull upstream before starting this PR?  It doesn't look like you have the latest genus 2 changes.

**Comment by roed314** [comment]
I pulled upstream at 1pm; I'm just changing double backslashes to raw strings for consistency (and because I think they're easier to read when writing latex).

**Comment by roed314** [comment]
We're waiting to merge this until @AndrewVSutherland pushes to web.

**Comment by edgarcosta** [comment]
@roed314 Some merge conflicts must be solved

**Comment by roed314** [comment]
Fixed.

**Comment by edgarcosta** [comment]
@AndrewVSutherland can I merge this?

**Comment by AndrewVSutherland** [comment]
Yes.

**Pull request merged**
