### PR TITLE
some fixes ; auto-done by ruff linter

### PR DESCRIPTION
**Pull request by fchapoton**
this was scripted using the very fast linter ruff

`ruff --fix --select=UP034,UP036,UP024,UP003,UP025 lmfdb/`

### CODE REVIEW

**Comment by roed314** [comment]
Why change `IOError` to `OSError`?  Also, this now fails our linter (now `sys` is imported but not used).

**Comment by fchapoton** [comment]
IOError is now an alias, so better use the new error name directly

**Comment by fchapoton** [comment]
maybe I should rather undo the change to this parsing file ?

**Comment by roed314** [comment]
Yeah, maybe it's best to leave it in since some people like to run the LMFDB on old versions of Sage.

**Pull request merged**
