### PR TITLE
some further details, as suggested by lgtm

### PR DESCRIPTION
**Pull request by fchapoton**
various little improvements, that fix some lgtm suggestions

### CODE REVIEW

**Comment by roed314** [comment]
This looks like the previous code contained a bug (I'd guess implicit multiplication was intended in the following rather than power series composition):

* Old version: `H_all = (1 + x ** 4)(1 + x ** 11) / (1 - x ** 2) ** 3 / (1 - x ** 6)`,
* Your version: `H_all = (1 + x**4) * (1 + x**11) / (1 - x**2)**3 / (1 - x**6)`.

I'd like to hear from someone more familiar with the siegel modular forms code though.  @AndrewVSutherland, do you know who the right person to ask would be?

**Comment by JohnCremona** [comment]
Surely @nilsskoruppa , but I am pretty sure that you are right.  It might be a good idea to check the rest of the file for similar glitches.

**Comment by AndrewVSutherland** [comment]
@roed314 This is clearly a bug in the old code (which I don't think is used anywhere).

**Comment by edgarcosta** [comment]
I agree that it also looks like an error.
The code is still used to display dimensions here: https://beta.lmfdb.org/ModularForm/GSp/Q/?family=Gamma0_4&k=&j=&table=1 (that is why the tests are failing)

Do we have a way to verify which one is the correct series?
```
2 + 6*x^2 + 12*x^4 + 22*x^6 + 36*x^8 + 54*x^10 + 4*x^11 + 78*x^12 + 12*x^13 + 108*x^14 + 24*x^15 + 144*x^16 + 44*x^17 + 188*x^18 + 72*x^19 + 240*x^20 + O(x^21)
1 + 3*x^2 + 7*x^4 + 14*x^6 + 24*x^8 + 38*x^10 + x^11 + 57*x^12 + 3*x^13 + 81*x^14 + 7*x^15 + 111*x^16 + 14*x^17 + 148*x^18 + 24*x^19 + 192*x^20 + 38*x^21 + O(x^22)
```

**Comment by AndrewVSutherland** [comment]
http://www.math.unt.edu/~schmidt/dimension_formulas/

**Comment by AndrewVSutherland** [comment]
This formula is meant to implement the first part of Proposition 5.4 in http://www.math.unt.edu/~schmidt/dimension_formulas/papers/2003_half_integral_weight_degree_two.pdf, which makes it clear that multiplication (not composition) was intended, and that the new code is correct.

My guess is the test was simply based on existing behavior (as opposed to a mathematical check) and needs to be changed to match reality rather than the old implementation.

**Comment by AndrewVSutherland** [comment]
@JohnCremona Agreed, I seriously doubt any of these formulas involve composition, but it would be easy to make this typo when copying them from a mathematical paper (the link above gives a convenient list of citations for most (possibly all) of the formulas that are used, so if anything else looks suspicious, that is the place to look).

**Comment by edgarcosta** [comment]
@AndrewVSutherland, I agree with you. I have changed the test.

**Pull request merged**
