### PR TITLE
adding modell images

### PR DESCRIPTION
**Pull request by shiva-chid**
I have added code to display the modell image as a knowl for each genus genus 2 curve. The data is pulled from g2c_galrep which currently contains for p = 2 and 3, the labels for mod p Galois images whenever they are not the full group GSp(4,Z/p).

### CODE REVIEW

**Comment by edgarcosta** [comment]
The tests fail, in particular, the curve fails to be constructed http://localhost:37777/Genus2Curve/Q/821741/a/821741/1

**Comment by edgarcosta** [comment]
Here is the traceback:
```
Traceback (most recent call last):
  File "/Applications/sage-dev/local/var/lib/sage/venv-python3.9/lib/python3.9/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/edgarcosta/Dropbox (Personal)/projects/LMFDB/lmfdb/lmfdb/app.py", line 43, in __call__
    return self.app(environ, start_response)
  File "/Applications/sage-dev/local/var/lib/sage/venv-python3.9/lib/python3.9/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/Applications/sage-dev/local/var/lib/sage/venv-python3.9/lib/python3.9/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Applications/sage-dev/local/var/lib/sage/venv-python3.9/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Applications/sage-dev/local/var/lib/sage/venv-python3.9/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Applications/sage-dev/local/var/lib/sage/venv-python3.9/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Applications/sage-dev/local/var/lib/sage/venv-python3.9/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Applications/sage-dev/local/var/lib/sage/venv-python3.9/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Applications/sage-dev/local/var/lib/sage/venv-python3.9/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Applications/sage-dev/local/var/lib/sage/venv-python3.9/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/edgarcosta/Dropbox (Personal)/projects/LMFDB/lmfdb/lmfdb/genus2_curves/main.py", line 253, in by_url_curve_label
    return render_curve_webpage(label)
  File "/Users/edgarcosta/Dropbox (Personal)/projects/LMFDB/lmfdb/lmfdb/genus2_curves/main.py", line 334, in render_curve_webpage
    g2c = WebG2C.by_label(label)
  File "/Users/edgarcosta/Dropbox (Personal)/projects/LMFDB/lmfdb/lmfdb/genus2_curves/web_g2c.py", line 751, in by_label
    return WebG2C(curve, endo, tama, galrep, ratpts, clus, is_curve=(len(slabel)==4))
TypeError: __init__() got multiple values for argument 'is_curve'

**Comment by edgarcosta** [comment]
I have preemptively copied the `g2c_galrep` table to proddb as #4971 already made reference to it.

**Comment by AndrewVSutherland** [comment]
The test failure will be fixed by #4995

**Comment by edgarcosta** [comment]
@shiva-chid you should merge `upstream/master` with your branch to reflect the new tests.

**Comment by shiva-chid** [comment]
Just noticed a few things that are off with db.gps_gsp4zhat.
1. The generators are with respect to the action on rows rather than columns.
2. The orbits data is actually with respect to the wrong action. So it is incompatible with Mordell-Weil Group info in some cases.
Will fix both of them soon.

**Comment by AndrewVSutherland** [comment]
@shiva-chid I presume the fixes to db.gps_gsp4zhat only involve data changes, not code changes?  But I think it makes sense to not merge this PR until the data has been updated.

**Comment by shiva-chid** [comment]
Yes, it is only data changes.

**Comment by shiva-chid** [comment]
The data changes are done, so good to go.

**Pull request merged**
