### PR TITLE
Better splitting of long series and polynomials

### PR DESCRIPTION
**Pull request by davidfarmer**
Fixes issue #726 .

Example:

ModularForm/GL2/Q/holomorphic/11/5/2/a/

or any other modular form with coefficients in a higher degree field.

### CODE REVIEW

**Comment by JohnCremona** [comment]
David, what does your Sage give for this:

sage: from sage.env import SAGE_VERSION
sage: version_major, version_minor = [int(x) for x in SAGE_VERSION.split('.')[:2]]
sage: (version_major, version_minor)
sage: (version_major, version_minor) >= (6,9)

-- since this PR includes the commenting out of the code which checks the Sage version and sets emf_version accordingly?  SImilarly, when you start lmfdb locally what do you see in the startup messages similar to this:

INFO:emf@2015-12-23 10:24:53,171: Initializing elliptic modular forms blueprint with Sage version 6.10, emf version 1.3 [__init__.py:22] ?

**Comment by davidfarmer** [comment]
I have Sage version 6.7. (so false on that last line)
On startup the following appears twice
(not sure why it happens twice)


INFO:emf@2015-12-23 05:52:36,910: Initializing elliptic modular forms 
blueprint with Sage version 6.7, emf version 1.3 [__init__.py:23]


The reason I commented out that code and set the emf version to 1.3
is that (if I understand correctly) the available data has that version.
So you don't have access to any modular forms if you use another
emf version, because the version is used when looking for data in
the database.

I could have changed 1.1 to 1.3 in the final else, but then we would have
an if-then-else block that always did the same thing.

SAGE_VERSION isn't used anywhere else in the code.

**Comment by JohnCremona** [comment]
Ok fair enough, this was only meant to be a temporary transitional switch.

**Comment by davidfarmer** [comment]
If the pull request that fixes this is okay, then I think we
are ready to update beta and production.  And email the google
group to let them know that modualr forms are in better shape.

**Comment by fredstro** [comment]
the reason for that version switch is that there was some changes in sage
pickles (as usual) in 6.8 so if you are  using 6.7 you might still
experience some problems with emf_version  1.3 so please update your sage.
Fredrik

**Comment by JohnCremona** [comment]
I'll test, pull and push later today family duties permitting.

**Pull request merged**
