### PR TITLE
Remove lingering reference to ec_curves caused by merge conflict

### PR DESCRIPTION
**Pull request by AndrewVSutherland**
Small cleanup to resolve a problem caused by a bad interaction between the two most recent PRs and a minor formatting tweak.  I will merge this as soon as tests pass.

### CODE REVIEW

**Comment by JohnCremona** [comment]
There is one thing here which needs fixing, in the find_firends which I had not noticed: j-invariants are now stored as a list of 2 ints [num,den] not a string.  Clearly we don't have a test for that...

**Comment by AndrewVSutherland** [comment]
@JohnCremona Are you fixing this or would you like me to?

**Comment by JohnCremona** [comment]
> @JohnCremona Are you fixing this or would you like me to?

I just did -- see new PR

**Comment by JohnCremona** [comment]
> > @JohnCremona Are you fixing this or would you like me to?
> 
> I will!

Done,  see PR #4305 .  It's only in a script so I don't know whether it matters as much as I had thought.  There should not be any more of these, as I had checked all occurrences of "ec_" at some point, but I missed this one even though in the same line as I just corrected I had changed curves to curvedata.

**Pull request merged**
