### PR TITLE
Add root discriminant to the display of a number field

### PR DESCRIPTION
**Pull request by jwj61**
Some bottom knowls point out that a field has small root discriminant.  This adds that value as a basic invariant of the field.  Just look at the home page of any number field.

### CODE REVIEW

**Comment by JohnCremona** [comment]
Looks fine to me.  Do you want the r.d. to also appear in the Properties box?

**Comment by jwj61** [comment]
Good suggestion, so now it does it.

I was really thinking of printing rd with fixed precision, which may be LMFDB heresy, but now this pull request does that.

**Comment by JohnCremona** [comment]
Looks good.  For the fixed precision output, I'm not sure why you do not use

>sage: R = RealField(200)
>sage: pi = R.pi()
>sage: pi.str(digits=5)
>'3.1416'
>sage: pi.str(digits=10)
>'3.141592654'
>sage: pi.str(digits=20)
>'3.1415926535897932385'
>sage: pi.str(digits=30)
>'3.14159265358979323846264338328'

but perhaps that does not have the same behaviour?  If we can standardise this the function should go into utils.  But that can wait.

**Comment by edgarcosta** [comment]
Why not `display_float`?

**Comment by jwj61** [comment]
Both display_float and the sage suggestion fixes the total number of digits.  I wanted 2 places after the decimal point regardless of number of digits in the number (so it can produce 3.14 and 10.23, not 3.14 and 10.2).

**Pull request merged**
