### PR TITLE
quick fix to problem introduced by #1732

### PR DESCRIPTION
**Pull request by AndrewVSutherland**

### CODE REVIEW

**Comment by JohnCremona** [comment]
I just ran this on atkin and the problem persists.  I will check more carefully by running each line from the file I was loading one at a time.

**Comment by AndrewVSutherland** [comment]
@JohnCremona Can you give me a test case that reproduces the problem you are having?  (I was nervous about just running the import script so I was just testing that import lmfdb works, which it does).

**Comment by JohnCremona** [comment]
OK:  I'm on commit f735229... which is your branch fix-1732-configuration-problem, on atkin.  I run
/usr/local/bin/sage (i.e. the standard system-wide one, not something else) from the lmfdb directory,  and at the sage prompt type
from lmfdb.base import getDBConnection
to see the error.
Obviously I can change my script, but this used to work fine.

**Comment by JohnCremona** [comment]
Another symptom:   I cannot run the websote normally either -- I put -p 37702 on the command line as I have that tunnelled through to a local port, but when the website starts up it shows that the configuration has port=37777.

**Comment by AndrewVSutherland** [comment]
OK from lmfdb.base import getDBConnection now works:

> drew@atkin:~/github/lmfdb$ /usr/local/bin/sage
┌────────────────────────────────────────────────────────────────────┐
│ SageMath Version 7.1, Release Date: 2016-03-20                     │
│ Type "notebook()" for the browser-based notebook interface.        │
│ Type "help()" for help.                                            │
└────────────────────────────────────────────────────────────────────┘
sage: from lmfdb.base import getDBConnection
INFO:emf@2016-07-13 21:23:39,116: Initializing elliptic modular forms blueprint with Sage version 7.1, emf version 1.3 [__init__.py:24]
INFO:ec@2016-07-13 21:23:39,322: Initializing elliptic curves blueprint [__init__.py:8]
INFO:g2c@2016-07-13 21:23:39,337: Initializing genus 2 curves blueprint [__init__.py:9]
INFO:artin@2016-07-13 21:23:39,668: Initializing Artin representations blueprint [__init__.py:10]
INFO:tensor_products@2016-07-13 21:23:39,682: Initializing tensor products blueprint [__init__.py:10]
INFO:LMFDB@2016-07-13 21:23:39,793: configuration: {'mongo_client_options': {'host': 'lmfdb-ib', 'port': 37010, 'replicaset': None, 'read_preference': Nearest(tag_sets=None)}, 'flask_options': {'debug': False, 'host': '127.0.0.1', 'port': 37777}} 
WARNING:LMFDB@2016-07-13 21:23:39,793: authentication: no password -- fallback to read-only access 
INFO:LMFDB@2016-07-13 21:23:39,793: attempting to establish mongo db connection on port 37010 ... 
INFO:LMFDB@2016-07-13 21:23:39,793: using pymongo version 3.2.2 
INFO:LMFDB@2016-07-13 21:23:39,807: mongodb version: 3.2.1 
INFO:LMFDB@2016-07-13 21:23:39,807: _mongo_C = (MongoClient(host=['lmfdb-ib:37010'], document_class=dict, tz_aware=False, connect=True, replicaset=None, read_preference=Nearest(tag_sets=None)),) 
INFO:LMFDB@2016-07-13 21:23:39,808: _mongo_C.address = ('lmfdb-ib', 37010) 
INFO:LMFDB@2016-07-13 21:23:39,808: _mongo_C.nodes = frozenset([('lmfdb-ib', 37010)]) 
INFO:LMFDB@2016-07-13 21:23:39,808: _mongo_C.read_preference = Nearest(tag_sets=None) 
INFO:LMFDB@2016-07-13 21:23:39,824: MongoClient conection is reading from: ('lmfdb-ib', 37010)

and so does "sage start-lmfdb.py -p 37702", but that worked before as well so I'm not sure if you are doing something different than I am.  For example on atkin:

> drew@atkin:~/github/lmfdb$ /usr/local/bin/sage start-lmfdb.py -p 37702
INFO:emf@2016-07-13 21:26:24,859: Initializing elliptic modular forms blueprint with Sage version 7.1, emf version 1.3 [__init__.py:24]
INFO:ec@2016-07-13 21:26:25,008: Initializing elliptic curves blueprint [__init__.py:8]
INFO:g2c@2016-07-13 21:26:25,024: Initializing genus 2 curves blueprint [__init__.py:9]
INFO:artin@2016-07-13 21:26:25,459: Initializing Artin representations blueprint [__init__.py:10]
INFO:tensor_products@2016-07-13 21:26:25,473: Initializing tensor products blueprint [__init__.py:10]
INFO:LMFDB@2016-07-13 21:26:25,577: configuration: {'mongo_client_options': {'host': 'lmfdb-ib', 'port': 37010, 'replicaset': None, 'read_preference': Nearest(tag_sets=None)}, 'flask_options': {'debug': False, 'host': '127.0.0.1', 'port': 37702}} 
WARNING:LMFDB@2016-07-13 21:26:25,577: authentication: no password -- fallback to read-only access 
INFO:LMFDB@2016-07-13 21:26:25,577: attempting to establish mongo db connection on port 37010 ... 
INFO:LMFDB@2016-07-13 21:26:25,577: using pymongo version 3.2.2 
INFO:LMFDB@2016-07-13 21:26:25,585: mongodb version: 3.2.1 
INFO:LMFDB@2016-07-13 21:26:25,586: _mongo_C = (MongoClient(host=['lmfdb-ib:37010'], document_class=dict, tz_aware=False, connect=True, replicaset=None, read_preference=Nearest(tag_sets=None)),) 
INFO:LMFDB@2016-07-13 21:26:25,586: _mongo_C.address = ('lmfdb-ib', 37010) 
INFO:LMFDB@2016-07-13 21:26:25,586: _mongo_C.nodes = frozenset([('lmfdb-ib', 37010)]) 
INFO:LMFDB@2016-07-13 21:26:25,586: _mongo_C.read_preference = Nearest(tag_sets=None) 
INFO:LMFDB@2016-07-13 21:26:25,603: MongoClient conection is reading from: ('lmfdb-ib', 37010) 
INFO:LMFDB@2016-07-13 21:26:25,603: ... done. 
INFO:werkzeug@2016-07-13 21:26:25,606:  * Running on http://127.0.0.1:37702/ (Press CTRL+C to quit)

**Comment by JohnCremona** [comment]
I do 'sage -python' not just 'sage' but they work the same for me, I do not get the port set even though I have -p 37702 on the command line.

**Comment by AndrewVSutherland** [comment]
@JohnCremona Does from lmfdb.base import getDBConnection now work for you?

For running the LMFDB, can you send me an exact transcript of the command line you are typing and the output?  I get:

drew@atkin:~/github/lmfdb$ sage -python start-lmfdb.py -p 37002
INFO:emf@2016-07-13 22:01:02,981: Initializing elliptic modular forms blueprint with Sage version 7.1, emf version 1.3 [__init__.py:24]
INFO:ec@2016-07-13 22:01:03,134: Initializing elliptic curves blueprint [__init__.py:8]
INFO:g2c@2016-07-13 22:01:03,161: Initializing genus 2 curves blueprint [__init__.py:9]
INFO:artin@2016-07-13 22:01:03,588: Initializing Artin representations blueprint [__init__.py:10]
INFO:tensor_products@2016-07-13 22:01:03,601: Initializing tensor products blueprint [__init__.py:10]
INFO:LMFDB@2016-07-13 22:01:03,705: configuration: {'mongo_client_options': {'host': 'lmfdb-ib', 'port': 37010, 'replicaset': None, 'read_preference': Nearest(tag_sets=None)}, 'flask_options': {'debug': False, 'host': '127.0.0.1', 'port': 37002}} 
WARNING:LMFDB@2016-07-13 22:01:03,705: authentication: no password -- fallback to read-only access 
INFO:LMFDB@2016-07-13 22:01:03,705: attempting to establish mongo db connection on port 37010 ... 
INFO:LMFDB@2016-07-13 22:01:03,705: using pymongo version 3.2.2 
INFO:LMFDB@2016-07-13 22:01:03,713: mongodb version: 3.2.1 
INFO:LMFDB@2016-07-13 22:01:03,713: _mongo_C = (MongoClient(host=['lmfdb-ib:37010'], document_class=dict, tz_aware=False, connect=True, replicaset=None, read_preference=Nearest(tag_sets=None)),) 
INFO:LMFDB@2016-07-13 22:01:03,713: _mongo_C.address = ('lmfdb-ib', 37010) 
INFO:LMFDB@2016-07-13 22:01:03,713: _mongo_C.nodes = frozenset([('lmfdb-ib', 37010)]) 
INFO:LMFDB@2016-07-13 22:01:03,713: _mongo_C.read_preference = Nearest(tag_sets=None) 
INFO:LMFDB@2016-07-13 22:01:03,729: MongoClient conection is reading from: ('lmfdb-ib', 37010) 
INFO:LMFDB@2016-07-13 22:01:03,730: ... done. 
INFO:werkzeug@2016-07-13 22:01:03,732:  * Running on http://127.0.0.1:37002/ (Press CTRL+C to quit)

**Comment by AndrewVSutherland** [comment]
@JohnCremona I could fix this by reverting to the way the code worked before, which is using a try/except that just ignores all errors (this is what Edgar changed in #1732), but I'd rather not do that, as it potentially hides problems that we would like to know about.

**Comment by edgarcosta** [comment]
Hello,

before the if below was in a try/except loop, I can put it back, but has @AndrewVSutherland said, that just hides all the errors. 
```
        import getopt
        try:
            opts, args = getopt.getopt(
                                        sys.argv[1:],
                                        "p:h:l:t:m:",
                                       [
                                           "port=",
                                           "host=", 
                                           "dbport=", 
                                           "log=", 
                                           "logfocus=", 
                                           "debug",
                                           "help", 
                                           "threading", 
                                           "mongo-client=",
                                            # undocumented, see below
                                            "enable-reloader", "disable-reloader",
                                            "enable-debugger", "disable-debugger",
                                            "enable-profiler"
                                        ]
                                       )
        except getopt.GetoptError, err:
            sys.stderr.write("%s: %s\n" % (sys.argv[0], err))
            sys.stderr.write("Try '%s --help' for usage\n" % sys.argv[0])
            sys.exit(2)

        for opt, arg in opts:
            if opt == "--help":
                usage()
                sys.exit(0)
            elif opt in ("-p", "--port"):
                flask_options["port"] = int(arg)
            elif opt in ("-h", "--host"):
                flask_options["host"] = arg
            #FIXME logfile isn't used
            elif opt in ("-l", "--log"):
                logfile = arg
            elif opt in ("--dbport"):
                mongo_client_options["port"] = int(arg)
            elif opt == "--debug":
                flask_options["debug"] = True
            elif opt == "--logfocus":
                logfocus = arg
                logging.getLogger(arg).setLevel(logging.DEBUG)
            elif opt in ("-m", "--mongo-client"):
                if os.path.exists(arg):
                    mongo_client_config_filename = arg
                else:
                    sys.stderr.write("%s doesn't exist\n" % arg);
                    sys.exit(2);
```

**Comment by AndrewVSutherland** [comment]
@edgarcosta After the 2nd of my two commits I don't have either of the problems that @JohnCremona reported -- it might be worth waiting to get more information from him.  The key point is that there are several different ways the configuration code in website.py may get executed: via start-lmfdb.py, via gunicorn, or by devs importing lmfdb modules directly into sage.  We need all of them to work.

**Comment by edgarcosta** [comment]
@AndrewVSutherland I totally agree, I just need to know how to recreate the error so I can fix it :)

**Comment by JohnCremona** [comment]
OK, I am awake again.  As of now (after the 2nd commit, now at 2851561) it works fine to import into a Sage session (so the original problem I reported is fixed) but running the webaite locally fails since it does not pick up the port number from the command line.
Let me know if I should try anything else.

**Comment by JohnCremona** [comment]
By the way, since I cannot run the master branch locally any more it will be hard for me to test / review anything until we sort this out.

**Comment by edgarcosta** [comment]
@JohnCremona could you give the command you are trying to run?

I just pulled this PR and it worked for me doing the following:

```
 $ sage -python start-lmfdb.py -p 111111
....
INFO:LMFDB@2016-07-14 20:01:08,330: configuration: {'mongo_client_options': {'host': 'localhost', 'port': 37010, 'replicaset': None, 'read_preference': Nearest(tag_sets=None)}, 'flask_options': {'debug': False, 'host': '127.0.0.1', 'port': 111111}} 
```

**Comment by AndrewVSutherland** [comment]
@JohnCremona Does it work if you just type "sage -python $HOME/lmfdb/start-lmfdb.py --debug -t -p 37702" at the command line?

**Comment by JohnCremona** [comment]
No, but it *does* work if I leave out the "-t".  Progress!

**Comment by JohnCremona** [comment]
Also as far I can see the -t option does nothing, and seem to remember Harald once saying that it was something he tried a long time ago which now did nothing.  Well, now it does something, but not what we want.  Though as far as I can see the function get_configuration() ignores it.

**Comment by AndrewVSutherland** [comment]
The -t argument is not used (I think it stands for threading), so you can and should leave it out. I think if you remove the -t from your .bashrc everything should work for you.

But hold off on merging this PR, getopt is not behaving the way I think it should (what is happening is that it is treating "-p" as the value of the "-t" parameter leaving 37702 as an argument that gets ignored rather than the value of -p).  I am going to try switching to argparse (which I like better anyway) to see if this fixes the problem.

**Comment by AndrewVSutherland** [comment]
Never mind the problem is that t just shouldn't have a colon after it (it does not require an argument).

@JohnCremona Please retry with my latest commit, and if this works, merge this PR.

**Comment by AndrewVSutherland** [comment]
Just to be clear: it should now work with your current .bashrc setup, but there is no reason not to remove the -t argument, which will get ignored in any case (and should be regarded as deprecated).

**Comment by edgarcosta** [comment]
@AndrewVSutherland,  you have also removed the argument of -m

**Comment by AndrewVSutherland** [comment]
@edgarcosta fixed.

**Comment by JohnCremona** [comment]
OK trying now in various ways...

**Comment by JohnCremona** [comment]
OK all works -- my little script both with and without '-t' (which I will leave out), and also the other scripts which do the imports directly.

**Pull request merged**
