### PR TITLE
Make extent of data a knowl for elliptic curves/Q, local fields, and Galois groups.

### PR DESCRIPTION
**Pull request by jwj61**
For elliptic curves, this involves invoking a function defined in the elliptic curve python file.

To test, look at the index pages for these three areas.

### CODE REVIEW

**Comment by JohnCremona** [comment]
I'll check this tomorrow.  In return...?

**Comment by davidfarmer** [comment]
Has the knowl for the top of the Galois Groups page not been created yet?  I don't see the
data at the top of the page.

**Comment by jwj61** [comment]
You are right, I forgot to add the galois group page to the commit.  Done now.

**Comment by JohnCremona** [comment]
Looks good!

**Pull request merged**
