### PR TITLE
refactor elliptic curve (over Q) and lhash L-function code

### PR DESCRIPTION
**Pull request by davidlowryduda**
In this pull request, I reorganize the code in set_bread_and_friends, to make that method less monolithic and to make the overall display of L-functions a bit more understandable.

### CODE REVIEW

**Comment by davidlowryduda** [comment]
See #2370 for a discussion and explanation behind this pull request.

**Comment by JohnCremona** [comment]
I suggested one tiny change in #2273 (to fix that issue at the same time) but more eyes would be welcome on this one.

**Comment by edgarcosta** [comment]
I agree with the proposed change

**Comment by davidlowryduda** [comment]
The proposed change makes sense to me. I've updated the pull request to incorporate @JohnCremona's suggestion.

**Comment by JohnCremona** [comment]
Thanks for the quick action.

**Pull request merged**
