### PR TITLE
Add testing for some dynamic knowls

### PR DESCRIPTION
**Pull request by jwj61**
Adds 6 tests, 1.5 seconds

### CODE REVIEW

**Comment by edgarcosta** [comment]
We souldn't ignore whenever the automatic test fails:
https://travis-ci.org/LMFDB/lmfdb/builds/274340819?utm_source=github_status&utm_medium=notification

**Comment by JohnCremona** [comment]
As far as I can tell, whenever there's a pull request to master this triggers travis to run the check, so all it takes to check that the tests pass (which includes pyflakes) is to wait a bit.

We rather got used to having a few tests which failed for known reasons.  There's small danger now that we'll suspend those tests rather than fixing them.

**Comment by edgarcosta** [comment]
The goal should be to always have the automatic tests to pass automatically.
If a known tests fails for known reasons, we should disable it or fix it.
We should really avoid a pull request to be merged if it triggers a failure on the automatic tests.
Otherwise after the merge, unrelated pull requests will start to fail...

**Comment by JohnCremona** [comment]
I agree entirely -- what I meant was that people might be *tempted to* disable a test rather than fix it...

**Comment by jwj61** [comment]
Sorry, I should have waited for the tests to finish.

**Comment by edgarcosta** [comment]
no problem!

**Pull request merged**
