### PR TITLE
activate pylint check for python3 compatibility

### PR DESCRIPTION
**Pull request by fchapoton**
this adds pylint --py3k to the travis checks

for the moment, with some exceptions in the checks, that should be taken care of later

this should help not to move backwards about python3 compatibility

### CODE REVIEW

**Comment by fchapoton** [comment]
When succesfull, pylint, unlike pyflakes, does return something. How to handle that ?

**Comment by fchapoton** [comment]
worse, it seems that the option --py3k has been removed recently from pylint

**Comment by edgarcosta** [comment]
One could check for the exit code.

**Comment by fchapoton** [comment]
The output should be ok, using the option "score=no". Now it's the install that is failing, do you see a way to fix it ? Should we add "pylint" to requirements.txt ?

**Comment by edgarcosta** [comment]
We must install pylint in python2 to have py3k option.
The current commit will fail, but now for a good reason: https://travis-ci.org/edgarcosta/lmfdb/builds/641826230#L1152

**Comment by fchapoton** [comment]
Damn, where are all these bad print coming from ???

**Comment by edgarcosta** [comment]
I figure it out, pylint is just complaining that we are not importing the print_function

**Comment by edgarcosta** [comment]
We should be good now.

**Comment by fchapoton** [comment]
Looks good to me.

**Pull request merged**
