### PR TITLE
Remove import * in character blueprint

### PR DESCRIPTION
**Pull request by pascalmolin**
this commit can be applied on sage 6.1 versions, it does not fix the issues with 6.4
(this will be the next pull request)

In d4118a88d0 I have disabled 3 tests which fail both on my machine and on beta.lmfdb.org -- from some time -- : I think those tests should be checked and commited again.
However I do not feel comfortable with this way of doing things so I can also revert d4118a88d0 : advice ?

### CODE REVIEW

**Comment by JohnCremona** [comment]
Update: before merging this should work properly with Sage 6.5.

**Comment by JohnCremona** [comment]
Should this request be closed?

**Comment by haraldschilly** [comment]
@pascalmolin this looks like it has bitrotten. any chance you could try to rebase it on the current master?

**Comment by davidfarmer** [comment]
Closing without merging because too much has happened since.

**Pull request closed without merging**
