### PR TITLE
Attribute completeness of class number 1 data

### PR DESCRIPTION
**Pull request by kedlaya**
Adding an attribution for the statement that the table of primitive lattices of class number one is complete. (I gather this is a subtable of the Catalogue of Lattices.)

### CODE REVIEW

**Comment by JohnCremona** [comment]
Should we give a citation (I found https://arxiv.org/abs/1208.5638)? Otherwise this is fine.
@kedlaya your branch names are most unimaginative!

**Comment by kedlaya** [comment]
If we give a citation, we should give both arXiv and DOI, and maybe also MR3091733. 

Re the branch names, these are defaults generated by Github when I generate pull requests there, without creating a local copy of the repository. This is handy for changes that are so trivial that I don't need to recompile to see if they work correctly.

**Comment by JohnCremona** [comment]
I agree with giving as many possible citation links (here and everywhere).

**Comment by edgarcosta** [comment]
I added the arxiv, MR and DOI references.

But honestly, half of that text is statistics of the data, and the other half is addressing some completeness of the data, and the later should be a knowl.

**Comment by edgarcosta** [comment]
ps: I'm happy to merge once someone agrees with my changes

**Comment by kedlaya** [comment]
I think you're right, the Kirschmer-Lorch attribution should go in the "Source of the data" knowl instead. I just added it there, so you can take it out of here.

**Comment by kedlaya** [comment]
I guess that makes this PR redundant...

**Pull request closed without merging**
