### PR TITLE
Fixed g2/G2 name conflict in curve_g2.html responsible for #1093

### PR DESCRIPTION
**Pull request by AndrewVSutherland**

### CODE REVIEW

**Comment by JohnCremona** [comment]
I am testing now.

**Comment by JohnCremona** [comment]
This does not work properly for me.  OK if you click G2, but not if you then click Igusa, or back to Igusa-Clebcsh.

**Comment by AndrewVSutherland** [comment]
Hmm, it works for me without any problems, I can click back and forth 
and cycle through all three with changing the endomorphism ring display.

Does the curve_g2.html file you are using have "G2" instead of "g2" in 
lines 210-213 (and a few other places)?

The branch I commited and pushed is called master (not genus2 which I 
used in Bristol).  I hope I didn't issue the pull request from the wrong 
branch?

Drew

**Comment by AndrewVSutherland** [comment]
I've checked this on both chrome and firefox on ubuntu 14.04 and it seems OK, what browser/OS are you using?

**Comment by JohnCremona** [comment]
Firefox on Suse.  I will check agan since I got mixed up with branches yesterday.

**Comment by JohnCremona** [comment]
Sorry, I checked out the branch drew/minorgenus2changes but I see that it should be drew/master.  Which works!

**Pull request merged**
