### PR TITLE
simplify ECNF constructor to do minimal arithmetic on ideals

### PR DESCRIPTION
**Pull request by JohnCremona**
This deals with more of the issues mentioned at Issue #4323.  The ECNF constructor now does much less work regarding constructing ideals from their string representation in the database, going directly from those strings to latex for display, even for the factorizations of the conductor and discriminant.

After this, the following will also be done, involving data (schema) changes which this code will handle without change:  (1) all ideal strings stored (for conductor, minimal discriminant, and bad primes) will be replaced by minimal generators (e.g. one generator for principal ideals, otherwise two) delimited by "(",")", whereas at present they are of the form "[N,a,alpha]" where N is the norm and a the smallest positive integer in the ideal.  The code here can tell when this has been done by seeing if the string started with "(" or "[".  (2) We now store the minimal discriminant in the database, and usually that is the same as the ideal generated by the discriminant of the model stored, but for cases where that is not the case I will add a column to hold the model discriminant; right now this is computed on the fly -- but when it is not the same as the minimal discriminant.

This code now also allows for computing reduced gens on the fly, as a temporary measure, and that is currently done when the degree is 2 or 3 *or* the class number is 1.  Reviewers are welcome to suggest a different condition, but this is only temporary -- users will not like to see ideals presented with 2 generators over fields like Q(i).  I'll work on the data changes next week.

### CODE REVIEW

**Comment by JohnCremona** [comment]
I restarted the failing check after the "escapes" branch was merged and all tests now pass -- as you can see if you look at the Travis log, even though the red cross has not been updated on this page.

**Comment by JohnCremona** [comment]
> I restarted the failing check after the "escapes" branch was merged and all tests now pass -- as you can see if you look at the Travis log, even though the red cross has not been updated on this page.

My mistake, it is green now -- but I am about to update the PR with some more simplifications so no hurry.

**Comment by JohnCremona** [comment]
This PR is again ready.  It contains all code changes in ECNF which have been made to (1) be more efficient already and (2) work when I have made some changes to the table ec_nfcurves.  This will add columns disc, normdisc (for the ideal discriminant of the model);  ensure all ideal strings (conductor, minimal discriminant ideal, bad primes) are in simplified form, e.g. show a single generator for principal ideals, and replace Kodaira symbol strings with pari encodings.

I am also considering deleting the column which holds the latex equation, since it can be quite along string.  This code version will create that string on the fly of the column does not exist.

In all respects, this code is supposed to work perfectly now and after the data changes.

**Comment by AndrewVSutherland** [comment]
@JohnCremona It looks like there are some merge conflicts caused by your earlier PR which I just merged -- can you take a look at these?

**Comment by JohnCremona** [comment]
> @JohnCremona It looks like there are some merge conflicts caused by your earlier PR which I just merged -- can you take a look at these?

OK, I'm on it

**Comment by JohnCremona** [comment]
Is more information needed to help review this?  I'll soon be ready to make some data changes which can only be done once this is merged -- and that includes correcting data as in issue #4332.

**Comment by JohnCremona** [comment]
On second thoughts I can update the data for those RQFs without waiting, but would still like this to progress

**Comment by AndrewVSutherland** [comment]
@JohnCremona Our plan is to wait and review and merge this next week (on Wednesday).

**Comment by JohnCremona** [comment]
That's fine.  I have some data uploads which can wait.

**Pull request merged**
