### PR TITLE
Colors3

### PR DESCRIPTION
**Pull request by swisherh**
Added color options to color.css file with original colors as default

### CODE REVIEW

**Comment by davidfarmer** [comment]
I'll take care of this and issue #1345

**Comment by AndrewVSutherland** [comment]
@davidfarmer I will leave this to you unless you tell me to merge it.

**Comment by AndrewVSutherland** [comment]
@davidfarmer I'm trying to get the outstanding pull requests cleared, can you tell me what I should do with this?  Close or merge? (you can always issue a new pull request when you address #1345).

**Comment by davidfarmer** [comment]
This should cause no harm to merge.  I will address issue #1345
separately instead of as part of this pull request.

**Comment by AndrewVSutherland** [comment]
@davidfarmer Thanks, I ran it locally and no evident changes, merging

**Pull request merged**
