### PR TITLE
merge master to beta

### PR DESCRIPTION
**Pull request by JohnCremona**
I think it is time to do this -- main visible change will be the citation pages.  OK?

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
Agreed, it's a bad idea to leave things unpushed for too long.

**Comment by JohnCremona** [comment]
OK, I'll merge this one.  prod too?

**Comment by AndrewVSutherland** [comment]
I suggest we let it run for a day on beta first, just in case.

**Comment by edgarcosta** [comment]
> I suggest we let it run for a day on beta first, just in case.

I agree

**Pull request merged**
