### PR TITLE
Remove beta status from abelian varieties

### PR DESCRIPTION
**Pull request by roed314**

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
I think this is ready for production.  I'm happy to merge but will wait for others to chime in.

**Comment by jwj61** [comment]
Looks good to me.

**Comment by davidfarmer** [comment]
Me too.

**Comment by edgarcosta** [comment]
Same

**Comment by AndrewVSutherland** [comment]
It looks like we have a consensus -- @JohnCremona have you had a chance to look at this at all?

**Pull request merged**
