### PR TITLE
fix some tiny errors found by lgtm

### PR DESCRIPTION
**Pull request by fchapoton**
see there for the full list of problems identified:

https://lgtm.com/projects/g/LMFDB/lmfdb/alerts/?mode=list

### CODE REVIEW

**Comment by fchapoton** [comment]
maybe "git_summary" could be removed altogether, as it is not used anywhere ?

**Comment by edgarcosta** [comment]
yes `git_summary` can be deleted

**Comment by fchapoton** [comment]
ok, I have removed git_summary

**Comment by fchapoton** [comment]
This one should be a very easy review..

**Comment by JohnCremona** [comment]
Fine.

BTW I did look at LGTM's verdict on our code some time ago and was rather daunted by the large number of things found (not all of which seemed very important), but I follow all its advice for eclib (C++ not Python of course).

**Pull request merged**
