### PR TITLE
Update abvar page

### PR DESCRIPTION
**Pull request by roed314**
to show info when `hyp_count` is known but not `jacobian_count`.  To test, compare

* http://localhost:37777/Variety/Abelian/Fq/4/3/ae_d_i_aw with https://beta.lmfdb.og/Variety/Abelian/Fq/4/3/ae_d_i_aw (no hyperelliptic Jacobian, unknown if other Jacobian)
* http://localhost:37777/Variety/Abelian/Fq/4/4/a_a_ab_au with https://beta.lmfdb.org/Variety/Abelian/Fq/4/4/a_a_ab_au (1 hyperelliptic Jacobian)
* http://localhost:37777/Variety/Abelian/Fq/3/23/a_v_a with https://beta.lmfdb.org/Variety/Abelian/Fq/3/23/a_v_a (contains 1902 hyperelliptic Jacobians).

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
I'm wondering if it is potentially confusing to have the "hence it is principally polarizable" after "it contains X hyperelliptic Jacobians", since the "hence" is independent of "hyperelliptic".  It might be clearer to make the the statement about containing (any sort of) Jacobian, hence PPAV first, then say how many are hyperelliptic.

**Comment by roed314** [comment]
I tried rewording it; let me know if you think the new version is an improvement (it's a bit wordier).

**Comment by AndrewVSutherland** [comment]
Hmm, the statements still seem to have the form "This isogeny class contains the Jacobian of X hyperelliptic curves, hence is principally polarizable, ...", which doesn't address the issue I was concerned about.  How about "This isogeny class is principally polarizable and contains the Jacobian of X hyperelliptic curves, ...".

I guess we are happy to call an isogeny class principally polarizable if it contains a principally polarizable AV (this is already implicit in the current wording).

**Comment by roed314** [comment]
@AndrewVSutherland, I've made the change you suggested.  I also added more features, so this now fixes #3310 (by adding new entries to the top of the browse page), adds a bunch of hidden search columns and several new sort orders.

**Comment by roed314** [comment]
To test, look at the browse page and play around with search columns and sort orders in abelian variety search results.

Before this is merged, we should push `av_fq_isog` to production.

**Comment by AndrewVSutherland** [comment]
Looks good, and I see that @edgarcosta copied av_fq_isog to proddb.

**Pull request merged**
