### PR TITLE
tweaking parse_list_start

### PR DESCRIPTION
**Pull request by edgarcosta**
When asking for the kth entry of an array to satisfy some condition, MongoDB isn't smart enough to use its multikey index. (MongoDB's multikey indexes are reverse lookups for the array elements)
However, if you on top of that also ask that some element in the array must satisfy the same condition (which is superfluous), then MongoDB stars to use its multikey index, which reduces the search space quite a lot.

In this PR I edited the parse_list_start to add those kind of superfluous conditions to the query.
Here is a cute example:
http://localhost:37777/Variety/Abelian/Fq/?start=0&count=50&q=&g=&p_rank=&angle_ranks=&newton_polygon=&initial_coefficients=%5B3%2C+9%2C+10%2C+87-100%5D&abvar_point_count=&curve_point_count=&decomposition=&number_field=&simple=any&primitive=any&jacobian=any&polarizable=any
where we search for initial coefficients = [3, 9, 10, 87-100]

As it is MongoDB loops over everything to check for those conditions, it ends up taking ~12s
```
2017-09-07T13:13:53.312+0000 I COMMAND  [conn709893] command abvar.fq_isog command: count { count: "fq_isog", query: { polynomial.4: { $lte: 100, $gte: 87 }, polynomial.1: 3, polynomial.2: 9, polynomial.3: 10 } } planSummary: COLLSCAN keyUpdates:0 writeConflicts:0 numYields:10683 reslen:62 locks:{ Global: { acquireCount: { r: 21368 } }, Database: { acquireCount: { r: 10684 } }, Collection: { acquireCount: { r: 10684 } } } protocol:op_query 4917ms
2017-09-07T13:14:01.374+0000 I COMMAND  [conn709893] command abvar.fq_isog command: find { find: "fq_isog", filter: { polynomial.4: { $lte: 100, $gte: 87 }, polynomial.1: 3, polynomial.2: 9, polynomial.3: 10 }, sort: { g: 1, q: 1, label: 1, p_rank: 1 }, limit: 50 } planSummary: IXSCAN { g: 1, q: 1, label: 1, p_rank: 1 } keysExamined:1367543 docsExamined:1367543 cursorExhausted:1 keyUpdates:0 writeConflicts:0 numYields:10683 nreturned:1 reslen:1188 locks:{ Global: { acquireCount: { r: 21368 } }, Database: { acquireCount: { r: 10684 } }, Collection: { acquireCount: { r: 10684 } } } protocol:op_query 8024ms
```

If we on top add the condition, that the polynomial key must have in its elements 3, 9 and 10, the search speeds up significantly, now a bit less than 4s:
```
2017-09-07T13:23:32.774+0000 I COMMAND  [conn709950] command abvar.fq_isog command: count { count: "fq_isog", query: { polynomial.4: { $lte: 100, $gte: 87 }, polynomial: { $all: [ 3, 9, 10 ] }, polynomial.1: 3, polynomial.2: 9, polynomial.3: 10 } } planSummary: IXSCAN { polynomial: 1, g: 1, q: 1, label: 1, p_rank: 1 } keyUpdates:0 writeConflicts:0 numYields:592 reslen:62 locks:{ Global: { acquireCount: { r: 1186 } }, Database: { acquireCount: { r: 593 } }, Collection: { acquireCount: { r: 593 } } } protocol:op_query 2042ms
2017-09-07T13:23:34.586+0000 I COMMAND  [conn709950] command abvar.fq_isog command: find { find: "fq_isog", filter: { polynomial.4: { $lte: 100, $gte: 87 }, polynomial: { $all: [ 3, 9, 10 ] }, polynomial.1: 3, polynomial.2: 9, polynomial.3: 10 }, sort: { g: 1, q: 1, label: 1, p_rank: 1 }, limit: 50 } planSummary: IXSCAN { polynomial: 1, g: 1, q: 1, label: 1, p_rank: 1 } keysExamined:75811 docsExamined:75811 cursorExhausted:1 keyUpdates:0 writeConflicts:0 numYields:596 nreturned:1 reslen:1188 locks:{ Global: { acquireCount: { r: 1194 } }, Database: { acquireCount: { r: 597 } }, Collection: { acquireCount: { r: 597 } } } protocol:op_query 1774ms

```

Further, if we also add the condition that one of its elements must be between (inclusively) 87 and 100, the overall spent time on the DB side is reduced to 1.3s: 
```
2017-09-07T13:31:54.352+0000 I COMMAND  [conn709998] command abvar.fq_isog command: count { count: "fq_isog", query: { polynomial.4: { $lte: 100, $gte: 87 }, polynomial: { $all: [ 3, 9, 10 ], $elemMatch: { $lte: 100, $gte: 87 } }, polynomial.1: 3, polynomial.2: 9, polynomial.3: 10 } } planSummary: IXSCAN { polynomial: 1, g: 1, q: 1, label: 1, p_rank: 1 } keyUpdates:0 writeConflicts:0 numYields:593 reslen:62 locks:{ Global: { acquireCount: { r: 1188 } }, Database: { acquireCount: { r: 594 } }, Collection: { acquireCount: { r: 594 } } } protocol:op_query 775ms
2017-09-07T13:31:54.904+0000 I COMMAND  [conn709998] command abvar.fq_isog command: find { find: "fq_isog", filter: { polynomial.4: { $lte: 100, $gte: 87 }, polynomial: { $all: [ 3, 9, 10 ], $elemMatch: { $lte: 100, $gte: 87 } }, polynomial.1: 3, polynomial.2: 9, polynomial.3: 10 }, sort: { g: 1, q: 1, label: 1, p_rank: 1 }, limit: 50 } planSummary: IXSCAN { polynomial: 1, g: 1, q: 1, label: 1, p_rank: 1 } keysExamined:75811 docsExamined:75811 cursorExhausted:1 keyUpdates:0 writeConflicts:0 numYields:592 nreturned:1 reslen:1188 locks:{ Global: { acquireCount: { r: 1186 } }, Database: { acquireCount: { r: 593 } }, Collection: { acquireCount: { r: 593 } } } protocol:op_query 513ms
```

If we go for something a bit harder: [[3, 9, 10-12, 87-100]](
http://localhost:37777/Variety/Abelian/Fq/?start=0&count=50&q=&g=&p_rank=&angle_ranks=&newton_polygon=&initial_coefficients=%5B3%2C+9%2C+10-12%2C+87-100%5D&abvar_point_count=&curve_point_count=&decomposition=&number_field=&simple=any&primitive=any&jacobian=any&polarizable=any).

Then we can only use one set of inequalities. Otherwise, we would need to wrap everything around with an $and and that doesn't end up speeding up things. 

For last, now running the tests on abvar only takes about 2 min, without this pull request and some of the indexes it was taking ~6min.

### CODE REVIEW

**Comment by edgarcosta** [comment]
CC: @roed314

**Comment by JohnCremona** [comment]
DId you know that you can tell mongo explicitly which index to use, as a hint?
https://docs.mongodb.com/manual/reference/operator/meta/hint/

**Comment by edgarcosta** [comment]
Yes, but MongoDB doesn't really understand that 
`array[k] == elt` implies `elt \in array`

Here some samples with the hint (just counting):
using $all  2.2s:
```
2017-09-07T14:08:05.966+0000 I COMMAND  [conn710171] command abvar.fq_isog command: count { count: "fq_isog", query: { polynomial.4: { $lte: 100, $gte: 87 }, polynomial: { $all: [ 3, 9, 10 ] }, polynomial.1: 3, polynomial.2: 9, polynomial.3: 10 } } planSummary: IXSCAN { polynomial: 1, g: 1, q: 1, label: 1, p_rank: 1 } keyUpdates:0 writeConflicts:0 numYields:594 reslen:62 locks:{ Global: { acquireCount: { r: 1190 } }, Database: { acquireCount: { r: 595 } }, Collection: { acquireCount: { r: 595 } } } protocol:op_query 2243ms
```
Dropping $all and hinting to use the same index 20s:
```
2017-09-07T14:10:17.061+0000 I COMMAND  [conn710171] command abvar.fq_isog command: count { count: "fq_isog", query: { polynomial.4: { $lte: 100, $gte: 87 }, polynomial.1: 3, polynomial.2: 9, polynomial.3: 10 }, hint: "polynomial_1_g_1_q_1_label_1_p_rank_1" } planSummary: IXSCAN { polynomial: 1, g: 1, q: 1, label: 1, p_rank: 1 } keyUpdates:0 writeConflicts:0 numYields:76963 reslen:62 locks:{ Global: { acquireCount: { r: 153928 } }, Database: { acquireCount: { r: 76964 } }, Collection: { acquireCount: { r: 76964 } } } protocol:op_query 20352ms
```
dropping `$all` and using index only on polynomial 32s:
```
017-09-07T14:11:08.647+0000 I COMMAND  [conn710171] command abvar.fq_isog command: count { count: "fq_isog", query: { polynomial.4: { $lte: 100, $gte: 87 }, polynomial.1: 3, polynomial.2: 9, polynomial.3: 10 }, hint: "polynomial_1" } planSummary: IXSCAN { polynomial: 1 } keyUpdates:0 writeConflicts:0 numYields:77142 reslen:62 locks:{ Global: { acquireCount: { r: 154286 } }, Database: { acquireCount: { r: 77143 } }, Collection: { acquireCount: { r: 77143 } } } protocol:op_query 32620ms
```

**Comment by JohnCremona** [comment]
Testing this now.  If all tests pass for me and it's faster then I'll merge it!

**Pull request merged**
