### PR TITLE
Debounce knowl clicking

### PR DESCRIPTION
**Pull request by alexjbest**
Currently if a knowl is double clicked quickly it gets messed up (will stop sliding in and out properly and not be visible at all), especially if the internet connection is bad as it needs to finish loading before the second click happens. One can test this using google chrome by setting your connection speed to 3g or something in the developer toolbar. This can happen even with fast internet completely accidentally.

This PR fixes this by "debouncing" the knowl, enforcing a .5s wait before a knowl is clicked again, otherwise nothing happens.

There may be a different way of fixing this by changing the knowl code, but the debounce function might be useful elsewhere so I did it this way.

<http://www.labbookpages.co.uk/electronics/debounce.html>

### CODE REVIEW

**Comment by JohnCremona** [comment]
Is someone reviewing this?  I don't think I am competent to.

**Comment by edgarcosta** [comment]
FYI, the pull request for CMFs will include this change.
Nevertheless, will be nice to know that people agree with this change.

**Comment by JohnCremona** [comment]
In that case I suggest that this PR be closed -- and similarly any others with the same status, after adding a comment to say why.
Is the same true for #2706? If so I will not bother testing it separately.

**Comment by alexjbest** [comment]
@JohnCremona I don't mind closing this, I was just trying to avoid duplication of effort, it happened once or twice that non-CMF things I fixed and pushed to Davids CMF branch were re-done over here by someone else (you I think!) so I made an effort to make general changes/fixes as PRs here instead. This is probably not something someone else will re-do in the mean time though.

**Comment by edgarcosta** [comment]
I'm okay with that.

> Is the same true for #2706? 
No

I will add a note to our PR text about this RP.

**Pull request closed without merging**
