### PR TITLE
Add quotient genus >0 to higher genus

### LINKED ISSUE #3110: Confusion about notation for signatures, and seemingly missing entries for higher genus curves
From the feedback page:

> Actually, I'm confused about the signature of the entry I just submitted about.
> 
> It's an automorphism of a genus 3 surface of order 2. 
> 
> http://www.lmfdb.org/HigherGenus/C/Aut/?start=0&paging=0&genus=3&count=200
> 
> Or to see it in a shorter list:
> 
> http://www.lmfdb.org/HigherGenus/C/Aut/?start=0&paging=0&genus=3&group_order=2&count=200
> 
> The signature says [2;2]. But shouldn't it be [2; -], or some other notation for no branch points? This should be a free action on a genus 3 curve, with quotient a genus 2 curve.
> 
> I feel like this may be an issue throughout the database. For instance here:
> 
> http://www.lmfdb.org/HigherGenus/C/Aut/?start=0&paging=0&genus=4&group_order=3&count=200
> 
> The [2;2] entry should be [2; -]
> 
> And I was going to say here, next:
> 
> http://www.lmfdb.org/HigherGenus/C/Aut/?start=0&paging=0&genus=7&group_order=3&count=200
> 
> There should be a [3; -] entry. But it doesn't even appear, despite the fact that there are genus 7 curves with an order 3 automorphisms acting freely and with a genus 3 quotient. 
> 
> If I'm mistaken or if some other convention I'm unfamiliar with is being used, please let me know.
> 
> Thanks!
> Justin Lanier
> 

Reply to jlanier8@gatech.edu

### PR DESCRIPTION
**Pull request by jenpaulhus**
This code fixes a number of small issues on the higher genus data pages.

I have updated the hgcwa_passports table in a few places to fix some small errors with the data,  so that will need to be updated on the production version eventually.  This fixed, for example, issue  Issue #3108  as you can see if you run the search on beta now:
http://beta.lmfdb.org/HigherGenus/C/Aut/?start=0&paging=0&genus=3&signature=%5B1%3B2%5D

The primary issue is that some data I thought did not make the switch to Postgres last August actually did make it.  This "new" data is for quotient genus >0  (only  for genus of the original curve up to 4 for the moment) and this data required a series of small changes.  But the pages for that data were works in progress back then, and so aren't displaying correctly on lmfdb.org.  This pull request fixes them. It might be worth considering these as "new" pages even though there are only a handful of entries currently in the database which display this way (instead of just as a pull request fixing errors). If you search for quotient genus >0 you will find one of the "new" pages.

We've fixed some pages returned errors:
http://www.lmfdb.org/HigherGenus/C/Aut/3.2-1.2.0.1
(See #3111  too)

Or a page like the following which had () instead of Id(G) for the identity element of the group.
http://www.lmfdb.org/HigherGenus/C/Aut/2.2-1.1.2-2.1

We also made searching by quotient genus a part of the main search functionality

Magma and Gap downloads had some issues on the page and I fixed most of them (except see #2577)

Notice that [2;2] now correctly shows as [2;-] which fixes #3110
http://localhost:37777/HigherGenus/C/Aut/?start=0&paging=0&genus=3&signature=%5B2%5D&count=200

Also in #3110 they ask about genus 7, but I only have data for genus 4 and quotient genus >0 in the database yet---Note the completeness knowl specifically says only quotient genus =0 but I will change that to include the quotient genus >0 once this pull request is accepted. I don't want to add higher genus data until I am sure these pages are stable. Similarly I  will need to update a couple knowls like signature and generating vectors to explain the quotient genus >0.  

There was an error if you searched for certain labels.  It was a small regex error.

Sort order like #3109 is coming soon...

### CODE REVIEW

**Comment by jenpaulhus** [comment]
Just noticed there were two files from maass_form which register changes with this pull request. You will notice they are just whitespace changes.   I likely forgot to commit or stash changes when I was trying to fix an old error message with maass_forms (#1820) and that corrupted this branch.   Those changes should have 0 impact on any pages.

**Comment by AndrewVSutherland** [comment]
Thanks for this Jen!  I took a look and I think there are still a few issues that need to be addressed.

(1) Searching on group order 2 gives different results than searching on group [2,1], compare:

http://localhost:37777/HigherGenus/C/Aut/?group_order=2
http://localhost:37777/HigherGenus/C/Aut/?start=0&paging=0&group=%5B2%2C1%5D

I expect this is because there are four entries in the search results where the group id still has an extra space in it.  This is not the only place where this happens, the database search

    db.hgcwa_passports.search({"group":{"$like":"[%, %]"}})

returns 128 results.  Presumably these also need to be fixed?  When they are you should let me know so I can copy them to the production database.

(2) There is a problem in how group order searches are being processed.  The value entered into the group order field on the main browse page is not present on the search results page, compare:

http://localhost:37777/HigherGenus/C/Aut/?group_order=2
http://beta.lmfdb.org/HigherGenus/C/Aut/?group_order=2

also, if you enter the group order on the search results page (rather than from the main browse page) it does not work correctly, compare

http://localhost:37777/HigherGenus/C/Aut/?start=0&paging=0&groupsize=2
http://beta.lmfdb.org/HigherGenus/C/Aut/?start=0&paging=0&group_order=2

I presume this is due to the discrepancy between "groupsize" and "group_order".  This change was made in the commit

     https://github.com/jenpaulhus/lmfdb/commit/8f971e7bad79577f030cf9f9f6e0cba768076c4f

labelled "these aren't ready, just saving" on March 22.  This commit (along with the inadvertent changes to Maass forms) makes me nervous; it includes a lot of changes that are not obviously related to this PR and makes a lot more changes to the search results template than are needed.

Would it make sense to create a completely new branch that contains only the changes intended for this PR?  It seems dangerous to be including code changes from two months ago that were obviously not made in response to the issues this PR is trying to address and look like they may be based on an older version of the code.

(3) I don't understand why the search results for quotient genus 2:

    http://localhost:37777/HigherGenus/C/Aut/?g0=2

include the signature [1;2,2,2].  According to

    http://localhost:37777/knowledge/show/curve.highergenus.aut.signature

the first entry of the signature (1 in this case) is the quotient genus.  Have I misunderstood something?

I also think the signature knowl should reference the quotient genus knowl.

(4) Just a small suggestion for improvement: it seems like the quotient genus would be a natural thing to add to the properties box and the list of invariants on the home page of the passport.

(5) I think it would be a good idea to add some additional tests to test_hwcga.py that specifically check the problems that this PR is intended to fix so that they don't recur, and to check that the new quotient genus search/display works as desired.

**Comment by jenpaulhus** [comment]
Thanks, Drew.   I will work on the changes you suggested (and/or start a different, clean pull request if needed).  I'm a bit swamped for the next week, so give me a bit of time to implement the changes.

**Comment by jenpaulhus** [comment]
Closing this because it is superseded by #3143

**Pull request closed without merging**
