### PR TITLE
Added Levelt matrices to HGM Families

### PR DESCRIPTION
**Pull request by tomgrubbmath**
Edited lmfdb/hypergm/web_family.py to allow for tex formatting of Levelt matrices and edited lmfdb/hypergm/templates/hgm_family.html to display Levelt matrices on HGM family pages. 

This work was supported by a grant from the Simons Foundation (546235) for the collaboration `Arithmetic Geometry, Number Theory, and Computation', through a workshop held at ICERM.

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
Thanks for the PR Tom!  I'm going to hold off reviewing this until we get a few pressing issues fixed, but I or someone else will review this sometime this week.

**Comment by edgarcosta** [comment]
@tomgrubbmath, can you add yourself as a contributor to https://github.com/LMFDB/lmfdb/blob/master/CONTRIBUTORS.yaml?
and merge master to your branch?

**Comment by tomgrubbmath** [comment]
@edgarcosta Done; it looks like the pull request automatically updated, but if there's something I missed just let me know.

**Comment by edgarcosta** [comment]
It looks good to me, but maybe we should make into these into knowls, at some point.
Screen Shot 2020-06-07 at 15 41 33

**Pull request merged**
