### PR TITLE
Add RCS knowls (re-implements PR #2692)

### PR DESCRIPTION
**Pull request by AndrewVSutherland**

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
I'll let Travis run and then merge this.

**Comment by AndrewVSutherland** [comment]
Travis found some issues, which I will fix.

**Comment by AndrewVSutherland** [comment]
I removed some code that was inadvertently included plotting code that Travis was complaining about that is not related to RCS knowls.  @davidfarmer if you want to add plots for Maass forms you should create a new PR for this.

**Comment by davidfarmer** [comment]
Thanks for fixing the litle mess in what was supposed to be a simple
pull request.

We have some work to do before thinking about plots of Maass forms.

**Comment by JohnCremona** [comment]
So this is good to go now?  @davidfarmer you are not the only one whose simple PR's needed work after the big CMFs one.

**Comment by AndrewVSutherland** [comment]
Travis is now happy, merging.

**Pull request merged**
