### PR TITLE
EC/Q  search by discriminant and Faltings height added

### PR DESCRIPTION
**Pull request by JohnCremona**
With newly added (and filled)  columns 'absD' (absolute value of discriminant), 'faltings_height' and 'table_faltings_height' to the table ec_curvedata, this adds two search options of elliptic curves, by abs(disc) and by Faltings height.

I'm making a PR to make it easier for people to look at how this is right now, not expecting it to be merged without tweaking.  I am not very good at arranging the search boxes well.

I have added both the (unstable) Faltings height and the FH itself to the page of every elliptic curve (only over Q), and also to the isogeny class page.  In the latter place it should probably be shown with fewer decimals.

It would be nice to have a boolean switch on the search page next to the Faltings height box for stable/unstable, choosing whether to search on the 'faltings_height' column or the 'unstable_faltings_height' column.  I don't know how to do that expect by having a complete separate search box of type boolean, which I don't think would look good.  Better would be a small select box next to the main search box as we have sets of bad primes, etc.

### CODE REVIEW

**Comment by JohnCremona** [comment]
See #4480

**Comment by JohnCremona** [comment]
In the latest commit:  in a search results table, the Faltings height and/or discriminant are shown in a column if and only if they werec specified in the search; the FH is displayed to reduced precision.  Secondly, in the page for an isogeny class, the discriminant and Faltings height (to reduced precision) are displayed in the table, as now is the j-invariant.  A relevant test has been adjusted.

**Comment by JohnCremona** [comment]
For reasons I do not understand, (1) not Travis test was triggered here by the pull request.  However (2) when I pushed this branch to my own github clone, which is configured to run Travis, I get a failure in one of the test blocks, on something not related (as far as I can see) to anything I changed.  The tests run fine for me locally.

=================================== FAILURES ===================================
____________________________ HomePageTest.test_box1 ____________________________
self = <lmfdb.tests.test_homepage.HomePageTest testMethod=test_box1>
    def test_box1(self):
        r"""
        Check that the links in Box 1 work.
        """
        homepage = self.tc.get("/").get_data(as_text=True)
>       self.check(homepage, "/L/?degree=2", '2-23-23.22-c0-0-0')
lmfdb/tests/test_homepage.py:14: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
lmfdb/tests/__init__.py:36: in check
    assert text in self.tc.get(path, follow_redirects=True).get_data(
../../../SageMath/local/lib/python3.7/site-packages/werkzeug/test.py:1006: in get
    return self.open(*args, **kw)
../../../SageMath/local/lib/python3.7/site-packages/flask/testing.py:227: in open
    follow_redirects=follow_redirects,
../../../SageMath/local/lib/python3.7/site-packages/werkzeug/test.py:970: in open
    response = self.run_wsgi_app(environ.copy(), buffered=buffered)
../../../SageMath/local/lib/python3.7/site-packages/werkzeug/test.py:861: in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
../../../SageMath/local/lib/python3.7/site-packages/werkzeug/test.py:1096: in run_wsgi_app
    app_rv = app(environ, start_response)
../../../SageMath/local/lib/python3.7/site-packages/flask/app.py:2464: in __call__
    return self.wsgi_app(environ, start_response)
lmfdb/app.py:32: in __call__
    return self.app(environ, start_response)
../../../SageMath/local/lib/python3.7/site-packages/flask/app.py:2450: in wsgi_app
    response = self.handle_exception(e)
../../../SageMath/local/lib/python3.7/site-packages/flask/app.py:1867: in handle_exception
    reraise(exc_type, exc_value, tb)
../../../SageMath/local/lib/python3.7/site-packages/flask/_compat.py:39: in reraise
    raise value
../../../SageMath/local/lib/python3.7/site-packages/flask/app.py:2447: in wsgi_app
    response = self.full_dispatch_request()
../../../SageMath/local/lib/python3.7/site-packages/flask/app.py:1952: in full_dispatch_request
    rv = self.handle_user_exception(e)
../../../SageMath/local/lib/python3.7/site-packages/flask/app.py:1821: in handle_user_exception
    reraise(exc_type, exc_value, tb)
../../../SageMath/local/lib/python3.7/site-packages/flask/_compat.py:39: in reraise
    raise value
../../../SageMath/local/lib/python3.7/site-packages/flask/app.py:1950: in full_dispatch_request
    rv = self.dispatch_request()
../../../SageMath/local/lib/python3.7/site-packages/flask/app.py:1936: in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
lmfdb/lfunctions/main.py:101: in index
    return l_function_search(info)
lmfdb/utils/search_wrapper.py:206: in __call__
    res = self.postprocess(res, info, query)
lmfdb/lfunctions/main.py:143: in process_search
    res = common_postprocess(res, info, query)
lmfdb/lfunctions/main.py:135: in common_postprocess
    for rec in db.lfunc_instances.search({'Lhash': {"$in": [L['Lhash'] for L in res]}}):
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
.0 = <list_iterator object at 0x7f659b93cdd8>
>   for rec in db.lfunc_instances.search({'Lhash': {"$in": [L['Lhash'] for L in res]}}):
E   KeyError: 'Lhash'
lmfdb/lfunctions/main.py:135: KeyError

**Comment by AndrewVSutherland** [comment]
Travis is effectively no longer available to us during the work week, but I do run tests on grace before merging PRs (you can also do this yourself on legendre).  We are looking into other CI options.

I get the same error you did.  My guess is that there are upstream changes that are not included in your branch and that  the problem will not persist once we merge (I don't see how it could be caused by any changes in your PR).

**Comment by edgarcosta** [comment]
If you rebase or merge your local branch with upstream/master the tests
pass.
I will let you do that.

**Comment by JohnCremona** [comment]
OK, good idea.  I just merged master into the branch.

About travis, my tests seem to b running on travis-ci.com.  I think it used to be .org.  Anyway, it does run on my github and the last report I got was at 11,46 GMT so perhaps it depends on whose working week counts?

**Comment by JohnCremona** [comment]
After merging, there are pyflakes issues:
Running pyflakes...
./lmfdb/lfunctions/main.py:6:1 'sage.all.real_part' imported but unused
./lmfdb/lfunctions/main.py:6:1 'sage.all.imag_part' imported but unused
./lmfdb/lfunctions/main.py:11:1 'collections.defaultdict' imported but unused
./lmfdb/lfunctions/main.py:25:1 '.Lfunctionutilities.string2number' imported but unused
WARNING: pyflakes reported 4 error(s)

**Comment by JohnCremona** [comment]
Thanks for merging. Before pushing to prod the table ec_curvedata will need to be copied across. Thanks!

**Pull request merged**
