### PR TITLE
Fix for critical issue #1207.

### PR DESCRIPTION
**Pull request by sehlen**
This should now *really* fix https://github.com/LMFDB/lmfdb/issues/1207 and related issues I discovered when looking at it. I have to say, we should probably trace back where all of these issues came from because I'm pretty sure the code was a lot better (even better than my fix now, I think) back in December when the pages got the last big overhaul. @sanni85 put a lot of work into this and it was thoroughly tested and now I see all these problems and the logic did just not do what it was supposed to do anymore.

### CODE REVIEW

**Comment by sehlen** [comment]
Sorry for the long title in the beginning. I was using hub (command line tool for github) to issue the pull request and apparently forgot how to use it.

**Comment by sehlen** [comment]
OK, sorry for blaming others... in fact it seems there were no changes to @sanni85's code after December that caused these problems so it is probably all his fault ;-) Anyway, I think my commits should do the job but someone should probably check many cases...

**Comment by sehlen** [comment]
Example page: http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/49/8/?group=0

**Comment by sehlen** [comment]
Please note that I added another commit because the ad-hoc fix by @AndrewVSutherland unfortunately breaks some modular forms pages, e.g. /ModularForm/GL2/Q/holomorphic/20/11/17/.

**Comment by sehlen** [comment]
Maybe @AndrewVSutherland and @JohnCremona could review this as this really fixes a lot of issues at once, I think - so it would be good to have it for 1.0.

**Comment by JohnCremona** [comment]
Will look in a minute

**Comment by jvoight** [comment]
@AndrewVSutherland has had his hands on this, so I would like for him to give an OK.  (But just let me know if should review and pull.)

**Comment by JohnCremona** [comment]
Some pointers at what to look at would be useful -- I have this branch running right now.  the systematic test has reached level 33 but is only testing that these pages load, not what their content is.

**Comment by AndrewVSutherland** [comment]
I'm back at MIT and can tack a look at this as well.  @sehlen did you also look at https://github.com/LMFDB/lmfdb/issues/1215?  It may be unrelated but it would be nice to have all the modular forms tests passing.

**Comment by JohnCremona** [comment]
I have not been able to verify that the changed logic in the code is correct since it is not simple and I never looked at it before, but the test pass and the spot checks I did look good.

Why don't we merge this now as we can always do more...?

**Comment by AndrewVSutherland** [comment]
Sounds good, please merge and push and I can test against production.

**Comment by JohnCremona** [comment]
Done and pushed -- test on beta or lmfdb.warwick.ac.uk pending the cloud server picking up the new prod branch.

**Pull request merged**
