### PR TITLE
Sato-Tate group knowls and Galois image knowls

### PR DESCRIPTION
**Pull request by AndrewVSutherland**
This PR adds Sato-Tate group knowls to ECQ, ECNF, G2C search result and object pages, which is the first step of addressing #4707, and adds Galois image knowls to search results and object pages for ECQ and ECNF.  You can view this on blue.lmfdb.xyz.  Some pages to look at:

- [EC/Q search results](https://blue.lmfdb.xyz/EllipticCurve/Q/?hst=List&search_type=List&showcol=modell_images.elladic_images.sato_tate_group)
- [non-CM EC/Q page](https://blue.lmfdb.xyz/EllipticCurve/Q/11/a/1) and [PCM EC/Q page](https://blue.lmfdb.xyz/EllipticCurve/Q/27/a/2) (click on Sato-Tate groups)
- [ECNF search results](https://blue.lmfdb.xyz/EllipticCurve/?hst=List&search_type=List&showcol=galois_images.sato_tate_group)
- [non-CM ECNF page](https://blue.lmfdb.xyz/EllipticCurve/2.0.10691.1/1.0.1/a/1) and [CM ECNF page](https://blue.lmfdb.xyz/EllipticCurve/2.0.11.1/9.1/CMa/1)
- [genus 2 search results](https://blue.lmfdb.xyz/Genus2Curve/Q/?hst=List&search_type=List&showcol=st_group)
- [genus 2 page](https://blue.lmfdb.xyz/Genus2Curve/Q/324/a/648/1) (click on Sato-Tate group)

Note: there are a few mod-ell images for ECNF curves that are not in the database yet, these knowls will work once I add them (no code change is required).

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
I still need to add Sato-Tate knowls to the CMF search result and object pages, but I can do that in a separate PR.

**Comment by AndrewVSutherland** [comment]
I added Sato-Tate knowls to the CMF [search results](https://blue.lmfdb.xyz/ModularForm/GL2/Q/holomorphic/?hst=List&weight=2-&search_type=List&showcol=sato_tate_group) and [object pages](https://blue.lmfdb.xyz/ModularForm/GL2/Q/holomorphic/9/3/d/a/).

**Comment by AndrewVSutherland** [comment]
@edgarcosta Do you want to review this? I think you opened #4707 which this partially addressed, I plan to do more work on #4707, but that will be in a separate PR.

**Comment by edgarcosta** [comment]
I would change two things:
- do not use the knowl inside the properties box, I only saw this on genus 2 curves
- (optional) always display the ambient group, even if it is itself.

**Pull request merged**
