### PR TITLE
Global random object

### PR DESCRIPTION
**Pull request by SamSchiavone**
Addressing https://github.com/LMFDB/lmfdb/issues/3102

### CODE REVIEW

**Comment by davidfarmer** [comment]
Small comments:

"ModularForm/GSp/Q/" is only on Beta.

Some of those things have L-functions, which also should occasionally appear
as a random object.  It might be reasonable to make the L-function of an object
less likely than the object itself.

**Comment by jwj61** [comment]
David's comment on GSp is right.

How hard is it to set up a route L/random to pull a random L-function from the database?

**Comment by SamSchiavone** [comment]
Thanks for the comments! I removed ModularForm/GSp/Q/ from main list.

Drew said it shouldn't be hard to add L/random so I'll look into it.

**Comment by SamSchiavone** [comment]
All right, I made a L/random and then added the route to the global random button. Let me know if you have any other suggestions!

**Comment by SamSchiavone** [comment]
Now on https://purple.lmfdb.xyz/

**Comment by davidfarmer** [comment]
I like it and probably clicked it more than 50 times.

The link to a random object is not obvious.  A natural place is
under "Introduction", below Universe and Knowledge, but I know
space in the nav bar is at a premium.

**Comment by roed314** [comment]
Yeah, it's pretty fun!

I agree that it would be nice to have in a more visible place.  To be fair, it's probably more visible to new users; I think most of us have come to ignore the homepage since it doesn't really change.

**Comment by davidfarmer** [comment]
Is it possible to get an individual modular form (what the modular forms people
call an "embedding")?  Those would be good, and not just spaces or galois orbits.
(It is possible to get a galois orbit?)

**Comment by davidfarmer** [comment]
I think the "random newform" link always gives an orbit.

**Comment by edgarcosta** [comment]
The webpage of an embedding is a reorganized version with less information than the orbit page, thus I don't think it makes much sense to return those on a random search, we also don't search on embeddings.

**Comment by davidfarmer** [comment]
It would be good to have E/Q and also isogeny classes of E/Q as possible random objects.

**Comment by davidfarmer** [comment]
Yet embeddings are the things that have primitive L-functions associated 
to them.

I understand there is a perspective that does not consider embeddings as
the important objects, and only focuses on orbits.  But not everyone
thinks that way.

**Comment by edgarcosta** [comment]
Try purple.lmfdb.xyz/L/random

**Comment by jwj61** [comment]
I think this can be committed and further refinements hashed out afterwards.

But until that happens, what do people think of increasing the probability of getting an L-function, e.g. 20% of the time?

**Comment by edgarcosta** [comment]
We just need to add "L/" to routes a couple of more times

**Comment by jwj61** [comment]
Right, or have a first call to random for L-functions if you want precise control over the probability.

**Comment by SamSchiavone** [comment]
All right, I added a couple more "L/" to routes. I could change the random_url to take a list of weights if we'd like to have more precise control over the frequency with which each type of object appears.

**Pull request merged**
