### PR TITLE
Minor look and feel changes to genus 2 curves

### PR DESCRIPTION
**Pull request by AndrewVSutherland**
Removes a stray colon and changes titles to use sentence case (only first word and proper names capitalized).

### CODE REVIEW

**Comment by roed314** [comment]
I'm happy with these changes, but they will need to be made many other places within the LMFDB (currently there are 3 hits for `Search results` and dozens for `Search Results` for example).

**Comment by AndrewVSutherland** [comment]
@roed314 Yes, we discussed this in the editorial meeting today where the consensus was to have all headings use sentence case (this is what Wikipedia does, and it is simpler to just be consistent everywhere rather than using a mixture as we do now).  I wanted to make the changes to the genus 2 curves pages first to see how things look before making them everywhere.

The good news is that the changes are easy to make (I just searched for title, bread, and Genus)

**Comment by AndrewVSutherland** [comment]
The Travis failure is in a test for Artin L-function plot that has nothing to do with this PR (but should be investigated separately):

>     def test_LartinPlot(self):
>       L = self.tc.get('/L/Zeros/ArtinRepresentation/2.2e2_17.4t3.2c1/')
lmfdb/lfunctions/test_lfunctions.py:580: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../../SageMath/local/lib/python3.7/site-packages/werkzeug/test.py:830: in get
    return self.open(*args, **kw)
../../../SageMath/local/lib/python3.7/site-packages/flask/testing.py:108: in open
    follow_redirects=follow_redirects)
../../../SageMath/local/lib/python3.7/site-packages/werkzeug/test.py:803: in open
    response = self.run_wsgi_app(environ, buffered=buffered)
../../../SageMath/local/lib/python3.7/site-packages/werkzeug/test.py:716: in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
../../../SageMath/local/lib/python3.7/site-packages/werkzeug/test.py:923: in run_wsgi_app
    app_rv = app(environ, start_response)
../../../SageMath/local/lib/python3.7/site-packages/flask/app.py:1836: in __call__
    return self.wsgi_app(environ, start_response)
1m../../../SageMath/local/lib/python3.7/site-packages/flask/app.py:1820: in wsgi_app
    response = self.make_response(self.handle_exception(e))
../../../SageMath/local/lib/python3.7/site-packages/flask/app.py:1403: in handle_exception
    reraise(exc_type, exc_value, tb)
../../../SageMath/local/lib/python3.7/site-packages/flask/_compat.py:33: in reraise
    raise value
../../../SageMath/local/lib/python3.7/site-packages/flask/app.py:1817: in wsgi_app
    response = self.full_dispatch_request()
../../../SageMath/local/lib/python3.7/site-packages/flask/app.py:1477: in full_dispatch_request
    rv = self.handle_user_exception(e)
../../../SageMath/local/lib/python3.7/site-packages/flask/app.py:1381: in handle_user_exception
    reraise(exc_type, exc_value, tb)
../../../SageMath/local/lib/python3.7/site-packages/flask/_compat.py:33: in reraise
    raise value
../../../SageMath/local/lib/python3.7/site-packages/flask/app.py:1475: in full_dispatch_request
    rv = self.dispatch_request()
../../../SageMath/local/lib/python3.7/site-packages/flask/app.py:1461: in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
lmfdb/lfunctions/main.py:793: in zerosLfunction
    return render_zerosLfunction(request, *args)
lmfdb/lfunctions/main.py:895: in render_zerosLfunction
    L = generateLfunctionFromUrl(*args, **to_dict(request.args))
lmfdb/lfunctions/main.py:992: in generateLfunctionFromUrl
    return ArtinLfunctionDB(label=label) if instance else ArtinLfunction(label=label)
lmfdb/lfunctions/Lfunction.py:1706: in __init__
    upperbound=1000)
lmfdb/artin_representations/math_classes.py:373: in coefficients_list
    return an_list(lambda p: self.euler_polynomial(p), upperbound=upperbound, base_field=ComplexField())
lmfdb/utils/utilities.py:160: in an_list
    euler_factor = (1 / (PP(euler_factor_polynomial_fn(p)))).padded_list()
lmfdb/artin_representations/math_classes.py:373: in <lambda>
    return an_list(lambda p: self.euler_polynomial(p), upperbound=upperbound, base_field=ComplexField())
lmfdb/artin_representations/math_classes.py:369: in euler_polynomial
    return self.local_factor(p)
lmfdb/artin_representations/math_classes.py:592: in local_factor
    return self.good_factor(p)
lmfdb/artin_representations/math_classes.py:570: in good_factor
    return self.from_conjugacy_class_index_to_polynomial(self.nf().from_prime_to_conjugacy_class_index(p))
lmfdb/artin_representations/math_classes.py:888: in from_prime_to_conjugacy_class_index
    return self.from_cycle_type_to_conjugacy_class_index(self.frobenius_cycle_type(p), p)
lmfdb/artin_representations/math_classes.py:885: in from_cycle_type_to_conjugacy_class_index
    return fn_to_use(p)
lmfdb/artin_representations/cyc_alt_res_engine.py:191: in RES_from_cycle_type_to_conjugacy_class_index
    return polynomial_conjugacy_class_matcher(alpha)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
alpha = 265*a + 71
    def polynomial_conjugacy_class_matcher(alpha):
        """
        A function that has an internal list of pairs (pol, return_val). Given alpha, finds the pol that it is a root of and returns
        the associated return_val
        """
        for pol_fn, conjugacy_class_index in fn_cc_pairs:
            if pol_fn(alpha) == 0:
                return conjugacy_class_index
>       raise AssertionError("alpha = %s is supposed to be root of one of %s" % (alpha, input))
E       AssertionError: alpha = 265*a + 71 is supposed to be root of one of [{'RootOf': ['-1', '1'], 'ConjugacyClass': 2}, {'RootOf': ['10', '6', '1'], 'ConjugacyClass': 3}]
lmfdb/artin_representations/cyc_alt_res_engine.py:62: AssertionError

**Comment by edgarcosta** [comment]
We have been seeing this failures for a while, I'm not sure what is going on. See #3760

**Comment by AndrewVSutherland** [comment]
@edgarcosta Got it, thanks.  It's suspicious that this only shows up in Sage 9, could it actually be due to a (non-deterministic) problem in Sage?

**Comment by roed314** [comment]
Yeah, we're worried it might have something to do with Python 3 changing sort order of dictionaries.  But we're not sure.

**Pull request merged**
