### PR TITLE
merged two lists of sponsors into one

### PR DESCRIPTION
**Pull request by JohnCremona**
See http://localhost:37777/acknowledgment

The wording looked odd to me, this merges (concatenates) two lists into one.

### CODE REVIEW

**Comment by edgarcosta** [comment]
I like the changes, but I will let others chime in.
Do you think we could also add the years for OpenDreamKit grant? (2015-2019)?

**Comment by JohnCremona** [comment]
Yes they should all have years. I'll fix that. I ran this past the other man.eds. first.

**Comment by jwj61** [comment]
Looks good, and agree on adding years for all.

**Comment by JohnCremona** [comment]
I added the dates requested.  Can be merged once tests pass.

**Pull request merged**
