### PR TITLE
Hide dimension 2 BMFs

### PR DESCRIPTION
**Pull request by JohnCremona**
This addresses issue #4170.  I have not deleted the (small number of) dimension 2 BMFs from the table bmf_forms, but I have 
   - removed Dimension from the search options
   - adjusted the stats page (the last two tables are now deleted)
   - adjusted the wording in the description of newform spaces.
I just realised that after removing the Dimension from the search options I should still add the constraint dimension=1 to the search.  I will fix that and update the PR shortly

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
You can still access the dimension 2 forms via the jump box, e.g. http://127.0.0.1:37777/ModularForm/GL2/ImaginaryQuadratic/2.0.4.1/1066.4/a2/

This doesn't necessarily mean the PR needs to change, I think we want to remove these entries from the table, right?

**Comment by JohnCremona** [comment]
> You can still access the dimension 2 forms via the jump box, e.g. http://127.0.0.1:37777/ModularForm/GL2/ImaginaryQuadratic/2.0.4.1/1066.4/a2/

True

> 
> This doesn't necessarily mean the PR needs to change, I think we want to remove these entries from the table, right?

OK -- I was going to ait but could do it now.  We would then need to synchronise the pushing of this to the web, copying the data to web, and positively reviewing the knowls.  I'll edit the knowls now in preparation, but I think it would be better not to delete the dim 2 forms from the database until this is on beta.  Is that sensible?

**Comment by JohnCremona** [comment]
I have just edited the two relevant rcs knowls, by commenting out the sentence which mentions the dim.2 newforms.

**Comment by AndrewVSutherland** [comment]
okay, pushing to beta now.

**Comment by JohnCremona** [comment]
> okay, pushing to beta now.

Thanks, now I'll delete the (ir)relevant data...done.  So what's left is: at next code merge to prod, copy bmf_forms (only) and positively review the two rcs knowls.

**Pull request merged**
