### PR TITLE
Update Inventory

### PR DESCRIPTION
**Pull request by hratcliffe**
This should restore the inventory on the postgres database, in particular reenabling editing and the scraping for collections and keys.

### CODE REVIEW

**Comment by hratcliffe** [comment]
@JohnCremona while I've checked this on a couple of new collections and on some with new keys, would be good to have a few tests before proceeding.

**Comment by JohnCremona** [comment]
@hratcliffe I'll test it -- any chance you could fix the pyflakes failures first?

**Comment by hratcliffe** [comment]
> @hratcliffe I'll test it -- any chance you could fix the pyflakes failures first?

Will do this afternoon and push update.

**Comment by JohnCremona** [comment]
@edgarcosta Do you know why Travis is failing miserably here?  I'm running thet test suite locally and all looks fine (I have not finished but the first few are OK, unlike on Travis).

**Comment by JohnCremona** [comment]
I've done some testing and looks good.  I tried editing some descriptions of fields and that was fine.   Rescraping is very fast now (I did all of ec), as expected given that we do not need to look at every row to work out the schema.

**Comment by JohnCremona** [comment]
When running the test locally all pass except one (which has nothing to do with this PR):

lmfdb/lfunctions/test_lfunctions.py::LfunctionTest::test_Lcmf FAILED

Looks like some whitespace has changed:

<expected>
1 -  T + T^{2} + 21 T^{3} - 219 T^{4} - 1365 T^{5} - 219 p T^{6} + 21 p^{2} T^{7} + p^{3} T^{8} -  p^{4} T^{9} + p^{5} T^{10}
<found>
1 - T + T^{2} + 21 T^{3} - 219 T^{4} - 1365 T^{5} - 219 p T^{6} + 21 p^{2} T^{7} + p^{3} T^{8} - p^{4} T^{9} + p^{5} T^{10}

**Comment by hratcliffe** [comment]
> @edgarcosta Do you know why Travis is failing miserably here? I'm running thet test suite locally and all looks fine (I have not finished but the first few are OK, unlike on Travis).
At the moment it's because I didn't completely remove all the logging. Previously it was a missing file. Hopefully get it fixed shortly.

**Comment by hratcliffe** [comment]
Hopefully that's the last pyflakes error caught.

**Comment by edgarcosta** [comment]
I'm aware that the test that @JohnCremona mentioned fails in Sage 8.7 but not in Sage 8.3.

This also showed up for me in #3130, feel free to edit the test.

**Comment by JohnCremona** [comment]
I suggest a small separate PR to fix that and then the others PRs will not need changing before merging.

**Comment by JohnCremona** [comment]
Sorry I just realised the issue.  Travis is using Sage 8.3 and now passes this so I'll merge it.  Locally (on legendre) we have 8.7 and there is some small formatting change.  It would be nice to be able to ignore whitespace in tests.

**Pull request merged**
