### PR TITLE
weight-1 newform friends for odd 2D Artin rep orbit pages

### PR DESCRIPTION
**Pull request by AndrewVSutherland**
This PR adds newform related object links to home pages of Galois orbits of odd 2d Artin reps that correspond to a weight-1 newform stored in the database (so conductor <= 4000)

Currently artin reps have related object links to embedded newforms (and vice versa), and newforms have related object links Artin rep Galois orbit pages, but Artin rep Galois orbit pages do now know about newforms.  This PR makes a small change to address this.

Before:
https://beta.lmfdb.org/ArtinRepresentation/2.2e2_31.16t60.1 (no newform friend or L-function :()
https://beta.lmfdb.org/ArtinRepresentation/2.2e2_31.16t60.1c1 (embedded newform friend)
https://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/124/1/i/a/87/2/ (atrin rep friend)
https://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/124/1/i/a/ (artin rep Galois orbit friend)

After:
http://127.0.0.1:37777/ArtinRepresentation/2.2e2_31.16t60.1  (newform friend and L-function :))
http://127.0.0.1:37777/ArtinRepresentation/2.2e2_31.16t60.1c1 (embedded newform friend)
http://127.0.0.1:37777/ModularForm/GL2/Q/holomorphic/124/1/i/a/87/2/ (atrin rep friend)
http://127.0.0.1:37777/ModularForm/GL2/Q/holomorphic/124/1/i/a/ (artin rep Galois orbit friend)

L-function instance records have already been added so the (imprimitive) rational L-function page already sees everybody (newform, Artin rep Galois orbit, embedded newforms, Artin reps)

https://beta.lmfdb.org/L/ModularForm/GL2/Q/holomorphic/124/1/i/a/
https://beta.lmfdb.org/L/ArtinRepresentation/2.2e2_31.16t60.1/

(note that these two URLs go to the same L-function page via two different origins -- eventually L-function URLs will be origin independent but not yet)

and each primitive L-function page sees both the Artin rep and the embedded modular form

https://beta.lmfdb.org/L/ModularForm/GL2/Q/holomorphic/124/1/i/a/67/1/
https://beta.lmfdb.org/L/ArtinRepresentation/2.2e2_31.16t60.1c1/

Note: I have not updated lfunc_instances on the production server yet, so the new lfunction instance entries for these Artin reps only appear on beta.  I will copy lfunc_instances over tomorrow (but this has no impact on the code change in this PR).

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
Broke a test, I'll fix it now.

**Comment by AndrewVSutherland** [comment]
The test failure is in test_artin and is fixed in #3529.  Once the tests for #3529 all pass it is safe to merge this.

**Comment by roed314** [comment]
Looks good.  There are artin representation tests failing on other PRs, so hopefully merging this can fix them.

**Comment by AndrewVSutherland** [comment]
Thanks, the data change to mf_newforms (which changed the related object links to artin reps to use artin rep Galois orbit labels when appropriate) is actually what broke the test, not code changes in this PR (which includes a fix to the test to look for the new artin rep label).

This issue will arise again when the Artin rep label format changes (but next time I can change the test in a backward compatible way first,if needed before changing the data).

**Pull request merged**
