### PR TITLE
Making it more clear that the ecnf database does not contain ec over Q

### PR DESCRIPTION
**Pull request by rbommel**
This should solve #3319.

### CODE REVIEW

**Comment by davidfarmer** [comment]
I think this addresses the point of issue #3319 , which can be closed after this is merged.

In future, please include in the pull request links to pages where the changes can be seen.
In this instance, /EllipticCurve .
I realize this may seem "obvious" in this particular case, but such links are a help to
the reviewer and also make sure that nothing is missed.

**Comment by davidlowryduda** [comment]
The reasons the tests are failing is unrelated to the changes made in this pull request.

See #3441 for information.

**Comment by JohnCremona** [comment]
Travis is now retesting after the PR to the other repo was merged.

**Comment by AndrewVSutherland** [comment]
@JohnCremona FYI, that wasn't automatic, I restarted it :)

**Comment by JohnCremona** [comment]
Thanks I spent 10 minutes failing to see the button to press which is sometimes visible but not always.

**Comment by AndrewVSutherland** [comment]
You might need to whitelist travis in your browser and/or extensions -- 
if travis notices your browser is interfering with javascript in any way 
(e.g. because you are using a secure browser, adblocker, noscript, 
ghostery, etc...) it won't show the button.  Note that whitelisting 
github does not whitelist travis.

**Comment by JohnCremona** [comment]
Is there a danger that some pedantic users will complain that the EC/NF collection does include some "curves defined over Q", or at least their base-changes to another field?  I think I prefer the wording 

"Elliptic curves defined over $\mathbb{Q}$ are contained in a separate database."

and then we could make the degree statement say "of degrees from 2 up to 6".

**Comment by rbommel** [comment]
Changed.

**Pull request merged**
