### PR TITLE
Script to fix #1656

### LINKED ISSUE #1656: Insufficient Hecke eigenvalues
@danyasaki reported that certain HMFs do not have as many Hecke eigenvalues as prime ideals; he found the following:

2.2.85.1-180.2-m
2.2.85.1-180.2-n
2.2.85.1-180.2-o
2.2.85.1-180.2-p
2.2.85.1-180.2-q
2.2.85.1-180.3-m
2.2.85.1-180.3-n
2.2.85.1-180.3-o
2.2.85.1-180.3-p
2.2.85.1-180.3-q

(There does not appear to be any problem with forms with level 180.1.)

### PR DESCRIPTION
**Pull request by AurelPage**
This script started by Dan Yasaki and edited by me checks that HMFs satisfy the condition from #1656: if there is the Hecke eigenvalue for a prime P, then there are eigenvalues for all primes of the same norm as P. The script is ready to be used, but since it deletes data from the DB I have used it on a single form so far: compare
http://www.lmfdb.org/ModularForm/GL2/TotallyReal/3.3.321.1/holomorphic/3.3.321.1-293.1-b?numeigs=10000&display_eigs=False
and
http://beta.lmfdb.org/ModularForm/GL2/TotallyReal/3.3.321.1/holomorphic/3.3.321.1-293.1-b?numeigs=10000&display_eigs=False
The eigenvalue for the prime of norm 647 was deleted because the DB does not contain the eigenvalues for the other two primes of norm 647 in that field.

### CODE REVIEW

**Comment by AurelPage** [comment]
The results will be easier to check on the webpages when PR #2092 will be merged.

**Comment by davidfarmer** [comment]
Asked Dan Yasaki to give the script a test run.

**Comment by danyasaki** [comment]
Adding a line 
assert abs(nb - num_ap) <= int(f['label'].split('.')[0]) - 1
in the truncation_bound
will ensure that not many eigenvalues are dropped.
I think it looks good.

**Comment by AurelPage** [comment]
I incorporated Dan's suggestions.

**Comment by davidfarmer** [comment]
Looks good!  Merging.

**Pull request merged**
