### PR TITLE
final removal of six imports

### PR DESCRIPTION
**Pull request by fchapoton**
next step will be removal of all  `from __future__`

### CODE REVIEW

**Comment by fchapoton** [comment]
hmm, we need to fix the pylint check. What should be checked by pylint ?

**Comment by fchapoton** [comment]
now at least one of these wrong asserts apparently fails in Sato-Tate. Should I just remove it ?

**Comment by fchapoton** [comment]
probably not a good idea to remove without a mathematical understanding of why it fails

**Comment by fchapoton** [comment]
should it be "No matches" instead of "0 matches" ?

**Comment by fchapoton** [comment]
ok, ready to go !

**Comment by roed314** [comment]
Looks good.  My only question is about the line in `tox.ini`, which now reads
```
pylint --score=no -d C,R,E,W -e W0129 start-lmfdb.py user-manager.py lmfdb/
```
What are `C,R,E,W` and `W0129`?

**Comment by fchapoton** [comment]
The previously used --py3k option was only checking compatibility with python3. Now that it is removed, by default pylint would run its full check suite. And this fails in **many many ways**.

C,R,E,W are four large categories of checks (E for errors, W for warnings, etc). None of these sets of checks currently pass, and by far. So we disactivate them all.

W0129 is checking that there is no wrong assert. I have chosen to re-activate this one as it was simple to fix, in order to keep at least one active check.

One could try to find other specific checks that do pass. I think this could be left to another merge request.

**Comment by fchapoton** [comment]
a reference for W0129 : https://pycodequ.al/docs/pylint-messages/w0129-assert-on-string-literal.html

**Comment by roed314** [comment]
Thanks for the explanation!

**Pull request merged**
