### PR TITLE
Add statistics page for ECNF, search by rank

### PR DESCRIPTION
**Pull request by roed314**

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
The rank table looks good but the links in the torsion structure search table throw errors.

**Comment by JohnCremona** [comment]
As of next week it will no longer be true to say that most ranks are missing.   It will still be true that for quite a few curves we will only have rank bounds, so I hope that the search facility on rank will explain how that is handled.  E. G. We mave bounds 0 and 2 with analytic rank 2.

**Comment by roed314** [comment]
That's great!  Currently the search facility on rank only takes the "rank" column into account.  What behavior would you like to see?  Have curves show up if input for the rank box overlaps the range on their rank bounds?

Also, any thoughts on what we should show on the statistics?

**Comment by JohnCremona** [comment]
I made some relevant comments at #3900  .  In particular, there will be a case for the rank search using only the analytic rank column since in all cases where the rank bounds are the same, the analytic rank is equal to the rank (you would not trust my data if that were not true!) but more importantly, when the lower bound is less than the upper bound, the expected value of the rank is the same as the analytic rank.

However I really think that progress on this issue should wait a few days as I am in the process of adding (and filling columns).

**Comment by roed314** [comment]
Sounds good; I'll wait until you finish updating the data.

**Pull request merged**
