### PR TITLE
Changing known search function to only consider most recent version of knowl

### PR DESCRIPTION
**Pull request by rbommel**
This pull request is meant to mitigate #4716.

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
Test failures are fixed in #4957.

**Comment by AndrewVSutherland** [comment]
LGTM, but it would be good for @roed314 to take a look.

**Comment by roed314** [comment]
LGTM

**Comment by jvoight** [comment]
Thanks Raymond for hunting this down!

**Pull request merged**
